// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_hl__Format
#define INC_hl__Format
typedef struct _hl__$Format *hl__$Format;
typedef struct _hl__Format *hl__Format;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _hl__$Format {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _hl__Format {
	hl_type *$type;
};
#endif

