// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_sys__FileSystem
#define INC_sys__FileSystem
typedef struct _sys__$FileSystem *sys__$FileSystem;
typedef struct _sys__FileSystem *sys__FileSystem;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _sys__$FileSystem {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* exists;
};
struct _sys__FileSystem {
	hl_type *$type;
};
#endif

