// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <sys/FileSystem.h>
vdynamic* String_charCodeAt(String,int);
extern hl_type t$_i32;
String haxe_io_Path_addTrailingSlash(String);
extern String s$6666cd7;
int String___compare(String,vdynamic*);
String haxe_io_Path_removeTrailingSlashes(String);
vbyte* Sys_getPath(String);
#include <hl/natives.h>

bool sys_FileSystem_exists(String r0) {
	String r3, r8;
	bool r1;
	vdynamic *r4, *r6;
	int r5, r7;
	vbyte *r2;
	if( r0 == NULL ) hl_null_access();
	r5 = 1;
	r4 = String_charCodeAt(r0,r5);
	r5 = 58;
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r5;
	if( r4 != r6 && (!r4 || !r6 || (r4->v.i != r6->v.i)) ) goto label$71a15a3_1_11;
	r5 = r0->length;
	r7 = 3;
	if( r7 < r5 ) goto label$71a15a3_1_11;
	r3 = haxe_io_Path_addTrailingSlash(r0);
	goto label$71a15a3_1_16;
	label$71a15a3_1_11:
	r8 = (String)s$6666cd7;
	if( r0 != r8 && (!r0 || !r8 || String___compare(r0,(vdynamic*)r8) != 0) ) goto label$71a15a3_1_15;
	r3 = (String)s$6666cd7;
	goto label$71a15a3_1_16;
	label$71a15a3_1_15:
	r3 = haxe_io_Path_removeTrailingSlashes(r0);
	label$71a15a3_1_16:
	r2 = Sys_getPath(r3);
	r1 = hl_sys_exists(r2);
	return r1;
}

