// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/Battery.h>
#include <objects/Item.h>
extern String s$ship_liquid_tank_png;
void objects_ExtendableObject_new(objects__ExtendableObject,int*,int*,String,int*);
extern hl_type t$objects_Item;
#include <hl/natives.h>
extern String s$Charge;
void objects_Item_new(objects__Item,String,int*);
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);

void objects_Battery_new(objects__Battery r0) {
	String r6;
	hl__types__ArrayObj r8;
	hl_type *r10;
	objects__Item r12;
	int *r3, *r5, *r7;
	varray *r9;
	int r2, r4, r11;
	r2 = 20;
	r3 = &r2;
	r4 = 20;
	r5 = &r4;
	r6 = (String)s$ship_liquid_tank_png;
	r7 = NULL;
	objects_ExtendableObject_new(((objects__ExtendableObject)r0),r3,r5,r6,r7);
	r10 = &t$objects_Item;
	r11 = 1;
	r9 = hl_alloc_array(r10,r11);
	r12 = (objects__Item)hl_alloc_obj(&t$objects_Item);
	r6 = (String)s$Charge;
	r3 = NULL;
	objects_Item_new(r12,r6,r3);
	r11 = 0;
	((objects__Item*)(r9 + 1))[r11] = r12;
	r8 = hl_types_ArrayObj_alloc(r9);
	r0->inventory = r8;
	return;
}

