// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_objects__ConnectorLink
#define INC_objects__ConnectorLink
typedef struct _objects__$ConnectorLink *objects__$ConnectorLink;
typedef struct _objects__ConnectorLink *objects__ConnectorLink;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <objects/ExtendableObject.h>
#include <hl/types/ArrayBytes_Float.h>


struct _objects__$ConnectorLink {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _objects__ConnectorLink {
	hl_type *$type;
	objects__ExtendableObject connected;
	hl__types__ArrayBytes_Float from;
	hl__types__ArrayBytes_Float to;
};
#endif

