// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/Connector.h>

void objects_Connector_new(objects__Connector r0,hl__types__ArrayBytes_Float r1,int* r2) {
	int r3;
	if( r2 ) goto label$a9b1c69_1_3;
	r3 = 0;
	goto label$a9b1c69_1_4;
	label$a9b1c69_1_3:
	r3 = *r2;
	label$a9b1c69_1_4:
	r0->pos = r1;
	r0->type = r3;
	return;
}

void objects_Connector_draw(objects__Connector r0) {
	return;
}

