// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/ConnectorLink.h>

void objects_ConnectorLink_new(objects__ConnectorLink r0,objects__ExtendableObject r1,hl__types__ArrayBytes_Float r2,hl__types__ArrayBytes_Float r3) {
	r0->connected = r1;
	r0->from = r2;
	r0->to = r3;
	return;
}

