// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/ExtendableObject.h>
#include <_std/Math.h>
extern $Math g$_Math;
#include <hl/natives.h>
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
#include <objects/Connector.h>
extern hl_type t$objects_Connector;
void objects_Connector_new(objects__Connector,hl__types__ArrayBytes_Float,int*);
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern hl_type t$objects_LogicConnector;
#include <objects/Neighbor.h>
int Std_random(int);
#include <objects/ConnectorLink.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
extern haxe__$Log g$_haxe_Log;
extern String s$Error_;
extern String s$_objects_Extendable_hx;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$objects_ExtendableObject;
extern String s$rotateConnected;
extern hl_type t$vrt_eaa6a3b;
extern String s$Failed_to_link_extendable_;
String Std_string(vdynamic*);
String String___add__(String,String);
double Math_max(double,double);
#include <objects/LogicConnector.h>
hl__Class Type_getClass(vdynamic*);
String Type_getClassName(hl__Class);
void util_FontManager_drawText(String,int,int,int*);
extern String s$Fuel_;
String String___alloc__(vbyte*,int);
extern String s$Temperature_;
extern String s$Conductivity_F_;
extern String s$Absorptivity_F_;
extern String s$Emission_F_;
extern String s$Current_;
extern String s$O2_;
extern String s$Broken_;
void objects_LogicConnector_draw(objects__LogicConnector);
void Object_draw(Object);
#include <_std/Game.h>
extern $Game g$_Game;
void Object_setOutline(Object,bool*,int*);
void Object_select(Object,bool);
#include <objects/Item.h>
#include <hl/types/ArrayBase.h>
int String___compare(String,vdynamic*);
hl__types__ArrayBase hl_types_ArrayObj_splice(hl__types__ArrayObj,int,int);
extern hl_type t$hl_types_ArrayObj;
extern hl_type t$hl_types_ArrayBase;
extern hl_type t$objects_Item;
extern hl_type t$objects_Neighbor;
extern hl_type t$objects_ConnectorLink;
void objects_GameObject_new(objects__GameObject,int*,int*,String,int*);
extern objects__$ExtendableObject g$_objects_ExtendableObject;

void objects_ExtendableObject_update(objects__ExtendableObject r0,double r1) {
	return;
}

hl__types__ArrayBytes_Float objects_ExtendableObject_dirV(objects__ExtendableObject r0) {
	$Math r4;
	hl__types__ArrayBytes_Float r12;
	double r1, r2, r3, r5, r6, r7, r8, r9, r10, r11, r15, r16;
	int r14, r17;
	vbyte *r13;
	r1 = r0->angle;
	r2 = r0->localAngle;
	r1 = r1 + r2;
	r2 = 2.;
	r4 = ($Math)g$_Math;
	r3 = r4->PI;
	r2 = r2 * r3;
	r1 = fmod(r1,r2);
	r2 = 2.;
	r4 = ($Math)g$_Math;
	r3 = r4->PI;
	r2 = r2 * r3;
	r1 = fmod(r1,r2);
	r4 = ($Math)g$_Math;
	r3 = r4->PI;
	if( !(r3 < r1) ) goto label$bd524ea_2_23;
	r3 = 2.;
	r4 = ($Math)g$_Math;
	r5 = r4->PI;
	r3 = r3 * r5;
	r2 = r1 - r3;
	r1 = r2;
	goto label$bd524ea_2_33;
	label$bd524ea_2_23:
	r4 = ($Math)g$_Math;
	r3 = r4->PI;
	r3 = -r3;
	if( !(r1 < r3) ) goto label$bd524ea_2_33;
	r3 = 2.;
	r4 = ($Math)g$_Math;
	r5 = r4->PI;
	r3 = r3 * r5;
	r2 = r1 + r3;
	r1 = r2;
	label$bd524ea_2_33:
	r2 = hl_math_abs(r1);
	r3 = 0.5;
	if( !(r2 < r3) ) goto label$bd524ea_2_42;
	r2 = 1.;
	r3 = r1 * r1;
	r5 = 2.;
	r3 = r3 / r5;
	r2 = r2 - r3;
	goto label$bd524ea_2_43;
	label$bd524ea_2_42:
	r2 = hl_math_cos(r1);
	label$bd524ea_2_43:
	r3 = r0->angle;
	r5 = r0->localAngle;
	r3 = r3 + r5;
	r5 = 2.;
	r4 = ($Math)g$_Math;
	r6 = r4->PI;
	r5 = r5 * r6;
	r3 = fmod(r3,r5);
	r5 = 2.;
	r4 = ($Math)g$_Math;
	r6 = r4->PI;
	r5 = r5 * r6;
	r3 = fmod(r3,r5);
	r4 = ($Math)g$_Math;
	r6 = r4->PI;
	if( !(r6 < r3) ) goto label$bd524ea_2_66;
	r6 = 2.;
	r4 = ($Math)g$_Math;
	r7 = r4->PI;
	r6 = r6 * r7;
	r5 = r3 - r6;
	r3 = r5;
	goto label$bd524ea_2_76;
	label$bd524ea_2_66:
	r4 = ($Math)g$_Math;
	r6 = r4->PI;
	r6 = -r6;
	if( !(r3 < r6) ) goto label$bd524ea_2_76;
	r6 = 2.;
	r4 = ($Math)g$_Math;
	r7 = r4->PI;
	r6 = r6 * r7;
	r5 = r3 + r6;
	r3 = r5;
	label$bd524ea_2_76:
	r5 = hl_math_abs(r3);
	r6 = 0.5;
	if( !(r5 < r6) ) goto label$bd524ea_2_85;
	r6 = r3 * r3;
	r6 = r6 * r3;
	r7 = 6.;
	r6 = r6 / r7;
	r5 = r3 - r6;
	goto label$bd524ea_2_86;
	label$bd524ea_2_85:
	r5 = hl_math_sin(r3);
	label$bd524ea_2_86:
	r8 = 0.;
	r9 = 0.;
	r10 = 0.;
	r11 = -1.;
	r14 = 24;
	r13 = hl_alloc_bytes(r14);
	r14 = 0;
	r15 = r5 * r11;
	r16 = r8 * r10;
	r15 = r15 - r16;
	r17 = 3;
	r17 = r14 << r17;
	*(double*)(r13 + r17) = r15;
	++r14;
	r15 = r8 * r9;
	r16 = r2 * r11;
	r15 = r15 - r16;
	r17 = 3;
	r17 = r14 << r17;
	*(double*)(r13 + r17) = r15;
	++r14;
	r15 = r2 * r10;
	r16 = r5 * r9;
	r15 = r15 - r16;
	r17 = 3;
	r17 = r14 << r17;
	*(double*)(r13 + r17) = r15;
	++r14;
	r14 = 3;
	r12 = hl_types_ArrayBase_allocF64(r13,r14);
	return r12;
}

void objects_ExtendableObject_addToVelocity(objects__ExtendableObject r0,hl__types__ArrayBytes_Float r1) {
	$Math r5;
	hl__types__ArrayBytes_Float r10, r16;
	double r2, r3, r4, r7, r8, r9, r14, r15, r17;
	vbyte *r13, *r19;
	int r11, r12, r18;
	r2 = r0->angle;
	r3 = r0->localAngle;
	r2 = r2 + r3;
	r3 = 2.;
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	r3 = r3 * r4;
	r2 = fmod(r2,r3);
	r3 = 2.;
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	r3 = r3 * r4;
	r2 = fmod(r2,r3);
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	if( !(r4 < r2) ) goto label$bd524ea_3_23;
	r4 = 2.;
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	r4 = r4 * r7;
	r3 = r2 - r4;
	r2 = r3;
	goto label$bd524ea_3_33;
	label$bd524ea_3_23:
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	r4 = -r4;
	if( !(r2 < r4) ) goto label$bd524ea_3_33;
	r4 = 2.;
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	r4 = r4 * r7;
	r3 = r2 + r4;
	r2 = r3;
	label$bd524ea_3_33:
	r3 = hl_math_abs(r2);
	r4 = 0.5;
	if( !(r3 < r4) ) goto label$bd524ea_3_42;
	r3 = 1.;
	r4 = r2 * r2;
	r7 = 2.;
	r4 = r4 / r7;
	r3 = r3 - r4;
	goto label$bd524ea_3_43;
	label$bd524ea_3_42:
	r3 = hl_math_cos(r2);
	label$bd524ea_3_43:
	r4 = r0->angle;
	r7 = r0->localAngle;
	r4 = r4 + r7;
	r7 = 2.;
	r5 = ($Math)g$_Math;
	r8 = r5->PI;
	r7 = r7 * r8;
	r4 = fmod(r4,r7);
	r7 = 2.;
	r5 = ($Math)g$_Math;
	r8 = r5->PI;
	r7 = r7 * r8;
	r4 = fmod(r4,r7);
	r5 = ($Math)g$_Math;
	r8 = r5->PI;
	if( !(r8 < r4) ) goto label$bd524ea_3_66;
	r8 = 2.;
	r5 = ($Math)g$_Math;
	r9 = r5->PI;
	r8 = r8 * r9;
	r7 = r4 - r8;
	r4 = r7;
	goto label$bd524ea_3_76;
	label$bd524ea_3_66:
	r5 = ($Math)g$_Math;
	r8 = r5->PI;
	r8 = -r8;
	if( !(r4 < r8) ) goto label$bd524ea_3_76;
	r8 = 2.;
	r5 = ($Math)g$_Math;
	r9 = r5->PI;
	r8 = r8 * r9;
	r7 = r4 + r8;
	r4 = r7;
	label$bd524ea_3_76:
	r7 = hl_math_abs(r4);
	r8 = 0.5;
	if( !(r7 < r8) ) goto label$bd524ea_3_85;
	r8 = r4 * r4;
	r8 = r8 * r4;
	r9 = 6.;
	r8 = r8 / r9;
	r7 = r4 - r8;
	goto label$bd524ea_3_86;
	label$bd524ea_3_85:
	r7 = hl_math_sin(r4);
	label$bd524ea_3_86:
	if( r1 == NULL ) hl_null_access();
	r11 = 0;
	r12 = r1->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$bd524ea_3_92;
	r8 = 0.;
	goto label$bd524ea_3_96;
	label$bd524ea_3_92:
	r13 = r1->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r8 = *(double*)(r13 + r12);
	label$bd524ea_3_96:
	r8 = r8 * r3;
	r11 = 1;
	r12 = r1->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$bd524ea_3_102;
	r9 = 0.;
	goto label$bd524ea_3_106;
	label$bd524ea_3_102:
	r13 = r1->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r9 = *(double*)(r13 + r12);
	label$bd524ea_3_106:
	r9 = r9 * r7;
	r8 = r8 - r9;
	r11 = 0;
	r12 = r1->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$bd524ea_3_113;
	r9 = 0.;
	goto label$bd524ea_3_117;
	label$bd524ea_3_113:
	r13 = r1->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r9 = *(double*)(r13 + r12);
	label$bd524ea_3_117:
	r9 = r9 * r7;
	r11 = 1;
	r12 = r1->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$bd524ea_3_123;
	r14 = 0.;
	goto label$bd524ea_3_127;
	label$bd524ea_3_123:
	r13 = r1->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r14 = *(double*)(r13 + r12);
	label$bd524ea_3_127:
	r14 = r14 * r3;
	r9 = r9 + r14;
	r10 = r0->velocity;
	r15 = 0.;
	r11 = 24;
	r13 = hl_alloc_bytes(r11);
	r11 = 0;
	if( r10 == NULL ) hl_null_access();
	r12 = 0;
	r18 = r10->length;
	if( ((unsigned)r12) < ((unsigned)r18) ) goto label$bd524ea_3_140;
	r17 = 0.;
	goto label$bd524ea_3_144;
	label$bd524ea_3_140:
	r19 = r10->bytes;
	r18 = 3;
	r18 = r12 << r18;
	r17 = *(double*)(r19 + r18);
	label$bd524ea_3_144:
	r17 = r17 + r8;
	r12 = 3;
	r12 = r11 << r12;
	*(double*)(r13 + r12) = r17;
	++r11;
	r12 = 1;
	r18 = r10->length;
	if( ((unsigned)r12) < ((unsigned)r18) ) goto label$bd524ea_3_154;
	r17 = 0.;
	goto label$bd524ea_3_158;
	label$bd524ea_3_154:
	r19 = r10->bytes;
	r18 = 3;
	r18 = r12 << r18;
	r17 = *(double*)(r19 + r18);
	label$bd524ea_3_158:
	r17 = r17 + r9;
	r12 = 3;
	r12 = r11 << r12;
	*(double*)(r13 + r12) = r17;
	++r11;
	r12 = 2;
	r18 = r10->length;
	if( ((unsigned)r12) < ((unsigned)r18) ) goto label$bd524ea_3_168;
	r17 = 0.;
	goto label$bd524ea_3_172;
	label$bd524ea_3_168:
	r19 = r10->bytes;
	r18 = 3;
	r18 = r12 << r18;
	r17 = *(double*)(r19 + r18);
	label$bd524ea_3_172:
	r17 = r17 + r15;
	r12 = 3;
	r12 = r11 << r12;
	*(double*)(r13 + r12) = r17;
	++r11;
	r11 = 3;
	r16 = hl_types_ArrayBase_allocF64(r13,r11);
	r0->velocity = r16;
	return;
}

void objects_ExtendableObject_addToVelocityDirect(objects__ExtendableObject r0,hl__types__ArrayBytes_Float r1) {
	hl__types__ArrayBytes_Float r2, r4;
	double r7, r11;
	int r6, r8, r9;
	vbyte *r5, *r10;
	r2 = r0->velocity;
	r6 = 24;
	r5 = hl_alloc_bytes(r6);
	r6 = 0;
	if( r2 == NULL ) hl_null_access();
	r8 = 0;
	r9 = r2->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$bd524ea_4_10;
	r7 = 0.;
	goto label$bd524ea_4_14;
	label$bd524ea_4_10:
	r10 = r2->bytes;
	r9 = 3;
	r9 = r8 << r9;
	r7 = *(double*)(r10 + r9);
	label$bd524ea_4_14:
	if( r1 == NULL ) hl_null_access();
	r8 = 0;
	r9 = r1->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$bd524ea_4_20;
	r11 = 0.;
	goto label$bd524ea_4_24;
	label$bd524ea_4_20:
	r10 = r1->bytes;
	r9 = 3;
	r9 = r8 << r9;
	r11 = *(double*)(r10 + r9);
	label$bd524ea_4_24:
	r7 = r7 + r11;
	r8 = 3;
	r8 = r6 << r8;
	*(double*)(r5 + r8) = r7;
	++r6;
	r8 = 1;
	r9 = r2->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$bd524ea_4_34;
	r7 = 0.;
	goto label$bd524ea_4_38;
	label$bd524ea_4_34:
	r10 = r2->bytes;
	r9 = 3;
	r9 = r8 << r9;
	r7 = *(double*)(r10 + r9);
	label$bd524ea_4_38:
	r8 = 1;
	r9 = r1->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$bd524ea_4_43;
	r11 = 0.;
	goto label$bd524ea_4_47;
	label$bd524ea_4_43:
	r10 = r1->bytes;
	r9 = 3;
	r9 = r8 << r9;
	r11 = *(double*)(r10 + r9);
	label$bd524ea_4_47:
	r7 = r7 + r11;
	r8 = 3;
	r8 = r6 << r8;
	*(double*)(r5 + r8) = r7;
	++r6;
	r8 = 2;
	r9 = r2->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$bd524ea_4_57;
	r7 = 0.;
	goto label$bd524ea_4_61;
	label$bd524ea_4_57:
	r10 = r2->bytes;
	r9 = 3;
	r9 = r8 << r9;
	r7 = *(double*)(r10 + r9);
	label$bd524ea_4_61:
	r8 = 2;
	r9 = r1->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$bd524ea_4_66;
	r11 = 0.;
	goto label$bd524ea_4_70;
	label$bd524ea_4_66:
	r10 = r1->bytes;
	r9 = 3;
	r9 = r8 << r9;
	r11 = *(double*)(r10 + r9);
	label$bd524ea_4_70:
	r7 = r7 + r11;
	r8 = 3;
	r8 = r6 << r8;
	*(double*)(r5 + r8) = r7;
	++r6;
	r6 = 3;
	r4 = hl_types_ArrayBase_allocF64(r5,r6);
	r0->velocity = r4;
	return;
}

hl__types__ArrayObj objects_ExtendableObject_generateConnectors(objects__ExtendableObject r0) {
	hl__types__ArrayObj r22;
	hl_type *r24;
	objects__Connector r7, r14, r18, r25;
	hl__types__ArrayBytes_Float r8;
	double r1, r3, r6, r12, r13, r16, r17, r20, r21;
	int *r11;
	varray *r23;
	vbyte *r9;
	int r2, r5, r10, r15, r19, r26;
	r2 = r0->sizeX;
	r1 = (double)r2;
	r3 = 2.;
	r1 = r1 / r3;
	r2 = (int)r1;
	r2 = -r2;
	r5 = r0->sizeY;
	r3 = (double)r5;
	r6 = 2.;
	r3 = r3 / r6;
	r7 = (objects__Connector)hl_alloc_obj(&t$objects_Connector);
	r5 = 24;
	r9 = hl_alloc_bytes(r5);
	r5 = 0;
	r6 = (double)r2;
	r10 = 3;
	r10 = r5 << r10;
	*(double*)(r9 + r10) = r6;
	++r5;
	r10 = (int)r3;
	r10 = -r10;
	r6 = (double)r10;
	r10 = 3;
	r10 = r5 << r10;
	*(double*)(r9 + r10) = r6;
	++r5;
	r6 = 0.;
	r10 = 3;
	r10 = r5 << r10;
	*(double*)(r9 + r10) = r6;
	++r5;
	r5 = 3;
	r8 = hl_types_ArrayBase_allocF64(r9,r5);
	r11 = NULL;
	objects_Connector_new(r7,r8,r11);
	r5 = r0->sizeX;
	r6 = (double)r5;
	r12 = 2.;
	r6 = r6 / r12;
	r5 = (int)r6;
	r10 = r0->sizeY;
	r12 = (double)r10;
	r13 = 2.;
	r12 = r12 / r13;
	r14 = (objects__Connector)hl_alloc_obj(&t$objects_Connector);
	r10 = 24;
	r9 = hl_alloc_bytes(r10);
	r10 = 0;
	r13 = (double)r5;
	r15 = 3;
	r15 = r10 << r15;
	*(double*)(r9 + r15) = r13;
	++r10;
	r15 = (int)r12;
	r15 = -r15;
	r13 = (double)r15;
	r15 = 3;
	r15 = r10 << r15;
	*(double*)(r9 + r15) = r13;
	++r10;
	r13 = 0.;
	r15 = 3;
	r15 = r10 << r15;
	*(double*)(r9 + r15) = r13;
	++r10;
	r10 = 3;
	r8 = hl_types_ArrayBase_allocF64(r9,r10);
	r11 = NULL;
	objects_Connector_new(r14,r8,r11);
	r10 = r0->sizeX;
	r13 = (double)r10;
	r16 = 2.;
	r13 = r13 / r16;
	r10 = (int)r13;
	r15 = r0->sizeY;
	r16 = (double)r15;
	r17 = 2.;
	r16 = r16 / r17;
	r18 = (objects__Connector)hl_alloc_obj(&t$objects_Connector);
	r15 = 24;
	r9 = hl_alloc_bytes(r15);
	r15 = 0;
	r17 = (double)r10;
	r19 = 3;
	r19 = r15 << r19;
	*(double*)(r9 + r19) = r17;
	++r15;
	r19 = (int)r16;
	r17 = (double)r19;
	r19 = 3;
	r19 = r15 << r19;
	*(double*)(r9 + r19) = r17;
	++r15;
	r17 = 0.;
	r19 = 3;
	r19 = r15 << r19;
	*(double*)(r9 + r19) = r17;
	++r15;
	r15 = 3;
	r8 = hl_types_ArrayBase_allocF64(r9,r15);
	r11 = NULL;
	objects_Connector_new(r18,r8,r11);
	r15 = r0->sizeX;
	r17 = (double)r15;
	r20 = 2.;
	r17 = r17 / r20;
	r15 = (int)r17;
	r15 = -r15;
	r19 = r0->sizeY;
	r20 = (double)r19;
	r21 = 2.;
	r20 = r20 / r21;
	r24 = &t$objects_Connector;
	r19 = 5;
	r23 = hl_alloc_array(r24,r19);
	r19 = 0;
	((objects__Connector*)(r23 + 1))[r19] = r7;
	r19 = 1;
	((objects__Connector*)(r23 + 1))[r19] = r14;
	r19 = 2;
	((objects__Connector*)(r23 + 1))[r19] = r18;
	r25 = (objects__Connector)hl_alloc_obj(&t$objects_Connector);
	r19 = 24;
	r9 = hl_alloc_bytes(r19);
	r19 = 0;
	r21 = (double)r15;
	r26 = 3;
	r26 = r19 << r26;
	*(double*)(r9 + r26) = r21;
	++r19;
	r26 = (int)r20;
	r21 = (double)r26;
	r26 = 3;
	r26 = r19 << r26;
	*(double*)(r9 + r26) = r21;
	++r19;
	r21 = 0.;
	r26 = 3;
	r26 = r19 << r26;
	*(double*)(r9 + r26) = r21;
	++r19;
	r19 = 3;
	r8 = hl_types_ArrayBase_allocF64(r9,r19);
	r11 = NULL;
	objects_Connector_new(r25,r8,r11);
	r19 = 3;
	((objects__Connector*)(r23 + 1))[r19] = r25;
	r25 = (objects__Connector)hl_alloc_obj(&t$objects_Connector);
	r19 = 24;
	r9 = hl_alloc_bytes(r19);
	r19 = 0;
	r21 = 0.;
	r26 = 3;
	r26 = r19 << r26;
	*(double*)(r9 + r26) = r21;
	++r19;
	r21 = 0.;
	r26 = 3;
	r26 = r19 << r26;
	*(double*)(r9 + r26) = r21;
	++r19;
	r21 = 0.;
	r26 = 3;
	r26 = r19 << r26;
	*(double*)(r9 + r26) = r21;
	++r19;
	r19 = 3;
	r8 = hl_types_ArrayBase_allocF64(r9,r19);
	r19 = 2;
	r11 = &r19;
	objects_Connector_new(r25,r8,r11);
	r26 = 4;
	((objects__Connector*)(r23 + 1))[r26] = r25;
	r22 = hl_types_ArrayObj_alloc(r23);
	return r22;
}

hl__types__ArrayObj objects_ExtendableObject_generateLogicConnectors(objects__ExtendableObject r0) {
	hl__types__ArrayObj r1;
	hl_type *r3;
	int r4;
	varray *r2;
	r3 = &t$objects_LogicConnector;
	r4 = 0;
	r2 = hl_alloc_array(r3,r4);
	r1 = hl_types_ArrayObj_alloc(r2);
	return r1;
}

void objects_ExtendableObject_placeAccordingly(objects__ExtendableObject r0,objects__ExtendableObject r1,hl__types__ArrayBytes_Float r2,hl__types__ArrayBytes_Float r3) {
	$Math r7;
	hl__types__ArrayBytes_Float r12;
	double r4, r5, r6, r9, r10, r11, r16, r17, r18, r19, r22;
	vbyte *r15, *r21;
	int r13, r14, r20;
	r4 = r0->angle;
	r5 = r0->localAngle;
	r4 = r4 + r5;
	r5 = 2.;
	r7 = ($Math)g$_Math;
	r6 = r7->PI;
	r5 = r5 * r6;
	r4 = fmod(r4,r5);
	r5 = 2.;
	r7 = ($Math)g$_Math;
	r6 = r7->PI;
	r5 = r5 * r6;
	r4 = fmod(r4,r5);
	r7 = ($Math)g$_Math;
	r6 = r7->PI;
	if( !(r6 < r4) ) goto label$bd524ea_7_23;
	r6 = 2.;
	r7 = ($Math)g$_Math;
	r9 = r7->PI;
	r6 = r6 * r9;
	r5 = r4 - r6;
	r4 = r5;
	goto label$bd524ea_7_33;
	label$bd524ea_7_23:
	r7 = ($Math)g$_Math;
	r6 = r7->PI;
	r6 = -r6;
	if( !(r4 < r6) ) goto label$bd524ea_7_33;
	r6 = 2.;
	r7 = ($Math)g$_Math;
	r9 = r7->PI;
	r6 = r6 * r9;
	r5 = r4 + r6;
	r4 = r5;
	label$bd524ea_7_33:
	r5 = hl_math_abs(r4);
	r6 = 0.5;
	if( !(r5 < r6) ) goto label$bd524ea_7_42;
	r5 = 1.;
	r6 = r4 * r4;
	r9 = 2.;
	r6 = r6 / r9;
	r5 = r5 - r6;
	goto label$bd524ea_7_43;
	label$bd524ea_7_42:
	r5 = hl_math_cos(r4);
	label$bd524ea_7_43:
	r6 = r0->angle;
	r9 = r0->localAngle;
	r6 = r6 + r9;
	r9 = 2.;
	r7 = ($Math)g$_Math;
	r10 = r7->PI;
	r9 = r9 * r10;
	r6 = fmod(r6,r9);
	r9 = 2.;
	r7 = ($Math)g$_Math;
	r10 = r7->PI;
	r9 = r9 * r10;
	r6 = fmod(r6,r9);
	r7 = ($Math)g$_Math;
	r10 = r7->PI;
	if( !(r10 < r6) ) goto label$bd524ea_7_66;
	r10 = 2.;
	r7 = ($Math)g$_Math;
	r11 = r7->PI;
	r10 = r10 * r11;
	r9 = r6 - r10;
	r6 = r9;
	goto label$bd524ea_7_76;
	label$bd524ea_7_66:
	r7 = ($Math)g$_Math;
	r10 = r7->PI;
	r10 = -r10;
	if( !(r6 < r10) ) goto label$bd524ea_7_76;
	r10 = 2.;
	r7 = ($Math)g$_Math;
	r11 = r7->PI;
	r10 = r10 * r11;
	r9 = r6 + r10;
	r6 = r9;
	label$bd524ea_7_76:
	r9 = hl_math_abs(r6);
	r10 = 0.5;
	if( !(r9 < r10) ) goto label$bd524ea_7_85;
	r10 = r6 * r6;
	r10 = r10 * r6;
	r11 = 6.;
	r10 = r10 / r11;
	r9 = r6 - r10;
	goto label$bd524ea_7_86;
	label$bd524ea_7_85:
	r9 = hl_math_sin(r6);
	label$bd524ea_7_86:
	if( r2 == NULL ) hl_null_access();
	r13 = 0;
	r14 = r2->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$bd524ea_7_92;
	r10 = 0.;
	goto label$bd524ea_7_96;
	label$bd524ea_7_92:
	r15 = r2->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r10 = *(double*)(r15 + r14);
	label$bd524ea_7_96:
	if( r3 == NULL ) hl_null_access();
	r13 = 0;
	r14 = r3->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$bd524ea_7_102;
	r11 = 0.;
	goto label$bd524ea_7_106;
	label$bd524ea_7_102:
	r15 = r3->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r11 = *(double*)(r15 + r14);
	label$bd524ea_7_106:
	r10 = r10 - r11;
	r13 = 1;
	r14 = r2->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$bd524ea_7_112;
	r11 = 0.;
	goto label$bd524ea_7_116;
	label$bd524ea_7_112:
	r15 = r2->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r11 = *(double*)(r15 + r14);
	label$bd524ea_7_116:
	r13 = 1;
	r14 = r3->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$bd524ea_7_121;
	r16 = 0.;
	goto label$bd524ea_7_125;
	label$bd524ea_7_121:
	r15 = r3->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r16 = *(double*)(r15 + r14);
	label$bd524ea_7_125:
	r11 = r11 - r16;
	r16 = r10 * r5;
	r17 = r11 * r9;
	r16 = r16 - r17;
	r17 = r10 * r9;
	r18 = r11 * r5;
	r17 = r17 + r18;
	if( r1 == NULL ) hl_null_access();
	r13 = 24;
	r15 = hl_alloc_bytes(r13);
	r13 = 0;
	r12 = r0->pos;
	if( r12 == NULL ) hl_null_access();
	r14 = 0;
	r20 = r12->length;
	if( ((unsigned)r14) < ((unsigned)r20) ) goto label$bd524ea_7_143;
	r18 = 0.;
	goto label$bd524ea_7_147;
	label$bd524ea_7_143:
	r21 = r12->bytes;
	r20 = 3;
	r20 = r14 << r20;
	r18 = *(double*)(r21 + r20);
	label$bd524ea_7_147:
	r18 = r18 + r16;
	r14 = 3;
	r14 = r13 << r14;
	*(double*)(r15 + r14) = r18;
	++r13;
	r12 = r0->pos;
	if( r12 == NULL ) hl_null_access();
	r14 = 1;
	r20 = r12->length;
	if( ((unsigned)r14) < ((unsigned)r20) ) goto label$bd524ea_7_159;
	r18 = 0.;
	goto label$bd524ea_7_163;
	label$bd524ea_7_159:
	r21 = r12->bytes;
	r20 = 3;
	r20 = r14 << r20;
	r18 = *(double*)(r21 + r20);
	label$bd524ea_7_163:
	r18 = r18 + r17;
	r14 = 3;
	r14 = r13 << r14;
	*(double*)(r15 + r14) = r18;
	++r13;
	r18 = 0.;
	r14 = 3;
	r14 = r13 << r14;
	*(double*)(r15 + r14) = r18;
	++r13;
	r13 = 3;
	r12 = hl_types_ArrayBase_allocF64(r15,r13);
	r1->pos = r12;
	r18 = r0->angle;
	r19 = r0->localAngle;
	r18 = r18 + r19;
	r19 = 2.;
	r7 = ($Math)g$_Math;
	r22 = r7->PI;
	r19 = r19 * r22;
	r18 = fmod(r18,r19);
	r1->angle = r18;
	return;
}

void objects_ExtendableObject_calculateMechanics(objects__ExtendableObject r0,double r1) {
	hl__types__ArrayObj r4, r6;
	objects__ExtendableObject r11;
	bool r10;
	double r12, r13, r14;
	vdynamic *r8;
	varray *r9;
	objects__Neighbor r7;
	int r3, r5, r15;
	r4 = r0->neighbors;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->length;
	r5 = 0;
	if( r3 == r5 ) goto label$bd524ea_8_52;
	r4 = r0->neighbors;
	if( r4 == NULL ) hl_null_access();
	r6 = r0->neighbors;
	if( r6 == NULL ) hl_null_access();
	r3 = r6->length;
	r3 = Std_random(r3);
	r5 = r4->length;
	if( ((unsigned)r3) < ((unsigned)r5) ) goto label$bd524ea_8_15;
	r7 = NULL;
	goto label$bd524ea_8_18;
	label$bd524ea_8_15:
	r9 = r4->array;
	r8 = ((vdynamic**)(r9 + 1))[r3];
	r7 = (objects__Neighbor)r8;
	label$bd524ea_8_18:
	if( r7 == NULL ) hl_null_access();
	r11 = r7->obj;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->gasPassable;
	if( !r10 ) goto label$bd524ea_8_52;
	r12 = r0->o2;
	r11 = r7->obj;
	if( r11 == NULL ) hl_null_access();
	r13 = r11->o2;
	r12 = r12 - r13;
	r12 = hl_math_abs(r12);
	r12 = r12 * r1;
	r11 = r7->obj;
	if( r11 == NULL ) hl_null_access();
	r13 = r11->o2;
	r14 = r0->o2;
	if( !(r13 < r14) ) goto label$bd524ea_8_44;
	r11 = r7->obj;
	if( r11 == NULL ) hl_null_access();
	r13 = r11->o2;
	r13 = r13 + r12;
	r11->o2 = r13;
	r13 = r0->o2;
	r13 = r13 - r12;
	r0->o2 = r13;
	goto label$bd524ea_8_52;
	label$bd524ea_8_44:
	r11 = r7->obj;
	if( r11 == NULL ) hl_null_access();
	r13 = r11->o2;
	r13 = r13 - r12;
	r11->o2 = r13;
	r13 = r0->o2;
	r13 = r13 + r12;
	r0->o2 = r13;
	label$bd524ea_8_52:
	r4 = r0->neighborsFuel;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->length;
	r5 = 0;
	if( r3 == r5 ) goto label$bd524ea_8_104;
	r3 = 0;
	r4 = r0->neighborsFuel;
	label$bd524ea_8_59:
	if( r4 == NULL ) hl_null_access();
	r15 = r4->length;
	if( r3 >= r15 ) goto label$bd524ea_8_104;
	r15 = r4->length;
	if( ((unsigned)r3) < ((unsigned)r15) ) goto label$bd524ea_8_67;
	r7 = NULL;
	goto label$bd524ea_8_70;
	label$bd524ea_8_67:
	r9 = r4->array;
	r8 = ((vdynamic**)(r9 + 1))[r3];
	r7 = (objects__Neighbor)r8;
	label$bd524ea_8_70:
	++r3;
	r12 = r0->fuel;
	if( r7 == NULL ) hl_null_access();
	r11 = r7->obj;
	if( r11 == NULL ) hl_null_access();
	r13 = r11->fuel;
	r12 = r12 - r13;
	r12 = hl_math_abs(r12);
	r12 = r12 * r1;
	r13 = 0.01;
	r12 = r12 * r13;
	r11 = r7->obj;
	if( r11 == NULL ) hl_null_access();
	r13 = r11->fuel;
	r14 = r0->fuel;
	if( !(r13 < r14) ) goto label$bd524ea_8_95;
	r11 = r7->obj;
	if( r11 == NULL ) hl_null_access();
	r13 = r11->fuel;
	r13 = r13 + r12;
	r11->fuel = r13;
	r13 = r0->fuel;
	r13 = r13 - r12;
	r0->fuel = r13;
	goto label$bd524ea_8_103;
	label$bd524ea_8_95:
	r11 = r7->obj;
	if( r11 == NULL ) hl_null_access();
	r13 = r11->fuel;
	r13 = r13 - r12;
	r11->fuel = r13;
	r13 = r0->fuel;
	r13 = r13 + r12;
	r0->fuel = r13;
	label$bd524ea_8_103:
	goto label$bd524ea_8_59;
	label$bd524ea_8_104:
	return;
}

void objects_ExtendableObject_rotateConnected(objects__ExtendableObject r0,double r1) {
	vdynobj *r33;
	String r32, r34;
	vvirtual *r35;
	hl__types__ArrayObj r5;
	objects__ExtendableObject r10;
	bool r36;
	haxe__$Log r31;
	$Math r16;
	hl__types__ArrayBytes_Float r11, r12, r20;
	vclosure *r30;
	double r13, r14, r15, r17, r18, r19, r22, r23, r24, r25, r28;
	vdynamic *r6, *r29;
	vbyte *r21, *r27;
	varray *r9;
	objects__ConnectorLink r8;
	int r2, r4, r7, r26;
	hl_trap_ctx trap$0;
	r2 = -1;
	label$bd524ea_9_1:
	++r2;
	r5 = r0->linked;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->length;
	if( r2 >= r4 ) goto label$bd524ea_9_265;
	hl_trap(trap$0,r6,label$bd524ea_9_244);
	r5 = r0->linked;
	if( r5 == NULL ) hl_null_access();
	r7 = r5->length;
	if( ((unsigned)r2) < ((unsigned)r7) ) goto label$bd524ea_9_14;
	r8 = NULL;
	goto label$bd524ea_9_17;
	label$bd524ea_9_14:
	r9 = r5->array;
	r6 = ((vdynamic**)(r9 + 1))[r2];
	r8 = (objects__ConnectorLink)r6;
	label$bd524ea_9_17:
	if( r8 == NULL ) hl_null_access();
	r10 = r8->connected;
	r11 = r8->from;
	r12 = r8->to;
	r13 = r0->angle;
	r14 = r0->localAngle;
	r13 = r13 + r14;
	r14 = 2.;
	r16 = ($Math)g$_Math;
	r15 = r16->PI;
	r14 = r14 * r15;
	r13 = fmod(r13,r14);
	r14 = 2.;
	r16 = ($Math)g$_Math;
	r15 = r16->PI;
	r14 = r14 * r15;
	r13 = fmod(r13,r14);
	r16 = ($Math)g$_Math;
	r15 = r16->PI;
	if( !(r15 < r13) ) goto label$bd524ea_9_44;
	r15 = 2.;
	r16 = ($Math)g$_Math;
	r17 = r16->PI;
	r15 = r15 * r17;
	r14 = r13 - r15;
	r13 = r14;
	goto label$bd524ea_9_54;
	label$bd524ea_9_44:
	r16 = ($Math)g$_Math;
	r15 = r16->PI;
	r15 = -r15;
	if( !(r13 < r15) ) goto label$bd524ea_9_54;
	r15 = 2.;
	r16 = ($Math)g$_Math;
	r17 = r16->PI;
	r15 = r15 * r17;
	r14 = r13 + r15;
	r13 = r14;
	label$bd524ea_9_54:
	r14 = hl_math_abs(r13);
	r15 = 0.5;
	if( !(r14 < r15) ) goto label$bd524ea_9_63;
	r14 = 1.;
	r15 = r13 * r13;
	r17 = 2.;
	r15 = r15 / r17;
	r14 = r14 - r15;
	goto label$bd524ea_9_64;
	label$bd524ea_9_63:
	r14 = hl_math_cos(r13);
	label$bd524ea_9_64:
	r15 = r0->angle;
	r17 = r0->localAngle;
	r15 = r15 + r17;
	r17 = 2.;
	r16 = ($Math)g$_Math;
	r18 = r16->PI;
	r17 = r17 * r18;
	r15 = fmod(r15,r17);
	r17 = 2.;
	r16 = ($Math)g$_Math;
	r18 = r16->PI;
	r17 = r17 * r18;
	r15 = fmod(r15,r17);
	r16 = ($Math)g$_Math;
	r18 = r16->PI;
	if( !(r18 < r15) ) goto label$bd524ea_9_87;
	r18 = 2.;
	r16 = ($Math)g$_Math;
	r19 = r16->PI;
	r18 = r18 * r19;
	r17 = r15 - r18;
	r15 = r17;
	goto label$bd524ea_9_97;
	label$bd524ea_9_87:
	r16 = ($Math)g$_Math;
	r18 = r16->PI;
	r18 = -r18;
	if( !(r15 < r18) ) goto label$bd524ea_9_97;
	r18 = 2.;
	r16 = ($Math)g$_Math;
	r19 = r16->PI;
	r18 = r18 * r19;
	r17 = r15 + r18;
	r15 = r17;
	label$bd524ea_9_97:
	r17 = hl_math_abs(r15);
	r18 = 0.5;
	if( !(r17 < r18) ) goto label$bd524ea_9_106;
	r18 = r15 * r15;
	r18 = r18 * r15;
	r19 = 6.;
	r18 = r18 / r19;
	r17 = r15 - r18;
	goto label$bd524ea_9_107;
	label$bd524ea_9_106:
	r17 = hl_math_sin(r15);
	label$bd524ea_9_107:
	if( r11 == NULL ) hl_null_access();
	r4 = 0;
	r7 = r11->length;
	if( ((unsigned)r4) < ((unsigned)r7) ) goto label$bd524ea_9_113;
	r18 = 0.;
	goto label$bd524ea_9_117;
	label$bd524ea_9_113:
	r21 = r11->bytes;
	r7 = 3;
	r7 = r4 << r7;
	r18 = *(double*)(r21 + r7);
	label$bd524ea_9_117:
	if( r12 == NULL ) hl_null_access();
	r4 = 0;
	r7 = r12->length;
	if( ((unsigned)r4) < ((unsigned)r7) ) goto label$bd524ea_9_123;
	r19 = 0.;
	goto label$bd524ea_9_127;
	label$bd524ea_9_123:
	r21 = r12->bytes;
	r7 = 3;
	r7 = r4 << r7;
	r19 = *(double*)(r21 + r7);
	label$bd524ea_9_127:
	r18 = r18 - r19;
	r4 = 1;
	r7 = r11->length;
	if( ((unsigned)r4) < ((unsigned)r7) ) goto label$bd524ea_9_133;
	r19 = 0.;
	goto label$bd524ea_9_137;
	label$bd524ea_9_133:
	r21 = r11->bytes;
	r7 = 3;
	r7 = r4 << r7;
	r19 = *(double*)(r21 + r7);
	label$bd524ea_9_137:
	r4 = 1;
	r7 = r12->length;
	if( ((unsigned)r4) < ((unsigned)r7) ) goto label$bd524ea_9_142;
	r22 = 0.;
	goto label$bd524ea_9_146;
	label$bd524ea_9_142:
	r21 = r12->bytes;
	r7 = 3;
	r7 = r4 << r7;
	r22 = *(double*)(r21 + r7);
	label$bd524ea_9_146:
	r19 = r19 - r22;
	r22 = r18 * r14;
	r23 = r19 * r17;
	r22 = r22 - r23;
	r23 = r18 * r17;
	r24 = r19 * r14;
	r23 = r23 + r24;
	if( r10 == NULL ) hl_null_access();
	r4 = 24;
	r21 = hl_alloc_bytes(r4);
	r4 = 0;
	r20 = r0->pos;
	if( r20 == NULL ) hl_null_access();
	r7 = 0;
	r26 = r20->length;
	if( ((unsigned)r7) < ((unsigned)r26) ) goto label$bd524ea_9_164;
	r24 = 0.;
	goto label$bd524ea_9_168;
	label$bd524ea_9_164:
	r27 = r20->bytes;
	r26 = 3;
	r26 = r7 << r26;
	r24 = *(double*)(r27 + r26);
	label$bd524ea_9_168:
	r24 = r24 + r22;
	r7 = 3;
	r7 = r4 << r7;
	*(double*)(r21 + r7) = r24;
	++r4;
	r20 = r0->pos;
	if( r20 == NULL ) hl_null_access();
	r7 = 1;
	r26 = r20->length;
	if( ((unsigned)r7) < ((unsigned)r26) ) goto label$bd524ea_9_180;
	r24 = 0.;
	goto label$bd524ea_9_184;
	label$bd524ea_9_180:
	r27 = r20->bytes;
	r26 = 3;
	r26 = r7 << r26;
	r24 = *(double*)(r27 + r26);
	label$bd524ea_9_184:
	r24 = r24 + r23;
	r7 = 3;
	r7 = r4 << r7;
	*(double*)(r21 + r7) = r24;
	++r4;
	r24 = 0.;
	r7 = 3;
	r7 = r4 << r7;
	*(double*)(r21 + r7) = r24;
	++r4;
	r4 = 3;
	r20 = hl_types_ArrayBase_allocF64(r21,r4);
	r10->pos = r20;
	r24 = r0->angle;
	r25 = r0->localAngle;
	r24 = r24 + r25;
	r25 = 2.;
	r16 = ($Math)g$_Math;
	r28 = r16->PI;
	r25 = r25 * r28;
	r24 = fmod(r24,r25);
	r10->angle = r24;
	r13 = r0->heat;
	r14 = r10->heat;
	r13 = r13 - r14;
	r14 = r0->heatConductivityF;
	r13 = r13 * r14;
	r13 = r13 * r1;
	r14 = 0.10000000000000001;
	r13 = r13 * r14;
	r14 = r10->heat;
	r14 = r14 + r13;
	r10->heat = r14;
	r14 = r0->heat;
	r14 = r14 - r13;
	r0->heat = r14;
	r14 = r0->current;
	r15 = r10->current;
	r14 = r14 - r15;
	r14 = hl_math_abs(r14);
	r15 = r0->currentConductivity;
	r14 = r14 * r15;
	r15 = r10->current;
	r17 = r0->current;
	if( !(r15 < r17) ) goto label$bd524ea_9_236;
	r15 = r10->current;
	r15 = r15 + r14;
	r10->current = r15;
	r15 = r0->current;
	r15 = r15 - r14;
	r0->current = r15;
	goto label$bd524ea_9_242;
	label$bd524ea_9_236:
	r15 = r10->current;
	r15 = r15 - r14;
	r10->current = r15;
	r15 = r0->current;
	r15 = r15 + r14;
	r0->current = r15;
	label$bd524ea_9_242:
	hl_endtrap(trap$0);
	goto label$bd524ea_9_264;
	label$bd524ea_9_244:
	r29 = NULL;
	r31 = (haxe__$Log)g$_haxe_Log;
	r30 = r31->trace;
	if( r30 == NULL ) hl_null_access();
	r32 = (String)s$Error_;
	r33 = hl_alloc_dynobj();
	r34 = (String)s$_objects_Extendable_hx;
	hl_dyn_setp((vdynamic*)r33,37969014/*fileName*/,&t$String,r34);
	r4 = 255;
	hl_dyn_seti((vdynamic*)r33,371360620/*lineNumber*/,&t$_i32,r4);
	r34 = (String)s$objects_ExtendableObject;
	hl_dyn_setp((vdynamic*)r33,-63073762/*className*/,&t$String,r34);
	r34 = (String)s$rotateConnected;
	hl_dyn_setp((vdynamic*)r33,302979532/*methodName*/,&t$String,r34);
	r35 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r33);
	r30->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r30->fun)((vdynamic*)r30->value,((vdynamic*)r32),r35) : ((void (*)(vdynamic*,vvirtual*))r30->fun)(((vdynamic*)r32),r35);
	r32 = (String)s$Failed_to_link_extendable_;
	r34 = Std_string(r6);
	r32 = String___add__(r32,r34);
	hl_throw((vdynamic*)r32);
	label$bd524ea_9_264:
	goto label$bd524ea_9_1;
	label$bd524ea_9_265:
	r36 = r0->isBroken;
	if( r36 ) goto label$bd524ea_9_305;
	r13 = r0->heat;
	r14 = 10000000.;
	r15 = r0->heat;
	r14 = r14 - r15;
	r15 = 1000000.;
	r14 = r14 / r15;
	r15 = 1360.;
	r14 = r14 * r15;
	r15 = r0->heatInF;
	r14 = r14 * r15;
	r14 = r14 * r1;
	r15 = 0.10000000000000001;
	r14 = r14 * r15;
	r13 = r13 + r14;
	r0->heat = r13;
	r13 = r0->heat;
	r14 = -300000.;
	r15 = r0->heat;
	r14 = r14 - r15;
	r15 = -300000.;
	r14 = r14 / r15;
	r15 = r0->heat;
	r14 = r14 * r15;
	r15 = r0->heatOutF;
	r14 = r14 * r15;
	r14 = r14 * r1;
	r15 = 0.10000000000000001;
	r14 = r14 * r15;
	r13 = r13 - r14;
	r0->heat = r13;
	r13 = r0->current;
	r14 = r0->currentGeneration;
	r14 = r14 * r1;
	r15 = 0.10000000000000001;
	r14 = r14 * r15;
	r13 = r13 + r14;
	r0->current = r13;
	goto label$bd524ea_9_312;
	label$bd524ea_9_305:
	r13 = 0.;
	r14 = r0->health;
	r17 = 0.002;
	r15 = r1 * r17;
	r14 = r14 - r15;
	r13 = Math_max(r13,r14);
	r0->health = r13;
	label$bd524ea_9_312:
	return;
}

void objects_ExtendableObject_draw(objects__ExtendableObject r0) {
	String r3, r11;
	hl__Class r4;
	hl__types__ArrayObj r22;
	bool r2;
	objects__LogicConnector r25;
	double r9, r13;
	vdynamic *r20;
	int *r8;
	varray *r26;
	vbyte *r10;
	int r5, r6, r7, r12, r14, r15, r16, r17, r18, r19, r21, r23, r24;
	r2 = r0->selected;
	if( !r2 ) goto label$bd524ea_10_98;
	r4 = Type_getClass(((vdynamic*)r0));
	r3 = Type_getClassName(r4);
	r5 = 500;
	r6 = 136;
	r7 = 3023651;
	r8 = &r7;
	util_FontManager_drawText(r3,r5,r6,r8);
	r3 = (String)s$Fuel_;
	r9 = r0->fuel;
	r8 = &r5;
	r10 = hl_ftos(r9,r8);
	r11 = String___alloc__(r10,r5);
	r3 = String___add__(r3,r11);
	r5 = 500;
	r6 = 118;
	r12 = 3023651;
	r8 = &r12;
	util_FontManager_drawText(r3,r5,r6,r8);
	r3 = (String)s$Temperature_;
	r9 = r0->heat;
	r13 = 1000.;
	r9 = r9 / r13;
	r8 = &r5;
	r10 = hl_ftos(r9,r8);
	r11 = String___alloc__(r10,r5);
	r3 = String___add__(r3,r11);
	r5 = 500;
	r6 = 100;
	r14 = 2432799;
	r8 = &r14;
	util_FontManager_drawText(r3,r5,r6,r8);
	r3 = (String)s$Conductivity_F_;
	r9 = r0->heatConductivityF;
	r8 = &r5;
	r10 = hl_ftos(r9,r8);
	r11 = String___alloc__(r10,r5);
	r3 = String___add__(r3,r11);
	r5 = 500;
	r6 = 82;
	r15 = 3023651;
	r8 = &r15;
	util_FontManager_drawText(r3,r5,r6,r8);
	r3 = (String)s$Absorptivity_F_;
	r9 = r0->heatInF;
	r8 = &r5;
	r10 = hl_ftos(r9,r8);
	r11 = String___alloc__(r10,r5);
	r3 = String___add__(r3,r11);
	r5 = 500;
	r6 = 64;
	r16 = 3023651;
	r8 = &r16;
	util_FontManager_drawText(r3,r5,r6,r8);
	r3 = (String)s$Emission_F_;
	r9 = r0->heatOutF;
	r8 = &r5;
	r10 = hl_ftos(r9,r8);
	r11 = String___alloc__(r10,r5);
	r3 = String___add__(r3,r11);
	r5 = 500;
	r6 = 46;
	r17 = 3023651;
	r8 = &r17;
	util_FontManager_drawText(r3,r5,r6,r8);
	r3 = (String)s$Current_;
	r9 = r0->current;
	r8 = &r5;
	r10 = hl_ftos(r9,r8);
	r11 = String___alloc__(r10,r5);
	r3 = String___add__(r3,r11);
	r5 = 500;
	r6 = 28;
	r18 = 3023651;
	r8 = &r18;
	util_FontManager_drawText(r3,r5,r6,r8);
	r3 = (String)s$O2_;
	r9 = r0->o2;
	r8 = &r5;
	r10 = hl_ftos(r9,r8);
	r11 = String___alloc__(r10,r5);
	r3 = String___add__(r3,r11);
	r5 = 500;
	r6 = 10;
	r19 = 3023651;
	r8 = &r19;
	util_FontManager_drawText(r3,r5,r6,r8);
	r3 = (String)s$Broken_;
	r2 = r0->isBroken;
	r20 = hl_alloc_dynbool(r2);
	r11 = Std_string(r20);
	r3 = String___add__(r3,r11);
	r5 = 500;
	r6 = -8;
	r21 = 3023651;
	r8 = &r21;
	util_FontManager_drawText(r3,r5,r6,r8);
	label$bd524ea_10_98:
	r5 = 0;
	r22 = r0->logicConnectors;
	if( r22 == NULL ) hl_null_access();
	r6 = r22->length;
	label$bd524ea_10_102:
	if( r5 >= r6 ) goto label$bd524ea_10_118;
	r23 = r5;
	++r5;
	r22 = r0->logicConnectors;
	if( r22 == NULL ) hl_null_access();
	r24 = r22->length;
	if( ((unsigned)r23) < ((unsigned)r24) ) goto label$bd524ea_10_112;
	r25 = NULL;
	goto label$bd524ea_10_115;
	label$bd524ea_10_112:
	r26 = r22->array;
	r20 = ((vdynamic**)(r26 + 1))[r23];
	r25 = (objects__LogicConnector)r20;
	label$bd524ea_10_115:
	if( r25 == NULL ) hl_null_access();
	objects_LogicConnector_draw(r25);
	goto label$bd524ea_10_102;
	label$bd524ea_10_118:
	Object_draw(((Object)r0));
	return;
}

hl__types__ArrayBytes_Float objects_ExtendableObject_getConnectorWorldPos(objects__ExtendableObject r0,hl__types__ArrayBytes_Float r1) {
	$Math r5;
	hl__types__ArrayBytes_Float r9;
	double r2, r3, r4, r6, r7, r8, r13;
	vbyte *r12;
	int r10, r11;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->angle;
	r3 = r0->localAngle;
	r2 = r2 + r3;
	r3 = 2.;
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	r3 = r3 * r4;
	r2 = fmod(r2,r3);
	r3 = 2.;
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	r3 = r3 * r4;
	r2 = fmod(r2,r3);
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	if( !(r4 < r2) ) goto label$bd524ea_11_24;
	r4 = 2.;
	r5 = ($Math)g$_Math;
	r6 = r5->PI;
	r4 = r4 * r6;
	r3 = r2 - r4;
	r2 = r3;
	goto label$bd524ea_11_34;
	label$bd524ea_11_24:
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	r4 = -r4;
	if( !(r2 < r4) ) goto label$bd524ea_11_34;
	r4 = 2.;
	r5 = ($Math)g$_Math;
	r6 = r5->PI;
	r4 = r4 * r6;
	r3 = r2 + r4;
	r2 = r3;
	label$bd524ea_11_34:
	r3 = hl_math_abs(r2);
	r4 = 0.5;
	if( !(r3 < r4) ) goto label$bd524ea_11_43;
	r3 = 1.;
	r4 = r2 * r2;
	r6 = 2.;
	r4 = r4 / r6;
	r3 = r3 - r4;
	goto label$bd524ea_11_44;
	label$bd524ea_11_43:
	r3 = hl_math_cos(r2);
	label$bd524ea_11_44:
	r4 = r0->angle;
	r6 = r0->localAngle;
	r4 = r4 + r6;
	r6 = 2.;
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	r6 = r6 * r7;
	r4 = fmod(r4,r6);
	r6 = 2.;
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	r6 = r6 * r7;
	r4 = fmod(r4,r6);
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	if( !(r7 < r4) ) goto label$bd524ea_11_67;
	r7 = 2.;
	r5 = ($Math)g$_Math;
	r8 = r5->PI;
	r7 = r7 * r8;
	r6 = r4 - r7;
	r4 = r6;
	goto label$bd524ea_11_77;
	label$bd524ea_11_67:
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	r7 = -r7;
	if( !(r4 < r7) ) goto label$bd524ea_11_77;
	r7 = 2.;
	r5 = ($Math)g$_Math;
	r8 = r5->PI;
	r7 = r7 * r8;
	r6 = r4 + r7;
	r4 = r6;
	label$bd524ea_11_77:
	r6 = hl_math_abs(r4);
	r7 = 0.5;
	if( !(r6 < r7) ) goto label$bd524ea_11_86;
	r7 = r4 * r4;
	r7 = r7 * r4;
	r8 = 6.;
	r7 = r7 / r8;
	r6 = r4 - r7;
	goto label$bd524ea_11_87;
	label$bd524ea_11_86:
	r6 = hl_math_sin(r4);
	label$bd524ea_11_87:
	r9 = r0->pos;
	if( r9 == NULL ) hl_null_access();
	r10 = 0;
	r11 = r9->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_11_94;
	r7 = 0.;
	goto label$bd524ea_11_98;
	label$bd524ea_11_94:
	r12 = r9->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r7 = *(double*)(r12 + r11);
	label$bd524ea_11_98:
	if( r1 == NULL ) hl_null_access();
	r10 = 0;
	r11 = r1->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_11_104;
	r8 = 0.;
	goto label$bd524ea_11_108;
	label$bd524ea_11_104:
	r12 = r1->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r8 = *(double*)(r12 + r11);
	label$bd524ea_11_108:
	r8 = r8 * r3;
	r7 = r7 + r8;
	r10 = 1;
	r11 = r1->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_11_115;
	r8 = 0.;
	goto label$bd524ea_11_119;
	label$bd524ea_11_115:
	r12 = r1->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r8 = *(double*)(r12 + r11);
	label$bd524ea_11_119:
	r8 = r8 * r6;
	r7 = r7 - r8;
	r9 = r0->pos;
	if( r9 == NULL ) hl_null_access();
	r10 = 1;
	r11 = r9->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_11_128;
	r8 = 0.;
	goto label$bd524ea_11_132;
	label$bd524ea_11_128:
	r12 = r9->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r8 = *(double*)(r12 + r11);
	label$bd524ea_11_132:
	r10 = 0;
	r11 = r1->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_11_137;
	r13 = 0.;
	goto label$bd524ea_11_141;
	label$bd524ea_11_137:
	r12 = r1->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r13 = *(double*)(r12 + r11);
	label$bd524ea_11_141:
	r13 = r13 * r6;
	r8 = r8 + r13;
	r10 = 1;
	r11 = r1->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_11_148;
	r13 = 0.;
	goto label$bd524ea_11_152;
	label$bd524ea_11_148:
	r12 = r1->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r13 = *(double*)(r12 + r11);
	label$bd524ea_11_152:
	r13 = r13 * r3;
	r8 = r8 + r13;
	r10 = 24;
	r12 = hl_alloc_bytes(r10);
	r10 = 0;
	r11 = 3;
	r11 = r10 << r11;
	*(double*)(r12 + r11) = r7;
	++r10;
	r11 = 3;
	r11 = r10 << r11;
	*(double*)(r12 + r11) = r8;
	++r10;
	r13 = 0.;
	r11 = 3;
	r11 = r10 << r11;
	*(double*)(r12 + r11) = r13;
	++r10;
	r10 = 3;
	r9 = hl_types_ArrayBase_allocF64(r12,r10);
	return r9;
}

hl__types__ArrayBytes_Float objects_ExtendableObject_getConnectorWorldPosThis(objects__ExtendableObject r0,hl__types__ArrayBytes_Float r1) {
	$Math r5;
	hl__types__ArrayBytes_Float r9;
	double r2, r3, r4, r6, r7, r8, r13;
	vbyte *r12;
	int r10, r11;
	r2 = r0->angle;
	r3 = r0->localAngle;
	r2 = r2 + r3;
	r3 = 2.;
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	r3 = r3 * r4;
	r2 = fmod(r2,r3);
	r3 = 2.;
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	r3 = r3 * r4;
	r2 = fmod(r2,r3);
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	if( !(r4 < r2) ) goto label$bd524ea_12_23;
	r4 = 2.;
	r5 = ($Math)g$_Math;
	r6 = r5->PI;
	r4 = r4 * r6;
	r3 = r2 - r4;
	r2 = r3;
	goto label$bd524ea_12_33;
	label$bd524ea_12_23:
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	r4 = -r4;
	if( !(r2 < r4) ) goto label$bd524ea_12_33;
	r4 = 2.;
	r5 = ($Math)g$_Math;
	r6 = r5->PI;
	r4 = r4 * r6;
	r3 = r2 + r4;
	r2 = r3;
	label$bd524ea_12_33:
	r3 = hl_math_abs(r2);
	r4 = 0.5;
	if( !(r3 < r4) ) goto label$bd524ea_12_42;
	r3 = 1.;
	r4 = r2 * r2;
	r6 = 2.;
	r4 = r4 / r6;
	r3 = r3 - r4;
	goto label$bd524ea_12_43;
	label$bd524ea_12_42:
	r3 = hl_math_cos(r2);
	label$bd524ea_12_43:
	r4 = r0->angle;
	r6 = r0->localAngle;
	r4 = r4 + r6;
	r6 = 2.;
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	r6 = r6 * r7;
	r4 = fmod(r4,r6);
	r6 = 2.;
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	r6 = r6 * r7;
	r4 = fmod(r4,r6);
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	if( !(r7 < r4) ) goto label$bd524ea_12_66;
	r7 = 2.;
	r5 = ($Math)g$_Math;
	r8 = r5->PI;
	r7 = r7 * r8;
	r6 = r4 - r7;
	r4 = r6;
	goto label$bd524ea_12_76;
	label$bd524ea_12_66:
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	r7 = -r7;
	if( !(r4 < r7) ) goto label$bd524ea_12_76;
	r7 = 2.;
	r5 = ($Math)g$_Math;
	r8 = r5->PI;
	r7 = r7 * r8;
	r6 = r4 + r7;
	r4 = r6;
	label$bd524ea_12_76:
	r6 = hl_math_abs(r4);
	r7 = 0.5;
	if( !(r6 < r7) ) goto label$bd524ea_12_85;
	r7 = r4 * r4;
	r7 = r7 * r4;
	r8 = 6.;
	r7 = r7 / r8;
	r6 = r4 - r7;
	goto label$bd524ea_12_86;
	label$bd524ea_12_85:
	r6 = hl_math_sin(r4);
	label$bd524ea_12_86:
	r9 = r0->pos;
	if( r9 == NULL ) hl_null_access();
	r10 = 0;
	r11 = r9->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_12_93;
	r7 = 0.;
	goto label$bd524ea_12_97;
	label$bd524ea_12_93:
	r12 = r9->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r7 = *(double*)(r12 + r11);
	label$bd524ea_12_97:
	if( r1 == NULL ) hl_null_access();
	r10 = 0;
	r11 = r1->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_12_103;
	r8 = 0.;
	goto label$bd524ea_12_107;
	label$bd524ea_12_103:
	r12 = r1->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r8 = *(double*)(r12 + r11);
	label$bd524ea_12_107:
	r8 = r8 * r3;
	r7 = r7 + r8;
	r10 = 1;
	r11 = r1->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_12_114;
	r8 = 0.;
	goto label$bd524ea_12_118;
	label$bd524ea_12_114:
	r12 = r1->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r8 = *(double*)(r12 + r11);
	label$bd524ea_12_118:
	r8 = r8 * r6;
	r7 = r7 - r8;
	r9 = r0->pos;
	if( r9 == NULL ) hl_null_access();
	r10 = 1;
	r11 = r9->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_12_127;
	r8 = 0.;
	goto label$bd524ea_12_131;
	label$bd524ea_12_127:
	r12 = r9->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r8 = *(double*)(r12 + r11);
	label$bd524ea_12_131:
	r10 = 0;
	r11 = r1->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_12_136;
	r13 = 0.;
	goto label$bd524ea_12_140;
	label$bd524ea_12_136:
	r12 = r1->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r13 = *(double*)(r12 + r11);
	label$bd524ea_12_140:
	r13 = r13 * r6;
	r8 = r8 + r13;
	r10 = 1;
	r11 = r1->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$bd524ea_12_147;
	r13 = 0.;
	goto label$bd524ea_12_151;
	label$bd524ea_12_147:
	r12 = r1->bytes;
	r11 = 3;
	r11 = r10 << r11;
	r13 = *(double*)(r12 + r11);
	label$bd524ea_12_151:
	r13 = r13 * r3;
	r8 = r8 + r13;
	r10 = 24;
	r12 = hl_alloc_bytes(r10);
	r10 = 0;
	r11 = 3;
	r11 = r10 << r11;
	*(double*)(r12 + r11) = r7;
	++r10;
	r11 = 3;
	r11 = r10 << r11;
	*(double*)(r12 + r11) = r8;
	++r10;
	r13 = 0.;
	r11 = 3;
	r11 = r10 << r11;
	*(double*)(r12 + r11) = r13;
	++r10;
	r10 = 3;
	r9 = hl_types_ArrayBase_allocF64(r12,r10);
	return r9;
}

void objects_ExtendableObject_select(objects__ExtendableObject r0,bool r1) {
	bool *r14;
	$Game r5;
	hl__types__ArrayObj r7;
	objects__ExtendableObject r13;
	bool r3;
	hl__types__ArrayBytes_Float r4;
	int *r15;
	vdynamic *r11;
	varray *r12;
	objects__ConnectorLink r10;
	int r6, r8, r9;
	if( !r1 ) goto label$bd524ea_13_28;
	r5 = ($Game)g$_Game;
	r4 = r5->worldPos;
	r5 = ($Game)g$_Game;
	r5->worldPosClicked = r4;
	r6 = 0;
	r7 = r0->linked;
	label$bd524ea_13_7:
	if( r7 == NULL ) hl_null_access();
	r9 = r7->length;
	if( r6 >= r9 ) goto label$bd524ea_13_28;
	r9 = r7->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$bd524ea_13_15;
	r10 = NULL;
	goto label$bd524ea_13_18;
	label$bd524ea_13_15:
	r12 = r7->array;
	r11 = ((vdynamic**)(r12 + 1))[r6];
	r10 = (objects__ConnectorLink)r11;
	label$bd524ea_13_18:
	++r6;
	if( r10 == NULL ) hl_null_access();
	r13 = r10->connected;
	if( r13 == NULL ) hl_null_access();
	r3 = true;
	r14 = &r3;
	r8 = 2903205;
	r15 = &r8;
	Object_setOutline(((Object)r13),r14,r15);
	goto label$bd524ea_13_7;
	label$bd524ea_13_28:
	Object_select(((Object)r0),r1);
	return;
}

objects__Item objects_ExtendableObject_takeItem(objects__ExtendableObject r0,String r1) {
	String r7;
	hl__types__ArrayObj r4;
	objects__Item r9;
	hl__types__ArrayBase r12;
	vdynamic *r10;
	varray *r11;
	int r2, r3, r5, r6, r8;
	r2 = 0;
	r4 = r0->inventory;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->length;
	label$bd524ea_14_4:
	if( r2 >= r3 ) goto label$bd524ea_14_36;
	r5 = r2;
	++r2;
	r4 = r0->inventory;
	if( r4 == NULL ) hl_null_access();
	r8 = r4->length;
	if( ((unsigned)r5) < ((unsigned)r8) ) goto label$bd524ea_14_14;
	r9 = NULL;
	goto label$bd524ea_14_17;
	label$bd524ea_14_14:
	r11 = r4->array;
	r10 = ((vdynamic**)(r11 + 1))[r5];
	r9 = (objects__Item)r10;
	label$bd524ea_14_17:
	if( r9 == NULL ) hl_null_access();
	r7 = r9->name;
	if( r7 != r1 && (!r7 || !r1 || String___compare(r7,(vdynamic*)r1) != 0) ) goto label$bd524ea_14_35;
	r4 = r0->inventory;
	if( r4 == NULL ) hl_null_access();
	r8 = 1;
	r12 = hl_types_ArrayObj_splice(r4,r5,r8);
	r4 = (hl__types__ArrayObj)hl_dyn_castp(&r12,&t$hl_types_ArrayBase,&t$hl_types_ArrayObj);
	if( r4 == NULL ) hl_null_access();
	r6 = 0;
	r8 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r8) ) goto label$bd524ea_14_31;
	r9 = NULL;
	goto label$bd524ea_14_34;
	label$bd524ea_14_31:
	r11 = r4->array;
	r10 = ((vdynamic**)(r11 + 1))[r6];
	r9 = (objects__Item)r10;
	label$bd524ea_14_34:
	return r9;
	label$bd524ea_14_35:
	goto label$bd524ea_14_4;
	label$bd524ea_14_36:
	r9 = NULL;
	return r9;
}

void objects_ExtendableObject_new(objects__ExtendableObject r0,int* r1,int* r2,String r3,int* r4) {
	hl__types__ArrayObj r10;
	hl_type *r12;
	bool r9;
	objects__$ExtendableObject r19;
	hl__types__ArrayBytes_Float r14;
	double r8;
	vbyte *r15;
	varray *r11;
	int r5, r6, r7, r13, r16, r18, r20, r21;
	if( r1 ) goto label$bd524ea_15_3;
	r5 = 61;
	goto label$bd524ea_15_4;
	label$bd524ea_15_3:
	r5 = *r1;
	label$bd524ea_15_4:
	if( r2 ) goto label$bd524ea_15_7;
	r6 = 61;
	goto label$bd524ea_15_8;
	label$bd524ea_15_7:
	r6 = *r2;
	label$bd524ea_15_8:
	if( r4 ) goto label$bd524ea_15_11;
	r7 = 0;
	goto label$bd524ea_15_12;
	label$bd524ea_15_11:
	r7 = *r4;
	label$bd524ea_15_12:
	r8 = 0.41999999999999998;
	r0->co2 = r8;
	r8 = 21.;
	r0->o2 = r8;
	r9 = true;
	r0->gasPassable = r9;
	r8 = 0.;
	r0->currentGeneration = r8;
	r8 = 0.;
	r0->currentConductivity = r8;
	r8 = 0.;
	r0->current = r8;
	r8 = 0.050000000000000003;
	r0->heatOutF = r8;
	r8 = 0.14999999999999999;
	r0->heatInF = r8;
	r8 = 0.80000000000000004;
	r0->heatConductivityF = r8;
	r8 = 0.;
	r0->heat = r8;
	r8 = 0.;
	r0->fuel = r8;
	r12 = &t$objects_Item;
	r13 = 0;
	r11 = hl_alloc_array(r12,r13);
	r10 = hl_types_ArrayObj_alloc(r11);
	r0->inventory = r10;
	r8 = 1.;
	r0->health = r8;
	r9 = false;
	r0->isBroken = r9;
	r8 = 0.;
	r0->angularVelocity = r8;
	r13 = 24;
	r15 = hl_alloc_bytes(r13);
	r13 = 0;
	r8 = 0.;
	r16 = 3;
	r16 = r13 << r16;
	*(double*)(r15 + r16) = r8;
	++r13;
	r8 = 0.;
	r16 = 3;
	r16 = r13 << r16;
	*(double*)(r15 + r16) = r8;
	++r13;
	r8 = 0.;
	r16 = 3;
	r16 = r13 << r16;
	*(double*)(r15 + r16) = r8;
	++r13;
	r13 = 3;
	r14 = hl_types_ArrayBase_allocF64(r15,r13);
	r0->velocity = r14;
	r8 = 10.;
	r0->mass = r8;
	r12 = &t$objects_LogicConnector;
	r13 = 0;
	r11 = hl_alloc_array(r12,r13);
	r10 = hl_types_ArrayObj_alloc(r11);
	r0->logicConnectors = r10;
	r12 = &t$objects_Neighbor;
	r13 = 0;
	r11 = hl_alloc_array(r12,r13);
	r10 = hl_types_ArrayObj_alloc(r11);
	r0->neighborsFuel = r10;
	r12 = &t$objects_Neighbor;
	r13 = 0;
	r11 = hl_alloc_array(r12,r13);
	r10 = hl_types_ArrayObj_alloc(r11);
	r0->neighbors = r10;
	r9 = true;
	r0->noClip = r9;
	r12 = &t$objects_ConnectorLink;
	r13 = 0;
	r11 = hl_alloc_array(r12,r13);
	r10 = hl_types_ArrayObj_alloc(r11);
	r0->linked = r10;
	r12 = &t$objects_Connector;
	r13 = 0;
	r11 = hl_alloc_array(r12,r13);
	r10 = hl_types_ArrayObj_alloc(r11);
	r0->connectors = r10;
	r13 = r5;
	r1 = &r13;
	r16 = r6;
	r2 = &r16;
	r18 = r7;
	r4 = &r18;
	objects_GameObject_new(((objects__GameObject)r0),r1,r2,r3,r4);
	r9 = true;
	r0->selectable = r9;
	r10 = ((hl__types__ArrayObj (*)(objects__ExtendableObject))r0->$type->vobj_proto[4])(r0);
	r0->connectors = r10;
	r10 = ((hl__types__ArrayObj (*)(objects__ExtendableObject))r0->$type->vobj_proto[5])(r0);
	r0->logicConnectors = r10;
	r19 = (objects__$ExtendableObject)g$_objects_ExtendableObject;
	r20 = r19->nextId;
	r21 = r20;
	++r20;
	r19->nextId = r20;
	r0->id = r21;
	return;
}

