// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_objects__ExtendableManager
#define INC_objects__ExtendableManager
typedef struct _objects__$ExtendableManager *objects__$ExtendableManager;
typedef struct _objects__ExtendableManager *objects__ExtendableManager;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <objects/ExtendableObject.h>
#include <hl/types/ArrayObj.h>
#include <haxe/ds/ObjectMap.h>


struct _objects__$ExtendableManager {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _objects__ExtendableManager {
	hl_type *$type;
	String template;
	objects__ExtendableObject core;
	hl__types__ArrayObj objects;
	hl__types__ArrayObj logicLinks;
	haxe__ds__ObjectMap traversed;
};
#endif

