// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/GameObject.h>
void Object_new(Object,int*,int*,String,int*);

void objects_GameObject_new(objects__GameObject r0,int* r1,int* r2,String r3,int* r4) {
	int r5, r6, r7, r9, r10, r11;
	if( r1 ) goto label$3ff8ed4_1_3;
	r5 = 61;
	goto label$3ff8ed4_1_4;
	label$3ff8ed4_1_3:
	r5 = *r1;
	label$3ff8ed4_1_4:
	if( r2 ) goto label$3ff8ed4_1_7;
	r6 = 61;
	goto label$3ff8ed4_1_8;
	label$3ff8ed4_1_7:
	r6 = *r2;
	label$3ff8ed4_1_8:
	if( r4 ) goto label$3ff8ed4_1_11;
	r7 = 0;
	goto label$3ff8ed4_1_12;
	label$3ff8ed4_1_11:
	r7 = *r4;
	label$3ff8ed4_1_12:
	r9 = r5;
	r1 = &r9;
	r10 = r6;
	r2 = &r10;
	r11 = r7;
	r4 = &r11;
	Object_new(((Object)r0),r1,r2,r3,r4);
	return;
}

