// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/Hydroponics.h>
#include <objects/Item.h>
extern String s$station_farm_png;
void objects_ExtendableObject_new(objects__ExtendableObject,int*,int*,String,int*);
extern hl_type t$objects_Item;
#include <hl/natives.h>
extern String s$Food;
void objects_Item_new(objects__Item,String,int*);
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);

void objects_Hydroponics_new(objects__Hydroponics r0) {
	String r6;
	hl__types__ArrayObj r10;
	hl_type *r12;
	objects__Item r13;
	double r9;
	int *r3, *r5, *r7;
	varray *r11;
	int r2, r4, r8;
	r2 = 40;
	r3 = &r2;
	r4 = 40;
	r5 = &r4;
	r6 = (String)s$station_farm_png;
	r7 = NULL;
	objects_ExtendableObject_new(((objects__ExtendableObject)r0),r3,r5,r6,r7);
	r8 = 1;
	r0->zlayer = r8;
	r9 = 0.14999999999999999;
	r0->heatInF = r9;
	r9 = 0.050000000000000003;
	r0->heatOutF = r9;
	r12 = &t$objects_Item;
	r8 = 1;
	r11 = hl_alloc_array(r12,r8);
	r13 = (objects__Item)hl_alloc_obj(&t$objects_Item);
	r6 = (String)s$Food;
	r3 = NULL;
	objects_Item_new(r13,r6,r3);
	r8 = 0;
	((objects__Item*)(r11 + 1))[r8] = r13;
	r10 = hl_types_ArrayObj_alloc(r11);
	r0->inventory = r10;
	return;
}

