// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_objects__Item
#define INC_objects__Item
typedef struct _objects__$Item *objects__$Item;
typedef struct _objects__Item *objects__Item;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _objects__$Item {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* getDefaultPrice;
};
struct _objects__Item {
	hl_type *$type;
	String name;
	int price;
};
#endif

