// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/Item.h>
int objects_Item_getDefaultPrice(String);
extern hl_type t$objects_Item;
#include <hl/natives.h>

void objects_Item_new(objects__Item r0,String r1,int* r2) {
	int r3, r4, r5;
	if( r2 ) goto label$6adcbe6_1_3;
	r3 = -1;
	goto label$6adcbe6_1_4;
	label$6adcbe6_1_3:
	r3 = *r2;
	label$6adcbe6_1_4:
	r0->name = r1;
	r5 = -1;
	if( r3 != r5 ) goto label$6adcbe6_1_9;
	r4 = objects_Item_getDefaultPrice(r1);
	goto label$6adcbe6_1_10;
	label$6adcbe6_1_9:
	r4 = r3;
	label$6adcbe6_1_10:
	r0->price = r4;
	return;
}

objects__Item objects_Item_clone(objects__Item r0) {
	String r2;
	objects__Item r1;
	int *r4;
	int r3;
	r1 = (objects__Item)hl_alloc_obj(&t$objects_Item);
	r2 = r0->name;
	r3 = r0->price;
	r4 = &r3;
	objects_Item_new(r1,r2,r4);
	return r1;
}

int objects_Item_getDefaultPrice(String r0) {
	vbyte *r3, *r4;
	int r1, r2;
	if( !r0 ) goto label$6adcbe6_3_9;
	r1 = r0->length;
	r2 = 7;
	if( r1 != r2 ) goto label$6adcbe6_3_9;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("Blanket");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$6adcbe6_3_65;
	label$6adcbe6_3_9:
	if( !r0 ) goto label$6adcbe6_3_18;
	r1 = r0->length;
	r2 = 6;
	if( r1 != r2 ) goto label$6adcbe6_3_18;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("Charge");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$6adcbe6_3_67;
	label$6adcbe6_3_18:
	if( !r0 ) goto label$6adcbe6_3_27;
	r1 = r0->length;
	r2 = 4;
	if( r1 != r2 ) goto label$6adcbe6_3_27;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("Food");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$6adcbe6_3_69;
	label$6adcbe6_3_27:
	if( !r0 ) goto label$6adcbe6_3_36;
	r1 = r0->length;
	r2 = 4;
	if( r1 != r2 ) goto label$6adcbe6_3_36;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("Fuel");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$6adcbe6_3_71;
	label$6adcbe6_3_36:
	if( !r0 ) goto label$6adcbe6_3_45;
	r1 = r0->length;
	r2 = 3;
	if( r1 != r2 ) goto label$6adcbe6_3_45;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("Ice");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$6adcbe6_3_73;
	label$6adcbe6_3_45:
	if( !r0 ) goto label$6adcbe6_3_54;
	r1 = r0->length;
	r2 = 22;
	if( r1 != r2 ) goto label$6adcbe6_3_54;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("Preserved food package");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$6adcbe6_3_75;
	label$6adcbe6_3_54:
	if( !r0 ) goto label$6adcbe6_3_63;
	r1 = r0->length;
	r2 = 7;
	if( r1 != r2 ) goto label$6adcbe6_3_63;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("Reactor");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$6adcbe6_3_77;
	label$6adcbe6_3_63:
	r1 = 4000;
	return r1;
	label$6adcbe6_3_65:
	r1 = 6;
	return r1;
	label$6adcbe6_3_67:
	r1 = 10;
	return r1;
	label$6adcbe6_3_69:
	r1 = 9;
	return r1;
	label$6adcbe6_3_71:
	r1 = 18;
	return r1;
	label$6adcbe6_3_73:
	r1 = 4;
	return r1;
	label$6adcbe6_3_75:
	r1 = 12;
	return r1;
	label$6adcbe6_3_77:
	r1 = 8000;
	return r1;
}

