// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_objects__LogicCircle
#define INC_objects__LogicCircle
typedef struct _objects__$LogicCircle *objects__$LogicCircle;
typedef struct _objects__LogicCircle *objects__LogicCircle;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <_std/Circle.h>
#include <_std/Object.h>
#include <hl/types/ArrayBytes_Float.h>
#include <util/Texture.h>
#include <objects/LogicConnector.h>


struct _objects__$LogicCircle {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _objects__LogicCircle {
	hl_type *$type;
	hl__types__ArrayBytes_Float pos;
	double angle;
	double localAngle;
	int sizeX;
	int sizeY;
	int sizeZ;
	int color;
	util__Texture texture;
	bool show;
	bool isUI;
	int zlayer;
	util__Texture outlineTexture;
	util__Texture standartTexture;
	bool selectable;
	bool selected;
	util__Texture ghostTexture;
	int r;
	objects__LogicConnector logicConnector;
};
#endif

