// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_objects__LogicConnector
#define INC_objects__LogicConnector
typedef struct _objects__$LogicConnector *objects__$LogicConnector;
typedef struct _objects__LogicConnector *objects__LogicConnector;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <objects/Connector.h>
#include <hl/types/ArrayBytes_Float.h>
#include <_std/Circle.h>
#include <objects/ExtendableObject.h>


struct _objects__$LogicConnector {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _objects__LogicConnector {
	hl_type *$type;
	hl__types__ArrayBytes_Float pos;
	int type;
	Circle circle;
	objects__ExtendableObject obj;
	bool isIn;
	vclosure* callback;
};
#endif

