// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/LogicConnectorLink.h>
#include <hl/types/ArrayBytes_Float.h>
#include <_std/Circle.h>
extern hl_type t$Line;
void Line_new(Line,hl__types__ArrayBytes_Float,hl__types__ArrayBytes_Float,String,int*);
#include <_std/Game.h>
extern $Game g$_Game;
#include <_std/Object.h>
void Object_setVisible(Object,bool);

void objects_LogicConnectorLink_new(objects__LogicConnectorLink r0,objects__LogicConnector r1,objects__LogicConnector r2) {
	String r8;
	Circle r6;
	Line r4;
	hl__types__ArrayBytes_Float r5, r7;
	objects__LogicConnector r3;
	int *r9;
	r0->from = r1;
	r0->to = r2;
	r4 = (Line)hl_alloc_obj(&t$Line);
	r3 = r0->from;
	if( r3 == NULL ) hl_null_access();
	r6 = r3->circle;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->pos;
	r3 = r0->to;
	if( r3 == NULL ) hl_null_access();
	r6 = r3->circle;
	if( r6 == NULL ) hl_null_access();
	r7 = r6->pos;
	r8 = NULL;
	r9 = NULL;
	Line_new(r4,r5,r7,r8,r9);
	r0->line = r4;
	return;
}

void objects_LogicConnectorLink_draw(objects__LogicConnectorLink r0,double r1) {
	$Game r5;
	Circle r7;
	bool r4;
	Line r3;
	hl__types__ArrayBytes_Float r6;
	objects__LogicConnector r8;
	r3 = r0->line;
	if( r3 == NULL ) hl_null_access();
	r5 = ($Game)g$_Game;
	r4 = r5->isLogicVisible;
	Object_setVisible(((Object)r3),r4);
	r3 = r0->line;
	if( r3 == NULL ) hl_null_access();
	r8 = r0->from;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->circle;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->pos;
	r3->pos1 = r6;
	r3 = r0->line;
	if( r3 == NULL ) hl_null_access();
	r8 = r0->to;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->circle;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->pos;
	r3->pos2 = r6;
	return;
}

