// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/Mainframe.h>
#include <hscript/Expr.h>
venum* hscript_Parser_parseString(hscript__Parser,String,String,vdynamic*);
extern String s$;
String Std_string(vdynamic*);
extern hl_type t$_bool;
extern hl_type t$_dyn;
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);
#include <haxe/ds/StringMap.h>
extern hl_type t$hscript_Interp;
void hscript_Interp_new(hscript__Interp);
extern String s$dt;
extern hl_type t$_f64;
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);
extern String s$time;
#include <hl/natives.h>
extern String s$getIn;
extern hl_type t$fun_736fd8b;
extern String s$setOut;
extern hl_type t$fun_33c0391;
extern hl_type t$hscript_Expr;
vdynamic* hscript_Interp_execute(hscript__Interp,venum*);
void objects_ExtendableObject_update(objects__ExtendableObject,double);
#include <objects/LogicConnector.h>
extern hl_type t$objects_LogicConnector;
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
extern hl_type t$fun_440a34f;
void objects_LogicConnector_new(objects__LogicConnector,hl__types__ArrayBytes_Float,objects__ExtendableObject,bool,vclosure*);
bool objects_Mainframe_generateLogicConnectors__$6(objects__Mainframe,bool,double);
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern String s$Inputs_;
String String___add__(String,String);
extern String s$7215ee9;
void util_FontManager_drawText(String,int,int,int*);
extern String s$Outputs_;
int String___compare(String,vdynamic*);
void objects_ExtendableObject_draw(objects__ExtendableObject);
extern String s$b4069ff;
extern String s$ship_sensor_png;
void objects_ExtendableObject_new(objects__ExtendableObject,int*,int*,String,int*);
extern hl_type t$hscript_Parser;
void hscript_Parser_new(hscript__Parser);

void objects_Mainframe_compileScript(objects__Mainframe r0) {
	String r5, r6;
	hscript__Parser r4;
	venum *r3;
	vdynamic *r1, *r7, *r8, *r9;
	hl_trap_ctx trap$0;
	hl_trap(trap$0,r1,label$06cd575_1_12);
	r4 = r0->parser;
	if( r4 == NULL ) hl_null_access();
	r5 = r0->script;
	r6 = NULL;
	r7 = NULL;
	r3 = hscript_Parser_parseString(r4,r5,r6,r7);
	r0->compiledExpr = ((vdynamic*)r3);
	r5 = (String)s$;
	r0->lastError = r5;
	hl_endtrap(trap$0);
	goto label$06cd575_1_17;
	label$06cd575_1_12:
	r8 = NULL;
	r9 = NULL;
	r0->compiledExpr = r9;
	r5 = Std_string(r1);
	r0->lastError = r5;
	label$06cd575_1_17:
	return;
}

bool objects_Mainframe_runScript__$1(objects__Mainframe r0,int r1) {
	hl__types__ArrayObj r3;
	bool r4;
	vdynamic *r5;
	varray *r6;
	int r2;
	r2 = 0;
	if( r1 < r2 ) goto label$06cd575_2_17;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->inputSignals;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	if( r1 >= r2 ) goto label$06cd575_2_17;
	r3 = r0->inputSignals;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	if( ((unsigned)r1) < ((unsigned)r2) ) goto label$06cd575_2_13;
	r4 = false;
	goto label$06cd575_2_16;
	label$06cd575_2_13:
	r6 = r3->array;
	r5 = ((vdynamic**)(r6 + 1))[r1];
	r4 = (bool)hl_dyn_casti(&r5,&t$_dyn,&t$_bool);
	label$06cd575_2_16:
	return r4;
	label$06cd575_2_17:
	r4 = false;
	return r4;
}

bool objects_Mainframe_runScript__$2(objects__Mainframe r0,int r1,bool r2) {
	hl__types__ArrayObj r5;
	vdynamic *r7;
	varray *r6;
	int r4;
	r4 = 0;
	if( r1 < r4 ) goto label$06cd575_3_15;
	if( r0 == NULL ) hl_null_access();
	r5 = r0->outputSignals;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->length;
	if( r1 >= r4 ) goto label$06cd575_3_15;
	r5 = r0->outputSignals;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->length;
	if( ((unsigned)r1) < ((unsigned)r4) ) goto label$06cd575_3_12;
	hl_types_ArrayObj___expand(r5,r1);
	label$06cd575_3_12:
	r6 = r5->array;
	r7 = hl_alloc_dynbool(r2);
	((vdynamic**)(r6 + 1))[r1] = r7;
	label$06cd575_3_15:
	return r2;
}

void objects_Mainframe_runScript(objects__Mainframe r0,double r1) {
	String r14;
	objects__Mainframe r2;
	haxe__ds__StringMap r13;
	hl__types__ArrayObj r7;
	venum *r18;
	bool r9;
	vclosure *r16, *r17;
	double r15;
	hscript__Interp r12;
	vdynamic *r4, *r19;
	varray *r11;
	int r5, r6, r8, r10;
	hl_trap_ctx trap$0;
	r2 = r0;
	r4 = r0->compiledExpr;
	if( r4 ) goto label$06cd575_4_4;
	return;
	label$06cd575_4_4:
	r5 = 0;
	r7 = r0->outputSignals;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->length;
	label$06cd575_4_8:
	if( r5 >= r6 ) goto label$06cd575_4_22;
	r8 = r5;
	++r5;
	r7 = r0->outputSignals;
	if( r7 == NULL ) hl_null_access();
	r9 = false;
	r10 = r7->length;
	if( ((unsigned)r8) < ((unsigned)r10) ) goto label$06cd575_4_18;
	hl_types_ArrayObj___expand(r7,r8);
	label$06cd575_4_18:
	r11 = r7->array;
	r4 = hl_alloc_dynbool(r9);
	((vdynamic**)(r11 + 1))[r8] = r4;
	goto label$06cd575_4_8;
	label$06cd575_4_22:
	r12 = (hscript__Interp)hl_alloc_obj(&t$hscript_Interp);
	hscript_Interp_new(r12);
	r0->interp = r12;
	r12 = r0->interp;
	if( r12 == NULL ) hl_null_access();
	r13 = r12->variables;
	if( r13 == NULL ) hl_null_access();
	r14 = (String)s$dt;
	r4 = hl_alloc_dynamic(&t$_f64);
	r4->v.d = r1;
	haxe_ds_StringMap_set(r13,r14,r4);
	r12 = r0->interp;
	if( r12 == NULL ) hl_null_access();
	r13 = r12->variables;
	if( r13 == NULL ) hl_null_access();
	r14 = (String)s$time;
	r15 = hl_sys_time();
	r4 = hl_alloc_dynamic(&t$_f64);
	r4->v.d = r15;
	haxe_ds_StringMap_set(r13,r14,r4);
	r12 = r0->interp;
	if( r12 == NULL ) hl_null_access();
	r13 = r12->variables;
	if( r13 == NULL ) hl_null_access();
	r14 = (String)s$getIn;
	r16 = hl_alloc_closure_ptr(&t$fun_736fd8b,objects_Mainframe_runScript__$1,r2);
	haxe_ds_StringMap_set(r13,r14,((vdynamic*)r16));
	r12 = r0->interp;
	if( r12 == NULL ) hl_null_access();
	r13 = r12->variables;
	if( r13 == NULL ) hl_null_access();
	r14 = (String)s$setOut;
	r17 = hl_alloc_closure_ptr(&t$fun_33c0391,objects_Mainframe_runScript__$2,r2);
	haxe_ds_StringMap_set(r13,r14,((vdynamic*)r17));
	hl_trap(trap$0,r4,label$06cd575_4_64);
	r12 = r0->interp;
	if( r12 == NULL ) hl_null_access();
	r4 = r0->compiledExpr;
	r18 = (venum*)hl_dyn_castp(&r4,&t$_dyn,&t$hscript_Expr);
	r4 = hscript_Interp_execute(r12,r18);
	r14 = (String)s$;
	r0->lastError = r14;
	hl_endtrap(trap$0);
	goto label$06cd575_4_67;
	label$06cd575_4_64:
	r19 = NULL;
	r14 = Std_string(r4);
	r0->lastError = r14;
	label$06cd575_4_67:
	return;
}

void objects_Mainframe_update(objects__Mainframe r0,double r1) {
	objects_ExtendableObject_update(((objects__ExtendableObject)r0),r1);
	objects_Mainframe_runScript(r0,r1);
	return;
}

bool objects_Mainframe_generateLogicConnectors__$1(objects__Mainframe r0,bool r1,double r2) {
	hl__types__ArrayObj r3;
	bool r5;
	vdynamic *r9;
	varray *r8;
	int r4, r6;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->inputSignals;
	if( r3 == NULL ) hl_null_access();
	r4 = 0;
	r6 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r6) ) goto label$06cd575_6_7;
	hl_types_ArrayObj___expand(r3,r4);
	label$06cd575_6_7:
	r8 = r3->array;
	r9 = hl_alloc_dynbool(r1);
	((vdynamic**)(r8 + 1))[r4] = r9;
	r5 = false;
	return r5;
}

bool objects_Mainframe_generateLogicConnectors__$2(objects__Mainframe r0,bool r1,double r2) {
	hl__types__ArrayObj r3;
	bool r5;
	vdynamic *r9;
	varray *r8;
	int r4, r6;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->inputSignals;
	if( r3 == NULL ) hl_null_access();
	r4 = 1;
	r6 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r6) ) goto label$06cd575_7_7;
	hl_types_ArrayObj___expand(r3,r4);
	label$06cd575_7_7:
	r8 = r3->array;
	r9 = hl_alloc_dynbool(r1);
	((vdynamic**)(r8 + 1))[r4] = r9;
	r5 = false;
	return r5;
}

bool objects_Mainframe_generateLogicConnectors__$3(objects__Mainframe r0,bool r1,double r2) {
	hl__types__ArrayObj r3;
	bool r6;
	vdynamic *r7;
	varray *r8;
	int r4, r5;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->outputSignals;
	if( r3 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$06cd575_8_8;
	r6 = false;
	goto label$06cd575_8_11;
	label$06cd575_8_8:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r6 = (bool)hl_dyn_casti(&r7,&t$_dyn,&t$_bool);
	label$06cd575_8_11:
	return r6;
}

bool objects_Mainframe_generateLogicConnectors__$4(objects__Mainframe r0,bool r1,double r2) {
	hl__types__ArrayObj r3;
	bool r6;
	vdynamic *r7;
	varray *r8;
	int r4, r5;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->outputSignals;
	if( r3 == NULL ) hl_null_access();
	r4 = 1;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$06cd575_9_8;
	r6 = false;
	goto label$06cd575_9_11;
	label$06cd575_9_8:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r6 = (bool)hl_dyn_casti(&r7,&t$_dyn,&t$_bool);
	label$06cd575_9_11:
	return r6;
}

bool objects_Mainframe_generateLogicConnectors__$5(objects__Mainframe r0,bool r1,double r2) {
	hl__types__ArrayObj r3;
	bool r6;
	vdynamic *r7;
	varray *r8;
	int r4, r5;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->outputSignals;
	if( r3 == NULL ) hl_null_access();
	r4 = 2;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$06cd575_10_8;
	r6 = false;
	goto label$06cd575_10_11;
	label$06cd575_10_8:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r6 = (bool)hl_dyn_casti(&r7,&t$_dyn,&t$_bool);
	label$06cd575_10_11:
	return r6;
}

hl__types__ArrayObj objects_Mainframe_generateLogicConnectors(objects__Mainframe r0) {
	hl__types__ArrayObj r20;
	hl_type *r22;
	bool r9;
	hl__types__ArrayBytes_Float r6;
	vclosure *r10;
	objects__LogicConnector r5, r12, r14, r16, r18, r23;
	double r2, r4, r11, r13, r15, r17, r19;
	varray *r21;
	vbyte *r7;
	int r3, r8;
	r3 = r0->sizeX;
	r2 = (double)r3;
	r4 = 2.;
	r2 = r2 / r4;
	r5 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r3 = 24;
	r7 = hl_alloc_bytes(r3);
	r3 = 0;
	r8 = (int)r2;
	r8 = -r8;
	r4 = (double)r8;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r4;
	++r3;
	r4 = 10.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r4;
	++r3;
	r4 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r4;
	++r3;
	r3 = 3;
	r6 = hl_types_ArrayBase_allocF64(r7,r3);
	r9 = true;
	r10 = hl_alloc_closure_ptr(&t$fun_440a34f,objects_Mainframe_generateLogicConnectors__$1,r0);
	objects_LogicConnector_new(r5,r6,((objects__ExtendableObject)r0),r9,r10);
	r3 = r0->sizeX;
	r4 = (double)r3;
	r11 = 2.;
	r4 = r4 / r11;
	r12 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r3 = 24;
	r7 = hl_alloc_bytes(r3);
	r3 = 0;
	r8 = (int)r4;
	r8 = -r8;
	r11 = (double)r8;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r11;
	++r3;
	r11 = -10.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r11;
	++r3;
	r11 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r11;
	++r3;
	r3 = 3;
	r6 = hl_types_ArrayBase_allocF64(r7,r3);
	r9 = true;
	r10 = hl_alloc_closure_ptr(&t$fun_440a34f,objects_Mainframe_generateLogicConnectors__$2,r0);
	objects_LogicConnector_new(r12,r6,((objects__ExtendableObject)r0),r9,r10);
	r3 = r0->sizeX;
	r11 = (double)r3;
	r13 = 2.;
	r11 = r11 / r13;
	r14 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r3 = 24;
	r7 = hl_alloc_bytes(r3);
	r3 = 0;
	r8 = (int)r11;
	r13 = (double)r8;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r13;
	++r3;
	r13 = 15.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r13;
	++r3;
	r13 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r13;
	++r3;
	r3 = 3;
	r6 = hl_types_ArrayBase_allocF64(r7,r3);
	r9 = false;
	r10 = hl_alloc_closure_ptr(&t$fun_440a34f,objects_Mainframe_generateLogicConnectors__$3,r0);
	objects_LogicConnector_new(r14,r6,((objects__ExtendableObject)r0),r9,r10);
	r3 = r0->sizeX;
	r13 = (double)r3;
	r15 = 2.;
	r13 = r13 / r15;
	r16 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r3 = 24;
	r7 = hl_alloc_bytes(r3);
	r3 = 0;
	r8 = (int)r13;
	r15 = (double)r8;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r15;
	++r3;
	r15 = 5.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r15;
	++r3;
	r15 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r15;
	++r3;
	r3 = 3;
	r6 = hl_types_ArrayBase_allocF64(r7,r3);
	r9 = false;
	r10 = hl_alloc_closure_ptr(&t$fun_440a34f,objects_Mainframe_generateLogicConnectors__$4,r0);
	objects_LogicConnector_new(r16,r6,((objects__ExtendableObject)r0),r9,r10);
	r3 = r0->sizeX;
	r15 = (double)r3;
	r17 = 2.;
	r15 = r15 / r17;
	r18 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r3 = 24;
	r7 = hl_alloc_bytes(r3);
	r3 = 0;
	r8 = (int)r15;
	r17 = (double)r8;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r17;
	++r3;
	r17 = -5.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r17;
	++r3;
	r17 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r17;
	++r3;
	r3 = 3;
	r6 = hl_types_ArrayBase_allocF64(r7,r3);
	r9 = false;
	r10 = hl_alloc_closure_ptr(&t$fun_440a34f,objects_Mainframe_generateLogicConnectors__$5,r0);
	objects_LogicConnector_new(r18,r6,((objects__ExtendableObject)r0),r9,r10);
	r3 = r0->sizeX;
	r17 = (double)r3;
	r19 = 2.;
	r17 = r17 / r19;
	r22 = &t$objects_LogicConnector;
	r3 = 6;
	r21 = hl_alloc_array(r22,r3);
	r3 = 0;
	((objects__LogicConnector*)(r21 + 1))[r3] = r5;
	r3 = 1;
	((objects__LogicConnector*)(r21 + 1))[r3] = r12;
	r3 = 2;
	((objects__LogicConnector*)(r21 + 1))[r3] = r14;
	r3 = 3;
	((objects__LogicConnector*)(r21 + 1))[r3] = r16;
	r3 = 4;
	((objects__LogicConnector*)(r21 + 1))[r3] = r18;
	r23 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r3 = 24;
	r7 = hl_alloc_bytes(r3);
	r3 = 0;
	r8 = (int)r17;
	r19 = (double)r8;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r19;
	++r3;
	r19 = -15.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r19;
	++r3;
	r19 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r19;
	++r3;
	r3 = 3;
	r6 = hl_types_ArrayBase_allocF64(r7,r3);
	r9 = false;
	r10 = hl_alloc_closure_ptr(&t$fun_440a34f,objects_Mainframe_generateLogicConnectors__$6,r0);
	objects_LogicConnector_new(r23,r6,((objects__ExtendableObject)r0),r9,r10);
	r3 = 5;
	((objects__LogicConnector*)(r21 + 1))[r3] = r23;
	r20 = hl_types_ArrayObj_alloc(r21);
	return r20;
}

bool objects_Mainframe_generateLogicConnectors__$6(objects__Mainframe r0,bool r1,double r2) {
	hl__types__ArrayObj r3;
	bool r6;
	vdynamic *r7;
	varray *r8;
	int r4, r5;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->outputSignals;
	if( r3 == NULL ) hl_null_access();
	r4 = 3;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$06cd575_12_8;
	r6 = false;
	goto label$06cd575_12_11;
	label$06cd575_12_8:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r6 = (bool)hl_dyn_casti(&r7,&t$_dyn,&t$_bool);
	label$06cd575_12_11:
	return r6;
}

void objects_Mainframe_draw(objects__Mainframe r0) {
	String r3, r4;
	hl__types__ArrayObj r5;
	bool r2;
	int *r11;
	vdynamic *r8;
	varray *r9;
	int r6, r7, r10, r12, r13;
	r2 = r0->selected;
	if( !r2 ) goto label$06cd575_13_109;
	r3 = (String)s$Inputs_;
	r5 = r0->inputSignals;
	if( r5 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$06cd575_13_10;
	r2 = false;
	goto label$06cd575_13_13;
	label$06cd575_13_10:
	r9 = r5->array;
	r8 = ((vdynamic**)(r9 + 1))[r6];
	r2 = (bool)hl_dyn_casti(&r8,&t$_dyn,&t$_bool);
	label$06cd575_13_13:
	r8 = hl_alloc_dynbool(r2);
	r4 = Std_string(r8);
	r3 = String___add__(r3,r4);
	r4 = (String)s$7215ee9;
	r3 = String___add__(r3,r4);
	r5 = r0->inputSignals;
	if( r5 == NULL ) hl_null_access();
	r6 = 1;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$06cd575_13_25;
	r2 = false;
	goto label$06cd575_13_28;
	label$06cd575_13_25:
	r9 = r5->array;
	r8 = ((vdynamic**)(r9 + 1))[r6];
	r2 = (bool)hl_dyn_casti(&r8,&t$_dyn,&t$_bool);
	label$06cd575_13_28:
	r8 = hl_alloc_dynbool(r2);
	r4 = Std_string(r8);
	r3 = String___add__(r3,r4);
	r6 = 500;
	r7 = 10;
	r10 = 2432799;
	r11 = &r10;
	util_FontManager_drawText(r3,r6,r7,r11);
	r3 = (String)s$Outputs_;
	r5 = r0->outputSignals;
	if( r5 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$06cd575_13_44;
	r2 = false;
	goto label$06cd575_13_47;
	label$06cd575_13_44:
	r9 = r5->array;
	r8 = ((vdynamic**)(r9 + 1))[r6];
	r2 = (bool)hl_dyn_casti(&r8,&t$_dyn,&t$_bool);
	label$06cd575_13_47:
	r8 = hl_alloc_dynbool(r2);
	r4 = Std_string(r8);
	r3 = String___add__(r3,r4);
	r4 = (String)s$7215ee9;
	r3 = String___add__(r3,r4);
	r5 = r0->outputSignals;
	if( r5 == NULL ) hl_null_access();
	r6 = 1;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$06cd575_13_59;
	r2 = false;
	goto label$06cd575_13_62;
	label$06cd575_13_59:
	r9 = r5->array;
	r8 = ((vdynamic**)(r9 + 1))[r6];
	r2 = (bool)hl_dyn_casti(&r8,&t$_dyn,&t$_bool);
	label$06cd575_13_62:
	r8 = hl_alloc_dynbool(r2);
	r4 = Std_string(r8);
	r3 = String___add__(r3,r4);
	r4 = (String)s$7215ee9;
	r3 = String___add__(r3,r4);
	r5 = r0->outputSignals;
	if( r5 == NULL ) hl_null_access();
	r6 = 2;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$06cd575_13_74;
	r2 = false;
	goto label$06cd575_13_77;
	label$06cd575_13_74:
	r9 = r5->array;
	r8 = ((vdynamic**)(r9 + 1))[r6];
	r2 = (bool)hl_dyn_casti(&r8,&t$_dyn,&t$_bool);
	label$06cd575_13_77:
	r8 = hl_alloc_dynbool(r2);
	r4 = Std_string(r8);
	r3 = String___add__(r3,r4);
	r4 = (String)s$7215ee9;
	r3 = String___add__(r3,r4);
	r5 = r0->outputSignals;
	if( r5 == NULL ) hl_null_access();
	r6 = 3;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$06cd575_13_89;
	r2 = false;
	goto label$06cd575_13_92;
	label$06cd575_13_89:
	r9 = r5->array;
	r8 = ((vdynamic**)(r9 + 1))[r6];
	r2 = (bool)hl_dyn_casti(&r8,&t$_dyn,&t$_bool);
	label$06cd575_13_92:
	r8 = hl_alloc_dynbool(r2);
	r4 = Std_string(r8);
	r3 = String___add__(r3,r4);
	r6 = 500;
	r7 = 28;
	r12 = 2432799;
	r11 = &r12;
	util_FontManager_drawText(r3,r6,r7,r11);
	r3 = r0->lastError;
	r4 = (String)s$;
	if( r3 == r4 || (r3 && r4 && String___compare(r3,(vdynamic*)r4) == 0) ) goto label$06cd575_13_109;
	r3 = r0->lastError;
	r6 = 500;
	r7 = 46;
	r13 = 2432799;
	r11 = &r13;
	util_FontManager_drawText(r3,r6,r7,r11);
	label$06cd575_13_109:
	objects_ExtendableObject_draw(((objects__ExtendableObject)r0));
	return;
}

void objects_Mainframe_new(objects__Mainframe r0) {
	String r1;
	hscript__Parser r13;
	hl__types__ArrayObj r2;
	hl_type *r4;
	bool r6;
	hscript__Interp r14;
	int *r9, *r11, *r12;
	vdynamic *r7;
	int r5, r10;
	varray *r3;
	r1 = (String)s$;
	r0->lastError = r1;
	r4 = &t$_dyn;
	r5 = 4;
	r3 = hl_alloc_array(r4,r5);
	r6 = false;
	r7 = hl_alloc_dynbool(r6);
	r5 = 0;
	((vdynamic**)(r3 + 1))[r5] = r7;
	r6 = false;
	r7 = hl_alloc_dynbool(r6);
	r5 = 1;
	((vdynamic**)(r3 + 1))[r5] = r7;
	r6 = false;
	r7 = hl_alloc_dynbool(r6);
	r5 = 2;
	((vdynamic**)(r3 + 1))[r5] = r7;
	r6 = false;
	r7 = hl_alloc_dynbool(r6);
	r5 = 3;
	((vdynamic**)(r3 + 1))[r5] = r7;
	r2 = hl_types_ArrayObj_alloc(r3);
	r0->outputSignals = r2;
	r4 = &t$_dyn;
	r5 = 2;
	r3 = hl_alloc_array(r4,r5);
	r6 = false;
	r7 = hl_alloc_dynbool(r6);
	r5 = 0;
	((vdynamic**)(r3 + 1))[r5] = r7;
	r6 = false;
	r7 = hl_alloc_dynbool(r6);
	r5 = 1;
	((vdynamic**)(r3 + 1))[r5] = r7;
	r2 = hl_types_ArrayObj_alloc(r3);
	r0->inputSignals = r2;
	r1 = (String)s$b4069ff;
	r0->script = r1;
	r5 = 40;
	r9 = &r5;
	r10 = 40;
	r11 = &r10;
	r1 = (String)s$ship_sensor_png;
	r12 = NULL;
	objects_ExtendableObject_new(((objects__ExtendableObject)r0),r9,r11,r1,r12);
	r6 = false;
	r0->noClip = r6;
	r13 = (hscript__Parser)hl_alloc_obj(&t$hscript_Parser);
	hscript_Parser_new(r13);
	r0->parser = r13;
	r14 = (hscript__Interp)hl_alloc_obj(&t$hscript_Interp);
	hscript_Interp_new(r14);
	r0->interp = r14;
	objects_Mainframe_compileScript(r0);
	return;
}

