// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_objects__MiniMap
#define INC_objects__MiniMap
typedef struct _objects__$MiniMap *objects__$MiniMap;
typedef struct _objects__MiniMap *objects__MiniMap;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayBytes_Float.h>
#include <hl/types/ArrayObj.h>
#include <_std/Line.h>


struct _objects__$MiniMap {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _objects__MiniMap {
	hl_type *$type;
	hl__types__ArrayBytes_Float pos;
	int width;
	int height;
	double scale;
	hl__types__ArrayObj lines;
	hl__types__ArrayObj circles;
	Line l1;
	Line l2;
	Line l3;
	Line l4;
};
#endif

