// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/Neighbor.h>

void objects_Neighbor_new(objects__Neighbor r0,objects__ExtendableObject r1,int r2) {
	r0->obj = r1;
	r0->type = r2;
	return;
}

