// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/PipeManager.h>
void objects_ExtendableManager_new(objects__ExtendableManager);

void objects_PipeManager_new(objects__PipeManager r0) {
	objects_ExtendableManager_new(((objects__ExtendableManager)r0));
	return;
}

