// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/Sensor.h>
extern String s$ship_sensor_png;
void objects_ExtendableObject_new(objects__ExtendableObject,int*,int*,String,int*);

void objects_Sensor_new(objects__Sensor r0) {
	String r6;
	double r8;
	int *r3, *r5, *r7;
	int r2, r4;
	r2 = 20;
	r3 = &r2;
	r4 = 20;
	r5 = &r4;
	r6 = (String)s$ship_sensor_png;
	r7 = NULL;
	objects_ExtendableObject_new(((objects__ExtendableObject)r0),r3,r5,r6,r7);
	r8 = 0.14999999999999999;
	r0->heatInF = r8;
	r8 = 0.050000000000000003;
	r0->heatOutF = r8;
	return;
}

