// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/ShipConsole.h>
extern String s$ship_ship_console_png;
void objects_ExtendableObject_new(objects__ExtendableObject,int*,int*,String,int*);
#include <objects/Connector.h>
extern hl_type t$objects_Connector;
#include <hl/natives.h>
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
void objects_Connector_new(objects__Connector,hl__types__ArrayBytes_Float,int*);
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern objects__$ShipConsole g$_objects_ShipConsole;
#include <objects/LogicConnector.h>
extern hl_type t$fun_a4cbe1d;
bool objects_ShipConsole_generateLogicConnectors__$6(bool,double);
extern hl_type t$objects_LogicConnector;
void objects_LogicConnector_new(objects__LogicConnector,hl__types__ArrayBytes_Float,objects__ExtendableObject,bool,vclosure*);

void objects_ShipConsole_new(objects__ShipConsole r0) {
	String r6;
	bool r8;
	int *r3, *r5, *r7;
	int r2, r4;
	r2 = 20;
	r3 = &r2;
	r4 = 20;
	r5 = &r4;
	r6 = (String)s$ship_ship_console_png;
	r7 = NULL;
	objects_ExtendableObject_new(((objects__ExtendableObject)r0),r3,r5,r6,r7);
	r8 = false;
	r0->noClip = r8;
	return;
}

hl__types__ArrayObj objects_ShipConsole_generateConnectors(objects__ShipConsole r0) {
	hl__types__ArrayObj r1;
	hl_type *r3;
	objects__Connector r5;
	hl__types__ArrayBytes_Float r6;
	double r8;
	int *r10;
	vbyte *r7;
	int r4, r9;
	varray *r2;
	r3 = &t$objects_Connector;
	r4 = 1;
	r2 = hl_alloc_array(r3,r4);
	r5 = (objects__Connector)hl_alloc_obj(&t$objects_Connector);
	r4 = 24;
	r7 = hl_alloc_bytes(r4);
	r4 = 0;
	r8 = 0.;
	r9 = 3;
	r9 = r4 << r9;
	*(double*)(r7 + r9) = r8;
	++r4;
	r8 = 0.;
	r9 = 3;
	r9 = r4 << r9;
	*(double*)(r7 + r9) = r8;
	++r4;
	r8 = 0.;
	r9 = 3;
	r9 = r4 << r9;
	*(double*)(r7 + r9) = r8;
	++r4;
	r4 = 3;
	r6 = hl_types_ArrayBase_allocF64(r7,r4);
	r4 = 2;
	r10 = &r4;
	objects_Connector_new(r5,r6,r10);
	r9 = 0;
	((objects__Connector*)(r2 + 1))[r9] = r5;
	r1 = hl_types_ArrayObj_alloc(r2);
	return r1;
}

bool objects_ShipConsole_generateLogicConnectors__$1(bool r0,double r1) {
	bool r2;
	objects__$ShipConsole r3;
	r3 = (objects__$ShipConsole)g$_objects_ShipConsole;
	r2 = r3->isQPressed;
	if( !r2 ) goto label$1731321_3_5;
	r2 = true;
	return r2;
	label$1731321_3_5:
	r2 = false;
	return r2;
}

bool objects_ShipConsole_generateLogicConnectors__$2(bool r0,double r1) {
	bool r2;
	objects__$ShipConsole r3;
	r3 = (objects__$ShipConsole)g$_objects_ShipConsole;
	r2 = r3->isEPressed;
	if( !r2 ) goto label$1731321_4_5;
	r2 = true;
	return r2;
	label$1731321_4_5:
	r2 = false;
	return r2;
}

bool objects_ShipConsole_generateLogicConnectors__$3(bool r0,double r1) {
	bool r2;
	objects__$ShipConsole r3;
	r3 = (objects__$ShipConsole)g$_objects_ShipConsole;
	r2 = r3->isAPressed;
	if( !r2 ) goto label$1731321_5_5;
	r2 = true;
	return r2;
	label$1731321_5_5:
	r2 = false;
	return r2;
}

bool objects_ShipConsole_generateLogicConnectors__$4(bool r0,double r1) {
	bool r2;
	objects__$ShipConsole r3;
	r3 = (objects__$ShipConsole)g$_objects_ShipConsole;
	r2 = r3->isDPressed;
	if( !r2 ) goto label$1731321_6_5;
	r2 = true;
	return r2;
	label$1731321_6_5:
	r2 = false;
	return r2;
}

bool objects_ShipConsole_generateLogicConnectors__$5(bool r0,double r1) {
	bool r2;
	objects__$ShipConsole r3;
	r3 = (objects__$ShipConsole)g$_objects_ShipConsole;
	r2 = r3->isSPressed;
	if( !r2 ) goto label$1731321_7_5;
	r2 = true;
	return r2;
	label$1731321_7_5:
	r2 = false;
	return r2;
}

hl__types__ArrayObj objects_ShipConsole_generateLogicConnectors(objects__ShipConsole r0) {
	hl__types__ArrayObj r24;
	hl_type *r26;
	bool r11;
	hl__types__ArrayBytes_Float r8;
	vclosure *r12;
	objects__LogicConnector r7, r15, r18, r20, r22, r27;
	double r1, r3, r6, r13, r14, r17, r19, r21, r23;
	varray *r25;
	vbyte *r9;
	int r2, r5, r10, r16;
	static vclosure cl$0 = { &t$fun_a4cbe1d, objects_ShipConsole_generateLogicConnectors__$1, 0 };
	static vclosure cl$1 = { &t$fun_a4cbe1d, objects_ShipConsole_generateLogicConnectors__$2, 0 };
	static vclosure cl$2 = { &t$fun_a4cbe1d, objects_ShipConsole_generateLogicConnectors__$3, 0 };
	static vclosure cl$3 = { &t$fun_a4cbe1d, objects_ShipConsole_generateLogicConnectors__$4, 0 };
	static vclosure cl$4 = { &t$fun_a4cbe1d, objects_ShipConsole_generateLogicConnectors__$5, 0 };
	static vclosure cl$5 = { &t$fun_a4cbe1d, objects_ShipConsole_generateLogicConnectors__$6, 0 };
	r2 = r0->sizeX;
	r1 = (double)r2;
	r3 = 2.;
	r1 = r1 / r3;
	r2 = (int)r1;
	r2 = -r2;
	r5 = r0->sizeX;
	r3 = (double)r5;
	r6 = 2.;
	r3 = r3 / r6;
	r7 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r5 = 24;
	r9 = hl_alloc_bytes(r5);
	r5 = 0;
	r6 = (double)r2;
	r10 = 3;
	r10 = r5 << r10;
	*(double*)(r9 + r10) = r6;
	++r5;
	r10 = (int)r3;
	r6 = (double)r10;
	r10 = 3;
	r10 = r5 << r10;
	*(double*)(r9 + r10) = r6;
	++r5;
	r6 = 0.;
	r10 = 3;
	r10 = r5 << r10;
	*(double*)(r9 + r10) = r6;
	++r5;
	r5 = 3;
	r8 = hl_types_ArrayBase_allocF64(r9,r5);
	r11 = false;
	r12 = &cl$0;
	objects_LogicConnector_new(r7,r8,((objects__ExtendableObject)r0),r11,r12);
	r5 = r0->sizeX;
	r6 = (double)r5;
	r13 = 2.;
	r6 = r6 / r13;
	r5 = (int)r6;
	r10 = r0->sizeX;
	r13 = (double)r10;
	r14 = 2.;
	r13 = r13 / r14;
	r15 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r10 = 24;
	r9 = hl_alloc_bytes(r10);
	r10 = 0;
	r14 = (double)r5;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r14;
	++r10;
	r16 = (int)r13;
	r14 = (double)r16;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r14;
	++r10;
	r14 = 0.;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r14;
	++r10;
	r10 = 3;
	r8 = hl_types_ArrayBase_allocF64(r9,r10);
	r11 = false;
	r12 = &cl$1;
	objects_LogicConnector_new(r15,r8,((objects__ExtendableObject)r0),r11,r12);
	r10 = r0->sizeX;
	r14 = (double)r10;
	r17 = 2.;
	r14 = r14 / r17;
	r18 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r10 = 24;
	r9 = hl_alloc_bytes(r10);
	r10 = 0;
	r16 = (int)r14;
	r16 = -r16;
	r17 = (double)r16;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r17;
	++r10;
	r17 = 0.;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r17;
	++r10;
	r17 = 0.;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r17;
	++r10;
	r10 = 3;
	r8 = hl_types_ArrayBase_allocF64(r9,r10);
	r11 = false;
	r12 = &cl$2;
	objects_LogicConnector_new(r18,r8,((objects__ExtendableObject)r0),r11,r12);
	r10 = r0->sizeX;
	r17 = (double)r10;
	r19 = 2.;
	r17 = r17 / r19;
	r20 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r10 = 24;
	r9 = hl_alloc_bytes(r10);
	r10 = 0;
	r16 = (int)r17;
	r19 = (double)r16;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r19;
	++r10;
	r19 = 0.;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r19;
	++r10;
	r19 = 0.;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r19;
	++r10;
	r10 = 3;
	r8 = hl_types_ArrayBase_allocF64(r9,r10);
	r11 = false;
	r12 = &cl$3;
	objects_LogicConnector_new(r20,r8,((objects__ExtendableObject)r0),r11,r12);
	r10 = r0->sizeY;
	r19 = (double)r10;
	r21 = 2.;
	r19 = r19 / r21;
	r22 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r10 = 24;
	r9 = hl_alloc_bytes(r10);
	r10 = 0;
	r21 = 0.;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r21;
	++r10;
	r16 = (int)r19;
	r16 = -r16;
	r21 = (double)r16;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r21;
	++r10;
	r21 = 0.;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r21;
	++r10;
	r10 = 3;
	r8 = hl_types_ArrayBase_allocF64(r9,r10);
	r11 = false;
	r12 = &cl$4;
	objects_LogicConnector_new(r22,r8,((objects__ExtendableObject)r0),r11,r12);
	r10 = r0->sizeY;
	r21 = (double)r10;
	r23 = 2.;
	r21 = r21 / r23;
	r26 = &t$objects_LogicConnector;
	r10 = 6;
	r25 = hl_alloc_array(r26,r10);
	r10 = 0;
	((objects__LogicConnector*)(r25 + 1))[r10] = r7;
	r10 = 1;
	((objects__LogicConnector*)(r25 + 1))[r10] = r15;
	r10 = 2;
	((objects__LogicConnector*)(r25 + 1))[r10] = r18;
	r10 = 3;
	((objects__LogicConnector*)(r25 + 1))[r10] = r20;
	r10 = 4;
	((objects__LogicConnector*)(r25 + 1))[r10] = r22;
	r27 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r10 = 24;
	r9 = hl_alloc_bytes(r10);
	r10 = 0;
	r23 = 0.;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r23;
	++r10;
	r16 = (int)r21;
	r23 = (double)r16;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r23;
	++r10;
	r23 = 0.;
	r16 = 3;
	r16 = r10 << r16;
	*(double*)(r9 + r16) = r23;
	++r10;
	r10 = 3;
	r8 = hl_types_ArrayBase_allocF64(r9,r10);
	r11 = false;
	r12 = &cl$5;
	objects_LogicConnector_new(r27,r8,((objects__ExtendableObject)r0),r11,r12);
	r10 = 5;
	((objects__LogicConnector*)(r25 + 1))[r10] = r27;
	r24 = hl_types_ArrayObj_alloc(r25);
	return r24;
}

bool objects_ShipConsole_generateLogicConnectors__$6(bool r0,double r1) {
	bool r2;
	objects__$ShipConsole r3;
	r3 = (objects__$ShipConsole)g$_objects_ShipConsole;
	r2 = r3->isWPressed;
	if( !r2 ) goto label$1731321_9_5;
	r2 = true;
	return r2;
	label$1731321_9_5:
	r2 = false;
	return r2;
}

