// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <objects/ShipEngine.h>
#include <objects/Connector.h>
hl__types__ArrayObj objects_ExtendableObject_generateConnectors(objects__ExtendableObject);
extern hl_type t$objects_Connector;
#include <hl/natives.h>
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
void objects_Connector_new(objects__Connector,hl__types__ArrayBytes_Float,int*);
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
hl__types__ArrayObj hl_types_ArrayObj_concat(hl__types__ArrayObj,hl__types__ArrayObj);
#include <_std/Game.h>
extern $Game g$_Game;
void objects_ExtendableObject_addToVelocity(objects__ExtendableObject,hl__types__ArrayBytes_Float);
#include <objects/LogicConnector.h>
extern hl_type t$objects_LogicConnector;
extern hl_type t$fun_c43dde5;
void objects_LogicConnector_new(objects__LogicConnector,hl__types__ArrayBytes_Float,objects__ExtendableObject,bool,vclosure*);
bool objects_ShipEngine_generateLogicConnectors__$4(objects__ShipEngine,bool,double);
#include <_std/Math.h>
extern $Math g$_Math;
void objects_ThrusterFlameFx_drawJet(hl__types__ArrayBytes_Float,hl__types__ArrayBytes_Float,double,double,double,double);
void objects_ExtendableObject_draw(objects__ExtendableObject);
extern String s$ship_engine_png;
void objects_ExtendableObject_new(objects__ExtendableObject,int*,int*,String,int*);

hl__types__ArrayObj objects_ShipEngine_generateConnectors(objects__ShipEngine r0) {
	hl__types__ArrayObj r1, r8, r9;
	hl_type *r11;
	objects__Connector r12;
	hl__types__ArrayBytes_Float r13;
	double r3, r5, r7;
	int *r16;
	vbyte *r14;
	varray *r10;
	int r4, r6, r15;
	r1 = objects_ExtendableObject_generateConnectors(((objects__ExtendableObject)r0));
	r4 = r0->sizeX;
	r3 = (double)r4;
	r5 = 4.;
	r3 = r3 / r5;
	r4 = (int)r3;
	r4 = -r4;
	r6 = r0->sizeY;
	r5 = (double)r6;
	r7 = 2.;
	r5 = r5 / r7;
	if( r1 == NULL ) hl_null_access();
	r11 = &t$objects_Connector;
	r6 = 1;
	r10 = hl_alloc_array(r11,r6);
	r12 = (objects__Connector)hl_alloc_obj(&t$objects_Connector);
	r6 = 24;
	r14 = hl_alloc_bytes(r6);
	r6 = 0;
	r7 = (double)r4;
	r15 = 3;
	r15 = r6 << r15;
	*(double*)(r14 + r15) = r7;
	++r6;
	r15 = (int)r5;
	r7 = (double)r15;
	r15 = 3;
	r15 = r6 << r15;
	*(double*)(r14 + r15) = r7;
	++r6;
	r7 = 0.;
	r15 = 3;
	r15 = r6 << r15;
	*(double*)(r14 + r15) = r7;
	++r6;
	r6 = 3;
	r13 = hl_types_ArrayBase_allocF64(r14,r6);
	r6 = 1;
	r16 = &r6;
	objects_Connector_new(r12,r13,r16);
	r15 = 0;
	((objects__Connector*)(r10 + 1))[r15] = r12;
	r9 = hl_types_ArrayObj_alloc(r10);
	r8 = hl_types_ArrayObj_concat(r1,r9);
	return r8;
}

bool objects_ShipEngine_generateLogicConnectors__$1(objects__ShipEngine r0,bool r1,double r2) {
	bool r4;
	double r3;
	if( r0 == NULL ) hl_null_access();
	r3 = 0.;
	r0->topFlameTarget = r3;
	r4 = false;
	return r4;
}

bool objects_ShipEngine_generateLogicConnectors__$2(objects__ShipEngine r0,bool r1,double r2) {
	$Game r9;
	objects__ExtendableObject r7;
	bool r4;
	hl__types__ArrayBytes_Float r10;
	objects__ExtendableManager r8;
	double r3, r5;
	int r12, r13;
	vbyte *r11;
	if( r0 == NULL ) hl_null_access();
	if( !r1 ) goto label$634f592_3_7;
	r3 = r0->fuel;
	r5 = 0.;
	if( !(r5 < r3) ) goto label$634f592_3_7;
	r3 = 1.;
	goto label$634f592_3_8;
	label$634f592_3_7:
	r3 = 0.;
	label$634f592_3_8:
	r0->topFlameTarget = r3;
	if( !r1 ) goto label$634f592_3_43;
	r3 = r0->fuel;
	r5 = 0.;
	if( !(r5 < r3) ) goto label$634f592_3_43;
	r9 = ($Game)g$_Game;
	r8 = r9->currentShip;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->core;
	if( r7 == NULL ) hl_null_access();
	r12 = 24;
	r11 = hl_alloc_bytes(r12);
	r12 = 0;
	r3 = 0.;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r11 + r13) = r3;
	++r12;
	r3 = 10.;
	r3 = r3 * r2;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r11 + r13) = r3;
	++r12;
	r3 = 0.;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r11 + r13) = r3;
	++r12;
	r12 = 3;
	r10 = hl_types_ArrayBase_allocF64(r11,r12);
	objects_ExtendableObject_addToVelocity(r7,r10);
	r3 = r0->fuel;
	r3 = r3 - r2;
	r0->fuel = r3;
	label$634f592_3_43:
	r4 = false;
	return r4;
}

bool objects_ShipEngine_generateLogicConnectors__$3(objects__ShipEngine r0,bool r1,double r2) {
	$Game r8;
	objects__ExtendableObject r6;
	bool r4;
	objects__ExtendableManager r7;
	double r3, r5;
	if( r0 == NULL ) hl_null_access();
	if( !r1 ) goto label$634f592_4_7;
	r3 = r0->fuel;
	r5 = 0.;
	if( !(r5 < r3) ) goto label$634f592_4_7;
	r3 = 0.90000000000000002;
	goto label$634f592_4_8;
	label$634f592_4_7:
	r3 = 0.;
	label$634f592_4_8:
	r0->leftFlameTarget = r3;
	if( !r1 ) goto label$634f592_4_26;
	r3 = r0->fuel;
	r5 = 0.;
	if( !(r5 < r3) ) goto label$634f592_4_26;
	r8 = ($Game)g$_Game;
	r7 = r8->currentShip;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->core;
	if( r6 == NULL ) hl_null_access();
	r3 = r6->angularVelocity;
	r5 = 10.;
	r5 = r5 * r2;
	r3 = r3 + r5;
	r6->angularVelocity = r3;
	r3 = r0->fuel;
	r3 = r3 - r2;
	r0->fuel = r3;
	label$634f592_4_26:
	r4 = false;
	return r4;
}

hl__types__ArrayObj objects_ShipEngine_generateLogicConnectors(objects__ShipEngine r0) {
	hl__types__ArrayObj r16;
	hl_type *r18;
	bool r9;
	hl__types__ArrayBytes_Float r6;
	vclosure *r10;
	objects__LogicConnector r5, r12, r14, r19;
	double r2, r4, r11, r13, r15;
	varray *r17;
	vbyte *r7;
	int r3, r8;
	r3 = r0->sizeY;
	r2 = (double)r3;
	r4 = 2.;
	r2 = r2 / r4;
	r5 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r3 = 24;
	r7 = hl_alloc_bytes(r3);
	r3 = 0;
	r4 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r4;
	++r3;
	r8 = (int)r2;
	r8 = -r8;
	r4 = (double)r8;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r4;
	++r3;
	r4 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r4;
	++r3;
	r3 = 3;
	r6 = hl_types_ArrayBase_allocF64(r7,r3);
	r9 = true;
	r10 = hl_alloc_closure_ptr(&t$fun_c43dde5,objects_ShipEngine_generateLogicConnectors__$1,r0);
	objects_LogicConnector_new(r5,r6,((objects__ExtendableObject)r0),r9,r10);
	r3 = r0->sizeY;
	r4 = (double)r3;
	r11 = 2.;
	r4 = r4 / r11;
	r12 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r3 = 24;
	r7 = hl_alloc_bytes(r3);
	r3 = 0;
	r11 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r11;
	++r3;
	r8 = (int)r4;
	r11 = (double)r8;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r11;
	++r3;
	r11 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r11;
	++r3;
	r3 = 3;
	r6 = hl_types_ArrayBase_allocF64(r7,r3);
	r9 = true;
	r10 = hl_alloc_closure_ptr(&t$fun_c43dde5,objects_ShipEngine_generateLogicConnectors__$2,r0);
	objects_LogicConnector_new(r12,r6,((objects__ExtendableObject)r0),r9,r10);
	r3 = r0->sizeX;
	r11 = (double)r3;
	r13 = 2.;
	r11 = r11 / r13;
	r14 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r3 = 24;
	r7 = hl_alloc_bytes(r3);
	r3 = 0;
	r8 = (int)r11;
	r8 = -r8;
	r13 = (double)r8;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r13;
	++r3;
	r13 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r13;
	++r3;
	r13 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r13;
	++r3;
	r3 = 3;
	r6 = hl_types_ArrayBase_allocF64(r7,r3);
	r9 = true;
	r10 = hl_alloc_closure_ptr(&t$fun_c43dde5,objects_ShipEngine_generateLogicConnectors__$3,r0);
	objects_LogicConnector_new(r14,r6,((objects__ExtendableObject)r0),r9,r10);
	r3 = r0->sizeX;
	r13 = (double)r3;
	r15 = 2.;
	r13 = r13 / r15;
	r18 = &t$objects_LogicConnector;
	r3 = 4;
	r17 = hl_alloc_array(r18,r3);
	r3 = 0;
	((objects__LogicConnector*)(r17 + 1))[r3] = r5;
	r3 = 1;
	((objects__LogicConnector*)(r17 + 1))[r3] = r12;
	r3 = 2;
	((objects__LogicConnector*)(r17 + 1))[r3] = r14;
	r19 = (objects__LogicConnector)hl_alloc_obj(&t$objects_LogicConnector);
	r3 = 24;
	r7 = hl_alloc_bytes(r3);
	r3 = 0;
	r8 = (int)r13;
	r15 = (double)r8;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r15;
	++r3;
	r15 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r15;
	++r3;
	r15 = 0.;
	r8 = 3;
	r8 = r3 << r8;
	*(double*)(r7 + r8) = r15;
	++r3;
	r3 = 3;
	r6 = hl_types_ArrayBase_allocF64(r7,r3);
	r9 = true;
	r10 = hl_alloc_closure_ptr(&t$fun_c43dde5,objects_ShipEngine_generateLogicConnectors__$4,r0);
	objects_LogicConnector_new(r19,r6,((objects__ExtendableObject)r0),r9,r10);
	r3 = 3;
	((objects__LogicConnector*)(r17 + 1))[r3] = r19;
	r16 = hl_types_ArrayObj_alloc(r17);
	return r16;
}

bool objects_ShipEngine_generateLogicConnectors__$4(objects__ShipEngine r0,bool r1,double r2) {
	$Game r8;
	objects__ExtendableObject r6;
	bool r4;
	objects__ExtendableManager r7;
	double r3, r5;
	if( r0 == NULL ) hl_null_access();
	if( !r1 ) goto label$634f592_6_7;
	r3 = r0->fuel;
	r5 = 0.;
	if( !(r5 < r3) ) goto label$634f592_6_7;
	r3 = 0.90000000000000002;
	goto label$634f592_6_8;
	label$634f592_6_7:
	r3 = 0.;
	label$634f592_6_8:
	r0->rightFlameTarget = r3;
	if( !r1 ) goto label$634f592_6_26;
	r3 = r0->fuel;
	r5 = 0.;
	if( !(r5 < r3) ) goto label$634f592_6_26;
	r8 = ($Game)g$_Game;
	r7 = r8->currentShip;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->core;
	if( r6 == NULL ) hl_null_access();
	r3 = r6->angularVelocity;
	r5 = 10.;
	r5 = r5 * r2;
	r3 = r3 - r5;
	r6->angularVelocity = r3;
	r3 = r0->fuel;
	r3 = r3 - r2;
	r0->fuel = r3;
	label$634f592_6_26:
	r4 = false;
	return r4;
}

void objects_ShipEngine_update(objects__ShipEngine r0,double r1) {
	double r2, r3, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15, r16, r17;
	r3 = 10.;
	r2 = r1 * r3;
	r3 = r0->topFlame;
	r5 = r0->topFlameTarget;
	r6 = r5 - r3;
	r7 = hl_math_abs(r6);
	if( !(r2 >= r7) ) goto label$634f592_7_9;
	r7 = r5;
	goto label$634f592_7_15;
	label$634f592_7_9:
	r9 = 0.;
	if( !(r9 < r6) ) goto label$634f592_7_13;
	r8 = r2;
	goto label$634f592_7_14;
	label$634f592_7_13:
	r8 = -r2;
	label$634f592_7_14:
	r7 = r3 + r8;
	label$634f592_7_15:
	r0->topFlame = r7;
	r7 = r0->leftFlame;
	r8 = r0->leftFlameTarget;
	r10 = 1.2;
	r9 = r2 * r10;
	r10 = r8 - r7;
	r11 = hl_math_abs(r10);
	if( !(r9 >= r11) ) goto label$634f592_7_25;
	r11 = r8;
	goto label$634f592_7_31;
	label$634f592_7_25:
	r13 = 0.;
	if( !(r13 < r10) ) goto label$634f592_7_29;
	r12 = r9;
	goto label$634f592_7_30;
	label$634f592_7_29:
	r12 = -r9;
	label$634f592_7_30:
	r11 = r7 + r12;
	label$634f592_7_31:
	r0->leftFlame = r11;
	r11 = r0->rightFlame;
	r12 = r0->rightFlameTarget;
	r14 = 1.2;
	r13 = r2 * r14;
	r14 = r12 - r11;
	r15 = hl_math_abs(r14);
	if( !(r13 >= r15) ) goto label$634f592_7_41;
	r15 = r12;
	goto label$634f592_7_47;
	label$634f592_7_41:
	r17 = 0.;
	if( !(r17 < r14) ) goto label$634f592_7_45;
	r16 = r13;
	goto label$634f592_7_46;
	label$634f592_7_45:
	r16 = -r13;
	label$634f592_7_46:
	r15 = r11 + r16;
	label$634f592_7_47:
	r0->rightFlame = r15;
	return;
}

void objects_ShipEngine_draw(objects__ShipEngine r0) {
	$Math r4;
	hl__types__ArrayBytes_Float r15, r19, r22, r25, r27, r28, r33;
	double r1, r2, r3, r6, r7, r8, r9, r10, r11, r12, r13, r14, r23, r24, r26, r29, r30, r31, r32, r34, r35, r36, r37, r38, r39;
	int r17, r18, r20;
	vbyte *r16, *r21;
	r1 = r0->angle;
	r2 = r0->localAngle;
	r1 = r1 + r2;
	r2 = 2.;
	r4 = ($Math)g$_Math;
	r3 = r4->PI;
	r2 = r2 * r3;
	r1 = fmod(r1,r2);
	r4 = ($Math)g$_Math;
	r2 = r4->PI;
	r3 = 2.;
	r2 = r2 / r3;
	r1 = r1 + r2;
	r2 = 2.;
	r4 = ($Math)g$_Math;
	r3 = r4->PI;
	r2 = r2 * r3;
	r1 = fmod(r1,r2);
	r4 = ($Math)g$_Math;
	r3 = r4->PI;
	if( !(r3 < r1) ) goto label$634f592_8_28;
	r3 = 2.;
	r4 = ($Math)g$_Math;
	r6 = r4->PI;
	r3 = r3 * r6;
	r2 = r1 - r3;
	r1 = r2;
	goto label$634f592_8_38;
	label$634f592_8_28:
	r4 = ($Math)g$_Math;
	r3 = r4->PI;
	r3 = -r3;
	if( !(r1 < r3) ) goto label$634f592_8_38;
	r3 = 2.;
	r4 = ($Math)g$_Math;
	r6 = r4->PI;
	r3 = r3 * r6;
	r2 = r1 + r3;
	r1 = r2;
	label$634f592_8_38:
	r2 = hl_math_abs(r1);
	r3 = 0.5;
	if( !(r2 < r3) ) goto label$634f592_8_47;
	r2 = 1.;
	r3 = r1 * r1;
	r6 = 2.;
	r3 = r3 / r6;
	r2 = r2 - r3;
	goto label$634f592_8_48;
	label$634f592_8_47:
	r2 = hl_math_cos(r1);
	label$634f592_8_48:
	r3 = r0->angle;
	r6 = r0->localAngle;
	r3 = r3 + r6;
	r6 = 2.;
	r4 = ($Math)g$_Math;
	r7 = r4->PI;
	r6 = r6 * r7;
	r3 = fmod(r3,r6);
	r4 = ($Math)g$_Math;
	r6 = r4->PI;
	r7 = 2.;
	r6 = r6 / r7;
	r3 = r3 + r6;
	r6 = 2.;
	r4 = ($Math)g$_Math;
	r7 = r4->PI;
	r6 = r6 * r7;
	r3 = fmod(r3,r6);
	r4 = ($Math)g$_Math;
	r7 = r4->PI;
	if( !(r7 < r3) ) goto label$634f592_8_76;
	r7 = 2.;
	r4 = ($Math)g$_Math;
	r8 = r4->PI;
	r7 = r7 * r8;
	r6 = r3 - r7;
	r3 = r6;
	goto label$634f592_8_86;
	label$634f592_8_76:
	r4 = ($Math)g$_Math;
	r7 = r4->PI;
	r7 = -r7;
	if( !(r3 < r7) ) goto label$634f592_8_86;
	r7 = 2.;
	r4 = ($Math)g$_Math;
	r8 = r4->PI;
	r7 = r7 * r8;
	r6 = r3 + r7;
	r3 = r6;
	label$634f592_8_86:
	r7 = hl_math_abs(r3);
	r8 = 0.5;
	if( !(r7 < r8) ) goto label$634f592_8_95;
	r8 = r3 * r3;
	r8 = r8 * r3;
	r9 = 6.;
	r8 = r8 / r9;
	r7 = r3 - r8;
	goto label$634f592_8_96;
	label$634f592_8_95:
	r7 = hl_math_sin(r3);
	label$634f592_8_96:
	r8 = 0.;
	r9 = r0->angle;
	r10 = r0->localAngle;
	r9 = r9 + r10;
	r10 = 2.;
	r4 = ($Math)g$_Math;
	r11 = r4->PI;
	r10 = r10 * r11;
	r9 = fmod(r9,r10);
	r10 = 2.;
	r4 = ($Math)g$_Math;
	r11 = r4->PI;
	r10 = r10 * r11;
	r9 = fmod(r9,r10);
	r4 = ($Math)g$_Math;
	r11 = r4->PI;
	if( !(r11 < r9) ) goto label$634f592_8_120;
	r11 = 2.;
	r4 = ($Math)g$_Math;
	r12 = r4->PI;
	r11 = r11 * r12;
	r10 = r9 - r11;
	r9 = r10;
	goto label$634f592_8_130;
	label$634f592_8_120:
	r4 = ($Math)g$_Math;
	r11 = r4->PI;
	r11 = -r11;
	if( !(r9 < r11) ) goto label$634f592_8_130;
	r11 = 2.;
	r4 = ($Math)g$_Math;
	r12 = r4->PI;
	r11 = r11 * r12;
	r10 = r9 + r11;
	r9 = r10;
	label$634f592_8_130:
	r10 = hl_math_abs(r9);
	r11 = 0.5;
	if( !(r10 < r11) ) goto label$634f592_8_139;
	r10 = 1.;
	r11 = r9 * r9;
	r12 = 2.;
	r11 = r11 / r12;
	r10 = r10 - r11;
	goto label$634f592_8_140;
	label$634f592_8_139:
	r10 = hl_math_cos(r9);
	label$634f592_8_140:
	r11 = r0->angle;
	r12 = r0->localAngle;
	r11 = r11 + r12;
	r12 = 2.;
	r4 = ($Math)g$_Math;
	r13 = r4->PI;
	r12 = r12 * r13;
	r11 = fmod(r11,r12);
	r12 = 2.;
	r4 = ($Math)g$_Math;
	r13 = r4->PI;
	r12 = r12 * r13;
	r11 = fmod(r11,r12);
	r4 = ($Math)g$_Math;
	r13 = r4->PI;
	if( !(r13 < r11) ) goto label$634f592_8_163;
	r13 = 2.;
	r4 = ($Math)g$_Math;
	r14 = r4->PI;
	r13 = r13 * r14;
	r12 = r11 - r13;
	r11 = r12;
	goto label$634f592_8_173;
	label$634f592_8_163:
	r4 = ($Math)g$_Math;
	r13 = r4->PI;
	r13 = -r13;
	if( !(r11 < r13) ) goto label$634f592_8_173;
	r13 = 2.;
	r4 = ($Math)g$_Math;
	r14 = r4->PI;
	r13 = r13 * r14;
	r12 = r11 + r13;
	r11 = r12;
	label$634f592_8_173:
	r17 = 24;
	r16 = hl_alloc_bytes(r17);
	r17 = 0;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r10;
	++r17;
	r12 = hl_math_abs(r11);
	r13 = 0.5;
	if( !(r12 < r13) ) goto label$634f592_8_189;
	r13 = r11 * r11;
	r13 = r13 * r11;
	r14 = 6.;
	r13 = r13 / r14;
	r12 = r11 - r13;
	goto label$634f592_8_190;
	label$634f592_8_189:
	r12 = hl_math_sin(r11);
	label$634f592_8_190:
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r12;
	++r17;
	r12 = 0.;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r12;
	++r17;
	r17 = 3;
	r15 = hl_types_ArrayBase_allocF64(r16,r17);
	r17 = 24;
	r16 = hl_alloc_bytes(r17);
	r17 = 0;
	if( r15 == NULL ) hl_null_access();
	r18 = 0;
	r20 = r15->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_210;
	r12 = 0.;
	goto label$634f592_8_214;
	label$634f592_8_210:
	r21 = r15->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r12 = *(double*)(r21 + r20);
	label$634f592_8_214:
	r12 = -r12;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r12;
	++r17;
	r18 = 1;
	r20 = r15->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_224;
	r12 = 0.;
	goto label$634f592_8_228;
	label$634f592_8_224:
	r21 = r15->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r12 = *(double*)(r21 + r20);
	label$634f592_8_228:
	r12 = -r12;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r12;
	++r17;
	r18 = 2;
	r20 = r15->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_238;
	r12 = 0.;
	goto label$634f592_8_242;
	label$634f592_8_238:
	r21 = r15->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r12 = *(double*)(r21 + r20);
	label$634f592_8_242:
	r12 = -r12;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r12;
	++r17;
	r17 = 3;
	r19 = hl_types_ArrayBase_allocF64(r16,r17);
	r22 = r0->pos;
	r17 = r0->sizeY;
	r17 = -r17;
	r12 = (double)r17;
	r13 = 0.41999999999999998;
	r12 = r12 * r13;
	r13 = r2 * r12;
	r14 = r7 * r12;
	r23 = r8 * r12;
	r17 = 24;
	r16 = hl_alloc_bytes(r17);
	r17 = 0;
	if( r22 == NULL ) hl_null_access();
	r18 = 0;
	r20 = r22->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_267;
	r24 = 0.;
	goto label$634f592_8_271;
	label$634f592_8_267:
	r21 = r22->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r24 = *(double*)(r21 + r20);
	label$634f592_8_271:
	r24 = r24 + r13;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r24;
	++r17;
	r18 = 1;
	r20 = r22->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_281;
	r24 = 0.;
	goto label$634f592_8_285;
	label$634f592_8_281:
	r21 = r22->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r24 = *(double*)(r21 + r20);
	label$634f592_8_285:
	r24 = r24 + r14;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r24;
	++r17;
	r18 = 2;
	r20 = r22->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_295;
	r24 = 0.;
	goto label$634f592_8_299;
	label$634f592_8_295:
	r21 = r22->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r24 = *(double*)(r21 + r20);
	label$634f592_8_299:
	r24 = r24 + r23;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r24;
	++r17;
	r17 = 3;
	r25 = hl_types_ArrayBase_allocF64(r16,r17);
	r17 = 24;
	r16 = hl_alloc_bytes(r17);
	r17 = 0;
	r24 = -r2;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r24;
	++r17;
	r24 = -r7;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r24;
	++r17;
	r24 = -r8;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r24;
	++r17;
	r17 = 3;
	r28 = hl_types_ArrayBase_allocF64(r16,r17);
	r24 = r0->topFlame;
	r26 = 4.2000000000000002;
	r29 = 18.;
	r30 = r0->topFlame;
	objects_ThrusterFlameFx_drawJet(r25,r28,r24,r26,r29,r30);
	r27 = r0->pos;
	r17 = r0->sizeX;
	r17 = -r17;
	r24 = (double)r17;
	r26 = 0.46000000000000002;
	r24 = r24 * r26;
	r17 = 0;
	r18 = r15->length;
	if( ((unsigned)r17) < ((unsigned)r18) ) goto label$634f592_8_342;
	r26 = 0.;
	goto label$634f592_8_346;
	label$634f592_8_342:
	r16 = r15->bytes;
	r18 = 3;
	r18 = r17 << r18;
	r26 = *(double*)(r16 + r18);
	label$634f592_8_346:
	r26 = r26 * r24;
	r17 = 1;
	r18 = r15->length;
	if( ((unsigned)r17) < ((unsigned)r18) ) goto label$634f592_8_352;
	r29 = 0.;
	goto label$634f592_8_356;
	label$634f592_8_352:
	r16 = r15->bytes;
	r18 = 3;
	r18 = r17 << r18;
	r29 = *(double*)(r16 + r18);
	label$634f592_8_356:
	r29 = r29 * r24;
	r17 = 2;
	r18 = r15->length;
	if( ((unsigned)r17) < ((unsigned)r18) ) goto label$634f592_8_362;
	r30 = 0.;
	goto label$634f592_8_366;
	label$634f592_8_362:
	r16 = r15->bytes;
	r18 = 3;
	r18 = r17 << r18;
	r30 = *(double*)(r16 + r18);
	label$634f592_8_366:
	r30 = r30 * r24;
	r17 = 24;
	r16 = hl_alloc_bytes(r17);
	r17 = 0;
	if( r27 == NULL ) hl_null_access();
	r18 = 0;
	r20 = r27->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_376;
	r31 = 0.;
	goto label$634f592_8_380;
	label$634f592_8_376:
	r21 = r27->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r31 = *(double*)(r21 + r20);
	label$634f592_8_380:
	r31 = r31 + r26;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r31;
	++r17;
	r18 = 1;
	r20 = r27->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_390;
	r31 = 0.;
	goto label$634f592_8_394;
	label$634f592_8_390:
	r21 = r27->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r31 = *(double*)(r21 + r20);
	label$634f592_8_394:
	r31 = r31 + r29;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r31;
	++r17;
	r18 = 2;
	r20 = r27->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_404;
	r31 = 0.;
	goto label$634f592_8_408;
	label$634f592_8_404:
	r21 = r27->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r31 = *(double*)(r21 + r20);
	label$634f592_8_408:
	r31 = r31 + r30;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r31;
	++r17;
	r17 = 3;
	r28 = hl_types_ArrayBase_allocF64(r16,r17);
	r31 = r0->leftFlame;
	r32 = 2.7999999999999998;
	r34 = 10.;
	r35 = r0->leftFlame;
	objects_ThrusterFlameFx_drawJet(r28,r19,r31,r32,r34,r35);
	r28 = r0->pos;
	r17 = r0->sizeX;
	r31 = (double)r17;
	r32 = 0.46000000000000002;
	r31 = r31 * r32;
	r17 = 0;
	r18 = r15->length;
	if( ((unsigned)r17) < ((unsigned)r18) ) goto label$634f592_8_430;
	r32 = 0.;
	goto label$634f592_8_434;
	label$634f592_8_430:
	r16 = r15->bytes;
	r18 = 3;
	r18 = r17 << r18;
	r32 = *(double*)(r16 + r18);
	label$634f592_8_434:
	r32 = r32 * r31;
	r17 = 1;
	r18 = r15->length;
	if( ((unsigned)r17) < ((unsigned)r18) ) goto label$634f592_8_440;
	r34 = 0.;
	goto label$634f592_8_444;
	label$634f592_8_440:
	r16 = r15->bytes;
	r18 = 3;
	r18 = r17 << r18;
	r34 = *(double*)(r16 + r18);
	label$634f592_8_444:
	r34 = r34 * r31;
	r17 = 2;
	r18 = r15->length;
	if( ((unsigned)r17) < ((unsigned)r18) ) goto label$634f592_8_450;
	r35 = 0.;
	goto label$634f592_8_454;
	label$634f592_8_450:
	r16 = r15->bytes;
	r18 = 3;
	r18 = r17 << r18;
	r35 = *(double*)(r16 + r18);
	label$634f592_8_454:
	r35 = r35 * r31;
	r17 = 24;
	r16 = hl_alloc_bytes(r17);
	r17 = 0;
	if( r28 == NULL ) hl_null_access();
	r18 = 0;
	r20 = r28->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_464;
	r36 = 0.;
	goto label$634f592_8_468;
	label$634f592_8_464:
	r21 = r28->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r36 = *(double*)(r21 + r20);
	label$634f592_8_468:
	r36 = r36 + r32;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r36;
	++r17;
	r18 = 1;
	r20 = r28->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_478;
	r36 = 0.;
	goto label$634f592_8_482;
	label$634f592_8_478:
	r21 = r28->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r36 = *(double*)(r21 + r20);
	label$634f592_8_482:
	r36 = r36 + r34;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r36;
	++r17;
	r18 = 2;
	r20 = r28->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$634f592_8_492;
	r36 = 0.;
	goto label$634f592_8_496;
	label$634f592_8_492:
	r21 = r28->bytes;
	r20 = 3;
	r20 = r18 << r20;
	r36 = *(double*)(r21 + r20);
	label$634f592_8_496:
	r36 = r36 + r35;
	r18 = 3;
	r18 = r17 << r18;
	*(double*)(r16 + r18) = r36;
	++r17;
	r17 = 3;
	r33 = hl_types_ArrayBase_allocF64(r16,r17);
	r36 = r0->rightFlame;
	r37 = 2.7999999999999998;
	r38 = 10.;
	r39 = r0->rightFlame;
	objects_ThrusterFlameFx_drawJet(r33,r15,r36,r37,r38,r39);
	objects_ExtendableObject_draw(((objects__ExtendableObject)r0));
	return;
}

void objects_ShipEngine_new(objects__ShipEngine r0) {
	String r7;
	double r1;
	int *r4, *r6, *r8;
	int r3, r5;
	r1 = 0.;
	r0->rightFlameTarget = r1;
	r1 = 0.;
	r0->leftFlameTarget = r1;
	r1 = 0.;
	r0->topFlameTarget = r1;
	r1 = 0.;
	r0->rightFlame = r1;
	r1 = 0.;
	r0->leftFlame = r1;
	r1 = 0.;
	r0->topFlame = r1;
	r1 = 1.22;
	r0->p1p2 = r1;
	r1 = 7000000.;
	r0->fuelCameraPressure = r1;
	r1 = 0.017999999999999999;
	r0->fuelMolecularMass = r1;
	r1 = 3227.;
	r0->fuelcombustionT = r1;
	r3 = 40;
	r4 = &r3;
	r5 = 40;
	r6 = &r5;
	r7 = (String)s$ship_engine_png;
	r8 = NULL;
	objects_ExtendableObject_new(((objects__ExtendableObject)r0),r4,r6,r7,r8);
	return;
}

