// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_util__FastTrig
#define INC_util__FastTrig
typedef struct _util__$FastTrig *util__$FastTrig;
typedef struct _util__FastTrig *util__FastTrig;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayBytes_Float.h>


struct _util__$FastTrig {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	int TABLE_SIZE;
	hl__types__ArrayBytes_Float sinTable;
	hl__types__ArrayBytes_Float cosTable;
	vclosure* init;
	vclosure* sin;
	vclosure* cos;
	vclosure* fastsin;
	vclosure* fastcos;
};
struct _util__FastTrig {
	hl_type *$type;
};
#endif

