// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_util__SeedRandom
#define INC_util__SeedRandom
typedef struct _util__$SeedRandom *util__$SeedRandom;
typedef struct _util__SeedRandom *util__SeedRandom;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _util__$SeedRandom {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _util__SeedRandom {
	hl_type *$type;
	int seed;
};
#endif

