// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_util__Sequence
#define INC_util__Sequence
typedef struct _util__$Sequence *util__$Sequence;
typedef struct _util__Sequence *util__Sequence;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>
#include <haxe/ds/StringMap.h>


struct _util__$Sequence {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _util__Sequence {
	hl_type *$type;
	hl__types__ArrayObj steps;
	int index;
	haxe__ds__StringMap namedSteps;
	bool running;
};
#endif

