// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <util/Sequence.h>
extern hl_type t$vrt_da4f160;
extern hl_type t$String;
extern hl_type t$fun_0a607b2;
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
extern hl_type t$_i32;
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);
void util_Sequence_runStep(util__Sequence);
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern hl_type t$haxe_ds_StringMap;
void haxe_ds_StringMap_new(haxe__ds__StringMap);

util__Sequence util_Sequence_then(util__Sequence r0,vclosure* r1,String r2) {
	haxe__ds__StringMap r7;
	vvirtual *r5;
	hl__types__ArrayObj r4;
	vdynamic *r9;
	int r3, r8;
	r4 = r0->steps;
	if( r4 == NULL ) hl_null_access();
	r5 = hl_alloc_virtual(&t$vrt_da4f160);
	if( hl_vfields(r5)[1] ) *(String*)(hl_vfields(r5)[1]) = (String)r2; else hl_dyn_setp(r5->value,150958933/*name*/,&t$String,r2);
	if( hl_vfields(r5)[0] ) *(vclosure**)(hl_vfields(r5)[0]) = (vclosure*)r1; else hl_dyn_setp(r5->value,63237198/*func*/,&t$fun_0a607b2,r1);
	r3 = hl_types_ArrayObj_push(r4,((vdynamic*)r5));
	if( !r2 ) goto label$c686c8b_1_16;
	r7 = r0->namedSteps;
	if( r7 == NULL ) hl_null_access();
	r4 = r0->steps;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->length;
	r8 = 1;
	r3 = r3 - r8;
	r9 = hl_alloc_dynamic(&t$_i32);
	r9->v.i = r3;
	haxe_ds_StringMap_set(r7,r2,((vdynamic*)r9));
	label$c686c8b_1_16:
	return r0;
}

void util_Sequence_next(util__Sequence r0) {
	hl__types__ArrayObj r4;
	bool r5;
	int r1, r2;
	r1 = r0->index;
	++r1;
	r0->index = r1;
	r1 = r0->index;
	r4 = r0->steps;
	if( r4 == NULL ) hl_null_access();
	r2 = r4->length;
	if( r1 >= r2 ) goto label$c686c8b_2_10;
	util_Sequence_runStep(r0);
	goto label$c686c8b_2_12;
	label$c686c8b_2_10:
	r5 = false;
	r0->running = r5;
	label$c686c8b_2_12:
	return;
}

void util_Sequence_step(util__Sequence r0,String r1) {
	haxe__ds__StringMap r3;
	vdynamic *r2, *r4;
	int r6;
	r3 = r0->namedSteps;
	if( r3 == NULL ) hl_null_access();
	r2 = haxe_ds_StringMap_get(r3,r1);
	r4 = (vdynamic*)r2;
	if( !r4 ) goto label$c686c8b_3_8;
	r6 = r4 ? r4->v.i : 0;
	r0->index = r6;
	util_Sequence_runStep(r0);
	label$c686c8b_3_8:
	return;
}

void util_Sequence_restart(util__Sequence r0) {
	bool r2;
	int r1;
	r1 = 0;
	r0->index = r1;
	r2 = true;
	r0->running = r2;
	util_Sequence_runStep(r0);
	return;
}

void util_Sequence_runStep(util__Sequence r0) {
	vvirtual *r6;
	hl__types__ArrayObj r4;
	bool r9;
	vclosure *r5;
	vdynamic *r7;
	varray *r8;
	int r2, r3;
	r2 = r0->index;
	r3 = 0;
	if( r2 < r3 ) goto label$c686c8b_5_23;
	r2 = r0->index;
	r4 = r0->steps;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->length;
	if( r2 >= r3 ) goto label$c686c8b_5_23;
	r4 = r0->steps;
	if( r4 == NULL ) hl_null_access();
	r2 = r0->index;
	r3 = r4->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$c686c8b_5_15;
	r6 = NULL;
	goto label$c686c8b_5_18;
	label$c686c8b_5_15:
	r8 = r4->array;
	r7 = ((vdynamic**)(r8 + 1))[r2];
	r6 = hl_to_virtual(&t$vrt_da4f160,(vdynamic*)r7);
	label$c686c8b_5_18:
	if( r6 == NULL ) hl_null_access();
	r5 = hl_vfields(r6)[0] ? (*(vclosure**)(hl_vfields(r6)[0])) : (vclosure*)hl_dyn_getp(r6->value,63237198/*func*/,&t$fun_0a607b2);
	if( r5 == NULL ) hl_null_access();
	r5->hasValue ? ((void (*)(vdynamic*,util__Sequence))r5->fun)((vdynamic*)r5->value,r0) : ((void (*)(util__Sequence))r5->fun)(r0);
	goto label$c686c8b_5_25;
	label$c686c8b_5_23:
	r9 = false;
	r0->running = r9;
	label$c686c8b_5_25:
	return;
}

void util_Sequence_new(util__Sequence r0) {
	haxe__ds__StringMap r6;
	hl__types__ArrayObj r3;
	hl_type *r5;
	bool r1;
	varray *r4;
	int r2;
	r1 = false;
	r0->running = r1;
	r2 = 0;
	r0->index = r2;
	r5 = &t$vrt_da4f160;
	r2 = 0;
	r4 = hl_alloc_array(r5,r2);
	r3 = hl_types_ArrayObj_alloc(r4);
	r0->steps = r3;
	r6 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r6);
	r0->namedSteps = r6;
	return;
}

