// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_util__Worker
#define INC_util__Worker
typedef struct _util__$Worker *util__$Worker;
typedef struct _util__Worker *util__Worker;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>


struct _util__$Worker {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	hl_mutex* mutex;
	hl__types__ArrayObj tasks;
	vclosure* run;
	vclosure* runTask;
};
struct _util__Worker {
	hl_type *$type;
};
#endif

