// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <util/Worker.h>
#include <hl/natives.h>
extern util__$Worker g$_util_Worker;
vdynamic* hl_types_ArrayObj_shift(hl__types__ArrayObj);
#include <sys/thread/_Thread/HaxeThread.h>
extern hl_type t$fun_7b48b4f;
sys__thread___Thread__HaxeThread sys_thread__Thread_HaxeThread_create(vclosure*,bool);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);

void util_Worker_run__$1() {
	hl__types__ArrayObj r5;
	bool r0;
	util__$Worker r3;
	hl_mutex *r2;
	double r7;
	vclosure *r6;
	vdynamic *r4;
	label$38796b3_1_0:
	r0 = true;
	if( !r0 ) goto label$38796b3_1_20;
	r3 = (util__$Worker)g$_util_Worker;
	r2 = r3->mutex;
	hl_mutex_acquire(r2);
	r3 = (util__$Worker)g$_util_Worker;
	r5 = r3->tasks;
	if( r5 == NULL ) hl_null_access();
	r4 = hl_types_ArrayObj_shift(r5);
	r6 = (vclosure*)r4;
	if( !r6 ) goto label$38796b3_1_14;
	if( r6 == NULL ) hl_null_access();
	r6->hasValue ? ((void (*)(vdynamic*))r6->fun)((vdynamic*)r6->value) : ((void (*)(void))r6->fun)();
	label$38796b3_1_14:
	r3 = (util__$Worker)g$_util_Worker;
	r2 = r3->mutex;
	hl_mutex_release(r2);
	r7 = 0.10000000000000001;
	hl_sys_sleep(r7);
	goto label$38796b3_1_0;
	label$38796b3_1_20:
	return;
}

void util_Worker_run() {
	sys__thread___Thread__HaxeThread r0;
	bool r2;
	vclosure *r1;
	static vclosure cl$0 = { &t$fun_7b48b4f, util_Worker_run__$1, 0 };
	r1 = &cl$0;
	r2 = false;
	r0 = sys_thread__Thread_HaxeThread_create(r1,r2);
	return;
}

void util_Worker_runTask(vclosure* r0) {
	hl__types__ArrayObj r5;
	util__$Worker r3;
	hl_mutex *r2;
	int r4;
	r3 = (util__$Worker)g$_util_Worker;
	r2 = r3->mutex;
	hl_mutex_acquire(r2);
	r3 = (util__$Worker)g$_util_Worker;
	r5 = r3->tasks;
	if( r5 == NULL ) hl_null_access();
	r4 = hl_types_ArrayObj_push(r5,((vdynamic*)r0));
	r3 = (util__$Worker)g$_util_Worker;
	r2 = r3->mutex;
	hl_mutex_release(r2);
	return;
}

