// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_hscript__ModuleDecl
#define INC_hscript__ModuleDecl
typedef struct _hscript__$ModuleDecl *hscript__$ModuleDecl;
#include <hl/Enum.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>
#include <hscript/ModuleDecl.h>
#include <hscript/CType.h>


struct _hscript__$ModuleDecl {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___ename__;
	hl_bytes_map* _hx___emap__;
	hl__types__ArrayObj _hx___constructs__;
	varray* _hx___evalues__;
};
typedef struct {
	HL__ENUM_CONSTRUCT__
	hl__types__ArrayObj p0;
} hscript_ModuleDecl_DPackage;
typedef struct {
	HL__ENUM_CONSTRUCT__
	hl__types__ArrayObj p0;
	vdynamic* p1;
	String p2;
} hscript_ModuleDecl_DImport;
typedef struct {
	HL__ENUM_CONSTRUCT__
	vvirtual* p0;
} hscript_ModuleDecl_DClass;
typedef struct {
	HL__ENUM_CONSTRUCT__
	vvirtual* p0;
} hscript_ModuleDecl_DTypedef;
#endif

