// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_hscript__Token
#define INC_hscript__Token
typedef struct _hscript__$Token *hscript__$Token;
#include <hl/Enum.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>
#include <hscript/Const.h>
#include <hscript/Token.h>


struct _hscript__$Token {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___ename__;
	hl_bytes_map* _hx___emap__;
	hl__types__ArrayObj _hx___constructs__;
	varray* _hx___evalues__;
};
typedef struct {
	HL__ENUM_CONSTRUCT__
	venum* p0;
} hscript_Token_TConst;
typedef struct {
	HL__ENUM_CONSTRUCT__
	String p0;
} hscript_Token_TId;
typedef struct {
	HL__ENUM_CONSTRUCT__
	String p0;
} hscript_Token_TOp;
typedef struct {
	HL__ENUM_CONSTRUCT__
	String p0;
} hscript_Token_TMeta;
typedef struct {
	HL__ENUM_CONSTRUCT__
	String p0;
} hscript_Token_TPrepro;
#endif

