// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <hscript/Tools.h>
#include <hscript/Const.h>
#include <hscript/CType.h>
#include <hl/types/ArrayObj.h>
extern hl_type t$vrt_a226c6b;
extern hl_type t$hscript_Expr;
extern hl_type t$vrt_9b52c5f;
extern hl_type t$hl_types_ArrayObj;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
extern hl_type t$String;
extern String s$in;
int String___compare(String,vdynamic*);
extern String s$467a1c8;

void hscript_Tools_iter(venum* r0,vclosure* r1) {
	String r6;
	vvirtual *r17, *r18;
	hl__types__ArrayObj r9, r12;
	venum *r4, *r5, *r7, *r8, *r15;
	bool r16;
	vdynamic *r13;
	varray *r14;
	int r3, r10, r11, r19;
	if( r0 == NULL ) hl_null_access();
	r3 = HL__ENUM_INDEX__(r0);
	switch(r3) {
		default:
			goto label$25ae9df_1_283;
		case 0:
			r5 = ((hscript_Expr_EConst*)r0)->p0;
			goto label$25ae9df_1_283;
		case 1:
			r6 = ((hscript_Expr_EIdent*)r0)->p0;
			goto label$25ae9df_1_283;
		case 2:
			r6 = ((hscript_Expr_EVar*)r0)->p0;
			r7 = ((hscript_Expr_EVar*)r0)->p1;
			r4 = ((hscript_Expr_EVar*)r0)->p2;
			if( !r4 ) goto label$25ae9df_1_14;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			label$25ae9df_1_14:
			goto label$25ae9df_1_283;
		case 3:
			r4 = ((hscript_Expr_EParent*)r0)->p0;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			goto label$25ae9df_1_283;
		case 4:
			r9 = ((hscript_Expr_EBlock*)r0)->p0;
			r3 = 0;
			label$25ae9df_1_21:
			if( r9 == NULL ) hl_null_access();
			r11 = r9->length;
			if( r3 >= r11 ) goto label$25ae9df_1_36;
			r11 = r9->length;
			if( ((unsigned)r3) < ((unsigned)r11) ) goto label$25ae9df_1_29;
			r4 = NULL;
			goto label$25ae9df_1_32;
			label$25ae9df_1_29:
			r14 = r9->array;
			r13 = ((vdynamic**)(r14 + 1))[r3];
			r4 = (venum*)r13;
			label$25ae9df_1_32:
			++r3;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			goto label$25ae9df_1_21;
			label$25ae9df_1_36:
			goto label$25ae9df_1_283;
		case 5:
			r6 = ((hscript_Expr_EField*)r0)->p1;
			r4 = ((hscript_Expr_EField*)r0)->p0;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			goto label$25ae9df_1_283;
		case 6:
			r6 = ((hscript_Expr_EBinop*)r0)->p0;
			r4 = ((hscript_Expr_EBinop*)r0)->p1;
			r8 = ((hscript_Expr_EBinop*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			goto label$25ae9df_1_283;
		case 7:
			r6 = ((hscript_Expr_EUnop*)r0)->p0;
			r16 = ((hscript_Expr_EUnop*)r0)->p1;
			r4 = ((hscript_Expr_EUnop*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			goto label$25ae9df_1_283;
		case 8:
			r4 = ((hscript_Expr_ECall*)r0)->p0;
			r9 = ((hscript_Expr_ECall*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			r3 = 0;
			label$25ae9df_1_60:
			if( r9 == NULL ) hl_null_access();
			r11 = r9->length;
			if( r3 >= r11 ) goto label$25ae9df_1_75;
			r11 = r9->length;
			if( ((unsigned)r3) < ((unsigned)r11) ) goto label$25ae9df_1_68;
			r8 = NULL;
			goto label$25ae9df_1_71;
			label$25ae9df_1_68:
			r14 = r9->array;
			r13 = ((vdynamic**)(r14 + 1))[r3];
			r8 = (venum*)r13;
			label$25ae9df_1_71:
			++r3;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			goto label$25ae9df_1_60;
			label$25ae9df_1_75:
			goto label$25ae9df_1_283;
		case 9:
			r4 = ((hscript_Expr_EIf*)r0)->p0;
			r8 = ((hscript_Expr_EIf*)r0)->p1;
			r15 = ((hscript_Expr_EIf*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			if( !r15 ) goto label$25ae9df_1_84;
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r15) : ((void (*)(venum*))r1->fun)(r15);
			label$25ae9df_1_84:
			goto label$25ae9df_1_283;
		case 10:
			r4 = ((hscript_Expr_EWhile*)r0)->p0;
			r8 = ((hscript_Expr_EWhile*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			goto label$25ae9df_1_283;
		case 11:
			r6 = ((hscript_Expr_EFor*)r0)->p0;
			r4 = ((hscript_Expr_EFor*)r0)->p1;
			r8 = ((hscript_Expr_EFor*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			goto label$25ae9df_1_283;
		case 12:
		case 13:
			goto label$25ae9df_1_283;
		case 14:
			r9 = ((hscript_Expr_EFunction*)r0)->p0;
			r6 = ((hscript_Expr_EFunction*)r0)->p2;
			r7 = ((hscript_Expr_EFunction*)r0)->p3;
			r4 = ((hscript_Expr_EFunction*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			goto label$25ae9df_1_283;
		case 15:
			r4 = ((hscript_Expr_EReturn*)r0)->p0;
			if( !r4 ) goto label$25ae9df_1_110;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			label$25ae9df_1_110:
			goto label$25ae9df_1_283;
		case 16:
			r4 = ((hscript_Expr_EArray*)r0)->p0;
			r8 = ((hscript_Expr_EArray*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			goto label$25ae9df_1_283;
		case 17:
			r9 = ((hscript_Expr_EArrayDecl*)r0)->p0;
			r3 = 0;
			label$25ae9df_1_119:
			if( r9 == NULL ) hl_null_access();
			r11 = r9->length;
			if( r3 >= r11 ) goto label$25ae9df_1_134;
			r11 = r9->length;
			if( ((unsigned)r3) < ((unsigned)r11) ) goto label$25ae9df_1_127;
			r4 = NULL;
			goto label$25ae9df_1_130;
			label$25ae9df_1_127:
			r14 = r9->array;
			r13 = ((vdynamic**)(r14 + 1))[r3];
			r4 = (venum*)r13;
			label$25ae9df_1_130:
			++r3;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			goto label$25ae9df_1_119;
			label$25ae9df_1_134:
			goto label$25ae9df_1_283;
		case 18:
			r6 = ((hscript_Expr_ENew*)r0)->p0;
			r9 = ((hscript_Expr_ENew*)r0)->p1;
			r3 = 0;
			label$25ae9df_1_138:
			if( r9 == NULL ) hl_null_access();
			r11 = r9->length;
			if( r3 >= r11 ) goto label$25ae9df_1_153;
			r11 = r9->length;
			if( ((unsigned)r3) < ((unsigned)r11) ) goto label$25ae9df_1_146;
			r4 = NULL;
			goto label$25ae9df_1_149;
			label$25ae9df_1_146:
			r14 = r9->array;
			r13 = ((vdynamic**)(r14 + 1))[r3];
			r4 = (venum*)r13;
			label$25ae9df_1_149:
			++r3;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			goto label$25ae9df_1_138;
			label$25ae9df_1_153:
			goto label$25ae9df_1_283;
		case 19:
			r4 = ((hscript_Expr_EThrow*)r0)->p0;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			goto label$25ae9df_1_283;
		case 20:
			r6 = ((hscript_Expr_ETry*)r0)->p1;
			r7 = ((hscript_Expr_ETry*)r0)->p2;
			r4 = ((hscript_Expr_ETry*)r0)->p0;
			r8 = ((hscript_Expr_ETry*)r0)->p3;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			goto label$25ae9df_1_283;
		case 21:
			r9 = ((hscript_Expr_EObject*)r0)->p0;
			r3 = 0;
			label$25ae9df_1_168:
			if( r9 == NULL ) hl_null_access();
			r11 = r9->length;
			if( r3 >= r11 ) goto label$25ae9df_1_185;
			r11 = r9->length;
			if( ((unsigned)r3) < ((unsigned)r11) ) goto label$25ae9df_1_176;
			r17 = NULL;
			goto label$25ae9df_1_179;
			label$25ae9df_1_176:
			r14 = r9->array;
			r13 = ((vdynamic**)(r14 + 1))[r3];
			r17 = hl_to_virtual(&t$vrt_a226c6b,(vdynamic*)r13);
			label$25ae9df_1_179:
			++r3;
			if( r1 == NULL ) hl_null_access();
			if( r17 == NULL ) hl_null_access();
			r4 = hl_vfields(r17)[0] ? (*(venum**)(hl_vfields(r17)[0])) : (venum*)hl_dyn_getp(r17->value,101/*e*/,&t$hscript_Expr);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			goto label$25ae9df_1_168;
			label$25ae9df_1_185:
			goto label$25ae9df_1_283;
		case 22:
			r4 = ((hscript_Expr_ETernary*)r0)->p0;
			r8 = ((hscript_Expr_ETernary*)r0)->p1;
			r15 = ((hscript_Expr_ETernary*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r15) : ((void (*)(venum*))r1->fun)(r15);
			goto label$25ae9df_1_283;
		case 23:
			r4 = ((hscript_Expr_ESwitch*)r0)->p0;
			r9 = ((hscript_Expr_ESwitch*)r0)->p1;
			r8 = ((hscript_Expr_ESwitch*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			r3 = 0;
			label$25ae9df_1_200:
			if( r9 == NULL ) hl_null_access();
			r11 = r9->length;
			if( r3 >= r11 ) goto label$25ae9df_1_235;
			r11 = r9->length;
			if( ((unsigned)r3) < ((unsigned)r11) ) goto label$25ae9df_1_208;
			r18 = NULL;
			goto label$25ae9df_1_211;
			label$25ae9df_1_208:
			r14 = r9->array;
			r13 = ((vdynamic**)(r14 + 1))[r3];
			r18 = hl_to_virtual(&t$vrt_9b52c5f,(vdynamic*)r13);
			label$25ae9df_1_211:
			++r3;
			r10 = 0;
			if( r18 == NULL ) hl_null_access();
			r12 = hl_vfields(r18)[1] ? (*(hl__types__ArrayObj*)(hl_vfields(r18)[1])) : (hl__types__ArrayObj)hl_dyn_getp(r18->value,263652588/*values*/,&t$hl_types_ArrayObj);
			label$25ae9df_1_215:
			if( r12 == NULL ) hl_null_access();
			r19 = r12->length;
			if( r10 >= r19 ) goto label$25ae9df_1_230;
			r19 = r12->length;
			if( ((unsigned)r10) < ((unsigned)r19) ) goto label$25ae9df_1_223;
			r15 = NULL;
			goto label$25ae9df_1_226;
			label$25ae9df_1_223:
			r14 = r12->array;
			r13 = ((vdynamic**)(r14 + 1))[r10];
			r15 = (venum*)r13;
			label$25ae9df_1_226:
			++r10;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r15) : ((void (*)(venum*))r1->fun)(r15);
			goto label$25ae9df_1_215;
			label$25ae9df_1_230:
			if( r1 == NULL ) hl_null_access();
			if( r18 == NULL ) hl_null_access();
			r15 = hl_vfields(r18)[0] ? (*(venum**)(hl_vfields(r18)[0])) : (venum*)hl_dyn_getp(r18->value,52297279/*expr*/,&t$hscript_Expr);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r15) : ((void (*)(venum*))r1->fun)(r15);
			goto label$25ae9df_1_200;
			label$25ae9df_1_235:
			if( !r8 ) goto label$25ae9df_1_238;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			label$25ae9df_1_238:
			goto label$25ae9df_1_283;
		case 24:
			r4 = ((hscript_Expr_EDoWhile*)r0)->p0;
			r8 = ((hscript_Expr_EDoWhile*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			goto label$25ae9df_1_283;
		case 25:
			r6 = ((hscript_Expr_EMeta*)r0)->p0;
			r9 = ((hscript_Expr_EMeta*)r0)->p1;
			r4 = ((hscript_Expr_EMeta*)r0)->p2;
			if( !r9 ) goto label$25ae9df_1_265;
			r3 = 0;
			label$25ae9df_1_250:
			if( r9 == NULL ) hl_null_access();
			r11 = r9->length;
			if( r3 >= r11 ) goto label$25ae9df_1_265;
			r11 = r9->length;
			if( ((unsigned)r3) < ((unsigned)r11) ) goto label$25ae9df_1_258;
			r8 = NULL;
			goto label$25ae9df_1_261;
			label$25ae9df_1_258:
			r14 = r9->array;
			r13 = ((vdynamic**)(r14 + 1))[r3];
			r8 = (venum*)r13;
			label$25ae9df_1_261:
			++r3;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			goto label$25ae9df_1_250;
			label$25ae9df_1_265:
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			goto label$25ae9df_1_283;
		case 26:
			r7 = ((hscript_Expr_ECheckType*)r0)->p1;
			r4 = ((hscript_Expr_ECheckType*)r0)->p0;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			goto label$25ae9df_1_283;
		case 27:
			r4 = ((hscript_Expr_EForGen*)r0)->p0;
			r8 = ((hscript_Expr_EForGen*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((void (*)(venum*))r1->fun)(r8);
			goto label$25ae9df_1_283;
		case 28:
			r7 = ((hscript_Expr_ECast*)r0)->p1;
			r4 = ((hscript_Expr_ECast*)r0)->p0;
			if( r1 == NULL ) hl_null_access();
			r1->hasValue ? ((void (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r4) : ((void (*)(venum*))r1->fun)(r4);
	}
	label$25ae9df_1_283:
	return;
}

venum* hscript_Tools_map(venum* r0,vclosure* r1) {
	String r6;
	vvirtual *r22, *r23, *r24, *r26;
	hl__types__ArrayObj r9, r10, r15, r25;
	hl_type *r12;
	venum *r3, *r4, *r5, *r7, *r8, *r17, *r18, *r20, *r21;
	bool r19;
	vdynamic *r16;
	varray *r11;
	int r2, r13, r14, r27;
	r3 = r0;
	if( r0 == NULL ) hl_null_access();
	r2 = HL__ENUM_INDEX__(r0);
	switch(r2) {
		default:
			goto label$25ae9df_2_402;
		case 0:
			r4 = ((hscript_Expr_EConst*)r0)->p0;
			r3 = r0;
			goto label$25ae9df_2_402;
		case 1:
			r6 = ((hscript_Expr_EIdent*)r0)->p0;
			r3 = r0;
			goto label$25ae9df_2_402;
		case 2:
			r6 = ((hscript_Expr_EVar*)r0)->p0;
			r7 = ((hscript_Expr_EVar*)r0)->p1;
			r5 = ((hscript_Expr_EVar*)r0)->p2;
			if( !r5 ) goto label$25ae9df_2_18;
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			goto label$25ae9df_2_19;
			label$25ae9df_2_18:
			r8 = NULL;
			label$25ae9df_2_19:
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,2);
			((hscript_Expr_EVar*)tmp)->p0 = r6;
			((hscript_Expr_EVar*)tmp)->p1 = r7;
			((hscript_Expr_EVar*)tmp)->p2 = r8;
			r8 = tmp; };
			r3 = r8;
			goto label$25ae9df_2_402;
		case 3:
			r5 = ((hscript_Expr_EParent*)r0)->p0;
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,3);
			((hscript_Expr_EParent*)tmp)->p0 = r8;
			r8 = tmp; };
			r3 = r8;
			goto label$25ae9df_2_402;
		case 4:
			r9 = ((hscript_Expr_EBlock*)r0)->p0;
			r12 = &t$hscript_Expr;
			r2 = 0;
			r11 = hl_alloc_array(r12,r2);
			r10 = hl_types_ArrayObj_alloc(r11);
			r2 = 0;
			label$25ae9df_2_34:
			if( r9 == NULL ) hl_null_access();
			r14 = r9->length;
			if( r2 >= r14 ) goto label$25ae9df_2_51;
			r14 = r9->length;
			if( ((unsigned)r2) < ((unsigned)r14) ) goto label$25ae9df_2_42;
			r5 = NULL;
			goto label$25ae9df_2_45;
			label$25ae9df_2_42:
			r11 = r9->array;
			r16 = ((vdynamic**)(r11 + 1))[r2];
			r5 = (venum*)r16;
			label$25ae9df_2_45:
			++r2;
			if( r10 == NULL ) hl_null_access();
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r13 = hl_types_ArrayObj_push(r10,((vdynamic*)r8));
			goto label$25ae9df_2_34;
			label$25ae9df_2_51:
			r5 = hl_alloc_enum(&t$hscript_Expr,4);
			((hscript_Expr_EBlock*)r5)->p0 = r10;
			r3 = r5;
			goto label$25ae9df_2_402;
		case 5:
			r5 = ((hscript_Expr_EField*)r0)->p0;
			r6 = ((hscript_Expr_EField*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,5);
			((hscript_Expr_EField*)tmp)->p0 = r8;
			((hscript_Expr_EField*)tmp)->p1 = r6;
			r8 = tmp; };
			r3 = r8;
			goto label$25ae9df_2_402;
		case 6:
			r6 = ((hscript_Expr_EBinop*)r0)->p0;
			r5 = ((hscript_Expr_EBinop*)r0)->p1;
			r8 = ((hscript_Expr_EBinop*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r17 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r18 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((venum* (*)(venum*))r1->fun)(r8);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,6);
			((hscript_Expr_EBinop*)tmp)->p0 = r6;
			((hscript_Expr_EBinop*)tmp)->p1 = r17;
			((hscript_Expr_EBinop*)tmp)->p2 = r18;
			r17 = tmp; };
			r3 = r17;
			goto label$25ae9df_2_402;
		case 7:
			r6 = ((hscript_Expr_EUnop*)r0)->p0;
			r19 = ((hscript_Expr_EUnop*)r0)->p1;
			r5 = ((hscript_Expr_EUnop*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,7);
			((hscript_Expr_EUnop*)tmp)->p0 = r6;
			((hscript_Expr_EUnop*)tmp)->p1 = r19;
			((hscript_Expr_EUnop*)tmp)->p2 = r8;
			r8 = tmp; };
			r3 = r8;
			goto label$25ae9df_2_402;
		case 8:
			r5 = ((hscript_Expr_ECall*)r0)->p0;
			r9 = ((hscript_Expr_ECall*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r12 = &t$hscript_Expr;
			r2 = 0;
			r11 = hl_alloc_array(r12,r2);
			r10 = hl_types_ArrayObj_alloc(r11);
			r2 = 0;
			label$25ae9df_2_87:
			if( r9 == NULL ) hl_null_access();
			r14 = r9->length;
			if( r2 >= r14 ) goto label$25ae9df_2_104;
			r14 = r9->length;
			if( ((unsigned)r2) < ((unsigned)r14) ) goto label$25ae9df_2_95;
			r17 = NULL;
			goto label$25ae9df_2_98;
			label$25ae9df_2_95:
			r11 = r9->array;
			r16 = ((vdynamic**)(r11 + 1))[r2];
			r17 = (venum*)r16;
			label$25ae9df_2_98:
			++r2;
			if( r10 == NULL ) hl_null_access();
			if( r1 == NULL ) hl_null_access();
			r18 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r17) : ((venum* (*)(venum*))r1->fun)(r17);
			r13 = hl_types_ArrayObj_push(r10,((vdynamic*)r18));
			goto label$25ae9df_2_87;
			label$25ae9df_2_104:
			r17 = hl_alloc_enum(&t$hscript_Expr,8);
			((hscript_Expr_ECall*)r17)->p0 = r8;
			((hscript_Expr_ECall*)r17)->p1 = r10;
			r3 = r17;
			goto label$25ae9df_2_402;
		case 9:
			r5 = ((hscript_Expr_EIf*)r0)->p0;
			r8 = ((hscript_Expr_EIf*)r0)->p1;
			r17 = ((hscript_Expr_EIf*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r18 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r20 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((venum* (*)(venum*))r1->fun)(r8);
			if( !r17 ) goto label$25ae9df_2_116;
			r21 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r17) : ((venum* (*)(venum*))r1->fun)(r17);
			goto label$25ae9df_2_117;
			label$25ae9df_2_116:
			r21 = NULL;
			label$25ae9df_2_117:
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,9);
			((hscript_Expr_EIf*)tmp)->p0 = r18;
			((hscript_Expr_EIf*)tmp)->p1 = r20;
			((hscript_Expr_EIf*)tmp)->p2 = r21;
			r18 = tmp; };
			r3 = r18;
			goto label$25ae9df_2_402;
		case 10:
			r5 = ((hscript_Expr_EWhile*)r0)->p0;
			r8 = ((hscript_Expr_EWhile*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r17 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r18 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((venum* (*)(venum*))r1->fun)(r8);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,10);
			((hscript_Expr_EWhile*)tmp)->p0 = r17;
			((hscript_Expr_EWhile*)tmp)->p1 = r18;
			r17 = tmp; };
			r3 = r17;
			goto label$25ae9df_2_402;
		case 11:
			r6 = ((hscript_Expr_EFor*)r0)->p0;
			r5 = ((hscript_Expr_EFor*)r0)->p1;
			r8 = ((hscript_Expr_EFor*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r17 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r18 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((venum* (*)(venum*))r1->fun)(r8);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,11);
			((hscript_Expr_EFor*)tmp)->p0 = r6;
			((hscript_Expr_EFor*)tmp)->p1 = r17;
			((hscript_Expr_EFor*)tmp)->p2 = r18;
			r17 = tmp; };
			r3 = r17;
			goto label$25ae9df_2_402;
		case 12:
		case 13:
			r3 = r0;
			goto label$25ae9df_2_402;
		case 14:
			r9 = ((hscript_Expr_EFunction*)r0)->p0;
			r5 = ((hscript_Expr_EFunction*)r0)->p1;
			r6 = ((hscript_Expr_EFunction*)r0)->p2;
			r7 = ((hscript_Expr_EFunction*)r0)->p3;
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,14);
			((hscript_Expr_EFunction*)tmp)->p0 = r9;
			((hscript_Expr_EFunction*)tmp)->p1 = r8;
			((hscript_Expr_EFunction*)tmp)->p2 = r6;
			((hscript_Expr_EFunction*)tmp)->p3 = r7;
			r8 = tmp; };
			r3 = r8;
			goto label$25ae9df_2_402;
		case 15:
			r5 = ((hscript_Expr_EReturn*)r0)->p0;
			if( !r5 ) goto label$25ae9df_2_153;
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			goto label$25ae9df_2_154;
			label$25ae9df_2_153:
			r8 = NULL;
			label$25ae9df_2_154:
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,15);
			((hscript_Expr_EReturn*)tmp)->p0 = r8;
			r8 = tmp; };
			r3 = r8;
			goto label$25ae9df_2_402;
		case 16:
			r5 = ((hscript_Expr_EArray*)r0)->p0;
			r8 = ((hscript_Expr_EArray*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r17 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r18 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((venum* (*)(venum*))r1->fun)(r8);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,16);
			((hscript_Expr_EArray*)tmp)->p0 = r17;
			((hscript_Expr_EArray*)tmp)->p1 = r18;
			r17 = tmp; };
			r3 = r17;
			goto label$25ae9df_2_402;
		case 17:
			r9 = ((hscript_Expr_EArrayDecl*)r0)->p0;
			r12 = &t$hscript_Expr;
			r2 = 0;
			r11 = hl_alloc_array(r12,r2);
			r10 = hl_types_ArrayObj_alloc(r11);
			r2 = 0;
			label$25ae9df_2_171:
			if( r9 == NULL ) hl_null_access();
			r14 = r9->length;
			if( r2 >= r14 ) goto label$25ae9df_2_188;
			r14 = r9->length;
			if( ((unsigned)r2) < ((unsigned)r14) ) goto label$25ae9df_2_179;
			r5 = NULL;
			goto label$25ae9df_2_182;
			label$25ae9df_2_179:
			r11 = r9->array;
			r16 = ((vdynamic**)(r11 + 1))[r2];
			r5 = (venum*)r16;
			label$25ae9df_2_182:
			++r2;
			if( r10 == NULL ) hl_null_access();
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r13 = hl_types_ArrayObj_push(r10,((vdynamic*)r8));
			goto label$25ae9df_2_171;
			label$25ae9df_2_188:
			r5 = hl_alloc_enum(&t$hscript_Expr,17);
			((hscript_Expr_EArrayDecl*)r5)->p0 = r10;
			r3 = r5;
			goto label$25ae9df_2_402;
		case 18:
			r6 = ((hscript_Expr_ENew*)r0)->p0;
			r9 = ((hscript_Expr_ENew*)r0)->p1;
			r12 = &t$hscript_Expr;
			r2 = 0;
			r11 = hl_alloc_array(r12,r2);
			r10 = hl_types_ArrayObj_alloc(r11);
			r2 = 0;
			label$25ae9df_2_198:
			if( r9 == NULL ) hl_null_access();
			r14 = r9->length;
			if( r2 >= r14 ) goto label$25ae9df_2_215;
			r14 = r9->length;
			if( ((unsigned)r2) < ((unsigned)r14) ) goto label$25ae9df_2_206;
			r5 = NULL;
			goto label$25ae9df_2_209;
			label$25ae9df_2_206:
			r11 = r9->array;
			r16 = ((vdynamic**)(r11 + 1))[r2];
			r5 = (venum*)r16;
			label$25ae9df_2_209:
			++r2;
			if( r10 == NULL ) hl_null_access();
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r13 = hl_types_ArrayObj_push(r10,((vdynamic*)r8));
			goto label$25ae9df_2_198;
			label$25ae9df_2_215:
			r5 = hl_alloc_enum(&t$hscript_Expr,18);
			((hscript_Expr_ENew*)r5)->p0 = r6;
			((hscript_Expr_ENew*)r5)->p1 = r10;
			r3 = r5;
			goto label$25ae9df_2_402;
		case 19:
			r5 = ((hscript_Expr_EThrow*)r0)->p0;
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,19);
			((hscript_Expr_EThrow*)tmp)->p0 = r8;
			r8 = tmp; };
			r3 = r8;
			goto label$25ae9df_2_402;
		case 20:
			r5 = ((hscript_Expr_ETry*)r0)->p0;
			r6 = ((hscript_Expr_ETry*)r0)->p1;
			r7 = ((hscript_Expr_ETry*)r0)->p2;
			r8 = ((hscript_Expr_ETry*)r0)->p3;
			if( r1 == NULL ) hl_null_access();
			r17 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r18 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((venum* (*)(venum*))r1->fun)(r8);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,20);
			((hscript_Expr_ETry*)tmp)->p0 = r17;
			((hscript_Expr_ETry*)tmp)->p1 = r6;
			((hscript_Expr_ETry*)tmp)->p2 = r7;
			((hscript_Expr_ETry*)tmp)->p3 = r18;
			r17 = tmp; };
			r3 = r17;
			goto label$25ae9df_2_402;
		case 21:
			r9 = ((hscript_Expr_EObject*)r0)->p0;
			r12 = &t$vrt_a226c6b;
			r2 = 0;
			r11 = hl_alloc_array(r12,r2);
			r10 = hl_types_ArrayObj_alloc(r11);
			r2 = 0;
			label$25ae9df_2_240:
			if( r9 == NULL ) hl_null_access();
			r14 = r9->length;
			if( r2 >= r14 ) goto label$25ae9df_2_263;
			r14 = r9->length;
			if( ((unsigned)r2) < ((unsigned)r14) ) goto label$25ae9df_2_248;
			r22 = NULL;
			goto label$25ae9df_2_251;
			label$25ae9df_2_248:
			r11 = r9->array;
			r16 = ((vdynamic**)(r11 + 1))[r2];
			r22 = hl_to_virtual(&t$vrt_a226c6b,(vdynamic*)r16);
			label$25ae9df_2_251:
			++r2;
			if( r10 == NULL ) hl_null_access();
			r23 = hl_alloc_virtual(&t$vrt_a226c6b);
			if( r22 == NULL ) hl_null_access();
			r6 = hl_vfields(r22)[1] ? (*(String*)(hl_vfields(r22)[1])) : (String)hl_dyn_getp(r22->value,150958933/*name*/,&t$String);
			if( hl_vfields(r23)[1] ) *(String*)(hl_vfields(r23)[1]) = (String)r6; else hl_dyn_setp(r23->value,150958933/*name*/,&t$String,r6);
			if( r1 == NULL ) hl_null_access();
			r5 = hl_vfields(r22)[0] ? (*(venum**)(hl_vfields(r22)[0])) : (venum*)hl_dyn_getp(r22->value,101/*e*/,&t$hscript_Expr);
			r5 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			if( hl_vfields(r23)[0] ) *(venum**)(hl_vfields(r23)[0]) = (venum*)r5; else hl_dyn_setp(r23->value,101/*e*/,&t$hscript_Expr,r5);
			r13 = hl_types_ArrayObj_push(r10,((vdynamic*)r23));
			goto label$25ae9df_2_240;
			label$25ae9df_2_263:
			r5 = hl_alloc_enum(&t$hscript_Expr,21);
			((hscript_Expr_EObject*)r5)->p0 = r10;
			r3 = r5;
			goto label$25ae9df_2_402;
		case 22:
			r5 = ((hscript_Expr_ETernary*)r0)->p0;
			r8 = ((hscript_Expr_ETernary*)r0)->p1;
			r17 = ((hscript_Expr_ETernary*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r18 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r20 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((venum* (*)(venum*))r1->fun)(r8);
			r21 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r17) : ((venum* (*)(venum*))r1->fun)(r17);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,22);
			((hscript_Expr_ETernary*)tmp)->p0 = r18;
			((hscript_Expr_ETernary*)tmp)->p1 = r20;
			((hscript_Expr_ETernary*)tmp)->p2 = r21;
			r18 = tmp; };
			r3 = r18;
			goto label$25ae9df_2_402;
		case 23:
			r5 = ((hscript_Expr_ESwitch*)r0)->p0;
			r9 = ((hscript_Expr_ESwitch*)r0)->p1;
			r8 = ((hscript_Expr_ESwitch*)r0)->p2;
			if( r1 == NULL ) hl_null_access();
			r17 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r12 = &t$vrt_9b52c5f;
			r2 = 0;
			r11 = hl_alloc_array(r12,r2);
			r10 = hl_types_ArrayObj_alloc(r11);
			r2 = 0;
			label$25ae9df_2_286:
			if( r9 == NULL ) hl_null_access();
			r14 = r9->length;
			if( r2 >= r14 ) goto label$25ae9df_2_332;
			r14 = r9->length;
			if( ((unsigned)r2) < ((unsigned)r14) ) goto label$25ae9df_2_294;
			r24 = NULL;
			goto label$25ae9df_2_297;
			label$25ae9df_2_294:
			r11 = r9->array;
			r16 = ((vdynamic**)(r11 + 1))[r2];
			r24 = hl_to_virtual(&t$vrt_9b52c5f,(vdynamic*)r16);
			label$25ae9df_2_297:
			++r2;
			r12 = &t$hscript_Expr;
			r13 = 0;
			r11 = hl_alloc_array(r12,r13);
			r15 = hl_types_ArrayObj_alloc(r11);
			r13 = 0;
			if( r24 == NULL ) hl_null_access();
			r25 = hl_vfields(r24)[1] ? (*(hl__types__ArrayObj*)(hl_vfields(r24)[1])) : (hl__types__ArrayObj)hl_dyn_getp(r24->value,263652588/*values*/,&t$hl_types_ArrayObj);
			label$25ae9df_2_305:
			if( r25 == NULL ) hl_null_access();
			r27 = r25->length;
			if( r13 >= r27 ) goto label$25ae9df_2_322;
			r27 = r25->length;
			if( ((unsigned)r13) < ((unsigned)r27) ) goto label$25ae9df_2_313;
			r18 = NULL;
			goto label$25ae9df_2_316;
			label$25ae9df_2_313:
			r11 = r25->array;
			r16 = ((vdynamic**)(r11 + 1))[r13];
			r18 = (venum*)r16;
			label$25ae9df_2_316:
			++r13;
			if( r15 == NULL ) hl_null_access();
			if( r1 == NULL ) hl_null_access();
			r20 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r18) : ((venum* (*)(venum*))r1->fun)(r18);
			r14 = hl_types_ArrayObj_push(r15,((vdynamic*)r20));
			goto label$25ae9df_2_305;
			label$25ae9df_2_322:
			if( r10 == NULL ) hl_null_access();
			r26 = hl_alloc_virtual(&t$vrt_9b52c5f);
			if( hl_vfields(r26)[1] ) *(hl__types__ArrayObj*)(hl_vfields(r26)[1]) = (hl__types__ArrayObj)r15; else hl_dyn_setp(r26->value,263652588/*values*/,&t$hl_types_ArrayObj,r15);
			if( r1 == NULL ) hl_null_access();
			if( r24 == NULL ) hl_null_access();
			r18 = hl_vfields(r24)[0] ? (*(venum**)(hl_vfields(r24)[0])) : (venum*)hl_dyn_getp(r24->value,52297279/*expr*/,&t$hscript_Expr);
			r18 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r18) : ((venum* (*)(venum*))r1->fun)(r18);
			if( hl_vfields(r26)[0] ) *(venum**)(hl_vfields(r26)[0]) = (venum*)r18; else hl_dyn_setp(r26->value,52297279/*expr*/,&t$hscript_Expr,r18);
			r13 = hl_types_ArrayObj_push(r10,((vdynamic*)r26));
			goto label$25ae9df_2_286;
			label$25ae9df_2_332:
			if( r8 ) goto label$25ae9df_2_335;
			r20 = NULL;
			goto label$25ae9df_2_337;
			label$25ae9df_2_335:
			if( r1 == NULL ) hl_null_access();
			r20 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((venum* (*)(venum*))r1->fun)(r8);
			label$25ae9df_2_337:
			r18 = hl_alloc_enum(&t$hscript_Expr,23);
			((hscript_Expr_ESwitch*)r18)->p0 = r17;
			((hscript_Expr_ESwitch*)r18)->p1 = r10;
			((hscript_Expr_ESwitch*)r18)->p2 = r20;
			r3 = r18;
			goto label$25ae9df_2_402;
		case 24:
			r5 = ((hscript_Expr_EDoWhile*)r0)->p0;
			r8 = ((hscript_Expr_EDoWhile*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r17 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r18 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((venum* (*)(venum*))r1->fun)(r8);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,24);
			((hscript_Expr_EDoWhile*)tmp)->p0 = r17;
			((hscript_Expr_EDoWhile*)tmp)->p1 = r18;
			r17 = tmp; };
			r3 = r17;
			goto label$25ae9df_2_402;
		case 25:
			r6 = ((hscript_Expr_EMeta*)r0)->p0;
			r9 = ((hscript_Expr_EMeta*)r0)->p1;
			r5 = ((hscript_Expr_EMeta*)r0)->p2;
			if( r9 ) goto label$25ae9df_2_354;
			r15 = NULL;
			goto label$25ae9df_2_376;
			label$25ae9df_2_354:
			r12 = &t$hscript_Expr;
			r2 = 0;
			r11 = hl_alloc_array(r12,r2);
			r15 = hl_types_ArrayObj_alloc(r11);
			r2 = 0;
			label$25ae9df_2_359:
			if( r9 == NULL ) hl_null_access();
			r14 = r9->length;
			if( r2 >= r14 ) goto label$25ae9df_2_376;
			r14 = r9->length;
			if( ((unsigned)r2) < ((unsigned)r14) ) goto label$25ae9df_2_367;
			r8 = NULL;
			goto label$25ae9df_2_370;
			label$25ae9df_2_367:
			r11 = r9->array;
			r16 = ((vdynamic**)(r11 + 1))[r2];
			r8 = (venum*)r16;
			label$25ae9df_2_370:
			++r2;
			if( r15 == NULL ) hl_null_access();
			if( r1 == NULL ) hl_null_access();
			r17 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((venum* (*)(venum*))r1->fun)(r8);
			r13 = hl_types_ArrayObj_push(r15,((vdynamic*)r17));
			goto label$25ae9df_2_359;
			label$25ae9df_2_376:
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,25);
			((hscript_Expr_EMeta*)tmp)->p0 = r6;
			((hscript_Expr_EMeta*)tmp)->p1 = r15;
			((hscript_Expr_EMeta*)tmp)->p2 = r8;
			r8 = tmp; };
			r3 = r8;
			goto label$25ae9df_2_402;
		case 26:
			r5 = ((hscript_Expr_ECheckType*)r0)->p0;
			r7 = ((hscript_Expr_ECheckType*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,26);
			((hscript_Expr_ECheckType*)tmp)->p0 = r8;
			((hscript_Expr_ECheckType*)tmp)->p1 = r7;
			r8 = tmp; };
			r3 = r8;
			goto label$25ae9df_2_402;
		case 27:
			r5 = ((hscript_Expr_EForGen*)r0)->p0;
			r8 = ((hscript_Expr_EForGen*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r17 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			r18 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r8) : ((venum* (*)(venum*))r1->fun)(r8);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,27);
			((hscript_Expr_EForGen*)tmp)->p0 = r17;
			((hscript_Expr_EForGen*)tmp)->p1 = r18;
			r17 = tmp; };
			r3 = r17;
			goto label$25ae9df_2_402;
		case 28:
			r5 = ((hscript_Expr_ECast*)r0)->p0;
			r7 = ((hscript_Expr_ECast*)r0)->p1;
			if( r1 == NULL ) hl_null_access();
			r8 = r1->hasValue ? ((venum* (*)(vdynamic*,venum*))r1->fun)((vdynamic*)r1->value,r5) : ((venum* (*)(venum*))r1->fun)(r5);
			{ venum *tmp;
			tmp = hl_alloc_enum(&t$hscript_Expr,28);
			((hscript_Expr_ECast*)tmp)->p0 = r8;
			((hscript_Expr_ECast*)tmp)->p1 = r7;
			r8 = tmp; };
			r3 = r8;
	}
	label$25ae9df_2_402:
	return r3;
}

venum* hscript_Tools_expr(venum* r0) {
	return r0;
}

venum* hscript_Tools_mk(venum* r0,venum* r1) {
	return r0;
}

vdynamic* hscript_Tools_getKeyIterator(venum* r0,vclosure* r1) {
	String r2, r3, r8, r9;
	venum *r4, *r6, *r10, *r11, *r12;
	vdynamic *r13;
	int r5, r7;
	r2 = NULL;
	r3 = NULL;
	r4 = r0;
	if( r0 == NULL ) hl_null_access();
	r5 = HL__ENUM_INDEX__(r0);
	r7 = 6;
	if( r5 != r7 ) goto label$25ae9df_5_34;
	r8 = ((hscript_Expr_EBinop*)r0)->p0;
	r9 = (String)s$in;
	if( r8 != r9 && (!r8 || !r9 || String___compare(r8,(vdynamic*)r9) != 0) ) goto label$25ae9df_5_34;
	r6 = ((hscript_Expr_EBinop*)r0)->p1;
	r10 = ((hscript_Expr_EBinop*)r0)->p2;
	if( r6 == NULL ) hl_null_access();
	r5 = HL__ENUM_INDEX__(r6);
	r7 = 6;
	if( r5 != r7 ) goto label$25ae9df_5_34;
	r8 = ((hscript_Expr_EBinop*)r6)->p0;
	r9 = (String)s$467a1c8;
	if( r8 != r9 && (!r8 || !r9 || String___compare(r8,(vdynamic*)r9) != 0) ) goto label$25ae9df_5_34;
	r11 = ((hscript_Expr_EBinop*)r6)->p1;
	r12 = ((hscript_Expr_EBinop*)r6)->p2;
	if( r11 == NULL ) hl_null_access();
	r5 = HL__ENUM_INDEX__(r11);
	r7 = 1;
	if( r5 != r7 ) goto label$25ae9df_5_34;
	if( r12 == NULL ) hl_null_access();
	r5 = HL__ENUM_INDEX__(r12);
	r7 = 1;
	if( r5 != r7 ) goto label$25ae9df_5_34;
	r8 = ((hscript_Expr_EIdent*)r12)->p0;
	r9 = ((hscript_Expr_EIdent*)r11)->p0;
	r2 = r9;
	r3 = r8;
	r4 = r10;
	label$25ae9df_5_34:
	if( r1 == NULL ) hl_null_access();
	r13 = r1->hasValue ? ((vdynamic* (*)(vdynamic*,String,String,venum*))r1->fun)((vdynamic*)r1->value,r2,r3,r4) : ((vdynamic* (*)(String,String,venum*))r1->fun)(r2,r3,r4);
	return r13;
}

