// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_hscript__Tools
#define INC_hscript__Tools
typedef struct _hscript__$Tools *hscript__$Tools;
typedef struct _hscript__Tools *hscript__Tools;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hscript/Expr.h>


struct _hscript__$Tools {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* iter;
	vclosure* map;
	vclosure* expr;
	vclosure* mk;
	vclosure* getKeyIterator;
};
struct _hscript__Tools {
	hl_type *$type;
};
#endif

