// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_hscript___Interp__Stop
#define INC_hscript___Interp__Stop
typedef struct _hscript___Interp__$Stop *hscript___Interp__$Stop;
#include <hl/Enum.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>


struct _hscript___Interp__$Stop {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___ename__;
	hl_bytes_map* _hx___emap__;
	hl__types__ArrayObj _hx___constructs__;
	varray* _hx___evalues__;
};
#endif

