// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/ds/EnumValueMap.h>
int Type_enumIndex(vdynamic*);
#include <hl/natives.h>
int haxe_ds_EnumValueMap_compareArg(haxe__ds__EnumValueMap,vdynamic*,vdynamic*);
#include <hl/types/ArrayDyn.h>
int hl_types_ArrayDyn_get_length(hl__types__ArrayDyn);
#include <hl/types/ArrayBase.h>
bool Reflect_isEnumValue(vdynamic*);
extern hl__types__$ArrayBase g$_hl_types_ArrayBase;
bool Std_isOfType(vdynamic*,vdynamic*);
extern hl_type t$hl_types_ArrayDyn;
extern hl_type t$_dyn;
void haxe_ds_BalancedTree_new(haxe__ds__BalancedTree);

int haxe_ds_EnumValueMap_compare(haxe__ds__EnumValueMap r0,vdynamic* r1,vdynamic* r2) {
	vdynamic *r4, *r12;
	varray *r7, *r8;
	int r3, r5, r6, r9, r10, r11, r13;
	r3 = Type_enumIndex(r1);
	r5 = Type_enumIndex(r2);
	r3 = r3 - r5;
	r6 = 0;
	if( r3 == r6 ) goto label$276aba4_1_6;
	return r3;
	label$276aba4_1_6:
	r7 = hl_enum_parameters(r1);
	r8 = hl_enum_parameters(r2);
	r5 = r7->size;
	r6 = r8->size;
	r5 = r5 - r6;
	r9 = 0;
	if( r5 == r9 ) goto label$276aba4_1_14;
	return r5;
	label$276aba4_1_14:
	r6 = 0;
	r9 = r7->size;
	label$276aba4_1_16:
	if( r6 >= r9 ) goto label$276aba4_1_27;
	r10 = r6;
	++r6;
	r4 = ((vdynamic**)(r7 + 1))[r10];
	r12 = ((vdynamic**)(r8 + 1))[r10];
	r11 = haxe_ds_EnumValueMap_compareArg(r0,r4,r12);
	r13 = 0;
	if( r11 == r13 ) goto label$276aba4_1_26;
	return r11;
	label$276aba4_1_26:
	goto label$276aba4_1_16;
	label$276aba4_1_27:
	r6 = 0;
	return r6;
}

int haxe_ds_EnumValueMap_compareArgs(haxe__ds__EnumValueMap r0,hl__types__ArrayDyn r1,hl__types__ArrayDyn r2) {
	vdynamic *r6, *r9;
	int r3, r4, r5, r7, r8, r10;
	if( r1 == NULL ) hl_null_access();
	r3 = hl_types_ArrayDyn_get_length(r1);
	if( r2 == NULL ) hl_null_access();
	r4 = hl_types_ArrayDyn_get_length(r2);
	r3 = r3 - r4;
	r5 = 0;
	if( r3 == r5 ) goto label$276aba4_2_8;
	return r3;
	label$276aba4_2_8:
	r4 = 0;
	r5 = hl_types_ArrayDyn_get_length(r1);
	label$276aba4_2_10:
	if( r4 >= r5 ) goto label$276aba4_2_23;
	r7 = r4;
	++r4;
	if( r1 == NULL ) hl_null_access();
	r6 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r1->$type->vobj_proto[0])(r1,r7);
	if( r2 == NULL ) hl_null_access();
	r9 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r2->$type->vobj_proto[0])(r2,r7);
	r8 = haxe_ds_EnumValueMap_compareArg(r0,r6,r9);
	r10 = 0;
	if( r8 == r10 ) goto label$276aba4_2_22;
	return r8;
	label$276aba4_2_22:
	goto label$276aba4_2_10;
	label$276aba4_2_23:
	r4 = 0;
	return r4;
}

int haxe_ds_EnumValueMap_compareArg(haxe__ds__EnumValueMap r0,vdynamic* r1,vdynamic* r2) {
	bool r3;
	hl__types__ArrayDyn r6, r7;
	hl__types__$ArrayBase r5;
	int r4;
	r3 = Reflect_isEnumValue(r1);
	if( !r3 ) goto label$276aba4_3_6;
	r3 = Reflect_isEnumValue(r2);
	if( !r3 ) goto label$276aba4_3_6;
	r4 = haxe_ds_EnumValueMap_compare(r0,r1,r2);
	return r4;
	label$276aba4_3_6:
	r5 = (hl__types__$ArrayBase)g$_hl_types_ArrayBase;
	r3 = Std_isOfType(r1,((vdynamic*)r5));
	if( !r3 ) goto label$276aba4_3_16;
	r5 = (hl__types__$ArrayBase)g$_hl_types_ArrayBase;
	r3 = Std_isOfType(r2,((vdynamic*)r5));
	if( !r3 ) goto label$276aba4_3_16;
	r6 = (hl__types__ArrayDyn)hl_dyn_castp(&r1,&t$_dyn,&t$hl_types_ArrayDyn);
	r7 = (hl__types__ArrayDyn)hl_dyn_castp(&r2,&t$_dyn,&t$hl_types_ArrayDyn);
	r4 = haxe_ds_EnumValueMap_compareArgs(r0,r6,r7);
	return r4;
	label$276aba4_3_16:
	r4 = hl_dyn_compare(r1,r2);
	return r4;
}

void haxe_ds_EnumValueMap_new(haxe__ds__EnumValueMap r0) {
	haxe_ds_BalancedTree_new(((haxe__ds__BalancedTree)r0));
	return;
}

