// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_haxe__ds__EnumValueMap
#define INC_haxe__ds__EnumValueMap
typedef struct _haxe__ds__$EnumValueMap *haxe__ds__$EnumValueMap;
typedef struct _haxe__ds__EnumValueMap *haxe__ds__EnumValueMap;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/ds/BalancedTree.h>
#include <haxe/ds/TreeNode.h>


struct _haxe__ds__$EnumValueMap {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _haxe__ds__EnumValueMap {
	hl_type *$type;
	haxe__ds__TreeNode root;
	vvirtual* f$1;
	vvirtual* f$2;
};
#endif

