// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_haxe__ds__GenericStack
#define INC_haxe__ds__GenericStack
typedef struct _haxe__ds__$GenericStack *haxe__ds__$GenericStack;
typedef struct _haxe__ds__GenericStack *haxe__ds__GenericStack;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/ds/GenericCell.h>


struct _haxe__ds__$GenericStack {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _haxe__ds__GenericStack {
	hl_type *$type;
	haxe__ds__GenericCell head;
};
#endif

