// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_haxe__ds__TreeNode
#define INC_haxe__ds__TreeNode
typedef struct _haxe__ds__$TreeNode *haxe__ds__$TreeNode;
typedef struct _haxe__ds__TreeNode *haxe__ds__TreeNode;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _haxe__ds__$TreeNode {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _haxe__ds__TreeNode {
	hl_type *$type;
	haxe__ds__TreeNode left;
	haxe__ds__TreeNode right;
	vdynamic* key;
	vdynamic* value;
	int _height;
};
#endif

