// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <ui/MainMenu.h>
#include <_std/Eight.h>
extern $Eight g$_Eight;
#include <_std/Object.h>
void Object_setVisible(Object,bool);
#include <_std/Engine.h>
extern hl_type t$fun_7b48b4f;
extern hl_type t$util_Button;
extern String s$New_game_;
extern $Engine g$_Engine;
void util_Button_new(util__Button,String,int*,int*,String);
extern String s$Save_;
extern String s$Load_;
extern String s$Options_;
extern String s$Exit_;

void ui_MainMenu_new__$1() {
	$Eight r1;
	bool r0;
	r0 = false;
	r1 = ($Eight)g$_Eight;
	r1->run = r0;
	return;
}

void ui_MainMenu_setVisible(ui__MainMenu r0,bool r1) {
	util__Button r3;
	r0->isShown = r1;
	r3 = r0->buttonNew;
	if( r3 == NULL ) hl_null_access();
	Object_setVisible(((Object)r3),r1);
	r3 = r0->buttonSave;
	if( r3 == NULL ) hl_null_access();
	Object_setVisible(((Object)r3),r1);
	r3 = r0->buttonLoad;
	if( r3 == NULL ) hl_null_access();
	Object_setVisible(((Object)r3),r1);
	r3 = r0->buttonOptions;
	if( r3 == NULL ) hl_null_access();
	Object_setVisible(((Object)r3),r1);
	r3 = r0->buttonExit;
	if( r3 == NULL ) hl_null_access();
	Object_setVisible(((Object)r3),r1);
	return;
}

void ui_MainMenu_new(ui__MainMenu r0) {
	String r3, r9;
	$Engine r5;
	bool r1;
	vclosure *r19;
	int *r7, *r8;
	util__Button r2;
	int r4, r6, r11, r12, r13, r14, r15, r16, r17, r18;
	static vclosure cl$0 = { &t$fun_7b48b4f, ui_MainMenu_new__$1, 0 };
	r1 = false;
	r0->isShown = r1;
	r2 = (util__Button)hl_alloc_obj(&t$util_Button);
	r3 = (String)s$New_game_;
	r5 = ($Engine)g$_Engine;
	r4 = r5->n;
	r6 = 200;
	r4 = r4 - r6;
	r7 = &r4;
	r6 = 272;
	r8 = &r6;
	r9 = NULL;
	util_Button_new(r2,r3,r7,r8,r9);
	r0->buttonNew = r2;
	r2 = (util__Button)hl_alloc_obj(&t$util_Button);
	r3 = (String)s$Save_;
	r5 = ($Engine)g$_Engine;
	r11 = r5->n;
	r12 = 200;
	r11 = r11 - r12;
	r7 = &r11;
	r12 = 254;
	r8 = &r12;
	r9 = NULL;
	util_Button_new(r2,r3,r7,r8,r9);
	r0->buttonSave = r2;
	r2 = (util__Button)hl_alloc_obj(&t$util_Button);
	r3 = (String)s$Load_;
	r5 = ($Engine)g$_Engine;
	r13 = r5->n;
	r14 = 200;
	r13 = r13 - r14;
	r7 = &r13;
	r14 = 236;
	r8 = &r14;
	r9 = NULL;
	util_Button_new(r2,r3,r7,r8,r9);
	r0->buttonLoad = r2;
	r2 = (util__Button)hl_alloc_obj(&t$util_Button);
	r3 = (String)s$Options_;
	r5 = ($Engine)g$_Engine;
	r15 = r5->n;
	r16 = 200;
	r15 = r15 - r16;
	r7 = &r15;
	r16 = 218;
	r8 = &r16;
	r9 = NULL;
	util_Button_new(r2,r3,r7,r8,r9);
	r0->buttonOptions = r2;
	r2 = (util__Button)hl_alloc_obj(&t$util_Button);
	r3 = (String)s$Exit_;
	r5 = ($Engine)g$_Engine;
	r17 = r5->n;
	r18 = 200;
	r17 = r17 - r18;
	r7 = &r17;
	r18 = 200;
	r8 = &r18;
	r9 = NULL;
	util_Button_new(r2,r3,r7,r8,r9);
	r0->buttonExit = r2;
	r2 = r0->buttonExit;
	if( r2 == NULL ) hl_null_access();
	r19 = &cl$0;
	r2->clicked = r19;
	r1 = false;
	ui_MainMenu_setVisible(r0,r1);
	return;
}

