// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_haxe__io__BytesDataImpl
#define INC_haxe__io__BytesDataImpl
typedef struct _haxe__io__$BytesDataImpl *haxe__io__$BytesDataImpl;
typedef struct _haxe__io__BytesDataImpl *haxe__io__BytesDataImpl;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _haxe__io__$BytesDataImpl {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _haxe__io__BytesDataImpl {
	hl_type *$type;
	vbyte* bytes;
	int length;
};
#endif

