// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_haxe__io__BytesInput
#define INC_haxe__io__BytesInput
typedef struct _haxe__io__$BytesInput *haxe__io__$BytesInput;
typedef struct _haxe__io__BytesInput *haxe__io__BytesInput;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/io/Input.h>


struct _haxe__io__$BytesInput {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _haxe__io__BytesInput {
	hl_type *$type;
	bool bigEndian;
	vbyte* b;
	int pos;
	int len;
	int totlen;
};
#endif

