// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_util__Button
#define INC_util__Button
typedef struct _util__$Button *util__$Button;
typedef struct _util__Button *util__Button;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <objects/GameObject.h>
#include <_std/Object.h>
#include <hl/types/ArrayBytes_Float.h>
#include <util/Texture.h>


struct _util__$Button {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _util__Button {
	hl_type *$type;
	hl__types__ArrayBytes_Float pos;
	double angle;
	double localAngle;
	int sizeX;
	int sizeY;
	int sizeZ;
	int color;
	util__Texture texture;
	bool show;
	bool isUI;
	int zlayer;
	util__Texture outlineTexture;
	util__Texture standartTexture;
	bool selectable;
	bool selected;
	util__Texture ghostTexture;
	String word;
	vclosure* clicked;
};
#endif

