// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_util__FontManager
#define INC_util__FontManager
typedef struct _util__$FontManager *util__$FontManager;
typedef struct _util__FontManager *util__FontManager;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <util/Texture.h>
#include <haxe/ds/StringMap.h>


struct _util__$FontManager {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	util__Texture font;
	String letters;
	haxe__ds__StringMap keyTex;
	int size;
	double sZ;
	vclosure* initialize;
	vclosure* loadLetterTextures;
	vclosure* drawText;
	vclosure* drawKey;
	vclosure* makeTexture;
};
struct _util__FontManager {
	hl_type *$type;
};
#endif

