// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_util__TextureManager
#define INC_util__TextureManager
typedef struct _util__$TextureManager *util__$TextureManager;
typedef struct _util__TextureManager *util__TextureManager;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/ds/StringMap.h>
#include <util/Texture.h>
#include <haxe/io/Bytes.h>
#include <haxe/io/BytesInput.h>
#include <hl/types/ArrayObj.h>


struct _util__$TextureManager {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	haxe__ds__StringMap textures;
	vclosure* loadTexture;
	vclosure* getPng;
	vclosure* readInt32BE;
	vclosure* resize;
	vclosure* resizeBilinear;
	vclosure* resizeBicubic;
	vclosure* resizeLanczos;
	vclosure* blurGaussian;
	vclosure* buildMipmaps;
};
struct _util__TextureManager {
	hl_type *$type;
};
#endif

