// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/format/JsonPrinter.h>
extern hl_type t$haxe_format_JsonPrinter;
void haxe_format_JsonPrinter_new(haxe__format__JsonPrinter,vclosure*,String);
extern String s$;
void haxe_format_JsonPrinter_write(haxe__format__JsonPrinter,vdynamic*,vdynamic*);
String StringBuf_toString(StringBuf);
int String___compare(String,vdynamic*);
extern hl_type t$StringBuf;
void StringBuf_new(StringBuf);
#include <_std/ValueType.h>
#include <hl/types/ArrayObj.h>
#include <_std/String.h>
#include <hl/types/ArrayBase.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/ds/StringMap.h>
#include <_std/Date.h>
venum* Type_typeof(vdynamic*);
extern String s$null;
void StringBuf_add(StringBuf,vdynamic*);
String Std_string(vdynamic*);
extern hl_type t$_dyn;
#include <hl/natives.h>
extern hl_type t$_bool;
extern String s$true;
extern String s$false;
hl__types__ArrayObj Reflect_fields(vdynamic*);
void haxe_format_JsonPrinter_fieldsString(haxe__format__JsonPrinter,vdynamic*,hl__types__ArrayObj);
extern String s$_fun_;
extern $String g$_String;
extern hl_type t$String;
void haxe_format_JsonPrinter_quote(haxe__format__JsonPrinter,String);
extern hl__types__$ArrayBase g$_hl_types_ArrayBase;
extern hl_type t$hl_types_ArrayDyn;
void StringBuf_addChar(StringBuf,int);
int hl_types_ArrayDyn_get_length(hl__types__ArrayDyn);
String StringTools_lpad(String,String,int);
extern hl_type t$_i32;
extern haxe__ds__$StringMap g$_haxe_ds_StringMap;
extern hl_type t$haxe_ds_StringMap;
vvirtual* haxe_ds_StringMap_keys(haxe__ds__StringMap);
extern hl_type t$fun_bf7849e;
extern hl_type t$fun_820f49a;
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
void Reflect_setField(vdynamic*,String,vdynamic*);
extern $Date g$_Date;
extern hl_type t$Date;
String Date_toString(Date);
void haxe_format_JsonPrinter_classString(haxe__format__JsonPrinter,vdynamic*);
int Type_enumIndex(vdynamic*);
extern String s$c0daf36;
hl__Class Type_getClass(vdynamic*);
hl__types__ArrayObj Type_getInstanceFields(hl__Class);
vdynamic* Reflect_field(vdynamic*,String);
extern String s$_b;
extern String s$_t;
extern String s$_n;
extern String s$_f;
extern String s$_r;
extern String s$3bd8640;
extern String s$7f81377;

String haxe_format_JsonPrinter_print(vdynamic* r0,vclosure* r1,String r2) {
	String r4;
	haxe__format__JsonPrinter r3;
	StringBuf r6;
	r3 = (haxe__format__JsonPrinter)hl_alloc_obj(&t$haxe_format_JsonPrinter);
	haxe_format_JsonPrinter_new(r3,r1,r2);
	r4 = (String)s$;
	haxe_format_JsonPrinter_write(r3,((vdynamic*)r4),r0);
	r6 = r3->buf;
	if( r6 == NULL ) hl_null_access();
	r4 = StringBuf_toString(r6);
	return r4;
}

void haxe_format_JsonPrinter_new(haxe__format__JsonPrinter r0,vclosure* r1,String r2) {
	String r4;
	bool r3;
	StringBuf r6;
	int r5;
	r0->replacer = r1;
	r0->indent = r2;
	r4 = NULL;
	if( r2 != r4 && (!r2 || !r4 || String___compare(r2,(vdynamic*)r4) != 0) ) goto label$ec39e6b_2_6;
	r3 = false;
	goto label$ec39e6b_2_7;
	label$ec39e6b_2_6:
	r3 = true;
	label$ec39e6b_2_7:
	r0->pretty = r3;
	r5 = 0;
	r0->nind = r5;
	r6 = (StringBuf)hl_alloc_obj(&t$StringBuf);
	StringBuf_new(r6);
	r0->buf = r6;
	return;
}

void haxe_format_JsonPrinter_write(haxe__format__JsonPrinter r0,vdynamic* r1,vdynamic* r2) {
	hl__BaseType r33;
	vdynobj *r28;
	$String r16;
	String r10, r11, r25;
	hl__Class r15;
	Date r32;
	vvirtual *r29;
	haxe__ds__StringMap r27;
	hl__types__ArrayObj r14;
	venum *r7;
	bool r12;
	haxe__ds__$StringMap r26;
	StringBuf r9;
	hl__types__ArrayDyn r18;
	hl__types__$ArrayBase r17;
	double r13;
	vclosure *r4;
	vdynamic *r5, *r6, *r30;
	$Date r31;
	int r8, r19, r20, r21, r22, r23, r24;
	r4 = r0->replacer;
	if( !r4 ) goto label$ec39e6b_3_6;
	r4 = r0->replacer;
	if( r4 == NULL ) hl_null_access();
	r5 = r4->hasValue ? ((vdynamic* (*)(vdynamic*,vdynamic*,vdynamic*))r4->fun)((vdynamic*)r4->value,r1,r2) : ((vdynamic* (*)(vdynamic*,vdynamic*))r4->fun)(r1,r2);
	r2 = r5;
	label$ec39e6b_3_6:
	r7 = Type_typeof(r2);
	if( r7 == NULL ) hl_null_access();
	r8 = HL__ENUM_INDEX__(r7);
	switch(r8) {
		default:
			goto label$ec39e6b_3_173;
		case 0:
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			r10 = (String)s$null;
			StringBuf_add(r9,((vdynamic*)r10));
			goto label$ec39e6b_3_173;
		case 1:
			r10 = Std_string(r2);
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			StringBuf_add(r9,((vdynamic*)r10));
			goto label$ec39e6b_3_173;
		case 2:
			r13 = (double)hl_dyn_castd(&r2,&t$_dyn);
			r12 = hl_math_isfinite(r13);
			if( !r12 ) goto label$ec39e6b_3_26;
			r10 = Std_string(r2);
			goto label$ec39e6b_3_27;
			label$ec39e6b_3_26:
			r10 = (String)s$null;
			label$ec39e6b_3_27:
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			StringBuf_add(r9,((vdynamic*)r10));
			goto label$ec39e6b_3_173;
		case 3:
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			r12 = (bool)hl_dyn_casti(&r2,&t$_dyn,&t$_bool);
			if( !r12 ) goto label$ec39e6b_3_37;
			r10 = (String)s$true;
			goto label$ec39e6b_3_38;
			label$ec39e6b_3_37:
			r10 = (String)s$false;
			label$ec39e6b_3_38:
			StringBuf_add(r9,((vdynamic*)r10));
			goto label$ec39e6b_3_173;
		case 4:
			r14 = Reflect_fields(r2);
			haxe_format_JsonPrinter_fieldsString(r0,r2,r14);
			goto label$ec39e6b_3_173;
		case 5:
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			r10 = (String)s$_fun_;
			StringBuf_add(r9,((vdynamic*)r10));
			goto label$ec39e6b_3_173;
		case 6:
			r15 = ((ValueType_TClass*)r7)->p0;
			r16 = ($String)g$_String;
			if( r15 != ((hl__Class)r16) ) goto label$ec39e6b_3_54;
			r10 = (String)hl_dyn_castp(&r2,&t$_dyn,&t$String);
			haxe_format_JsonPrinter_quote(r0,r10);
			goto label$ec39e6b_3_160;
			label$ec39e6b_3_54:
			r17 = (hl__types__$ArrayBase)g$_hl_types_ArrayBase;
			if( r15 != ((hl__Class)r17) ) goto label$ec39e6b_3_133;
			r18 = (hl__types__ArrayDyn)hl_dyn_castp(&r2,&t$_dyn,&t$hl_types_ArrayDyn);
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			r8 = 91;
			StringBuf_addChar(r9,r8);
			if( r18 == NULL ) hl_null_access();
			r8 = hl_types_ArrayDyn_get_length(r18);
			r20 = 1;
			r19 = r8 - r20;
			r20 = 0;
			r21 = r8;
			label$ec39e6b_3_67:
			if( r20 >= r21 ) goto label$ec39e6b_3_128;
			r22 = r20;
			++r20;
			r24 = 0;
			if( r24 >= r22 ) goto label$ec39e6b_3_78;
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			r23 = 44;
			StringBuf_addChar(r9,r23);
			goto label$ec39e6b_3_81;
			label$ec39e6b_3_78:
			r23 = r0->nind;
			++r23;
			r0->nind = r23;
			label$ec39e6b_3_81:
			r12 = r0->pretty;
			if( !r12 ) goto label$ec39e6b_3_87;
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			r23 = 10;
			StringBuf_addChar(r9,r23);
			label$ec39e6b_3_87:
			r12 = r0->pretty;
			if( !r12 ) goto label$ec39e6b_3_100;
			r10 = (String)s$;
			r11 = r0->indent;
			r23 = r0->nind;
			r25 = r0->indent;
			if( r25 == NULL ) hl_null_access();
			r24 = r25->length;
			r23 = r23 * r24;
			r10 = StringTools_lpad(r10,r11,r23);
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			StringBuf_add(r9,((vdynamic*)r10));
			label$ec39e6b_3_100:
			r5 = hl_alloc_dynamic(&t$_i32);
			r5->v.i = r22;
			if( r18 == NULL ) hl_null_access();
			r6 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r18->$type->vobj_proto[0])(r18,r22);
			haxe_format_JsonPrinter_write(r0,r5,r6);
			if( r22 != r19 ) goto label$ec39e6b_3_127;
			r23 = r0->nind;
			--r23;
			r0->nind = r23;
			r12 = r0->pretty;
			if( !r12 ) goto label$ec39e6b_3_114;
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			r23 = 10;
			StringBuf_addChar(r9,r23);
			label$ec39e6b_3_114:
			r12 = r0->pretty;
			if( !r12 ) goto label$ec39e6b_3_127;
			r10 = (String)s$;
			r11 = r0->indent;
			r23 = r0->nind;
			r25 = r0->indent;
			if( r25 == NULL ) hl_null_access();
			r24 = r25->length;
			r23 = r23 * r24;
			r10 = StringTools_lpad(r10,r11,r23);
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			StringBuf_add(r9,((vdynamic*)r10));
			label$ec39e6b_3_127:
			goto label$ec39e6b_3_67;
			label$ec39e6b_3_128:
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			r20 = 93;
			StringBuf_addChar(r9,r20);
			goto label$ec39e6b_3_160;
			label$ec39e6b_3_133:
			r26 = (haxe__ds__$StringMap)g$_haxe_ds_StringMap;
			if( r15 != ((hl__Class)r26) ) goto label$ec39e6b_3_152;
			r27 = (haxe__ds__StringMap)hl_dyn_castp(&r2,&t$_dyn,&t$haxe_ds_StringMap);
			r28 = hl_alloc_dynobj();
			r5 = ((vdynamic*)r28);
			if( r27 == NULL ) hl_null_access();
			r29 = haxe_ds_StringMap_keys(r27);
			label$ec39e6b_3_140:
			if( r29 == NULL ) hl_null_access();
			if( hl_vfields(r29)[0] ) r12 = ((bool (*)(vdynamic*))hl_vfields(r29)[0])(r29->value); else {
				vdynamic ret;
				hl_dyn_call_obj(r29->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
				r12 = (bool)ret.v.i;
			}
			if( !r12 ) goto label$ec39e6b_3_149;
			if( hl_vfields(r29)[1] ) r10 = ((String (*)(vdynamic*))hl_vfields(r29)[1])(r29->value); else {
				r10 = (String)hl_dyn_call_obj(r29->value,&t$fun_820f49a,151160317/*next*/,NULL,NULL);
			}
			if( r27 == NULL ) hl_null_access();
			r30 = haxe_ds_StringMap_get(r27,r10);
			Reflect_setField(r5,r10,r30);
			goto label$ec39e6b_3_140;
			label$ec39e6b_3_149:
			r14 = Reflect_fields(r5);
			haxe_format_JsonPrinter_fieldsString(r0,r5,r14);
			goto label$ec39e6b_3_160;
			label$ec39e6b_3_152:
			r31 = ($Date)g$_Date;
			if( r15 != ((hl__Class)r31) ) goto label$ec39e6b_3_159;
			r32 = (Date)hl_dyn_castp(&r2,&t$_dyn,&t$Date);
			if( r32 == NULL ) hl_null_access();
			r10 = Date_toString(r32);
			haxe_format_JsonPrinter_quote(r0,r10);
			goto label$ec39e6b_3_160;
			label$ec39e6b_3_159:
			haxe_format_JsonPrinter_classString(r0,r2);
			label$ec39e6b_3_160:
			goto label$ec39e6b_3_173;
		case 7:
			r33 = ((ValueType_TEnum*)r7)->p0;
			r8 = Type_enumIndex(r2);
			r5 = hl_alloc_dynamic(&t$_i32);
			r5->v.i = r8;
			r10 = Std_string(r5);
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			StringBuf_add(r9,((vdynamic*)r10));
			goto label$ec39e6b_3_173;
		case 8:
			r9 = r0->buf;
			if( r9 == NULL ) hl_null_access();
			r10 = (String)s$c0daf36;
			StringBuf_add(r9,((vdynamic*)r10));
	}
	label$ec39e6b_3_173:
	return;
}

void haxe_format_JsonPrinter_classString(haxe__format__JsonPrinter r0,vdynamic* r1) {
	hl__Class r4;
	hl__types__ArrayObj r3;
	r4 = Type_getClass(r1);
	r3 = Type_getInstanceFields(r4);
	haxe_format_JsonPrinter_fieldsString(r0,r1,r3);
	return;
}

void haxe_format_JsonPrinter_fieldsString(haxe__format__JsonPrinter r0,vdynamic* r1,hl__types__ArrayObj r2) {
	String r12, r15, r18, r19;
	hl_type *r16;
	bool r6, r17;
	StringBuf r4;
	vdynamic *r13;
	varray *r14;
	int r5, r7, r8, r9, r10, r11;
	r4 = r0->buf;
	if( r4 == NULL ) hl_null_access();
	r5 = 123;
	StringBuf_addChar(r4,r5);
	if( r2 == NULL ) hl_null_access();
	r5 = r2->length;
	r6 = true;
	r7 = 0;
	r8 = r5;
	label$ec39e6b_5_9:
	if( r7 >= r8 ) goto label$ec39e6b_5_70;
	r9 = r7;
	++r7;
	if( r2 == NULL ) hl_null_access();
	r11 = r2->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$ec39e6b_5_18;
	r12 = NULL;
	goto label$ec39e6b_5_21;
	label$ec39e6b_5_18:
	r14 = r2->array;
	r13 = ((vdynamic**)(r14 + 1))[r9];
	r12 = (String)r13;
	label$ec39e6b_5_21:
	r13 = Reflect_field(r1,r12);
	r16 = r13 ? ((vdynamic*)r13)->t : &hlt_void;
	r10 = r16->kind;
	r11 = 10;
	if( r10 != r11 ) goto label$ec39e6b_5_27;
	goto label$ec39e6b_5_9;
	label$ec39e6b_5_27:
	if( !r6 ) goto label$ec39e6b_5_34;
	r10 = r0->nind;
	++r10;
	r0->nind = r10;
	r17 = false;
	r6 = r17;
	goto label$ec39e6b_5_38;
	label$ec39e6b_5_34:
	r4 = r0->buf;
	if( r4 == NULL ) hl_null_access();
	r10 = 44;
	StringBuf_addChar(r4,r10);
	label$ec39e6b_5_38:
	r17 = r0->pretty;
	if( !r17 ) goto label$ec39e6b_5_44;
	r4 = r0->buf;
	if( r4 == NULL ) hl_null_access();
	r10 = 10;
	StringBuf_addChar(r4,r10);
	label$ec39e6b_5_44:
	r17 = r0->pretty;
	if( !r17 ) goto label$ec39e6b_5_57;
	r15 = (String)s$;
	r18 = r0->indent;
	r10 = r0->nind;
	r19 = r0->indent;
	if( r19 == NULL ) hl_null_access();
	r11 = r19->length;
	r10 = r10 * r11;
	r15 = StringTools_lpad(r15,r18,r10);
	r4 = r0->buf;
	if( r4 == NULL ) hl_null_access();
	StringBuf_add(r4,((vdynamic*)r15));
	label$ec39e6b_5_57:
	haxe_format_JsonPrinter_quote(r0,r12);
	r4 = r0->buf;
	if( r4 == NULL ) hl_null_access();
	r10 = 58;
	StringBuf_addChar(r4,r10);
	r17 = r0->pretty;
	if( !r17 ) goto label$ec39e6b_5_68;
	r4 = r0->buf;
	if( r4 == NULL ) hl_null_access();
	r10 = 32;
	StringBuf_addChar(r4,r10);
	label$ec39e6b_5_68:
	haxe_format_JsonPrinter_write(r0,((vdynamic*)r12),r13);
	goto label$ec39e6b_5_9;
	label$ec39e6b_5_70:
	if( r6 ) goto label$ec39e6b_5_93;
	r7 = r0->nind;
	--r7;
	r0->nind = r7;
	r17 = r0->pretty;
	if( !r17 ) goto label$ec39e6b_5_80;
	r4 = r0->buf;
	if( r4 == NULL ) hl_null_access();
	r7 = 10;
	StringBuf_addChar(r4,r7);
	label$ec39e6b_5_80:
	r17 = r0->pretty;
	if( !r17 ) goto label$ec39e6b_5_93;
	r12 = (String)s$;
	r15 = r0->indent;
	r7 = r0->nind;
	r18 = r0->indent;
	if( r18 == NULL ) hl_null_access();
	r8 = r18->length;
	r7 = r7 * r8;
	r12 = StringTools_lpad(r12,r15,r7);
	r4 = r0->buf;
	if( r4 == NULL ) hl_null_access();
	StringBuf_add(r4,((vdynamic*)r12));
	label$ec39e6b_5_93:
	r4 = r0->buf;
	if( r4 == NULL ) hl_null_access();
	r7 = 125;
	StringBuf_addChar(r4,r7);
	return;
}

void haxe_format_JsonPrinter_quote(haxe__format__JsonPrinter r0,String r1) {
	String r6;
	StringBuf r3;
	vbyte *r10;
	int r4, r5, r7, r8, r9, r11, r12, r13;
	r3 = r0->buf;
	if( r3 == NULL ) hl_null_access();
	r4 = 34;
	StringBuf_addChar(r3,r4);
	r4 = 0;
	if( r1 == NULL ) hl_null_access();
	r5 = r1->length;
	r7 = -1;
	label$ec39e6b_6_8:
	if( r4 >= r5 ) goto label$ec39e6b_6_90;
	r8 = r4;
	++r4;
	if( r1 == NULL ) hl_null_access();
	r10 = r1->bytes;
	r11 = 1;
	r9 = r8 << r11;
	r9 = *(unsigned short*)(r10 + r9);
	switch(r9) {
		default:
		case 0:
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
		case 7:
		case 11:
		case 14:
		case 15:
		case 16:
		case 17:
		case 18:
		case 19:
		case 20:
		case 21:
		case 22:
		case 23:
		case 24:
		case 25:
		case 26:
		case 27:
		case 28:
		case 29:
		case 30:
		case 31:
		case 32:
		case 33:
		case 35:
		case 36:
		case 37:
		case 38:
		case 39:
		case 40:
		case 41:
		case 42:
		case 43:
		case 44:
		case 45:
		case 46:
		case 47:
		case 48:
		case 49:
		case 50:
		case 51:
		case 52:
		case 53:
		case 54:
		case 55:
		case 56:
		case 57:
		case 58:
		case 59:
		case 60:
		case 61:
		case 62:
		case 63:
		case 64:
		case 65:
		case 66:
		case 67:
		case 68:
		case 69:
		case 70:
		case 71:
		case 72:
		case 73:
		case 74:
		case 75:
		case 76:
		case 77:
		case 78:
		case 79:
		case 80:
		case 81:
		case 82:
		case 83:
		case 84:
		case 85:
		case 86:
		case 87:
		case 88:
		case 89:
		case 90:
		case 91:
			r12 = 0;
			if( r7 < r12 ) goto label$ec39e6b_6_45;
			r12 = 55296;
			if( r9 < r12 ) goto label$ec39e6b_6_39;
			r12 = 57343;
			if( r12 < r9 ) goto label$ec39e6b_6_39;
			r3 = r0->buf;
			if( r3 == NULL ) hl_null_access();
			r12 = 55296;
			r11 = r7 - r12;
			r12 = 10;
			r11 = r11 << r12;
			r13 = 56320;
			r12 = r9 - r13;
			r11 = r11 | r12;
			r12 = 65536;
			r11 = r11 + r12;
			StringBuf_addChar(r3,r11);
			r11 = -1;
			r7 = r11;
			goto label$ec39e6b_6_44;
			label$ec39e6b_6_39:
			r3 = r0->buf;
			if( r3 == NULL ) hl_null_access();
			r11 = 9633;
			StringBuf_addChar(r3,r11);
			r7 = r9;
			label$ec39e6b_6_44:
			goto label$ec39e6b_6_54;
			label$ec39e6b_6_45:
			r12 = 55296;
			if( r9 < r12 ) goto label$ec39e6b_6_51;
			r12 = 57343;
			if( r12 < r9 ) goto label$ec39e6b_6_51;
			r7 = r9;
			goto label$ec39e6b_6_54;
			label$ec39e6b_6_51:
			r3 = r0->buf;
			if( r3 == NULL ) hl_null_access();
			StringBuf_addChar(r3,r9);
			label$ec39e6b_6_54:
			goto label$ec39e6b_6_89;
		case 8:
			r3 = r0->buf;
			if( r3 == NULL ) hl_null_access();
			r6 = (String)s$_b;
			StringBuf_add(r3,((vdynamic*)r6));
			goto label$ec39e6b_6_89;
		case 9:
			r3 = r0->buf;
			if( r3 == NULL ) hl_null_access();
			r6 = (String)s$_t;
			StringBuf_add(r3,((vdynamic*)r6));
			goto label$ec39e6b_6_89;
		case 10:
			r3 = r0->buf;
			if( r3 == NULL ) hl_null_access();
			r6 = (String)s$_n;
			StringBuf_add(r3,((vdynamic*)r6));
			goto label$ec39e6b_6_89;
		case 12:
			r3 = r0->buf;
			if( r3 == NULL ) hl_null_access();
			r6 = (String)s$_f;
			StringBuf_add(r3,((vdynamic*)r6));
			goto label$ec39e6b_6_89;
		case 13:
			r3 = r0->buf;
			if( r3 == NULL ) hl_null_access();
			r6 = (String)s$_r;
			StringBuf_add(r3,((vdynamic*)r6));
			goto label$ec39e6b_6_89;
		case 34:
			r3 = r0->buf;
			if( r3 == NULL ) hl_null_access();
			r6 = (String)s$3bd8640;
			StringBuf_add(r3,((vdynamic*)r6));
			goto label$ec39e6b_6_89;
		case 92:
			r3 = r0->buf;
			if( r3 == NULL ) hl_null_access();
			r6 = (String)s$7f81377;
			StringBuf_add(r3,((vdynamic*)r6));
	}
	label$ec39e6b_6_89:
	goto label$ec39e6b_6_8;
	label$ec39e6b_6_90:
	r9 = 0;
	if( r7 < r9 ) goto label$ec39e6b_6_96;
	r3 = r0->buf;
	if( r3 == NULL ) hl_null_access();
	r8 = 9633;
	StringBuf_addChar(r3,r8);
	label$ec39e6b_6_96:
	r3 = r0->buf;
	if( r3 == NULL ) hl_null_access();
	r8 = 34;
	StringBuf_addChar(r3,r8);
	return;
}

