// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_haxe__io___Float32Array__Float32Array_Impl_
#define INC_haxe__io___Float32Array__Float32Array_Impl_
typedef struct _haxe__io___Float32Array__$Float32Array_Impl_ *haxe__io___Float32Array__$Float32Array_Impl_;
typedef struct _haxe__io___Float32Array__Float32Array_Impl_ *haxe__io___Float32Array__Float32Array_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayBytes_Float.h>
#include <haxe/io/ArrayBufferViewImpl.h>


struct _haxe__io___Float32Array__$Float32Array_Impl_ {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* fromArray;
};
struct _haxe__io___Float32Array__Float32Array_Impl_ {
	hl_type *$type;
};
#endif

