// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/Exception.h>
varray* haxe_NativeStackTrace_exceptionStack(void);
#include <hl/natives.h>
extern hl_type t$hl_symbol;
String haxe_Exception_get_message(haxe__Exception);

void haxe_Exception_new(haxe__Exception r0,String r1,haxe__Exception r2,vdynamic* r3) {
	hl_type *r8;
	int r6, r7, r10, r12;
	varray *r5, *r9, *r11;
	r0->_hx___exceptionMessage = r1;
	r0->_hx___previousException = r2;
	if( !r3 ) goto label$2937a61_1_7;
	r5 = haxe_NativeStackTrace_exceptionStack();
	r0->_hx___nativeStack = r5;
	r0->_hx___nativeException = r3;
	goto label$2937a61_1_28;
	label$2937a61_1_7:
	r5 = NULL;
	r6 = hl_call_stack_raw(r5);
	r8 = &t$hl_symbol;
	r5 = hl_alloc_array(r8,r6);
	r7 = hl_call_stack_raw(r5);
	r7 = r5->size;
	r10 = 0;
	if( r7 != r10 ) goto label$2937a61_1_17;
	r9 = r5;
	goto label$2937a61_1_26;
	label$2937a61_1_17:
	r7 = r5->size;
	r10 = 1;
	r7 = r7 - r10;
	r8 = &t$hl_symbol;
	r11 = hl_alloc_array(r8,r7);
	r10 = 0;
	r12 = 1;
	hl_array_blit(r11,r10,r5,r12,r7);
	r9 = r11;
	label$2937a61_1_26:
	r0->_hx___nativeStack = r9;
	r0->_hx___nativeException = ((vdynamic*)r0);
	label$2937a61_1_28:
	return;
}

vbyte* haxe_Exception___string(haxe__Exception r0) {
	String r2;
	vbyte *r1;
	r2 = ((String (*)(haxe__Exception))r0->$type->vobj_proto[0])(r0);
	if( r2 == NULL ) hl_null_access();
	r1 = r2->bytes;
	return r1;
}

String haxe_Exception_toString(haxe__Exception r0) {
	String r1;
	r1 = haxe_Exception_get_message(r0);
	return r1;
}

String haxe_Exception_get_message(haxe__Exception r0) {
	String r1;
	r1 = r0->_hx___exceptionMessage;
	return r1;
}

