// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/NativeStackTrace.h>
#include <hl/natives.h>
extern hl_type t$hl_symbol;

void haxe_NativeStackTrace_saveStack(vdynamic* r0) {
	return;
}

varray* haxe_NativeStackTrace_exceptionStack() {
	hl_type *r3;
	varray *r1;
	int r0, r2;
	r1 = NULL;
	r0 = hl_exception_stack_raw(r1);
	r3 = &t$hl_symbol;
	r1 = hl_alloc_array(r3,r0);
	r2 = hl_exception_stack_raw(r1);
	return r1;
}

