// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_haxe__ValueException
#define INC_haxe__ValueException
typedef struct _haxe__$ValueException *haxe__$ValueException;
typedef struct _haxe__ValueException *haxe__ValueException;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/Exception.h>


struct _haxe__$ValueException {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _haxe__ValueException {
	hl_type *$type;
	String _hx___exceptionMessage;
	varray* _hx___nativeStack;
	vdynamic* _hx___nativeException;
	haxe__Exception _hx___previousException;
	vdynamic* value;
};
#endif

