// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <util/_Math/Vec3_Impl_.h>
void hl_types_ArrayBytes_Float___expand(hl__types__ArrayBytes_Float,int);
#include <hl/natives.h>
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
#include <_std/Math.h>
extern $Math g$_Math;

double util__Math_Vec3_Impl__get(hl__types__ArrayBytes_Float r0,int r1) {
	double r3;
	vbyte *r4;
	int r2;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->length;
	if( ((unsigned)r1) < ((unsigned)r2) ) goto label$85c675a_1_5;
	r3 = 0.;
	goto label$85c675a_1_9;
	label$85c675a_1_5:
	r4 = r0->bytes;
	r2 = 3;
	r2 = r1 << r2;
	r3 = *(double*)(r4 + r2);
	label$85c675a_1_9:
	return r3;
}

double util__Math_Vec3_Impl__set(hl__types__ArrayBytes_Float r0,int r1,double r2) {
	vbyte *r5;
	int r3;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->length;
	if( ((unsigned)r1) < ((unsigned)r3) ) goto label$85c675a_2_4;
	hl_types_ArrayBytes_Float___expand(r0,r1);
	label$85c675a_2_4:
	r5 = r0->bytes;
	r3 = 3;
	r3 = r1 << r3;
	*(double*)(r5 + r3) = r2;
	return r2;
}

hl__types__ArrayBytes_Float util__Math_Vec3_Impl__fromArray(hl__types__ArrayBytes_Float r0) {
	return r0;
}

hl__types__ArrayBytes_Float util__Math_Vec3_Impl__toArray(hl__types__ArrayBytes_Float r0) {
	return r0;
}

hl__types__ArrayBytes_Float util__Math_Vec3_Impl___new(double r0,double r1,double r2) {
	hl__types__ArrayBytes_Float r3;
	int r5, r6;
	vbyte *r4;
	r5 = 24;
	r4 = hl_alloc_bytes(r5);
	r5 = 0;
	r6 = 3;
	r6 = r5 << r6;
	*(double*)(r4 + r6) = r0;
	++r5;
	r6 = 3;
	r6 = r5 << r6;
	*(double*)(r4 + r6) = r1;
	++r5;
	r6 = 3;
	r6 = r5 << r6;
	*(double*)(r4 + r6) = r2;
	++r5;
	r5 = 3;
	r3 = hl_types_ArrayBase_allocF64(r4,r5);
	return r3;
}

double util__Math_Vec3_Impl__get_x(hl__types__ArrayBytes_Float r0) {
	double r3;
	vbyte *r4;
	int r1, r2;
	if( r0 == NULL ) hl_null_access();
	r1 = 0;
	r2 = r0->length;
	if( ((unsigned)r1) < ((unsigned)r2) ) goto label$85c675a_6_6;
	r3 = 0.;
	goto label$85c675a_6_10;
	label$85c675a_6_6:
	r4 = r0->bytes;
	r2 = 3;
	r2 = r1 << r2;
	r3 = *(double*)(r4 + r2);
	label$85c675a_6_10:
	return r3;
}

double util__Math_Vec3_Impl__set_x(hl__types__ArrayBytes_Float r0,double r1) {
	vbyte *r5;
	int r2, r3;
	if( r0 == NULL ) hl_null_access();
	r2 = 0;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_7_5;
	hl_types_ArrayBytes_Float___expand(r0,r2);
	label$85c675a_7_5:
	r5 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	*(double*)(r5 + r3) = r1;
	return r1;
}

double util__Math_Vec3_Impl__get_y(hl__types__ArrayBytes_Float r0) {
	double r3;
	vbyte *r4;
	int r1, r2;
	if( r0 == NULL ) hl_null_access();
	r1 = 1;
	r2 = r0->length;
	if( ((unsigned)r1) < ((unsigned)r2) ) goto label$85c675a_8_6;
	r3 = 0.;
	goto label$85c675a_8_10;
	label$85c675a_8_6:
	r4 = r0->bytes;
	r2 = 3;
	r2 = r1 << r2;
	r3 = *(double*)(r4 + r2);
	label$85c675a_8_10:
	return r3;
}

double util__Math_Vec3_Impl__set_y(hl__types__ArrayBytes_Float r0,double r1) {
	vbyte *r5;
	int r2, r3;
	if( r0 == NULL ) hl_null_access();
	r2 = 1;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_9_5;
	hl_types_ArrayBytes_Float___expand(r0,r2);
	label$85c675a_9_5:
	r5 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	*(double*)(r5 + r3) = r1;
	return r1;
}

double util__Math_Vec3_Impl__get_z(hl__types__ArrayBytes_Float r0) {
	double r3;
	vbyte *r4;
	int r1, r2;
	if( r0 == NULL ) hl_null_access();
	r1 = 2;
	r2 = r0->length;
	if( ((unsigned)r1) < ((unsigned)r2) ) goto label$85c675a_10_6;
	r3 = 0.;
	goto label$85c675a_10_10;
	label$85c675a_10_6:
	r4 = r0->bytes;
	r2 = 3;
	r2 = r1 << r2;
	r3 = *(double*)(r4 + r2);
	label$85c675a_10_10:
	return r3;
}

double util__Math_Vec3_Impl__set_z(hl__types__ArrayBytes_Float r0,double r1) {
	vbyte *r5;
	int r2, r3;
	if( r0 == NULL ) hl_null_access();
	r2 = 2;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_11_5;
	hl_types_ArrayBytes_Float___expand(r0,r2);
	label$85c675a_11_5:
	r5 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	*(double*)(r5 + r3) = r1;
	return r1;
}

hl__types__ArrayBytes_Float util__Math_Vec3_Impl__add(hl__types__ArrayBytes_Float r0,hl__types__ArrayBytes_Float r1) {
	hl__types__ArrayBytes_Float r2;
	double r5, r9;
	int r4, r6, r7;
	vbyte *r3, *r8;
	r4 = 24;
	r3 = hl_alloc_bytes(r4);
	r4 = 0;
	if( r0 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_12_9;
	r5 = 0.;
	goto label$85c675a_12_13;
	label$85c675a_12_9:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_12_13:
	if( r1 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_12_19;
	r9 = 0.;
	goto label$85c675a_12_23;
	label$85c675a_12_19:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_12_23:
	r5 = r5 + r9;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r6 = 1;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_12_33;
	r5 = 0.;
	goto label$85c675a_12_37;
	label$85c675a_12_33:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_12_37:
	r6 = 1;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_12_42;
	r9 = 0.;
	goto label$85c675a_12_46;
	label$85c675a_12_42:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_12_46:
	r5 = r5 + r9;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r6 = 2;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_12_56;
	r5 = 0.;
	goto label$85c675a_12_60;
	label$85c675a_12_56:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_12_60:
	r6 = 2;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_12_65;
	r9 = 0.;
	goto label$85c675a_12_69;
	label$85c675a_12_65:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_12_69:
	r5 = r5 + r9;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r4 = 3;
	r2 = hl_types_ArrayBase_allocF64(r3,r4);
	return r2;
}

hl__types__ArrayBytes_Float util__Math_Vec3_Impl__sub(hl__types__ArrayBytes_Float r0,hl__types__ArrayBytes_Float r1) {
	hl__types__ArrayBytes_Float r2;
	double r5, r9;
	int r4, r6, r7;
	vbyte *r3, *r8;
	r4 = 24;
	r3 = hl_alloc_bytes(r4);
	r4 = 0;
	if( r0 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_13_9;
	r5 = 0.;
	goto label$85c675a_13_13;
	label$85c675a_13_9:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_13_13:
	if( r1 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_13_19;
	r9 = 0.;
	goto label$85c675a_13_23;
	label$85c675a_13_19:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_13_23:
	r5 = r5 - r9;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r6 = 1;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_13_33;
	r5 = 0.;
	goto label$85c675a_13_37;
	label$85c675a_13_33:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_13_37:
	r6 = 1;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_13_42;
	r9 = 0.;
	goto label$85c675a_13_46;
	label$85c675a_13_42:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_13_46:
	r5 = r5 - r9;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r6 = 2;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_13_56;
	r5 = 0.;
	goto label$85c675a_13_60;
	label$85c675a_13_56:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_13_60:
	r6 = 2;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_13_65;
	r9 = 0.;
	goto label$85c675a_13_69;
	label$85c675a_13_65:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_13_69:
	r5 = r5 - r9;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r4 = 3;
	r2 = hl_types_ArrayBase_allocF64(r3,r4);
	return r2;
}

double util__Math_Vec3_Impl__dot(hl__types__ArrayBytes_Float r0,hl__types__ArrayBytes_Float r1) {
	double r2, r6, r7;
	vbyte *r5;
	int r3, r4;
	if( r0 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r0->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$85c675a_14_6;
	r2 = 0.;
	goto label$85c675a_14_10;
	label$85c675a_14_6:
	r5 = r0->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r2 = *(double*)(r5 + r4);
	label$85c675a_14_10:
	if( r1 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r1->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$85c675a_14_16;
	r6 = 0.;
	goto label$85c675a_14_20;
	label$85c675a_14_16:
	r5 = r1->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r6 = *(double*)(r5 + r4);
	label$85c675a_14_20:
	r2 = r2 * r6;
	r3 = 1;
	r4 = r0->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$85c675a_14_26;
	r6 = 0.;
	goto label$85c675a_14_30;
	label$85c675a_14_26:
	r5 = r0->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r6 = *(double*)(r5 + r4);
	label$85c675a_14_30:
	r3 = 1;
	r4 = r1->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$85c675a_14_35;
	r7 = 0.;
	goto label$85c675a_14_39;
	label$85c675a_14_35:
	r5 = r1->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r7 = *(double*)(r5 + r4);
	label$85c675a_14_39:
	r6 = r6 * r7;
	r2 = r2 + r6;
	r3 = 2;
	r4 = r0->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$85c675a_14_46;
	r6 = 0.;
	goto label$85c675a_14_50;
	label$85c675a_14_46:
	r5 = r0->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r6 = *(double*)(r5 + r4);
	label$85c675a_14_50:
	r3 = 2;
	r4 = r1->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$85c675a_14_55;
	r7 = 0.;
	goto label$85c675a_14_59;
	label$85c675a_14_55:
	r5 = r1->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r7 = *(double*)(r5 + r4);
	label$85c675a_14_59:
	r6 = r6 * r7;
	r2 = r2 + r6;
	return r2;
}

hl__types__ArrayBytes_Float util__Math_Vec3_Impl__cross(hl__types__ArrayBytes_Float r0,hl__types__ArrayBytes_Float r1) {
	hl__types__ArrayBytes_Float r2;
	double r5, r9, r10;
	int r4, r6, r7;
	vbyte *r3, *r8;
	r4 = 24;
	r3 = hl_alloc_bytes(r4);
	r4 = 0;
	if( r0 == NULL ) hl_null_access();
	r6 = 1;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_9;
	r5 = 0.;
	goto label$85c675a_15_13;
	label$85c675a_15_9:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_15_13:
	if( r1 == NULL ) hl_null_access();
	r6 = 2;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_19;
	r9 = 0.;
	goto label$85c675a_15_23;
	label$85c675a_15_19:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_15_23:
	r5 = r5 * r9;
	r6 = 2;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_29;
	r9 = 0.;
	goto label$85c675a_15_33;
	label$85c675a_15_29:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_15_33:
	r6 = 1;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_38;
	r10 = 0.;
	goto label$85c675a_15_42;
	label$85c675a_15_38:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r10 = *(double*)(r8 + r7);
	label$85c675a_15_42:
	r9 = r9 * r10;
	r5 = r5 - r9;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r6 = 2;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_53;
	r5 = 0.;
	goto label$85c675a_15_57;
	label$85c675a_15_53:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_15_57:
	r6 = 0;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_62;
	r9 = 0.;
	goto label$85c675a_15_66;
	label$85c675a_15_62:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_15_66:
	r5 = r5 * r9;
	r6 = 0;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_72;
	r9 = 0.;
	goto label$85c675a_15_76;
	label$85c675a_15_72:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_15_76:
	r6 = 2;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_81;
	r10 = 0.;
	goto label$85c675a_15_85;
	label$85c675a_15_81:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r10 = *(double*)(r8 + r7);
	label$85c675a_15_85:
	r9 = r9 * r10;
	r5 = r5 - r9;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r6 = 0;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_96;
	r5 = 0.;
	goto label$85c675a_15_100;
	label$85c675a_15_96:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_15_100:
	r6 = 1;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_105;
	r9 = 0.;
	goto label$85c675a_15_109;
	label$85c675a_15_105:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_15_109:
	r5 = r5 * r9;
	r6 = 1;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_115;
	r9 = 0.;
	goto label$85c675a_15_119;
	label$85c675a_15_115:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$85c675a_15_119:
	r6 = 0;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_15_124;
	r10 = 0.;
	goto label$85c675a_15_128;
	label$85c675a_15_124:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r10 = *(double*)(r8 + r7);
	label$85c675a_15_128:
	r9 = r9 * r10;
	r5 = r5 - r9;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r4 = 3;
	r2 = hl_types_ArrayBase_allocF64(r3,r4);
	return r2;
}

hl__types__ArrayBytes_Float util__Math_Vec3_Impl__multiply(hl__types__ArrayBytes_Float r0,double r1) {
	hl__types__ArrayBytes_Float r2;
	double r5;
	int r4, r6, r7;
	vbyte *r3, *r8;
	r4 = 24;
	r3 = hl_alloc_bytes(r4);
	r4 = 0;
	if( r0 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_16_9;
	r5 = 0.;
	goto label$85c675a_16_13;
	label$85c675a_16_9:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_16_13:
	r5 = r5 * r1;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r6 = 1;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_16_23;
	r5 = 0.;
	goto label$85c675a_16_27;
	label$85c675a_16_23:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_16_27:
	r5 = r5 * r1;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r6 = 2;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$85c675a_16_37;
	r5 = 0.;
	goto label$85c675a_16_41;
	label$85c675a_16_37:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r5 = *(double*)(r8 + r7);
	label$85c675a_16_41:
	r5 = r5 * r1;
	r6 = 3;
	r6 = r4 << r6;
	*(double*)(r3 + r6) = r5;
	++r4;
	r4 = 3;
	r2 = hl_types_ArrayBase_allocF64(r3,r4);
	return r2;
}

double util__Math_Vec3_Impl__length(hl__types__ArrayBytes_Float r0) {
	double r1, r5, r6;
	vbyte *r4;
	int r2, r3;
	if( r0 == NULL ) hl_null_access();
	r2 = 0;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_17_6;
	r1 = 0.;
	goto label$85c675a_17_10;
	label$85c675a_17_6:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r1 = *(double*)(r4 + r3);
	label$85c675a_17_10:
	r2 = 0;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_17_15;
	r5 = 0.;
	goto label$85c675a_17_19;
	label$85c675a_17_15:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r5 = *(double*)(r4 + r3);
	label$85c675a_17_19:
	r1 = r1 * r5;
	r2 = 1;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_17_25;
	r5 = 0.;
	goto label$85c675a_17_29;
	label$85c675a_17_25:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r5 = *(double*)(r4 + r3);
	label$85c675a_17_29:
	r2 = 1;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_17_34;
	r6 = 0.;
	goto label$85c675a_17_38;
	label$85c675a_17_34:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r6 = *(double*)(r4 + r3);
	label$85c675a_17_38:
	r5 = r5 * r6;
	r1 = r1 + r5;
	r2 = 2;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_17_45;
	r5 = 0.;
	goto label$85c675a_17_49;
	label$85c675a_17_45:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r5 = *(double*)(r4 + r3);
	label$85c675a_17_49:
	r2 = 2;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_17_54;
	r6 = 0.;
	goto label$85c675a_17_58;
	label$85c675a_17_54:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r6 = *(double*)(r4 + r3);
	label$85c675a_17_58:
	r5 = r5 * r6;
	r1 = r1 + r5;
	r1 = hl_math_sqrt(r1);
	return r1;
}

hl__types__ArrayBytes_Float util__Math_Vec3_Impl__normalize(hl__types__ArrayBytes_Float r0) {
	double r1, r5, r6;
	vbyte *r4;
	int r2, r3;
	if( r0 == NULL ) hl_null_access();
	r2 = 0;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_18_6;
	r1 = 0.;
	goto label$85c675a_18_10;
	label$85c675a_18_6:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r1 = *(double*)(r4 + r3);
	label$85c675a_18_10:
	r2 = 0;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_18_15;
	r5 = 0.;
	goto label$85c675a_18_19;
	label$85c675a_18_15:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r5 = *(double*)(r4 + r3);
	label$85c675a_18_19:
	r1 = r1 * r5;
	r2 = 1;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_18_25;
	r5 = 0.;
	goto label$85c675a_18_29;
	label$85c675a_18_25:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r5 = *(double*)(r4 + r3);
	label$85c675a_18_29:
	r2 = 1;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_18_34;
	r6 = 0.;
	goto label$85c675a_18_38;
	label$85c675a_18_34:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r6 = *(double*)(r4 + r3);
	label$85c675a_18_38:
	r5 = r5 * r6;
	r1 = r1 + r5;
	r2 = 2;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_18_45;
	r5 = 0.;
	goto label$85c675a_18_49;
	label$85c675a_18_45:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r5 = *(double*)(r4 + r3);
	label$85c675a_18_49:
	r2 = 2;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_18_54;
	r6 = 0.;
	goto label$85c675a_18_58;
	label$85c675a_18_54:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r6 = *(double*)(r4 + r3);
	label$85c675a_18_58:
	r5 = r5 * r6;
	r1 = r1 + r5;
	r1 = hl_math_sqrt(r1);
	r6 = 0.;
	if( r1 == r6 ) goto label$85c675a_18_95;
	r5 = 1.;
	r5 = r5 / r1;
	r2 = 0;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_18_69;
	hl_types_ArrayBytes_Float___expand(r0,r2);
	label$85c675a_18_69:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r6 = *(double*)(r4 + r3);
	r6 = r6 * r5;
	*(double*)(r4 + r3) = r6;
	r2 = 1;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_18_79;
	hl_types_ArrayBytes_Float___expand(r0,r2);
	label$85c675a_18_79:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r6 = *(double*)(r4 + r3);
	r6 = r6 * r5;
	*(double*)(r4 + r3) = r6;
	r2 = 2;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$85c675a_18_89;
	hl_types_ArrayBytes_Float___expand(r0,r2);
	label$85c675a_18_89:
	r4 = r0->bytes;
	r3 = 3;
	r3 = r2 << r3;
	r6 = *(double*)(r4 + r3);
	r6 = r6 * r5;
	*(double*)(r4 + r3) = r6;
	label$85c675a_18_95:
	return r0;
}

hl__types__ArrayBytes_Float util__Math_Vec3_Impl__negate(hl__types__ArrayBytes_Float r0) {
	hl__types__ArrayBytes_Float r1;
	double r4;
	int r3, r5, r6;
	vbyte *r2, *r7;
	r3 = 24;
	r2 = hl_alloc_bytes(r3);
	r3 = 0;
	if( r0 == NULL ) hl_null_access();
	r5 = 0;
	r6 = r0->length;
	if( ((unsigned)r5) < ((unsigned)r6) ) goto label$85c675a_19_9;
	r4 = 0.;
	goto label$85c675a_19_13;
	label$85c675a_19_9:
	r7 = r0->bytes;
	r6 = 3;
	r6 = r5 << r6;
	r4 = *(double*)(r7 + r6);
	label$85c675a_19_13:
	r4 = -r4;
	r5 = 3;
	r5 = r3 << r5;
	*(double*)(r2 + r5) = r4;
	++r3;
	r5 = 1;
	r6 = r0->length;
	if( ((unsigned)r5) < ((unsigned)r6) ) goto label$85c675a_19_23;
	r4 = 0.;
	goto label$85c675a_19_27;
	label$85c675a_19_23:
	r7 = r0->bytes;
	r6 = 3;
	r6 = r5 << r6;
	r4 = *(double*)(r7 + r6);
	label$85c675a_19_27:
	r4 = -r4;
	r5 = 3;
	r5 = r3 << r5;
	*(double*)(r2 + r5) = r4;
	++r3;
	r5 = 2;
	r6 = r0->length;
	if( ((unsigned)r5) < ((unsigned)r6) ) goto label$85c675a_19_37;
	r4 = 0.;
	goto label$85c675a_19_41;
	label$85c675a_19_37:
	r7 = r0->bytes;
	r6 = 3;
	r6 = r5 << r6;
	r4 = *(double*)(r7 + r6);
	label$85c675a_19_41:
	r4 = -r4;
	r5 = 3;
	r5 = r3 << r5;
	*(double*)(r2 + r5) = r4;
	++r3;
	r3 = 3;
	r1 = hl_types_ArrayBase_allocF64(r2,r3);
	return r1;
}

hl__types__ArrayBytes_Float util__Math_Vec3_Impl__rotate(hl__types__ArrayBytes_Float r0,double r1) {
	$Math r4;
	hl__types__ArrayBytes_Float r10;
	double r2, r3, r5, r6, r7, r8, r9, r14;
	vbyte *r13;
	int r11, r12;
	r4 = ($Math)g$_Math;
	r3 = r4->PI;
	r2 = r1 * r3;
	r3 = 180.;
	r2 = r2 / r3;
	r5 = 2.;
	r4 = ($Math)g$_Math;
	r6 = r4->PI;
	r5 = r5 * r6;
	r3 = fmod(r2,r5);
	r4 = ($Math)g$_Math;
	r6 = r4->PI;
	if( !(r6 < r3) ) goto label$85c675a_20_20;
	r6 = 2.;
	r4 = ($Math)g$_Math;
	r7 = r4->PI;
	r6 = r6 * r7;
	r5 = r3 - r6;
	r3 = r5;
	goto label$85c675a_20_30;
	label$85c675a_20_20:
	r4 = ($Math)g$_Math;
	r6 = r4->PI;
	r6 = -r6;
	if( !(r3 < r6) ) goto label$85c675a_20_30;
	r6 = 2.;
	r4 = ($Math)g$_Math;
	r7 = r4->PI;
	r6 = r6 * r7;
	r5 = r3 + r6;
	r3 = r5;
	label$85c675a_20_30:
	r5 = hl_math_abs(r3);
	r6 = 0.5;
	if( !(r5 < r6) ) goto label$85c675a_20_39;
	r5 = 1.;
	r6 = r3 * r3;
	r7 = 2.;
	r6 = r6 / r7;
	r5 = r5 - r6;
	goto label$85c675a_20_40;
	label$85c675a_20_39:
	r5 = hl_math_cos(r3);
	label$85c675a_20_40:
	r7 = 2.;
	r4 = ($Math)g$_Math;
	r8 = r4->PI;
	r7 = r7 * r8;
	r6 = fmod(r2,r7);
	r4 = ($Math)g$_Math;
	r8 = r4->PI;
	if( !(r8 < r6) ) goto label$85c675a_20_55;
	r8 = 2.;
	r4 = ($Math)g$_Math;
	r9 = r4->PI;
	r8 = r8 * r9;
	r7 = r6 - r8;
	r6 = r7;
	goto label$85c675a_20_65;
	label$85c675a_20_55:
	r4 = ($Math)g$_Math;
	r8 = r4->PI;
	r8 = -r8;
	if( !(r6 < r8) ) goto label$85c675a_20_65;
	r8 = 2.;
	r4 = ($Math)g$_Math;
	r9 = r4->PI;
	r8 = r8 * r9;
	r7 = r6 + r8;
	r6 = r7;
	label$85c675a_20_65:
	r7 = hl_math_abs(r6);
	r8 = 0.5;
	if( !(r7 < r8) ) goto label$85c675a_20_74;
	r8 = r6 * r6;
	r8 = r8 * r6;
	r9 = 6.;
	r8 = r8 / r9;
	r7 = r6 - r8;
	goto label$85c675a_20_75;
	label$85c675a_20_74:
	r7 = hl_math_sin(r6);
	label$85c675a_20_75:
	if( r0 == NULL ) hl_null_access();
	r11 = 0;
	r12 = r0->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$85c675a_20_81;
	r8 = 0.;
	goto label$85c675a_20_85;
	label$85c675a_20_81:
	r13 = r0->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r8 = *(double*)(r13 + r12);
	label$85c675a_20_85:
	r8 = r8 * r5;
	r11 = 1;
	r12 = r0->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$85c675a_20_91;
	r9 = 0.;
	goto label$85c675a_20_95;
	label$85c675a_20_91:
	r13 = r0->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r9 = *(double*)(r13 + r12);
	label$85c675a_20_95:
	r9 = r9 * r7;
	r8 = r8 - r9;
	r11 = 0;
	r12 = r0->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$85c675a_20_102;
	r9 = 0.;
	goto label$85c675a_20_106;
	label$85c675a_20_102:
	r13 = r0->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r9 = *(double*)(r13 + r12);
	label$85c675a_20_106:
	r9 = r9 * r7;
	r11 = 1;
	r12 = r0->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$85c675a_20_112;
	r14 = 0.;
	goto label$85c675a_20_116;
	label$85c675a_20_112:
	r13 = r0->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r14 = *(double*)(r13 + r12);
	label$85c675a_20_116:
	r14 = r14 * r5;
	r9 = r9 + r14;
	r11 = 24;
	r13 = hl_alloc_bytes(r11);
	r11 = 0;
	r12 = 3;
	r12 = r11 << r12;
	*(double*)(r13 + r12) = r8;
	++r11;
	r12 = 3;
	r12 = r11 << r12;
	*(double*)(r13 + r12) = r9;
	++r11;
	r14 = 0.;
	r12 = 3;
	r12 = r11 << r12;
	*(double*)(r13 + r12) = r14;
	++r11;
	r11 = 3;
	r10 = hl_types_ArrayBase_allocF64(r13,r11);
	return r10;
}

void util__Math_Vec3_Impl__applyRotation(hl__types__ArrayBytes_Float r0,double r1) {
	$Math r4;
	double r2, r3, r6, r7, r8, r9, r10, r14;
	vbyte *r13;
	int r11, r12;
	r4 = ($Math)g$_Math;
	r3 = r4->PI;
	r2 = r1 * r3;
	r3 = 180.;
	r2 = r2 / r3;
	r6 = 2.;
	r4 = ($Math)g$_Math;
	r7 = r4->PI;
	r6 = r6 * r7;
	r3 = fmod(r2,r6);
	r4 = ($Math)g$_Math;
	r7 = r4->PI;
	if( !(r7 < r3) ) goto label$85c675a_21_20;
	r7 = 2.;
	r4 = ($Math)g$_Math;
	r8 = r4->PI;
	r7 = r7 * r8;
	r6 = r3 - r7;
	r3 = r6;
	goto label$85c675a_21_30;
	label$85c675a_21_20:
	r4 = ($Math)g$_Math;
	r7 = r4->PI;
	r7 = -r7;
	if( !(r3 < r7) ) goto label$85c675a_21_30;
	r7 = 2.;
	r4 = ($Math)g$_Math;
	r8 = r4->PI;
	r7 = r7 * r8;
	r6 = r3 + r7;
	r3 = r6;
	label$85c675a_21_30:
	r6 = hl_math_abs(r3);
	r7 = 0.5;
	if( !(r6 < r7) ) goto label$85c675a_21_39;
	r6 = 1.;
	r7 = r3 * r3;
	r8 = 2.;
	r7 = r7 / r8;
	r6 = r6 - r7;
	goto label$85c675a_21_40;
	label$85c675a_21_39:
	r6 = hl_math_cos(r3);
	label$85c675a_21_40:
	r8 = 2.;
	r4 = ($Math)g$_Math;
	r9 = r4->PI;
	r8 = r8 * r9;
	r7 = fmod(r2,r8);
	r4 = ($Math)g$_Math;
	r9 = r4->PI;
	if( !(r9 < r7) ) goto label$85c675a_21_55;
	r9 = 2.;
	r4 = ($Math)g$_Math;
	r10 = r4->PI;
	r9 = r9 * r10;
	r8 = r7 - r9;
	r7 = r8;
	goto label$85c675a_21_65;
	label$85c675a_21_55:
	r4 = ($Math)g$_Math;
	r9 = r4->PI;
	r9 = -r9;
	if( !(r7 < r9) ) goto label$85c675a_21_65;
	r9 = 2.;
	r4 = ($Math)g$_Math;
	r10 = r4->PI;
	r9 = r9 * r10;
	r8 = r7 + r9;
	r7 = r8;
	label$85c675a_21_65:
	r8 = hl_math_abs(r7);
	r9 = 0.5;
	if( !(r8 < r9) ) goto label$85c675a_21_74;
	r9 = r7 * r7;
	r9 = r9 * r7;
	r10 = 6.;
	r9 = r9 / r10;
	r8 = r7 - r9;
	goto label$85c675a_21_75;
	label$85c675a_21_74:
	r8 = hl_math_sin(r7);
	label$85c675a_21_75:
	if( r0 == NULL ) hl_null_access();
	r11 = 0;
	r12 = r0->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$85c675a_21_81;
	r9 = 0.;
	goto label$85c675a_21_85;
	label$85c675a_21_81:
	r13 = r0->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r9 = *(double*)(r13 + r12);
	label$85c675a_21_85:
	r9 = r9 * r6;
	r11 = 1;
	r12 = r0->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$85c675a_21_91;
	r10 = 0.;
	goto label$85c675a_21_95;
	label$85c675a_21_91:
	r13 = r0->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r10 = *(double*)(r13 + r12);
	label$85c675a_21_95:
	r10 = r10 * r8;
	r9 = r9 - r10;
	r11 = 0;
	r12 = r0->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$85c675a_21_102;
	r10 = 0.;
	goto label$85c675a_21_106;
	label$85c675a_21_102:
	r13 = r0->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r10 = *(double*)(r13 + r12);
	label$85c675a_21_106:
	r10 = r10 * r8;
	r11 = 1;
	r12 = r0->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$85c675a_21_112;
	r14 = 0.;
	goto label$85c675a_21_116;
	label$85c675a_21_112:
	r13 = r0->bytes;
	r12 = 3;
	r12 = r11 << r12;
	r14 = *(double*)(r13 + r12);
	label$85c675a_21_116:
	r14 = r14 * r6;
	r10 = r10 + r14;
	r11 = 0;
	r12 = r0->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$85c675a_21_122;
	hl_types_ArrayBytes_Float___expand(r0,r11);
	label$85c675a_21_122:
	r13 = r0->bytes;
	r12 = 3;
	r12 = r11 << r12;
	*(double*)(r13 + r12) = r9;
	r11 = 1;
	r12 = r0->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$85c675a_21_130;
	hl_types_ArrayBytes_Float___expand(r0,r11);
	label$85c675a_21_130:
	r13 = r0->bytes;
	r12 = 3;
	r12 = r11 << r12;
	*(double*)(r13 + r12) = r10;
	return;
}

