// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_sys__io__FileOutput
#define INC_sys__io__FileOutput
typedef struct _sys__io__$FileOutput *sys__io__$FileOutput;
typedef struct _sys__io__FileOutput *sys__io__FileOutput;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/io/Output.h>
#include <hl/natives.h>


struct _sys__io__$FileOutput {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _sys__io__FileOutput {
	hl_type *$type;
	hl_fdesc* _hx___f;
};
#endif

