// Generated by HLC 4.3.7 (HL v4)
#ifndef INC_sys__io__File
#define INC_sys__io__File
typedef struct _sys__io__$File *sys__io__$File;
typedef struct _sys__io__File *sys__io__File;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/io/Bytes.h>
#include <sys/io/FileOutput.h>


struct _sys__io__$File {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* getContent;
	vclosure* getBytes;
	vclosure* saveContent;
	vclosure* write;
};
struct _sys__io__File {
	hl_type *$type;
};
#endif

