// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <ui/MainframeEditor.h>
void objects_Mainframe_compileScript(objects__Mainframe);
extern String s$;
int String___compare(String,vdynamic*);
extern String s$Saved;
extern String s$Error;
void ui_MainframeEditor_close(ui__MainframeEditor,bool*);
#include <hl/types/ArrayBytes_Float.h>
#include <_std/Engine.h>
#include <hl/types/ArrayObj.h>
#include <hl/natives.h>
extern $Engine g$_Engine;
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
extern String s$Mainframe_editor;
void util_FontManager_drawText(String,int,int,int*);
extern String s$68b329d;
hl__types__ArrayObj String_split(String,String);
double Math_min(double,double);
extern String s$Script_API_;
extern String s$setOut_index_bool_;
extern String s$getIn_index_;
extern String s$time_dt;
extern hl_type t$_i32;
String String_substr(String,int,vdynamic*);
String String___add__(String,String);
extern String s$0cf31b2;
extern String s$7215ee9;
String ui_MainframeEditor_keyCodeToChar(ui__MainframeEditor,int);
extern String s$Editing;
extern hl_type t$Object;
void Object_new(Object,int*,int*,String,int*);
extern hl_type t$util_Button;
extern String s$Save;
void util_Button_new(util__Button,String,int*,int*,String);
void Object_setVisible(Object,bool);
extern hl_type t$fun_7c3d67c;
extern String s$Close;
extern hl_type t$fun_e9e8936;
extern hl_type t$fun_f67de73;
void Eight_registerUpdateCallback(vclosure*);
void Eight_registerEventCallback(vclosure*);
String String_fromCharCode(int);
extern String s$3590cb8;
extern String s$c0cb5f0;
extern String s$336d5eb;
extern String s$5058f1a;
extern String s$6666cd7;
extern String s$9eecb7d;
extern String s$43ec3e5;
extern String s$8154172;
extern String s$28d397e;
extern String s$0fbd177;
extern String s$833344d;
hl__types__ArrayObj Eight_unregisterUpdateCallback(vclosure*);
hl__types__ArrayObj Eight_unregisterEventCallback(vclosure*);
void Object_destroy(Object);
extern String s$Ready;

void ui_MainframeEditor_open__$1(ui__MainframeEditor r0) {
	String r3, r4;
	objects__Mainframe r2;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->current;
	if( r2 ) goto label$8c7a2de_1_4;
	return;
	label$8c7a2de_1_4:
	r2 = r0->current;
	if( r2 == NULL ) hl_null_access();
	r3 = r0->text;
	r2->script = r3;
	r2 = r0->current;
	if( r2 == NULL ) hl_null_access();
	objects_Mainframe_compileScript(r2);
	r2 = r0->current;
	if( r2 == NULL ) hl_null_access();
	r3 = r2->lastError;
	r4 = (String)s$;
	if( r3 != r4 && (!r3 || !r4 || String___compare(r3,(vdynamic*)r4) != 0) ) goto label$8c7a2de_1_18;
	r3 = (String)s$Saved;
	goto label$8c7a2de_1_19;
	label$8c7a2de_1_18:
	r3 = (String)s$Error;
	label$8c7a2de_1_19:
	r0->status = r3;
	return;
}

void ui_MainframeEditor_open__$2(ui__MainframeEditor r0) {
	bool *r2;
	if( r0 == NULL ) hl_null_access();
	r2 = NULL;
	ui_MainframeEditor_close(r0,r2);
	return;
}

void ui_MainframeEditor_open__$3(ui__MainframeEditor r0,double r1) {
	objects__Mainframe r24;
	String r11, r15;
	hl__types__ArrayObj r14;
	$Engine r8;
	Object r2;
	hl__types__ArrayBytes_Float r3;
	double r6, r9, r16;
	vdynamic *r21;
	int *r13;
	varray *r22;
	int r5, r7, r12, r17, r18, r19, r20, r23;
	vbyte *r4;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->bg;
	if( r2 == NULL ) hl_null_access();
	r5 = 24;
	r4 = hl_alloc_bytes(r5);
	r5 = 0;
	r8 = ($Engine)g$_Engine;
	r7 = r8->n;
	r6 = (double)r7;
	r9 = 2.;
	r6 = r6 / r9;
	r7 = 3;
	r7 = r5 << r7;
	*(double*)(r4 + r7) = r6;
	++r5;
	r8 = ($Engine)g$_Engine;
	r7 = r8->n2;
	r6 = (double)r7;
	r9 = 2.;
	r6 = r6 / r9;
	r7 = 3;
	r7 = r5 << r7;
	*(double*)(r4 + r7) = r6;
	++r5;
	r6 = 0.;
	r7 = 3;
	r7 = r5 << r7;
	*(double*)(r4 + r7) = r6;
	++r5;
	r5 = 3;
	r3 = hl_types_ArrayBase_allocF64(r4,r5);
	r2->pos = r3;
	r11 = (String)s$Mainframe_editor;
	r5 = 30;
	r8 = ($Engine)g$_Engine;
	r7 = r8->n2;
	r12 = 54;
	r7 = r7 - r12;
	r13 = NULL;
	util_FontManager_drawText(r11,r5,r7,r13);
	r11 = r0->status;
	r5 = 30;
	r8 = ($Engine)g$_Engine;
	r7 = r8->n2;
	r12 = 74;
	r7 = r7 - r12;
	r13 = NULL;
	util_FontManager_drawText(r11,r5,r7,r13);
	r11 = r0->text;
	if( r11 == NULL ) hl_null_access();
	r15 = (String)s$68b329d;
	r14 = String_split(r11,r15);
	r8 = ($Engine)g$_Engine;
	r5 = r8->n2;
	r7 = 180;
	r5 = r5 - r7;
	r6 = (double)r5;
	r9 = 18.;
	r6 = r6 / r9;
	r5 = (int)r6;
	if( r14 == NULL ) hl_null_access();
	r7 = r14->length;
	r9 = (double)r7;
	r16 = (double)r5;
	r9 = Math_min(r9,r16);
	r7 = (int)r9;
	r12 = 0;
	r17 = r7;
	label$8c7a2de_3_68:
	if( r12 >= r17 ) goto label$8c7a2de_3_91;
	r18 = r12;
	++r12;
	if( r14 == NULL ) hl_null_access();
	r20 = r14->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$8c7a2de_3_77;
	r11 = NULL;
	goto label$8c7a2de_3_80;
	label$8c7a2de_3_77:
	r22 = r14->array;
	r21 = ((vdynamic**)(r22 + 1))[r18];
	r11 = (String)r21;
	label$8c7a2de_3_80:
	r19 = 30;
	r8 = ($Engine)g$_Engine;
	r20 = r8->n2;
	r23 = 110;
	r20 = r20 - r23;
	r23 = 18;
	r23 = r23 * r18;
	r20 = r20 - r23;
	r13 = NULL;
	util_FontManager_drawText(r11,r19,r20,r13);
	goto label$8c7a2de_3_68;
	label$8c7a2de_3_91:
	r11 = (String)s$Script_API_;
	r8 = ($Engine)g$_Engine;
	r12 = r8->n;
	r17 = 320;
	r12 = r12 - r17;
	r8 = ($Engine)g$_Engine;
	r17 = r8->n2;
	r18 = 54;
	r17 = r17 - r18;
	r13 = NULL;
	util_FontManager_drawText(r11,r12,r17,r13);
	r11 = (String)s$setOut_index_bool_;
	r8 = ($Engine)g$_Engine;
	r12 = r8->n;
	r17 = 320;
	r12 = r12 - r17;
	r8 = ($Engine)g$_Engine;
	r17 = r8->n2;
	r18 = 74;
	r17 = r17 - r18;
	r13 = NULL;
	util_FontManager_drawText(r11,r12,r17,r13);
	r11 = (String)s$getIn_index_;
	r8 = ($Engine)g$_Engine;
	r12 = r8->n;
	r17 = 320;
	r12 = r12 - r17;
	r8 = ($Engine)g$_Engine;
	r17 = r8->n2;
	r18 = 92;
	r17 = r17 - r18;
	r13 = NULL;
	util_FontManager_drawText(r11,r12,r17,r13);
	r11 = (String)s$time_dt;
	r8 = ($Engine)g$_Engine;
	r12 = r8->n;
	r17 = 320;
	r12 = r12 - r17;
	r8 = ($Engine)g$_Engine;
	r17 = r8->n2;
	r18 = 110;
	r17 = r17 - r18;
	r13 = NULL;
	util_FontManager_drawText(r11,r12,r17,r13);
	if( r0 == NULL ) hl_null_access();
	r24 = r0->current;
	if( !r24 ) goto label$8c7a2de_3_150;
	r24 = r0->current;
	if( r24 == NULL ) hl_null_access();
	r11 = r24->lastError;
	r15 = (String)s$;
	if( r11 == r15 || (r11 && r15 && String___compare(r11,(vdynamic*)r15) == 0) ) goto label$8c7a2de_3_150;
	r24 = r0->current;
	if( r24 == NULL ) hl_null_access();
	r11 = r24->lastError;
	r12 = 30;
	r17 = 70;
	r13 = NULL;
	util_FontManager_drawText(r11,r12,r17,r13);
	label$8c7a2de_3_150:
	return;
}

void ui_MainframeEditor_open__$4(ui__MainframeEditor r0,sdl__Event r1) {
	String r6, r7;
	bool *r5;
	vdynamic *r9;
	int r3, r4, r8;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->type;
	r4 = 7;
	if( r3 == r4 ) goto label$8c7a2de_4_5;
	return;
	label$8c7a2de_4_5:
	r3 = r1->keyCode;
	r4 = 27;
	if( r3 != r4 ) goto label$8c7a2de_4_12;
	if( r0 == NULL ) hl_null_access();
	r5 = NULL;
	ui_MainframeEditor_close(r0,r5);
	return;
	label$8c7a2de_4_12:
	r3 = r1->keyCode;
	r4 = 8;
	if( r3 != r4 ) goto label$8c7a2de_4_33;
	if( r0 == NULL ) hl_null_access();
	r6 = r0->text;
	if( r6 == NULL ) hl_null_access();
	r3 = r6->length;
	r4 = 0;
	if( r4 >= r3 ) goto label$8c7a2de_4_32;
	r6 = r0->text;
	if( r6 == NULL ) hl_null_access();
	r3 = 0;
	r7 = r0->text;
	if( r7 == NULL ) hl_null_access();
	r4 = r7->length;
	r8 = 1;
	r4 = r4 - r8;
	r9 = hl_alloc_dynamic(&t$_i32);
	r9->v.i = r4;
	r6 = String_substr(r6,r3,r9);
	r0->text = r6;
	label$8c7a2de_4_32:
	return;
	label$8c7a2de_4_33:
	r3 = r1->keyCode;
	r4 = 13;
	if( r3 != r4 ) goto label$8c7a2de_4_42;
	if( r0 == NULL ) hl_null_access();
	r6 = r0->text;
	r7 = (String)s$68b329d;
	r6 = String___add__(r6,r7);
	r0->text = r6;
	return;
	label$8c7a2de_4_42:
	r3 = r1->keyCode;
	r4 = 9;
	if( r3 != r4 ) goto label$8c7a2de_4_51;
	if( r0 == NULL ) hl_null_access();
	r6 = r0->text;
	r7 = (String)s$0cf31b2;
	r6 = String___add__(r6,r7);
	r0->text = r6;
	return;
	label$8c7a2de_4_51:
	r3 = r1->keyCode;
	r4 = 32;
	if( r3 != r4 ) goto label$8c7a2de_4_60;
	if( r0 == NULL ) hl_null_access();
	r6 = r0->text;
	r7 = (String)s$7215ee9;
	r6 = String___add__(r6,r7);
	r0->text = r6;
	return;
	label$8c7a2de_4_60:
	if( r0 == NULL ) hl_null_access();
	r3 = r1->keyCode;
	r6 = ui_MainframeEditor_keyCodeToChar(r0,r3);
	if( !r6 ) goto label$8c7a2de_4_67;
	r7 = r0->text;
	r7 = String___add__(r7,r6);
	r0->text = r7;
	label$8c7a2de_4_67:
	return;
}

void ui_MainframeEditor_open(ui__MainframeEditor r0,objects__Mainframe r1) {
	String r5, r16;
	bool *r4;
	$Engine r9;
	bool r3, r6;
	Object r7;
	hl__types__ArrayBytes_Float r17;
	vclosure *r22, *r23, *r24;
	double r20;
	util__Button r15;
	int *r11, *r13, *r14;
	vbyte *r18;
	int r8, r10, r12, r19, r21;
	r3 = r0->isOpen;
	if( !r3 ) goto label$8c7a2de_5_5;
	r3 = false;
	r4 = &r3;
	ui_MainframeEditor_close(r0,r4);
	label$8c7a2de_5_5:
	r0->current = r1;
	if( r1 == NULL ) hl_null_access();
	r5 = r1->script;
	r0->text = r5;
	r5 = (String)s$Editing;
	r0->status = r5;
	r6 = true;
	r0->isOpen = r6;
	r7 = (Object)hl_alloc_obj(&t$Object);
	r9 = ($Engine)g$_Engine;
	r8 = r9->n;
	r10 = 120;
	r8 = r8 - r10;
	r11 = &r8;
	r9 = ($Engine)g$_Engine;
	r10 = r9->n2;
	r12 = 120;
	r10 = r10 - r12;
	r13 = &r10;
	r5 = NULL;
	r12 = -14802649;
	r14 = &r12;
	Object_new(r7,r11,r13,r5,r14);
	r0->bg = r7;
	r7 = r0->bg;
	if( r7 == NULL ) hl_null_access();
	r6 = true;
	r7->isUI = r6;
	r15 = (util__Button)hl_alloc_obj(&t$util_Button);
	r5 = (String)s$Save;
	r11 = NULL;
	r13 = NULL;
	r16 = NULL;
	util_Button_new(r15,r5,r11,r13,r16);
	r0->buttonSave = r15;
	r15 = r0->buttonSave;
	if( r15 == NULL ) hl_null_access();
	r19 = 24;
	r18 = hl_alloc_bytes(r19);
	r19 = 0;
	r20 = 120.;
	r21 = 3;
	r21 = r19 << r21;
	*(double*)(r18 + r21) = r20;
	++r19;
	r20 = 34.;
	r21 = 3;
	r21 = r19 << r21;
	*(double*)(r18 + r21) = r20;
	++r19;
	r20 = 0.;
	r21 = 3;
	r21 = r19 << r21;
	*(double*)(r18 + r21) = r20;
	++r19;
	r19 = 3;
	r17 = hl_types_ArrayBase_allocF64(r18,r19);
	r15->pos = r17;
	r15 = r0->buttonSave;
	if( r15 == NULL ) hl_null_access();
	r6 = true;
	Object_setVisible(((Object)r15),r6);
	r15 = r0->buttonSave;
	if( r15 == NULL ) hl_null_access();
	r22 = hl_alloc_closure_ptr(&t$fun_7c3d67c,ui_MainframeEditor_open__$1,r0);
	r15->clicked = r22;
	r15 = (util__Button)hl_alloc_obj(&t$util_Button);
	r5 = (String)s$Close;
	r11 = NULL;
	r13 = NULL;
	r16 = NULL;
	util_Button_new(r15,r5,r11,r13,r16);
	r0->buttonClose = r15;
	r15 = r0->buttonClose;
	if( r15 == NULL ) hl_null_access();
	r19 = 24;
	r18 = hl_alloc_bytes(r19);
	r19 = 0;
	r20 = 240.;
	r21 = 3;
	r21 = r19 << r21;
	*(double*)(r18 + r21) = r20;
	++r19;
	r20 = 34.;
	r21 = 3;
	r21 = r19 << r21;
	*(double*)(r18 + r21) = r20;
	++r19;
	r20 = 0.;
	r21 = 3;
	r21 = r19 << r21;
	*(double*)(r18 + r21) = r20;
	++r19;
	r19 = 3;
	r17 = hl_types_ArrayBase_allocF64(r18,r19);
	r15->pos = r17;
	r15 = r0->buttonClose;
	if( r15 == NULL ) hl_null_access();
	r6 = true;
	Object_setVisible(((Object)r15),r6);
	r15 = r0->buttonClose;
	if( r15 == NULL ) hl_null_access();
	r22 = hl_alloc_closure_ptr(&t$fun_7c3d67c,ui_MainframeEditor_open__$2,r0);
	r15->clicked = r22;
	r23 = hl_alloc_closure_ptr(&t$fun_e9e8936,ui_MainframeEditor_open__$3,r0);
	r0->updateCb = r23;
	r24 = hl_alloc_closure_ptr(&t$fun_f67de73,ui_MainframeEditor_open__$4,r0);
	r0->eventCb = r24;
	r23 = r0->updateCb;
	Eight_registerUpdateCallback(r23);
	r24 = r0->eventCb;
	Eight_registerEventCallback(r24);
	return;
}

String ui_MainframeEditor_keyCodeToChar(ui__MainframeEditor r0,int r1) {
	String r3;
	int r2;
	r2 = 97;
	if( r1 < r2 ) goto label$8c7a2de_6_6;
	r2 = 122;
	if( r2 < r1 ) goto label$8c7a2de_6_6;
	r3 = String_fromCharCode(r1);
	return r3;
	label$8c7a2de_6_6:
	r2 = 48;
	if( r1 < r2 ) goto label$8c7a2de_6_12;
	r2 = 57;
	if( r2 < r1 ) goto label$8c7a2de_6_12;
	r3 = String_fromCharCode(r1);
	return r3;
	label$8c7a2de_6_12:
	switch(r1) {
		default:
		case 0:
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
		case 7:
		case 8:
		case 9:
		case 10:
		case 11:
		case 12:
		case 13:
		case 14:
		case 15:
		case 16:
		case 17:
		case 18:
		case 19:
		case 20:
		case 21:
		case 22:
		case 23:
		case 24:
		case 25:
		case 26:
		case 27:
		case 28:
		case 29:
		case 30:
		case 31:
		case 32:
		case 33:
		case 34:
		case 35:
		case 36:
		case 37:
		case 38:
		case 40:
		case 41:
		case 42:
		case 43:
		case 48:
		case 49:
		case 50:
		case 51:
		case 52:
		case 53:
		case 54:
		case 55:
		case 56:
		case 57:
		case 58:
		case 60:
		case 62:
		case 63:
		case 64:
		case 65:
		case 66:
		case 67:
		case 68:
		case 69:
		case 70:
		case 71:
		case 72:
		case 73:
		case 74:
		case 75:
		case 76:
		case 77:
		case 78:
		case 79:
		case 80:
		case 81:
		case 82:
		case 83:
		case 84:
		case 85:
		case 86:
		case 87:
		case 88:
		case 89:
		case 90:
		case 94:
		case 95:
			r3 = NULL;
			return r3;
		case 39:
			r3 = (String)s$3590cb8;
			return r3;
		case 44:
			r3 = (String)s$c0cb5f0;
			return r3;
		case 45:
			r3 = (String)s$336d5eb;
			return r3;
		case 46:
			r3 = (String)s$5058f1a;
			return r3;
		case 47:
			r3 = (String)s$6666cd7;
			return r3;
		case 59:
			r3 = (String)s$9eecb7d;
			return r3;
		case 61:
			r3 = (String)s$43ec3e5;
			return r3;
		case 91:
			r3 = (String)s$8154172;
			return r3;
		case 92:
			r3 = (String)s$28d397e;
			return r3;
		case 93:
			r3 = (String)s$0fbd177;
			return r3;
		case 96:
			r3 = (String)s$833344d;
			return r3;
	}
}

void ui_MainframeEditor_close(ui__MainframeEditor r0,bool* r1) {
	String r6;
	objects__Mainframe r5;
	hl__types__ArrayObj r8;
	bool r2, r4;
	Object r11;
	vclosure *r7, *r9;
	util__Button r10;
	if( r1 ) goto label$8c7a2de_7_3;
	r2 = false;
	goto label$8c7a2de_7_4;
	label$8c7a2de_7_3:
	r2 = *r1;
	label$8c7a2de_7_4:
	r4 = r0->isOpen;
	if( r4 ) goto label$8c7a2de_7_7;
	return;
	label$8c7a2de_7_7:
	if( !r2 ) goto label$8c7a2de_7_17;
	r5 = r0->current;
	if( !r5 ) goto label$8c7a2de_7_17;
	r5 = r0->current;
	if( r5 == NULL ) hl_null_access();
	r6 = r0->text;
	r5->script = r6;
	r5 = r0->current;
	if( r5 == NULL ) hl_null_access();
	objects_Mainframe_compileScript(r5);
	label$8c7a2de_7_17:
	r4 = false;
	r0->isOpen = r4;
	r7 = r0->updateCb;
	if( !r7 ) goto label$8c7a2de_7_23;
	r7 = r0->updateCb;
	r8 = Eight_unregisterUpdateCallback(r7);
	label$8c7a2de_7_23:
	r9 = r0->eventCb;
	if( !r9 ) goto label$8c7a2de_7_27;
	r9 = r0->eventCb;
	r8 = Eight_unregisterEventCallback(r9);
	label$8c7a2de_7_27:
	r10 = r0->buttonSave;
	if( !r10 ) goto label$8c7a2de_7_32;
	r10 = r0->buttonSave;
	if( r10 == NULL ) hl_null_access();
	Object_destroy(((Object)r10));
	label$8c7a2de_7_32:
	r10 = r0->buttonClose;
	if( !r10 ) goto label$8c7a2de_7_37;
	r10 = r0->buttonClose;
	if( r10 == NULL ) hl_null_access();
	Object_destroy(((Object)r10));
	label$8c7a2de_7_37:
	r11 = r0->bg;
	if( !r11 ) goto label$8c7a2de_7_42;
	r11 = r0->bg;
	if( r11 == NULL ) hl_null_access();
	Object_destroy(r11);
	label$8c7a2de_7_42:
	r7 = NULL;
	r0->updateCb = r7;
	r9 = NULL;
	r0->eventCb = r9;
	r10 = NULL;
	r0->buttonSave = r10;
	r10 = NULL;
	r0->buttonClose = r10;
	r11 = NULL;
	r0->bg = r11;
	r5 = NULL;
	r0->current = r5;
	return;
}

void ui_MainframeEditor_new(ui__MainframeEditor r0) {
	String r1;
	bool r2;
	r1 = (String)s$Ready;
	r0->status = r1;
	r1 = (String)s$;
	r0->text = r1;
	r2 = false;
	r0->isOpen = r2;
	return;
}

