// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <ui/UI.h>
#include <_std/Game.h>
extern $Game g$_Game;
#include <_std/Object.h>
void Object_setVisible(Object,bool);
extern hl_type t$fun_7b48b4f;
extern hl_type t$util_Button;
extern String s$Logic;
void util_Button_new(util__Button,String,int*,int*,String);

void ui_UI_new__$1() {
	$Game r1;
	bool r0;
	r1 = ($Game)g$_Game;
	r0 = r1->isLogicVisible;
	r0 = !r0;
	r1 = ($Game)g$_Game;
	r1->isLogicVisible = r0;
	return;
}

void ui_UI_setVisible(ui__UI r0,bool r1) {
	util__Button r3;
	r0->isShown = r1;
	r3 = r0->buttonLogic;
	if( r3 == NULL ) hl_null_access();
	Object_setVisible(((Object)r3),r1);
	return;
}

void ui_UI_new(ui__UI r0) {
	String r3, r8;
	bool r1;
	vclosure *r10;
	int *r5, *r7;
	util__Button r2;
	int r4, r6;
	static vclosure cl$0 = { &t$fun_7b48b4f, ui_UI_new__$1, 0 };
	r1 = false;
	r0->isShown = r1;
	r2 = (util__Button)hl_alloc_obj(&t$util_Button);
	r3 = (String)s$Logic;
	r4 = 50;
	r5 = &r4;
	r6 = 9;
	r7 = &r6;
	r8 = NULL;
	util_Button_new(r2,r3,r5,r7,r8);
	r0->buttonLogic = r2;
	r2 = r0->buttonLogic;
	if( r2 == NULL ) hl_null_access();
	r10 = &cl$0;
	r2->clicked = r10;
	r1 = true;
	ui_UI_setVisible(r0,r1);
	return;
}

