// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/Character.h>
extern hl_type t$Object;
extern hl_type t$_dyn;
#include <objects/ExtendableObject.h>
#include <objects/Bed.h>
extern objects__$Bed g$_objects_Bed;
bool Std_isOfType(vdynamic*,vdynamic*);
#include <_std/SleepJob.h>
extern hl_type t$fun_988ed22;
#include <hl/natives.h>
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
extern String s$Sleep;
bool Character_hasJobType(Character,String);
objects__ExtendableObject Character_findNearestInteractable(Character,vclosure*);
extern hl_type t$SleepJob;
void SleepJob_new(SleepJob,objects__ExtendableObject,double*);
void Character_enqueueJob(Character,PawnJob);
void Character_startNextJob(Character);
extern String s$O2_;
String String___alloc__(vbyte*,int);
String String___add__(String,String);
void util_FontManager_drawText(String,int,int,int*);
extern String s$Food_;
extern String s$8c9db0a;
extern String s$Job_;
extern String s$Idle;
extern String s$Queue_;
extern String s$Carry_;
void Object_draw(Object);
int String___compare(String,vdynamic*);
extern hl_type t$PawnJob;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
vdynamic* hl_types_ArrayObj_shift(hl__types__ArrayObj);
extern hl_type t$ctx_2089d06;
extern hl_type t$fun_5a8fccd;
#include <objects/ExtendableManager.h>
#include <_std/Game.h>
extern $Game g$_Game;
extern hl_type t$ctx_041753c;
void Character_setTarget__$2(venum*,vvirtual*);
extern hl_type t$fun_87f9032;
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
hl__types__ArrayObj Eight_unregisterUpdateCallback(vclosure*);
extern haxe__$Log g$_haxe_Log;
extern String s$Approached_;
extern hl_type t$vrt_eaa6a3b;
extern String s$Character_hx;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$Character;
extern String s$setTarget;
extern hl_type t$_f64;
#include <hl/types/ArrayBase.h>
hl__types__ArrayDyn hl_types_ArrayDyn_alloc(hl__types__ArrayBase,bool*);
extern hl_type t$hl_types_ArrayDyn;
extern hl_type t$fun_7b48b4f;
extern String s$Moving_character_to_;
extern hl_type t$fun_0a89fd7;
extern hl_type t$ctx_cbf3c7f;
extern hl_type t$fun_077f60c;
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);
void Eight_registerUpdateCallback(vclosure*);
#include <objects/Door.h>
extern objects__$Door g$_objects_Door;
#include <util/Sequence.h>
extern String s$Inside_;
void util_Sequence_next(util__Sequence);
#include <_std/Eight.h>
#include <objects/Hull.h>
extern hl_type t$fun_4bb4509;
extern hl_type t$fun_efbe4b1;
extern $Eight g$_Eight;
hl__types__ArrayObj hl_types_ArrayObj_copy(hl__types__ArrayObj);
extern hl_type t$fun_c6993f3;
extern hl_type t$fun_41f671f;
void hl_types_ArrayObj_sort(hl__types__ArrayObj,vclosure*);
void hl_types_ArrayObj_reverse(hl__types__ArrayObj);
Object Game_findObject(hl__types__ArrayObj,vclosure*);
extern String s$Null_errror_;
Object Game_findObjectOnMouse(double,double,vclosure*);
extern objects__$Hull g$_objects_Hull;
extern hl_type t$util_Sequence;
void util_Sequence_new(util__Sequence);
void wrapt$fun_3eab8b5(vclosure*,util__Sequence);
extern hl_type t$fun_3eab8b5;
util__Sequence util_Sequence_then(util__Sequence,vclosure*,String);
extern hl_type t$ctx_48573a3;
extern hl_type t$fun_60b000c;
void util_Sequence_start(util__Sequence);
extern hl_type t$ctx_521e260;
extern hl_type t$fun_c967d5a;
extern String s$character_png;
void objects_GameObject_new(objects__GameObject,int*,int*,String,int*);

int Character_setTarget__$5(vclosure* r0,vdynamic* r1,vdynamic* r2) {
	Object r3, r4;
	int r5;
	r3 = (Object)hl_dyn_castp(&r1,&t$_dyn,&t$Object);
	r4 = (Object)hl_dyn_castp(&r2,&t$_dyn,&t$Object);
	r5 = r0->hasValue ? ((int (*)(vdynamic*,Object,Object))r0->fun)((vdynamic*)r0->value,r3,r4) : ((int (*)(Object,Object))r0->fun)(r3,r4);
	return r5;
}

bool Character_update__$1(objects__ExtendableObject r0) {
	objects__$Bed r2;
	bool r1;
	r2 = (objects__$Bed)g$_objects_Bed;
	r1 = Std_isOfType(((vdynamic*)r0),((vdynamic*)r2));
	return r1;
}

void Character_update(Character r0,double r1) {
	String r15;
	hl__types__ArrayObj r21;
	objects__ExtendableObject r16;
	bool r9;
	Object r10;
	SleepJob r18;
	hl__types__ArrayBytes_Float r11;
	vclosure *r17;
	double r2, r3, r5, r6, r7, r8;
	double *r19;
	PawnJob r20;
	vbyte *r14;
	int r12, r13;
	static vclosure cl$0 = { &t$fun_988ed22, Character_update__$1, 0 };
	r2 = r0->targetX;
	r3 = r0->x;
	r2 = r2 - r3;
	r3 = r0->targetY;
	r5 = r0->y;
	r3 = r3 - r5;
	r5 = r2 * r2;
	r6 = r3 * r3;
	r5 = r5 + r6;
	r5 = hl_math_sqrt(r5);
	r7 = r0->speed;
	r7 = r7 * r1;
	if( !(r7 < r5) ) goto label$2b8dca1_3_28;
	r6 = r0->x;
	r7 = r2 / r5;
	r8 = r0->speed;
	r7 = r7 * r8;
	r7 = r7 * r1;
	r6 = r6 + r7;
	r0->x = r6;
	r6 = r0->y;
	r7 = r3 / r5;
	r8 = r0->speed;
	r7 = r7 * r8;
	r7 = r7 * r1;
	r6 = r6 + r7;
	r0->y = r6;
	goto label$2b8dca1_3_64;
	label$2b8dca1_3_28:
	r9 = r0->isInside;
	if( !r9 ) goto label$2b8dca1_3_60;
	r10 = r0->currentObj;
	if( !r10 ) goto label$2b8dca1_3_60;
	r10 = r0->currentObj;
	if( r10 == NULL ) hl_null_access();
	r11 = r10->pos;
	if( r11 == NULL ) hl_null_access();
	r12 = 0;
	r13 = r11->length;
	if( ((unsigned)r12) < ((unsigned)r13) ) goto label$2b8dca1_3_41;
	r6 = 0.;
	goto label$2b8dca1_3_45;
	label$2b8dca1_3_41:
	r14 = r11->bytes;
	r13 = 3;
	r13 = r12 << r13;
	r6 = *(double*)(r14 + r13);
	label$2b8dca1_3_45:
	r0->targetX = r6;
	r10 = r0->currentObj;
	if( r10 == NULL ) hl_null_access();
	r11 = r10->pos;
	if( r11 == NULL ) hl_null_access();
	r12 = 1;
	r13 = r11->length;
	if( ((unsigned)r12) < ((unsigned)r13) ) goto label$2b8dca1_3_55;
	r6 = 0.;
	goto label$2b8dca1_3_59;
	label$2b8dca1_3_55:
	r14 = r11->bytes;
	r13 = 3;
	r13 = r12 << r13;
	r6 = *(double*)(r14 + r13);
	label$2b8dca1_3_59:
	r0->targetY = r6;
	label$2b8dca1_3_60:
	r6 = r0->targetX;
	r0->x = r6;
	r6 = r0->targetY;
	r0->y = r6;
	label$2b8dca1_3_64:
	r12 = 24;
	r14 = hl_alloc_bytes(r12);
	r12 = 0;
	r6 = r0->x;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r14 + r13) = r6;
	++r12;
	r6 = r0->y;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r14 + r13) = r6;
	++r12;
	r6 = 0.;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r14 + r13) = r6;
	++r12;
	r12 = 3;
	r11 = hl_types_ArrayBase_allocF64(r14,r12);
	r0->pos = r11;
	r6 = r0->o2;
	r7 = 0.0050000000000000001;
	r7 = r7 * r1;
	r6 = r6 - r7;
	r0->o2 = r6;
	r6 = r0->food;
	r7 = 0.00050000000000000001;
	r7 = r7 * r1;
	r6 = r6 - r7;
	r0->food = r6;
	r6 = r0->sleep;
	r7 = 0.0001;
	r7 = r7 * r1;
	r6 = r6 - r7;
	r0->sleep = r6;
	r6 = r0->sleep;
	r7 = 0.20000000000000001;
	if( !(r6 < r7) ) goto label$2b8dca1_3_113;
	r15 = (String)s$Sleep;
	r9 = Character_hasJobType(r0,r15);
	if( r9 ) goto label$2b8dca1_3_113;
	r17 = &cl$0;
	r16 = Character_findNearestInteractable(r0,r17);
	if( !r16 ) goto label$2b8dca1_3_113;
	r18 = (SleepJob)hl_alloc_obj(&t$SleepJob);
	r19 = NULL;
	SleepJob_new(r18,r16,r19);
	Character_enqueueJob(r0,((PawnJob)r18));
	label$2b8dca1_3_113:
	r9 = r0->isInside;
	if( !r9 ) goto label$2b8dca1_3_117;
	r6 = 1.;
	r0->o2 = r6;
	label$2b8dca1_3_117:
	r20 = r0->currentJob;
	if( r20 ) goto label$2b8dca1_3_125;
	r21 = r0->jobs;
	if( r21 == NULL ) hl_null_access();
	r12 = r21->length;
	r13 = 0;
	if( r13 >= r12 ) goto label$2b8dca1_3_125;
	Character_startNextJob(r0);
	label$2b8dca1_3_125:
	return;
}

void Character_draw(Character r0) {
	String r3, r8;
	hl__types__ArrayObj r15;
	bool r2;
	objects__Item r17;
	double r4;
	int *r6;
	PawnJob r13;
	vbyte *r7;
	int r5, r9, r10, r11, r12, r14, r16, r18;
	r2 = r0->selected;
	if( !r2 ) goto label$2b8dca1_4_74;
	r3 = (String)s$O2_;
	r4 = r0->o2;
	r6 = &r5;
	r7 = hl_ftos(r4,r6);
	r8 = String___alloc__(r7,r5);
	r3 = String___add__(r3,r8);
	r5 = 500;
	r9 = 118;
	r10 = 3023651;
	r6 = &r10;
	util_FontManager_drawText(r3,r5,r9,r6);
	r3 = (String)s$Food_;
	r4 = r0->food;
	r6 = &r5;
	r7 = hl_ftos(r4,r6);
	r8 = String___alloc__(r7,r5);
	r3 = String___add__(r3,r8);
	r5 = 500;
	r9 = 100;
	r11 = 2432799;
	r6 = &r11;
	util_FontManager_drawText(r3,r5,r9,r6);
	r3 = (String)s$8c9db0a;
	r4 = r0->sleep;
	r6 = &r5;
	r7 = hl_ftos(r4,r6);
	r8 = String___alloc__(r7,r5);
	r3 = String___add__(r3,r8);
	r5 = 500;
	r9 = 82;
	r12 = 2432799;
	r6 = &r12;
	util_FontManager_drawText(r3,r5,r9,r6);
	r3 = (String)s$Job_;
	r13 = r0->currentJob;
	if( !r13 ) goto label$2b8dca1_4_42;
	r13 = r0->currentJob;
	if( r13 == NULL ) hl_null_access();
	r8 = r13->label;
	goto label$2b8dca1_4_43;
	label$2b8dca1_4_42:
	r8 = (String)s$Idle;
	label$2b8dca1_4_43:
	r3 = String___add__(r3,r8);
	r5 = 500;
	r9 = 64;
	r14 = 2432799;
	r6 = &r14;
	util_FontManager_drawText(r3,r5,r9,r6);
	r3 = (String)s$Queue_;
	r15 = r0->jobs;
	if( r15 == NULL ) hl_null_access();
	r5 = r15->length;
	r6 = &r5;
	r7 = hl_itos(r5,r6);
	r8 = String___alloc__(r7,r5);
	r3 = String___add__(r3,r8);
	r5 = 500;
	r9 = 46;
	r16 = 2432799;
	r6 = &r16;
	util_FontManager_drawText(r3,r5,r9,r6);
	r17 = r0->carriedItem;
	if( !r17 ) goto label$2b8dca1_4_74;
	r3 = (String)s$Carry_;
	r17 = r0->carriedItem;
	if( r17 == NULL ) hl_null_access();
	r8 = r17->name;
	r3 = String___add__(r3,r8);
	r5 = 500;
	r9 = 28;
	r18 = 2432799;
	r6 = &r18;
	util_FontManager_drawText(r3,r5,r9,r6);
	label$2b8dca1_4_74:
	Object_draw(((Object)r0));
	return;
}

bool Character_hasJobType(Character r0,String r1) {
	String r3;
	hl__types__ArrayObj r6, r10;
	hl_type *r8;
	bool r4;
	vdynamic *r5;
	int r9, r11, r12;
	varray *r7;
	PawnJob r2;
	r2 = r0->currentJob;
	if( !r2 ) goto label$2b8dca1_5_8;
	r2 = r0->currentJob;
	if( r2 == NULL ) hl_null_access();
	r3 = r2->label;
	if( r3 != r1 && (!r3 || !r1 || String___compare(r3,(vdynamic*)r1) != 0) ) goto label$2b8dca1_5_8;
	r4 = true;
	return r4;
	label$2b8dca1_5_8:
	r8 = &t$PawnJob;
	r9 = 0;
	r7 = hl_alloc_array(r8,r9);
	r6 = hl_types_ArrayObj_alloc(r7);
	r9 = 0;
	r10 = r0->jobs;
	label$2b8dca1_5_14:
	if( r10 == NULL ) hl_null_access();
	r12 = r10->length;
	if( r9 >= r12 ) goto label$2b8dca1_5_32;
	r12 = r10->length;
	if( ((unsigned)r9) < ((unsigned)r12) ) goto label$2b8dca1_5_22;
	r2 = NULL;
	goto label$2b8dca1_5_25;
	label$2b8dca1_5_22:
	r7 = r10->array;
	r5 = ((vdynamic**)(r7 + 1))[r9];
	r2 = (PawnJob)r5;
	label$2b8dca1_5_25:
	++r9;
	if( r2 == NULL ) hl_null_access();
	r3 = r2->label;
	if( r3 != r1 && (!r3 || !r1 || String___compare(r3,(vdynamic*)r1) != 0) ) goto label$2b8dca1_5_31;
	if( r6 == NULL ) hl_null_access();
	r11 = hl_types_ArrayObj_push(r6,((vdynamic*)r2));
	label$2b8dca1_5_31:
	goto label$2b8dca1_5_14;
	label$2b8dca1_5_32:
	if( r6 == NULL ) hl_null_access();
	r9 = r6->length;
	r11 = 0;
	if( r9 > r11 ) goto label$2b8dca1_5_38;
	r4 = false;
	goto label$2b8dca1_5_39;
	label$2b8dca1_5_38:
	r4 = true;
	label$2b8dca1_5_39:
	return r4;
}

void Character_clearJobs(Character r0) {
	hl__types__ArrayObj r1;
	hl_type *r3;
	PawnJob r5;
	int r4;
	varray *r2;
	r3 = &t$PawnJob;
	r4 = 0;
	r2 = hl_alloc_array(r3,r4);
	r1 = hl_types_ArrayObj_alloc(r2);
	r0->jobs = r1;
	r5 = NULL;
	r0->currentJob = r5;
	r4 = r0->jobVersion;
	++r4;
	r0->jobVersion = r4;
	r4 = r0->moveRequestId;
	++r4;
	r0->moveRequestId = r4;
	return;
}

void Character_enqueueJob(Character r0,PawnJob r1) {
	hl__types__ArrayObj r3;
	PawnJob r4;
	int r2;
	r3 = r0->jobs;
	if( r3 == NULL ) hl_null_access();
	r2 = hl_types_ArrayObj_push(r3,((vdynamic*)r1));
	r4 = r0->currentJob;
	if( r4 ) goto label$2b8dca1_7_6;
	Character_startNextJob(r0);
	label$2b8dca1_7_6:
	return;
}

void Character_setSingleJob(Character r0,PawnJob r1) {
	Character_clearJobs(r0);
	Character_enqueueJob(r0,r1);
	return;
}

void Character_startNextJob__$1(venum* r0) {
	Character r4;
	PawnJob r5;
	int r2, r3;
	r2 = ((Enumt$ctx_2089d06*)r0)->p0;
	r4 = ((Enumt$ctx_2089d06*)r0)->p1;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->jobVersion;
	if( r2 == r3 ) goto label$2b8dca1_9_6;
	return;
	label$2b8dca1_9_6:
	r4 = ((Enumt$ctx_2089d06*)r0)->p1;
	if( r4 == NULL ) hl_null_access();
	r5 = NULL;
	r4->currentJob = r5;
	r4 = ((Enumt$ctx_2089d06*)r0)->p1;
	if( r4 == NULL ) hl_null_access();
	Character_startNextJob(r4);
	return;
}

void Character_startNextJob(Character r0) {
	hl__types__ArrayObj r3;
	venum *r8;
	vclosure *r7;
	vdynamic *r6;
	PawnJob r5;
	int r2, r4;
	r3 = r0->jobs;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	r4 = 0;
	if( r2 != r4 ) goto label$2b8dca1_10_8;
	r5 = NULL;
	r0->currentJob = r5;
	return;
	label$2b8dca1_10_8:
	r3 = r0->jobs;
	if( r3 == NULL ) hl_null_access();
	r6 = hl_types_ArrayObj_shift(r3);
	r5 = (PawnJob)r6;
	r0->currentJob = r5;
	r2 = r0->jobVersion;
	r5 = r0->currentJob;
	if( r5 == NULL ) hl_null_access();
	r8 = hl_alloc_enum(&t$ctx_2089d06,0);
	((Enumt$ctx_2089d06*)r8)->p0 = (int)r2;
	((Enumt$ctx_2089d06*)r8)->p1 = (Character)r0;
	r7 = hl_alloc_closure_ptr(&t$fun_5a8fccd,Character_startNextJob__$1,r8);
	((void (*)(PawnJob,Character,vclosure*))r5->$type->vobj_proto[0])(r5,r0,r7);
	return;
}

objects__ExtendableObject Character_findNearestInteractable(Character r0,vclosure* r1) {
	$Game r7;
	hl__types__ArrayObj r5;
	objects__ExtendableObject r2, r10;
	bool r13;
	hl__types__ArrayBytes_Float r14, r15;
	objects__ExtendableManager r6;
	double r3, r16, r18, r19, r20;
	vdynamic *r11;
	vbyte *r17;
	varray *r12;
	int r4, r8, r9;
	r2 = NULL;
	r3 = 1000000000.;
	r4 = 0;
	r7 = ($Game)g$_Game;
	r6 = r7->currentShip;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->objects;
	label$2b8dca1_11_7:
	if( r5 == NULL ) hl_null_access();
	r9 = r5->length;
	if( r4 >= r9 ) goto label$2b8dca1_11_74;
	r9 = r5->length;
	if( ((unsigned)r4) < ((unsigned)r9) ) goto label$2b8dca1_11_15;
	r10 = NULL;
	goto label$2b8dca1_11_18;
	label$2b8dca1_11_15:
	r12 = r5->array;
	r11 = ((vdynamic**)(r12 + 1))[r4];
	r10 = (objects__ExtendableObject)r11;
	label$2b8dca1_11_18:
	++r4;
	if( r1 == NULL ) hl_null_access();
	r13 = r1->hasValue ? ((bool (*)(vdynamic*,objects__ExtendableObject))r1->fun)((vdynamic*)r1->value,r10) : ((bool (*)(objects__ExtendableObject))r1->fun)(r10);
	if( r13 ) goto label$2b8dca1_11_23;
	goto label$2b8dca1_11_7;
	label$2b8dca1_11_23:
	r14 = r0->pos;
	if( r10 == NULL ) hl_null_access();
	r15 = r10->pos;
	if( r14 == NULL ) hl_null_access();
	r8 = 0;
	r9 = r14->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$2b8dca1_11_32;
	r16 = 0.;
	goto label$2b8dca1_11_36;
	label$2b8dca1_11_32:
	r17 = r14->bytes;
	r9 = 3;
	r9 = r8 << r9;
	r16 = *(double*)(r17 + r9);
	label$2b8dca1_11_36:
	if( r15 == NULL ) hl_null_access();
	r8 = 0;
	r9 = r15->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$2b8dca1_11_42;
	r18 = 0.;
	goto label$2b8dca1_11_46;
	label$2b8dca1_11_42:
	r17 = r15->bytes;
	r9 = 3;
	r9 = r8 << r9;
	r18 = *(double*)(r17 + r9);
	label$2b8dca1_11_46:
	r16 = r16 - r18;
	r8 = 1;
	r9 = r14->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$2b8dca1_11_52;
	r18 = 0.;
	goto label$2b8dca1_11_56;
	label$2b8dca1_11_52:
	r17 = r14->bytes;
	r9 = 3;
	r9 = r8 << r9;
	r18 = *(double*)(r17 + r9);
	label$2b8dca1_11_56:
	r8 = 1;
	r9 = r15->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$2b8dca1_11_61;
	r19 = 0.;
	goto label$2b8dca1_11_65;
	label$2b8dca1_11_61:
	r17 = r15->bytes;
	r9 = 3;
	r9 = r8 << r9;
	r19 = *(double*)(r17 + r9);
	label$2b8dca1_11_65:
	r18 = r18 - r19;
	r19 = r16 * r16;
	r20 = r18 * r18;
	r19 = r19 + r20;
	r19 = hl_math_sqrt(r19);
	if( !(r19 < r3) ) goto label$2b8dca1_11_73;
	r2 = r10;
	r3 = r19;
	label$2b8dca1_11_73:
	goto label$2b8dca1_11_7;
	label$2b8dca1_11_74:
	return r2;
}

vclosure* Character_setTarget__$1(venum* r0,hl__types__ArrayBytes_Float r1) {
	Character r5;
	venum *r3;
	vclosure *r2;
	int r4;
	r3 = hl_alloc_enum(&t$ctx_041753c,0);
	r4 = ((Enumt$ctx_2089d06*)r0)->p0;
	((Enumt$ctx_041753c*)r3)->p0 = (int)r4;
	((Enumt$ctx_041753c*)r3)->p1 = (hl__types__ArrayBytes_Float)r1;
	r5 = ((Enumt$ctx_2089d06*)r0)->p1;
	((Enumt$ctx_041753c*)r3)->p2 = (Character)r5;
	r2 = hl_alloc_closure_ptr(&t$fun_87f9032,Character_setTarget__$2,r3);
	return r2;
}

void Character_setTarget__$3(venum* r0,double r1) {
	bool *r28;
	String r21, r23;
	vvirtual *r24, *r30;
	hl__types__ArrayObj r6;
	Character r5;
	hl_type *r26;
	bool r27;
	haxe__$Log r20;
	hl__types__ArrayBytes_Float r10;
	hl__types__ArrayDyn r25;
	double r11, r12, r13, r14, r16, r17, r18;
	vclosure *r7, *r19, *r29;
	int *r22;
	vdynamic *r8;
	vbyte *r15;
	varray *r9;
	int r3, r4;
	r3 = ((Enumt$ctx_cbf3c7f*)r0)->p0;
	r5 = ((Enumt$ctx_cbf3c7f*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->moveRequestId;
	if( r3 == r4 ) goto label$2b8dca1_13_17;
	r6 = ((Enumt$ctx_cbf3c7f*)r0)->p3;
	if( r6 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r6->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$2b8dca1_13_12;
	r7 = NULL;
	goto label$2b8dca1_13_15;
	label$2b8dca1_13_12:
	r9 = r6->array;
	r8 = ((vdynamic**)(r9 + 1))[r3];
	r7 = (vclosure*)r8;
	label$2b8dca1_13_15:
	r6 = Eight_unregisterUpdateCallback(r7);
	return;
	label$2b8dca1_13_17:
	r5 = ((Enumt$ctx_cbf3c7f*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r10 = r5->pos;
	r5 = ((Enumt$ctx_cbf3c7f*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r11 = r5->targetX;
	r5 = ((Enumt$ctx_cbf3c7f*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r12 = r5->targetY;
	r13 = 0.;
	if( r10 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r10->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$2b8dca1_13_33;
	r14 = 0.;
	goto label$2b8dca1_13_37;
	label$2b8dca1_13_33:
	r15 = r10->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r14 = *(double*)(r15 + r4);
	label$2b8dca1_13_37:
	r14 = r14 - r11;
	r3 = 1;
	r4 = r10->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$2b8dca1_13_43;
	r16 = 0.;
	goto label$2b8dca1_13_47;
	label$2b8dca1_13_43:
	r15 = r10->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r16 = *(double*)(r15 + r4);
	label$2b8dca1_13_47:
	r16 = r16 - r12;
	r17 = r14 * r14;
	r18 = r16 * r16;
	r17 = r17 + r18;
	r17 = hl_math_sqrt(r17);
	r18 = 1.;
	if( !(r17 < r18) ) goto label$2b8dca1_13_105;
	r20 = (haxe__$Log)g$_haxe_Log;
	r19 = r20->trace;
	if( r19 == NULL ) hl_null_access();
	r21 = (String)s$Approached_;
	r5 = ((Enumt$ctx_cbf3c7f*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r17 = r5->targetX;
	r22 = &r3;
	r15 = hl_ftos(r17,r22);
	r23 = String___alloc__(r15,r3);
	r21 = String___add__(r21,r23);
	r24 = hl_alloc_virtual(&t$vrt_eaa6a3b);
	r23 = (String)s$Character_hx;
	if( hl_vfields(r24)[2] ) *(String*)(hl_vfields(r24)[2]) = (String)r23; else hl_dyn_setp(r24->value,37969014/*fileName*/,&t$String,r23);
	r3 = 305;
	if( hl_vfields(r24)[3] ) *(int*)(hl_vfields(r24)[3]) = (int)r3; else hl_dyn_seti(r24->value,371360620/*lineNumber*/,&t$_i32,r3);
	r23 = (String)s$Character;
	if( hl_vfields(r24)[0] ) *(String*)(hl_vfields(r24)[0]) = (String)r23; else hl_dyn_setp(r24->value,-63073762/*className*/,&t$String,r23);
	r23 = (String)s$setTarget;
	if( hl_vfields(r24)[4] ) *(String*)(hl_vfields(r24)[4]) = (String)r23; else hl_dyn_setp(r24->value,302979532/*methodName*/,&t$String,r23);
	r26 = &t$_dyn;
	r3 = 1;
	r9 = hl_alloc_array(r26,r3);
	r5 = ((Enumt$ctx_cbf3c7f*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r17 = r5->targetY;
	r8 = hl_alloc_dynamic(&t$_f64);
	r8->v.d = r17;
	r3 = 0;
	((vdynamic**)(r9 + 1))[r3] = r8;
	r6 = hl_types_ArrayObj_alloc(r9);
	r27 = true;
	r28 = &r27;
	r25 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r6),r28);
	if( hl_vfields(r24)[1] ) *(hl__types__ArrayDyn*)(hl_vfields(r24)[1]) = (hl__types__ArrayDyn)r25; else hl_dyn_setp(r24->value,-317173289/*customParams*/,&t$hl_types_ArrayDyn,r25);
	r19->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r19->fun)((vdynamic*)r19->value,((vdynamic*)r21),r24) : ((void (*)(vdynamic*,vvirtual*))r19->fun)(((vdynamic*)r21),r24);
	r6 = ((Enumt$ctx_cbf3c7f*)r0)->p3;
	if( r6 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r6->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$2b8dca1_13_96;
	r7 = NULL;
	goto label$2b8dca1_13_99;
	label$2b8dca1_13_96:
	r9 = r6->array;
	r8 = ((vdynamic**)(r9 + 1))[r3];
	r7 = (vclosure*)r8;
	label$2b8dca1_13_99:
	r6 = Eight_unregisterUpdateCallback(r7);
	r30 = ((Enumt$ctx_cbf3c7f*)r0)->p1;
	if( r30 == NULL ) hl_null_access();
	r29 = hl_vfields(r30)[0] ? (*(vclosure**)(hl_vfields(r30)[0])) : (vclosure*)hl_dyn_getp(r30->value,151160317/*next*/,&t$fun_7b48b4f);
	if( r29 == NULL ) hl_null_access();
	r29->hasValue ? ((void (*)(vdynamic*))r29->fun)((vdynamic*)r29->value) : ((void (*)(void))r29->fun)();
	label$2b8dca1_13_105:
	return;
}

void Character_setTarget__$2(venum* r0,vvirtual* r1) {
	bool *r21;
	String r12, r14;
	hl__types__ArrayObj r19;
	vvirtual *r15;
	Character r5;
	venum *r23;
	hl_type *r18;
	bool r20;
	haxe__$Log r11;
	hl__types__ArrayBytes_Float r7;
	hl__types__ArrayDyn r16;
	vclosure *r10, *r22;
	double r8;
	int *r13;
	vdynamic *r6;
	varray *r17;
	vbyte *r9;
	int r3, r4;
	r3 = ((Enumt$ctx_041753c*)r0)->p0;
	r5 = ((Enumt$ctx_041753c*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->moveRequestId;
	if( r3 == r4 ) goto label$2b8dca1_14_6;
	return;
	label$2b8dca1_14_6:
	r5 = ((Enumt$ctx_041753c*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r7 = ((Enumt$ctx_041753c*)r0)->p1;
	if( r7 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r7->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$2b8dca1_14_15;
	r8 = 0.;
	goto label$2b8dca1_14_19;
	label$2b8dca1_14_15:
	r9 = r7->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r8 = *(double*)(r9 + r4);
	label$2b8dca1_14_19:
	r5->targetX = r8;
	r5 = ((Enumt$ctx_041753c*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r7 = ((Enumt$ctx_041753c*)r0)->p1;
	if( r7 == NULL ) hl_null_access();
	r3 = 1;
	r4 = r7->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$2b8dca1_14_29;
	r8 = 0.;
	goto label$2b8dca1_14_33;
	label$2b8dca1_14_29:
	r9 = r7->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r8 = *(double*)(r9 + r4);
	label$2b8dca1_14_33:
	r5->targetY = r8;
	r11 = (haxe__$Log)g$_haxe_Log;
	r10 = r11->trace;
	if( r10 == NULL ) hl_null_access();
	r12 = (String)s$Moving_character_to_;
	r5 = ((Enumt$ctx_041753c*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r8 = r5->targetX;
	r13 = &r3;
	r9 = hl_ftos(r8,r13);
	r14 = String___alloc__(r9,r3);
	r12 = String___add__(r12,r14);
	r15 = hl_alloc_virtual(&t$vrt_eaa6a3b);
	r14 = (String)s$Character_hx;
	if( hl_vfields(r15)[2] ) *(String*)(hl_vfields(r15)[2]) = (String)r14; else hl_dyn_setp(r15->value,37969014/*fileName*/,&t$String,r14);
	r3 = 296;
	if( hl_vfields(r15)[3] ) *(int*)(hl_vfields(r15)[3]) = (int)r3; else hl_dyn_seti(r15->value,371360620/*lineNumber*/,&t$_i32,r3);
	r14 = (String)s$Character;
	if( hl_vfields(r15)[0] ) *(String*)(hl_vfields(r15)[0]) = (String)r14; else hl_dyn_setp(r15->value,-63073762/*className*/,&t$String,r14);
	r14 = (String)s$setTarget;
	if( hl_vfields(r15)[4] ) *(String*)(hl_vfields(r15)[4]) = (String)r14; else hl_dyn_setp(r15->value,302979532/*methodName*/,&t$String,r14);
	r18 = &t$_dyn;
	r3 = 1;
	r17 = hl_alloc_array(r18,r3);
	r5 = ((Enumt$ctx_041753c*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r8 = r5->targetY;
	r6 = hl_alloc_dynamic(&t$_f64);
	r6->v.d = r8;
	r3 = 0;
	((vdynamic**)(r17 + 1))[r3] = r6;
	r19 = hl_types_ArrayObj_alloc(r17);
	r20 = true;
	r21 = &r20;
	r16 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r19),r21);
	if( hl_vfields(r15)[1] ) *(hl__types__ArrayDyn*)(hl_vfields(r15)[1]) = (hl__types__ArrayDyn)r16; else hl_dyn_setp(r15->value,-317173289/*customParams*/,&t$hl_types_ArrayDyn,r16);
	r10->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r10->fun)((vdynamic*)r10->value,((vdynamic*)r12),r15) : ((void (*)(vdynamic*,vvirtual*))r10->fun)(((vdynamic*)r12),r15);
	r18 = &t$fun_0a89fd7;
	r3 = 1;
	r17 = hl_alloc_array(r18,r3);
	r22 = NULL;
	r3 = 0;
	((vclosure**)(r17 + 1))[r3] = r22;
	r19 = hl_types_ArrayObj_alloc(r17);
	if( r19 == NULL ) hl_null_access();
	r3 = 0;
	r23 = hl_alloc_enum(&t$ctx_cbf3c7f,0);
	r4 = ((Enumt$ctx_041753c*)r0)->p0;
	((Enumt$ctx_cbf3c7f*)r23)->p0 = (int)r4;
	((Enumt$ctx_cbf3c7f*)r23)->p1 = (vvirtual*)r1;
	r5 = ((Enumt$ctx_041753c*)r0)->p2;
	((Enumt$ctx_cbf3c7f*)r23)->p2 = (Character)r5;
	((Enumt$ctx_cbf3c7f*)r23)->p3 = (hl__types__ArrayObj)r19;
	r22 = hl_alloc_closure_ptr(&t$fun_077f60c,Character_setTarget__$3,r23);
	r4 = r19->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$2b8dca1_14_89;
	hl_types_ArrayObj___expand(r19,r3);
	label$2b8dca1_14_89:
	r17 = r19->array;
	((vclosure**)(r17 + 1))[r3] = r22;
	r3 = 0;
	r4 = r19->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$2b8dca1_14_96;
	r22 = NULL;
	goto label$2b8dca1_14_99;
	label$2b8dca1_14_96:
	r17 = r19->array;
	r6 = ((vdynamic**)(r17 + 1))[r3];
	r22 = (vclosure*)r6;
	label$2b8dca1_14_99:
	Eight_registerUpdateCallback(r22);
	return;
}

int Character_setTarget__$4(Character r0,Object r1,Object r2) {
	hl__types__ArrayBytes_Float r3, r4, r6, r14;
	double r5, r10, r11, r12, r13, r15, r16;
	vbyte *r9;
	int r7, r8;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->pos;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->pos;
	if( r3 == NULL ) hl_null_access();
	r7 = 0;
	r8 = r3->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$2b8dca1_15_10;
	r5 = 0.;
	goto label$2b8dca1_15_14;
	label$2b8dca1_15_10:
	r9 = r3->bytes;
	r8 = 3;
	r8 = r7 << r8;
	r5 = *(double*)(r9 + r8);
	label$2b8dca1_15_14:
	if( r4 == NULL ) hl_null_access();
	r7 = 0;
	r8 = r4->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$2b8dca1_15_20;
	r10 = 0.;
	goto label$2b8dca1_15_24;
	label$2b8dca1_15_20:
	r9 = r4->bytes;
	r8 = 3;
	r8 = r7 << r8;
	r10 = *(double*)(r9 + r8);
	label$2b8dca1_15_24:
	r5 = r5 - r10;
	r7 = 1;
	r8 = r3->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$2b8dca1_15_30;
	r10 = 0.;
	goto label$2b8dca1_15_34;
	label$2b8dca1_15_30:
	r9 = r3->bytes;
	r8 = 3;
	r8 = r7 << r8;
	r10 = *(double*)(r9 + r8);
	label$2b8dca1_15_34:
	r7 = 1;
	r8 = r4->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$2b8dca1_15_39;
	r11 = 0.;
	goto label$2b8dca1_15_43;
	label$2b8dca1_15_39:
	r9 = r4->bytes;
	r8 = 3;
	r8 = r7 << r8;
	r11 = *(double*)(r9 + r8);
	label$2b8dca1_15_43:
	r10 = r10 - r11;
	r11 = r5 * r5;
	r12 = r10 * r10;
	r11 = r11 + r12;
	r11 = hl_math_sqrt(r11);
	r6 = r0->pos;
	if( r2 == NULL ) hl_null_access();
	r14 = r2->pos;
	if( r6 == NULL ) hl_null_access();
	r7 = 0;
	r8 = r6->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$2b8dca1_15_57;
	r12 = 0.;
	goto label$2b8dca1_15_61;
	label$2b8dca1_15_57:
	r9 = r6->bytes;
	r8 = 3;
	r8 = r7 << r8;
	r12 = *(double*)(r9 + r8);
	label$2b8dca1_15_61:
	if( r14 == NULL ) hl_null_access();
	r7 = 0;
	r8 = r14->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$2b8dca1_15_67;
	r13 = 0.;
	goto label$2b8dca1_15_71;
	label$2b8dca1_15_67:
	r9 = r14->bytes;
	r8 = 3;
	r8 = r7 << r8;
	r13 = *(double*)(r9 + r8);
	label$2b8dca1_15_71:
	r12 = r12 - r13;
	r7 = 1;
	r8 = r6->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$2b8dca1_15_77;
	r13 = 0.;
	goto label$2b8dca1_15_81;
	label$2b8dca1_15_77:
	r9 = r6->bytes;
	r8 = 3;
	r8 = r7 << r8;
	r13 = *(double*)(r9 + r8);
	label$2b8dca1_15_81:
	r7 = 1;
	r8 = r14->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$2b8dca1_15_86;
	r15 = 0.;
	goto label$2b8dca1_15_90;
	label$2b8dca1_15_86:
	r9 = r14->bytes;
	r8 = 3;
	r8 = r7 << r8;
	r15 = *(double*)(r9 + r8);
	label$2b8dca1_15_90:
	r13 = r13 - r15;
	r15 = r12 * r12;
	r16 = r13 * r13;
	r15 = r15 + r16;
	r15 = hl_math_sqrt(r15);
	if( !(r11 < r15) ) goto label$2b8dca1_15_98;
	r7 = -1;
	return r7;
	label$2b8dca1_15_98:
	if( !(r15 < r11) ) goto label$2b8dca1_15_101;
	r7 = 1;
	return r7;
	label$2b8dca1_15_101:
	r7 = 0;
	return r7;
}

bool Character_setTarget__$6(Object r0) {
	bool r1;
	objects__$Door r2;
	r2 = (objects__$Door)g$_objects_Door;
	r1 = Std_isOfType(((vdynamic*)r0),((vdynamic*)r2));
	return r1;
}

bool Character_setTarget__$7(Object r0) {
	bool r1;
	r1 = true;
	return r1;
}

void Character_setTarget__$8(venum* r0,util__Sequence r1) {
	vdynobj *r9;
	String r8, r10;
	vvirtual *r11;
	Character r5;
	bool r12;
	haxe__$Log r7;
	Object r13;
	vclosure *r6, *r14;
	int r3, r4;
	r3 = ((Enumt$ctx_48573a3*)r0)->p1;
	r5 = ((Enumt$ctx_48573a3*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->moveRequestId;
	if( r3 == r4 ) goto label$2b8dca1_18_6;
	return;
	label$2b8dca1_18_6:
	r7 = (haxe__$Log)g$_haxe_Log;
	r6 = r7->trace;
	if( r6 == NULL ) hl_null_access();
	r8 = (String)s$Inside_;
	r9 = hl_alloc_dynobj();
	r10 = (String)s$Character_hx;
	hl_dyn_setp((vdynamic*)r9,37969014/*fileName*/,&t$String,r10);
	r3 = 332;
	hl_dyn_seti((vdynamic*)r9,371360620/*lineNumber*/,&t$_i32,r3);
	r10 = (String)s$Character;
	hl_dyn_setp((vdynamic*)r9,-63073762/*className*/,&t$String,r10);
	r10 = (String)s$setTarget;
	hl_dyn_setp((vdynamic*)r9,302979532/*methodName*/,&t$String,r10);
	r11 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r9);
	r6->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r6->fun)((vdynamic*)r6->value,((vdynamic*)r8),r11) : ((void (*)(vdynamic*,vvirtual*))r6->fun)(((vdynamic*)r8),r11);
	r5 = ((Enumt$ctx_48573a3*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r12 = true;
	r5->isInside = r12;
	r5 = ((Enumt$ctx_48573a3*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r13 = ((Enumt$ctx_48573a3*)r0)->p3;
	r5->currentObj = r13;
	r14 = ((Enumt$ctx_48573a3*)r0)->p0;
	if( !r14 ) goto label$2b8dca1_18_34;
	r14 = ((Enumt$ctx_48573a3*)r0)->p0;
	if( r14 == NULL ) hl_null_access();
	r14->hasValue ? ((void (*)(vdynamic*))r14->fun)((vdynamic*)r14->value) : ((void (*)(void))r14->fun)();
	label$2b8dca1_18_34:
	if( r1 == NULL ) hl_null_access();
	util_Sequence_next(r1);
	return;
}

void Character_setTarget__$9(venum* r0,util__Sequence r1) {
	Character r5;
	bool r6;
	Object r7;
	vclosure *r8;
	int r3, r4;
	r3 = ((Enumt$ctx_521e260*)r0)->p1;
	r5 = ((Enumt$ctx_521e260*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->moveRequestId;
	if( r3 == r4 ) goto label$2b8dca1_19_6;
	return;
	label$2b8dca1_19_6:
	r5 = ((Enumt$ctx_521e260*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r6 = false;
	r5->isInside = r6;
	r5 = ((Enumt$ctx_521e260*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r7 = NULL;
	r5->currentObj = r7;
	r8 = ((Enumt$ctx_521e260*)r0)->p0;
	if( !r8 ) goto label$2b8dca1_19_19;
	r8 = ((Enumt$ctx_521e260*)r0)->p0;
	if( r8 == NULL ) hl_null_access();
	r8->hasValue ? ((void (*)(vdynamic*))r8->fun)((vdynamic*)r8->value) : ((void (*)(void))r8->fun)();
	label$2b8dca1_19_19:
	if( r1 == NULL ) hl_null_access();
	util_Sequence_next(r1);
	return;
}

void Character_setTarget__$10(venum* r0,util__Sequence r1) {
	Character r5;
	Object r6;
	hl__types__ArrayBytes_Float r7;
	vclosure *r10;
	double r8;
	vbyte *r9;
	int r3, r4;
	r3 = ((Enumt$ctx_48573a3*)r0)->p1;
	r5 = ((Enumt$ctx_48573a3*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->moveRequestId;
	if( r3 == r4 ) goto label$2b8dca1_20_6;
	return;
	label$2b8dca1_20_6:
	r5 = ((Enumt$ctx_48573a3*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r6 = ((Enumt$ctx_48573a3*)r0)->p3;
	r5->currentObj = r6;
	r5 = ((Enumt$ctx_48573a3*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r6 = ((Enumt$ctx_48573a3*)r0)->p3;
	if( r6 == NULL ) hl_null_access();
	r7 = r6->pos;
	if( r7 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r7->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$2b8dca1_20_21;
	r8 = 0.;
	goto label$2b8dca1_20_25;
	label$2b8dca1_20_21:
	r9 = r7->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r8 = *(double*)(r9 + r4);
	label$2b8dca1_20_25:
	r5->targetX = r8;
	r5 = ((Enumt$ctx_48573a3*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r6 = ((Enumt$ctx_48573a3*)r0)->p3;
	if( r6 == NULL ) hl_null_access();
	r7 = r6->pos;
	if( r7 == NULL ) hl_null_access();
	r3 = 1;
	r4 = r7->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$2b8dca1_20_37;
	r8 = 0.;
	goto label$2b8dca1_20_41;
	label$2b8dca1_20_37:
	r9 = r7->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r8 = *(double*)(r9 + r4);
	label$2b8dca1_20_41:
	r5->targetY = r8;
	r10 = ((Enumt$ctx_48573a3*)r0)->p0;
	if( !r10 ) goto label$2b8dca1_20_47;
	r10 = ((Enumt$ctx_48573a3*)r0)->p0;
	if( r10 == NULL ) hl_null_access();
	r10->hasValue ? ((void (*)(vdynamic*))r10->fun)((vdynamic*)r10->value) : ((void (*)(void))r10->fun)();
	label$2b8dca1_20_47:
	if( r1 == NULL ) hl_null_access();
	util_Sequence_next(r1);
	return;
}

void Character_setTarget__$11(venum* r0,util__Sequence r1) {
	Character r5;
	vclosure *r6;
	int r3, r4;
	r3 = ((Enumt$ctx_521e260*)r0)->p1;
	r5 = ((Enumt$ctx_521e260*)r0)->p2;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->moveRequestId;
	if( r3 == r4 ) goto label$2b8dca1_21_6;
	return;
	label$2b8dca1_21_6:
	r6 = ((Enumt$ctx_521e260*)r0)->p0;
	if( !r6 ) goto label$2b8dca1_21_11;
	r6 = ((Enumt$ctx_521e260*)r0)->p0;
	if( r6 == NULL ) hl_null_access();
	r6->hasValue ? ((void (*)(vdynamic*))r6->fun)((vdynamic*)r6->value) : ((void (*)(void))r6->fun)();
	label$2b8dca1_21_11:
	if( r1 == NULL ) hl_null_access();
	util_Sequence_next(r1);
	return;
}

void Character_setTarget(Character r0,hl__types__ArrayBytes_Float r1,vclosure* r2) {
	$Game r22;
	vdynobj *r18;
	String r17, r19;
	$Eight r9;
	vvirtual *r20;
	hl__types__ArrayObj r8;
	venum *r7, *r31, *r32;
	bool r24, r26;
	haxe__$Log r16;
	util__Sequence r27;
	Object r12, r14;
	hl__types__ArrayBytes_Float r29;
	double r21, r23;
	vclosure *r6, *r10, *r11, *r13, *r15, *r28, *r30;
	objects__$Hull r25;
	int r4, r5;
	static vclosure cl$0 = { &t$fun_4bb4509, Character_setTarget__$6, 0 };
	static vclosure cl$1 = { &t$fun_4bb4509, Character_setTarget__$7, 0 };
	r4 = r0->moveRequestId;
	++r4;
	r0->moveRequestId = r4;
	r4 = r0->moveRequestId;
	r7 = hl_alloc_enum(&t$ctx_2089d06,0);
	((Enumt$ctx_2089d06*)r7)->p0 = (int)r4;
	((Enumt$ctx_2089d06*)r7)->p1 = (Character)r0;
	r6 = hl_alloc_closure_ptr(&t$fun_efbe4b1,Character_setTarget__$1,r7);
	r9 = ($Eight)g$_Eight;
	r8 = r9->objects;
	if( r8 == NULL ) hl_null_access();
	r8 = hl_types_ArrayObj_copy(r8);
	if( r8 == NULL ) hl_null_access();
	r10 = hl_alloc_closure_ptr(&t$fun_c6993f3,Character_setTarget__$4,r0);
	if( r10 ) goto label$2b8dca1_22_17;
	r11 = NULL;
	goto label$2b8dca1_22_18;
	label$2b8dca1_22_17:
	r11 = hl_alloc_closure_ptr(&t$fun_41f671f,Character_setTarget__$5,r10);
	label$2b8dca1_22_18:
	hl_types_ArrayObj_sort(r8,r11);
	hl_types_ArrayObj_reverse(r8);
	r13 = &cl$0;
	r12 = Game_findObject(r8,r13);
	if( r12 ) goto label$2b8dca1_22_39;
	r16 = (haxe__$Log)g$_haxe_Log;
	r15 = r16->trace;
	if( r15 == NULL ) hl_null_access();
	r17 = (String)s$Null_errror_;
	r18 = hl_alloc_dynobj();
	r19 = (String)s$Character_hx;
	hl_dyn_setp((vdynamic*)r18,37969014/*fileName*/,&t$String,r19);
	r5 = 322;
	hl_dyn_seti((vdynamic*)r18,371360620/*lineNumber*/,&t$_i32,r5);
	r19 = (String)s$Character;
	hl_dyn_setp((vdynamic*)r18,-63073762/*className*/,&t$String,r19);
	r19 = (String)s$setTarget;
	hl_dyn_setp((vdynamic*)r18,302979532/*methodName*/,&t$String,r19);
	r20 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r18);
	r15->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r15->fun)((vdynamic*)r15->value,((vdynamic*)r17),r20) : ((void (*)(vdynamic*,vvirtual*))r15->fun)(((vdynamic*)r17),r20);
	return;
	label$2b8dca1_22_39:
	r22 = ($Game)g$_Game;
	r21 = r22->mx;
	r22 = ($Game)g$_Game;
	r23 = r22->my;
	r13 = &cl$1;
	r14 = Game_findObjectOnMouse(r21,r23,r13);
	r25 = (objects__$Hull)g$_objects_Hull;
	r24 = Std_isOfType(((vdynamic*)r14),((vdynamic*)r25));
	r26 = r0->isInside;
	if( r26 ) goto label$2b8dca1_22_82;
	if( !r24 ) goto label$2b8dca1_22_82;
	r27 = (util__Sequence)hl_alloc_obj(&t$util_Sequence);
	util_Sequence_new(r27);
	if( r6 == NULL ) hl_null_access();
	if( r12 == NULL ) hl_null_access();
	r29 = r12->pos;
	r28 = r6->hasValue ? ((vclosure* (*)(vdynamic*,hl__types__ArrayBytes_Float))r6->fun)((vdynamic*)r6->value,r29) : ((vclosure* (*)(hl__types__ArrayBytes_Float))r6->fun)(r29);
	if( r28 ) goto label$2b8dca1_22_59;
	r30 = NULL;
	goto label$2b8dca1_22_60;
	label$2b8dca1_22_59:
	r30 = hl_alloc_closure_ptr(&t$fun_3eab8b5,wrapt$fun_3eab8b5,r28);
	label$2b8dca1_22_60:
	r17 = NULL;
	r27 = util_Sequence_then(r27,r30,r17);
	if( r27 == NULL ) hl_null_access();
	r28 = r6->hasValue ? ((vclosure* (*)(vdynamic*,hl__types__ArrayBytes_Float))r6->fun)((vdynamic*)r6->value,r1) : ((vclosure* (*)(hl__types__ArrayBytes_Float))r6->fun)(r1);
	if( r28 ) goto label$2b8dca1_22_67;
	r30 = NULL;
	goto label$2b8dca1_22_68;
	label$2b8dca1_22_67:
	r30 = hl_alloc_closure_ptr(&t$fun_3eab8b5,wrapt$fun_3eab8b5,r28);
	label$2b8dca1_22_68:
	r17 = NULL;
	r27 = util_Sequence_then(r27,r30,r17);
	if( r27 == NULL ) hl_null_access();
	r31 = hl_alloc_enum(&t$ctx_48573a3,0);
	((Enumt$ctx_48573a3*)r31)->p0 = (vclosure*)r2;
	((Enumt$ctx_48573a3*)r31)->p1 = (int)r4;
	((Enumt$ctx_48573a3*)r31)->p2 = (Character)r0;
	((Enumt$ctx_48573a3*)r31)->p3 = (Object)r14;
	r30 = hl_alloc_closure_ptr(&t$fun_60b000c,Character_setTarget__$8,r31);
	r17 = NULL;
	r27 = util_Sequence_then(r27,r30,r17);
	if( r27 == NULL ) hl_null_access();
	util_Sequence_start(r27);
	goto label$2b8dca1_22_162;
	label$2b8dca1_22_82:
	r26 = r0->isInside;
	if( !r26 ) goto label$2b8dca1_22_116;
	if( r24 ) goto label$2b8dca1_22_116;
	r27 = (util__Sequence)hl_alloc_obj(&t$util_Sequence);
	util_Sequence_new(r27);
	if( r6 == NULL ) hl_null_access();
	if( r12 == NULL ) hl_null_access();
	r29 = r12->pos;
	r28 = r6->hasValue ? ((vclosure* (*)(vdynamic*,hl__types__ArrayBytes_Float))r6->fun)((vdynamic*)r6->value,r29) : ((vclosure* (*)(hl__types__ArrayBytes_Float))r6->fun)(r29);
	if( r28 ) goto label$2b8dca1_22_94;
	r30 = NULL;
	goto label$2b8dca1_22_95;
	label$2b8dca1_22_94:
	r30 = hl_alloc_closure_ptr(&t$fun_3eab8b5,wrapt$fun_3eab8b5,r28);
	label$2b8dca1_22_95:
	r17 = NULL;
	r27 = util_Sequence_then(r27,r30,r17);
	if( r27 == NULL ) hl_null_access();
	r28 = r6->hasValue ? ((vclosure* (*)(vdynamic*,hl__types__ArrayBytes_Float))r6->fun)((vdynamic*)r6->value,r1) : ((vclosure* (*)(hl__types__ArrayBytes_Float))r6->fun)(r1);
	if( r28 ) goto label$2b8dca1_22_102;
	r30 = NULL;
	goto label$2b8dca1_22_103;
	label$2b8dca1_22_102:
	r30 = hl_alloc_closure_ptr(&t$fun_3eab8b5,wrapt$fun_3eab8b5,r28);
	label$2b8dca1_22_103:
	r17 = NULL;
	r27 = util_Sequence_then(r27,r30,r17);
	if( r27 == NULL ) hl_null_access();
	r32 = hl_alloc_enum(&t$ctx_521e260,0);
	((Enumt$ctx_521e260*)r32)->p0 = (vclosure*)r2;
	((Enumt$ctx_521e260*)r32)->p1 = (int)r4;
	((Enumt$ctx_521e260*)r32)->p2 = (Character)r0;
	r30 = hl_alloc_closure_ptr(&t$fun_c967d5a,Character_setTarget__$9,r32);
	r17 = NULL;
	r27 = util_Sequence_then(r27,r30,r17);
	if( r27 == NULL ) hl_null_access();
	util_Sequence_start(r27);
	goto label$2b8dca1_22_162;
	label$2b8dca1_22_116:
	r26 = r0->isInside;
	if( !r26 ) goto label$2b8dca1_22_140;
	r27 = (util__Sequence)hl_alloc_obj(&t$util_Sequence);
	util_Sequence_new(r27);
	if( r6 == NULL ) hl_null_access();
	r28 = r6->hasValue ? ((vclosure* (*)(vdynamic*,hl__types__ArrayBytes_Float))r6->fun)((vdynamic*)r6->value,r1) : ((vclosure* (*)(hl__types__ArrayBytes_Float))r6->fun)(r1);
	if( r28 ) goto label$2b8dca1_22_125;
	r30 = NULL;
	goto label$2b8dca1_22_126;
	label$2b8dca1_22_125:
	r30 = hl_alloc_closure_ptr(&t$fun_3eab8b5,wrapt$fun_3eab8b5,r28);
	label$2b8dca1_22_126:
	r17 = NULL;
	r27 = util_Sequence_then(r27,r30,r17);
	if( r27 == NULL ) hl_null_access();
	r31 = hl_alloc_enum(&t$ctx_48573a3,0);
	((Enumt$ctx_48573a3*)r31)->p0 = (vclosure*)r2;
	((Enumt$ctx_48573a3*)r31)->p1 = (int)r4;
	((Enumt$ctx_48573a3*)r31)->p2 = (Character)r0;
	((Enumt$ctx_48573a3*)r31)->p3 = (Object)r14;
	r30 = hl_alloc_closure_ptr(&t$fun_60b000c,Character_setTarget__$10,r31);
	r17 = NULL;
	r27 = util_Sequence_then(r27,r30,r17);
	if( r27 == NULL ) hl_null_access();
	util_Sequence_start(r27);
	goto label$2b8dca1_22_162;
	label$2b8dca1_22_140:
	r26 = r0->isInside;
	if( r26 ) goto label$2b8dca1_22_162;
	r27 = (util__Sequence)hl_alloc_obj(&t$util_Sequence);
	util_Sequence_new(r27);
	if( r6 == NULL ) hl_null_access();
	r28 = r6->hasValue ? ((vclosure* (*)(vdynamic*,hl__types__ArrayBytes_Float))r6->fun)((vdynamic*)r6->value,r1) : ((vclosure* (*)(hl__types__ArrayBytes_Float))r6->fun)(r1);
	if( r28 ) goto label$2b8dca1_22_149;
	r30 = NULL;
	goto label$2b8dca1_22_150;
	label$2b8dca1_22_149:
	r30 = hl_alloc_closure_ptr(&t$fun_3eab8b5,wrapt$fun_3eab8b5,r28);
	label$2b8dca1_22_150:
	r17 = NULL;
	r27 = util_Sequence_then(r27,r30,r17);
	if( r27 == NULL ) hl_null_access();
	r32 = hl_alloc_enum(&t$ctx_521e260,0);
	((Enumt$ctx_521e260*)r32)->p0 = (vclosure*)r2;
	((Enumt$ctx_521e260*)r32)->p1 = (int)r4;
	((Enumt$ctx_521e260*)r32)->p2 = (Character)r0;
	r30 = hl_alloc_closure_ptr(&t$fun_c967d5a,Character_setTarget__$11,r32);
	r17 = NULL;
	r27 = util_Sequence_then(r27,r30,r17);
	if( r27 == NULL ) hl_null_access();
	util_Sequence_start(r27);
	label$2b8dca1_22_162:
	return;
}

void Character_new(Character r0,double* r1,double* r2) {
	String r15;
	hl__types__ArrayObj r6;
	hl_type *r8;
	bool r10;
	hl__types__ArrayBytes_Float r18;
	double r3, r4, r9;
	int *r12, *r14, *r16;
	vbyte *r19;
	varray *r7;
	int r5, r13, r17, r20;
	if( r1 ) goto label$2b8dca1_23_3;
	r3 = 0.;
	goto label$2b8dca1_23_4;
	label$2b8dca1_23_3:
	r3 = *r1;
	label$2b8dca1_23_4:
	if( r2 ) goto label$2b8dca1_23_7;
	r4 = 0.;
	goto label$2b8dca1_23_8;
	label$2b8dca1_23_7:
	r4 = *r2;
	label$2b8dca1_23_8:
	r5 = 0;
	r0->moveRequestId = r5;
	r5 = 0;
	r0->jobVersion = r5;
	r8 = &t$PawnJob;
	r5 = 0;
	r7 = hl_alloc_array(r8,r5);
	r6 = hl_types_ArrayObj_alloc(r7);
	r0->jobs = r6;
	r5 = 0;
	r0->skillScience = r5;
	r5 = 0;
	r0->skillConstructing = r5;
	r5 = 0;
	r0->skillMining = r5;
	r5 = 0;
	r0->skillFarming = r5;
	r9 = 1.;
	r0->sleep = r9;
	r9 = 1.;
	r0->food = r9;
	r9 = 1.;
	r0->o2 = r9;
	r9 = 75.;
	r0->speed = r9;
	r10 = false;
	r0->isInside = r10;
	r5 = 15;
	r12 = &r5;
	r13 = 22;
	r14 = &r13;
	r15 = (String)s$character_png;
	r16 = NULL;
	objects_GameObject_new(((objects__GameObject)r0),r12,r14,r15,r16);
	r17 = 1;
	r0->zlayer = r17;
	r0->x = r3;
	r0->y = r4;
	r0->targetX = r3;
	r0->targetY = r4;
	r10 = true;
	r0->selectable = r10;
	r17 = 24;
	r19 = hl_alloc_bytes(r17);
	r17 = 0;
	r20 = 3;
	r20 = r17 << r20;
	*(double*)(r19 + r20) = r3;
	++r17;
	r20 = 3;
	r20 = r17 << r20;
	*(double*)(r19 + r20) = r4;
	++r17;
	r9 = 0.;
	r20 = 3;
	r20 = r17 << r20;
	*(double*)(r19 + r20) = r9;
	++r17;
	r17 = 3;
	r18 = hl_types_ArrayBase_allocF64(r19,r17);
	r0->pos = r18;
	return;
}

