// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/Circle.h>
void Object_new(Object,int*,int*,String,int*);
#include <_std/Eight.h>
#include <_std/Math.h>
#include <_std/Engine.h>
extern $Eight g$_Eight;
extern $Math g$_Math;
#include <hl/natives.h>
extern $Engine g$_Engine;

void Circle_new(Circle r0,hl__types__ArrayBytes_Float r1,int r2,String r3,int* r4) {
	String r8;
	int *r7, *r9;
	int r5, r10, r11;
	if( r4 ) goto label$49c6e58_1_3;
	r5 = 14078931;
	goto label$49c6e58_1_4;
	label$49c6e58_1_3:
	r5 = *r4;
	label$49c6e58_1_4:
	r4 = NULL;
	r7 = NULL;
	r8 = NULL;
	r9 = NULL;
	Object_new(((Object)r0),r4,r7,r8,r9);
	r11 = 4;
	r10 = r2 + r11;
	r0->sizeX = r10;
	r11 = 4;
	r10 = r2 + r11;
	r0->sizeY = r10;
	r0->color = r5;
	r0->pos = r1;
	r0->r = r2;
	return;
}

void Circle_draw(Circle r0) {
	$Eight r4;
	$Engine r20;
	bool r2;
	$Math r11;
	hl__types__ArrayBytes_Float r12;
	double r9, r10, r15, r16, r17, r23;
	vbyte *r14;
	int r3, r5, r6, r7, r8, r13, r18, r19, r21, r22, r24;
	r2 = r0->show;
	if( r2 ) goto label$49c6e58_2_3;
	return;
	label$49c6e58_2_3:
	r4 = ($Eight)g$_Eight;
	r3 = r4->frameNumber;
	r5 = 2;
	r3 = r5 == 0 ? 0 : r3 % r5;
	r5 = 0;
	if( r3 != r5 ) goto label$49c6e58_2_10;
	return;
	label$49c6e58_2_10:
	r3 = 50;
	r5 = 0;
	r6 = r3;
	label$49c6e58_2_13:
	if( r5 >= r6 ) goto label$49c6e58_2_118;
	r7 = r5;
	++r5;
	r9 = (double)r7;
	r10 = (double)r3;
	r9 = r9 / r10;
	r11 = ($Math)g$_Math;
	r10 = r11->PI;
	r9 = r9 * r10;
	r10 = 2.;
	r9 = r9 * r10;
	r12 = r0->pos;
	if( r12 == NULL ) hl_null_access();
	r8 = 0;
	r13 = r12->length;
	if( ((unsigned)r8) < ((unsigned)r13) ) goto label$49c6e58_2_32;
	r10 = 0.;
	goto label$49c6e58_2_36;
	label$49c6e58_2_32:
	r14 = r12->bytes;
	r13 = 3;
	r13 = r8 << r13;
	r10 = *(double*)(r14 + r13);
	label$49c6e58_2_36:
	r15 = hl_math_cos(r9);
	r8 = r0->r;
	r16 = (double)r8;
	r15 = r15 * r16;
	r10 = r10 + r15;
	r12 = r0->pos;
	if( r12 == NULL ) hl_null_access();
	r8 = 1;
	r13 = r12->length;
	if( ((unsigned)r8) < ((unsigned)r13) ) goto label$49c6e58_2_48;
	r15 = 0.;
	goto label$49c6e58_2_52;
	label$49c6e58_2_48:
	r14 = r12->bytes;
	r13 = 3;
	r13 = r8 << r13;
	r15 = *(double*)(r14 + r13);
	label$49c6e58_2_52:
	r16 = hl_math_sin(r9);
	r8 = r0->r;
	r17 = (double)r8;
	r16 = r16 * r17;
	r15 = r15 + r16;
	r8 = 0;
	r13 = r0->color;
	r18 = (int)r10;
	r19 = (int)r15;
	r2 = r0->isUI;
	if( r2 ) goto label$49c6e58_2_94;
	r20 = ($Engine)g$_Engine;
	r12 = r20->cameraOffset;
	if( r12 == NULL ) hl_null_access();
	r21 = 0;
	r22 = r12->length;
	if( ((unsigned)r21) < ((unsigned)r22) ) goto label$49c6e58_2_71;
	r17 = 0.;
	goto label$49c6e58_2_75;
	label$49c6e58_2_71:
	r14 = r12->bytes;
	r22 = 3;
	r22 = r21 << r22;
	r17 = *(double*)(r14 + r22);
	label$49c6e58_2_75:
	r16 = r10 - r17;
	r20 = ($Engine)g$_Engine;
	r12 = r20->cameraOffset;
	if( r12 == NULL ) hl_null_access();
	r21 = 1;
	r22 = r12->length;
	if( ((unsigned)r21) < ((unsigned)r22) ) goto label$49c6e58_2_84;
	r23 = 0.;
	goto label$49c6e58_2_88;
	label$49c6e58_2_84:
	r14 = r12->bytes;
	r22 = 3;
	r22 = r21 << r22;
	r23 = *(double*)(r14 + r22);
	label$49c6e58_2_88:
	r17 = r15 - r23;
	r23 = 0.;
	r21 = (int)r16;
	r18 = r21;
	r21 = (int)r17;
	r19 = r21;
	label$49c6e58_2_94:
	r22 = 1;
	if( r18 < r22 ) goto label$49c6e58_2_117;
	r22 = 1;
	if( r19 < r22 ) goto label$49c6e58_2_117;
	r20 = ($Engine)g$_Engine;
	r22 = r20->n;
	r24 = 1;
	r22 = r22 - r24;
	if( r22 < r18 ) goto label$49c6e58_2_117;
	r20 = ($Engine)g$_Engine;
	r22 = r20->n2;
	r24 = 1;
	r22 = r22 - r24;
	if( r22 < r19 ) goto label$49c6e58_2_117;
	r20 = ($Engine)g$_Engine;
	r14 = r20->data;
	r20 = ($Engine)g$_Engine;
	r22 = r20->n;
	r21 = r19 * r22;
	r21 = r21 + r18;
	r22 = 2;
	r21 = r21 << r22;
	*(int*)(r14 + r21) = r13;
	label$49c6e58_2_117:
	goto label$49c6e58_2_13;
	label$49c6e58_2_118:
	return;
}

void Circle_setOutline(Circle r0,bool* r1,int* r2) {
	bool r3, r6;
	int r4, r7;
	if( r1 ) goto label$49c6e58_3_3;
	r3 = true;
	goto label$49c6e58_3_4;
	label$49c6e58_3_3:
	r3 = *r1;
	label$49c6e58_3_4:
	if( r2 ) goto label$49c6e58_3_7;
	r4 = 2925868;
	goto label$49c6e58_3_8;
	label$49c6e58_3_7:
	r4 = *r2;
	label$49c6e58_3_8:
	r6 = r0->selected;
	if( !r6 ) goto label$49c6e58_3_12;
	r0->color = r4;
	goto label$49c6e58_3_13;
	label$49c6e58_3_12:
	r7 = 14078931;
	label$49c6e58_3_13:
	return;
}

