// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__ConnectorLink
#define INC__std__ConnectorLink
typedef struct _$ConnectorLink *$ConnectorLink;
typedef struct _ConnectorLink *ConnectorLink;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <_std/ExtendableObject.h>
#include <hl/types/ArrayBytes_Float.h>


struct _$ConnectorLink {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _ConnectorLink {
	hl_type *$type;
	ExtendableObject connected;
	hl__types__ArrayBytes_Float from;
	hl__types__ArrayBytes_Float to;
};
#endif

