// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/Eight.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
void util_FastTrig_init(void);
void sdl_Sdl_init(void);
void sdl_Sdl_setGLOptions(int*,int*,int*,int*,int*,int*);
extern hl_type t$_i32;
vvirtual* sdl_Sdl_getCurrentDisplayMode(vdynamic*,bool*);
extern $Eight g$_Eight;
extern hl_type t$sdl_Window;
extern String s$;
void sdl_Window_new(sdl__Window,String,int,int,int*,int*,int*);
extern String s$VoidDwellers;
String sdl_Window_set_title(sdl__Window,String);
#include <hl/natives.h>
extern haxe__$Log g$_haxe_Log;
extern String s$GL_init_failed;
extern String s$Eight_hx;
extern hl_type t$String;
extern String s$Eight;
extern String s$new;
extern hl_type t$vrt_eaa6a3b;
void Engine_allocBuffers(double*);
void Engine_initShaderEngine(void);
void Engine_createRenderTexture(void);
void util_FontManager_initialize(void);
#include <_std/Engine.h>
#include <hl/types/ArrayBase.h>
extern hl_type t$fun_ac87071;
bool sdl_Sdl_processEvents(vclosure*);
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
extern $Engine g$_Engine;
extern String s$uTexelSize;
void sdl_Window_present(sdl__Window);
extern hl_type t$vrt_bcaa630;
extern hl_type t$fun_7b48b4f;
hl__types__ArrayBase hl_types_ArrayObj_splice(hl__types__ArrayObj,int,int);
extern hl_type t$hl_types_ArrayObj;
extern hl_type t$hl_types_ArrayBase;
extern String s$Timer_fired_;
String String___alloc__(vbyte*,int);
String String___add__(String,String);
extern String s$fc763cb;
String Std_string(vdynamic*);
extern String s$runMainLoop;
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
extern String s$Timer_registered_;
extern String s$wait;
extern String s$Event_callbacks_;
extern String s$registerEventCallback;
extern hl_type t$fun_4dfbfe4;
extern String s$unregisterEventCallback;
extern String s$Event_callback_not_found_;
extern String s$Update_callbacks_;
extern String s$registerUpdateCallback;
extern String s$unregisterUpdateCallback;
extern String s$Update_callback_not_found_;

void Eight_new(Eight r0) {
	vdynobj *r26;
	String r17, r27;
	bool *r13;
	$Eight r14;
	vvirtual *r10, *r28;
	bool r23;
	haxe__$Log r25;
	sdl__Window r16;
	double r31, r32, r33, r34;
	vclosure *r24;
	double *r35;
	vdynamic *r12;
	int *r3, *r5, *r6, *r7, *r8, *r9;
	int r2, r4, r11, r15, r18, r19, r20, r21, r22, r29, r30;
	util_FastTrig_init();
	sdl_Sdl_init();
	r2 = 4;
	r3 = &r2;
	r4 = 6;
	r5 = &r4;
	r6 = NULL;
	r7 = NULL;
	r8 = NULL;
	r9 = NULL;
	sdl_Sdl_setGLOptions(r3,r5,r6,r7,r8,r9);
	r11 = 0;
	r12 = hl_alloc_dynamic(&t$_i32);
	r12->v.i = r11;
	r13 = NULL;
	r10 = sdl_Sdl_getCurrentDisplayMode(r12,r13);
	if( r10 == NULL ) hl_null_access();
	r11 = hl_vfields(r10)[3] ? (*(int*)(hl_vfields(r10)[3])) : (int)hl_dyn_geti(r10->value,-362629759/*width*/,&t$_i32);
	r14 = ($Eight)g$_Eight;
	r14->screenW = r11;
	r11 = hl_vfields(r10)[2] ? (*(int*)(hl_vfields(r10)[2])) : (int)hl_dyn_geti(r10->value,38537191/*height*/,&t$_i32);
	r14 = ($Eight)g$_Eight;
	r14->screenH = r11;
	r11 = 0;
	r15 = 0;
	r16 = (sdl__Window)hl_alloc_obj(&t$sdl_Window);
	r17 = (String)s$;
	r14 = ($Eight)g$_Eight;
	r18 = r14->screenW;
	r14 = ($Eight)g$_Eight;
	r19 = r14->screenH;
	r20 = r11;
	r3 = &r20;
	r21 = r15;
	r5 = &r21;
	r22 = 2;
	r6 = &r22;
	sdl_Window_new(r16,r17,r18,r19,r3,r5,r6);
	r0->window = r16;
	r16 = r0->window;
	if( r16 == NULL ) hl_null_access();
	r17 = (String)s$VoidDwellers;
	r17 = sdl_Window_set_title(r16,r17);
	r23 = sdl_gl_init();
	r23 = sdl_gl_init();
	if( r23 ) goto label$1a968c6_1_61;
	r25 = (haxe__$Log)g$_haxe_Log;
	r24 = r25->trace;
	if( r24 == NULL ) hl_null_access();
	r17 = (String)s$GL_init_failed;
	r26 = hl_alloc_dynobj();
	r27 = (String)s$Eight_hx;
	hl_dyn_setp((vdynamic*)r26,37969014/*fileName*/,&t$String,r27);
	r18 = 295;
	hl_dyn_seti((vdynamic*)r26,371360620/*lineNumber*/,&t$_i32,r18);
	r27 = (String)s$Eight;
	hl_dyn_setp((vdynamic*)r26,-63073762/*className*/,&t$String,r27);
	r27 = (String)s$new;
	hl_dyn_setp((vdynamic*)r26,302979532/*methodName*/,&t$String,r27);
	r28 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r26);
	r24->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r24->fun)((vdynamic*)r24->value,((vdynamic*)r17),r28) : ((void (*)(vdynamic*,vvirtual*))r24->fun)(((vdynamic*)r17),r28);
	return;
	label$1a968c6_1_61:
	r18 = 0;
	r19 = 0;
	r14 = ($Eight)g$_Eight;
	r29 = r14->screenW;
	r14 = ($Eight)g$_Eight;
	r30 = r14->screenH;
	sdl_gl_viewport(r18,r19,r29,r30);
	r31 = 0.5;
	r32 = 0.5;
	r33 = 0.5;
	r34 = 1.;
	sdl_gl_clear_color(r31,r32,r33,r34);
	r31 = 0.80000000000000004;
	r35 = &r31;
	Engine_allocBuffers(r35);
	Engine_initShaderEngine();
	Engine_createRenderTexture();
	util_FontManager_initialize();
	return;
}

void Eight_runMainLoop(Eight r0) {
	vdynobj *r39;
	String r28, r38;
	$Eight r3;
	vvirtual *r32, *r40;
	hl__types__ArrayObj r12;
	$Engine r11;
	bool r1;
	haxe__$Log r36;
	hl__types__ArrayBase r34;
	sdl__Window r31;
	Object r15;
	float r29;
	hl__types__ArrayBytes_Float r8;
	double r4, r6, r7, r19, r20, r21;
	vclosure *r2, *r18, *r33, *r35;
	int *r37;
	vdynamic *r16, *r27;
	varray *r17;
	int r10, r13, r14, r22, r23, r24, r25, r26;
	vbyte *r9, *r30;
	label$1a968c6_2_0:
	r2 = hl_alloc_closure_ptr(&t$fun_ac87071,r0->$type->vobj_proto[0],r0);
	r1 = sdl_Sdl_processEvents(r2);
	if( !r1 ) goto label$1a968c6_2_297;
	r3 = ($Eight)g$_Eight;
	r1 = r3->run;
	if( !r1 ) goto label$1a968c6_2_297;
	r4 = hl_sys_time();
	r3 = ($Eight)g$_Eight;
	r7 = r3->lastTime;
	r6 = r4 - r7;
	r3 = ($Eight)g$_Eight;
	r3->lastTime = r4;
	r10 = 0;
	r9 = hl_alloc_bytes(r10);
	r10 = 0;
	r10 = 0;
	r8 = hl_types_ArrayBase_allocF64(r9,r10);
	r11 = ($Engine)g$_Engine;
	r11->vertices = r8;
	r10 = 0;
	r3 = ($Eight)g$_Eight;
	r12 = r3->objects;
	label$1a968c6_2_23:
	if( r12 == NULL ) hl_null_access();
	r14 = r12->length;
	if( r10 >= r14 ) goto label$1a968c6_2_41;
	r14 = r12->length;
	if( ((unsigned)r10) < ((unsigned)r14) ) goto label$1a968c6_2_31;
	r15 = NULL;
	goto label$1a968c6_2_34;
	label$1a968c6_2_31:
	r17 = r12->array;
	r16 = ((vdynamic**)(r17 + 1))[r10];
	r15 = (Object)r16;
	label$1a968c6_2_34:
	++r10;
	if( r15 == NULL ) hl_null_access();
	r13 = r15->zlayer;
	r14 = 0;
	if( r13 != r14 ) goto label$1a968c6_2_40;
	((void (*)(Object))r15->$type->vobj_proto[0])(r15);
	label$1a968c6_2_40:
	goto label$1a968c6_2_23;
	label$1a968c6_2_41:
	r10 = 0;
	r3 = ($Eight)g$_Eight;
	r12 = r3->objects;
	label$1a968c6_2_44:
	if( r12 == NULL ) hl_null_access();
	r14 = r12->length;
	if( r10 >= r14 ) goto label$1a968c6_2_62;
	r14 = r12->length;
	if( ((unsigned)r10) < ((unsigned)r14) ) goto label$1a968c6_2_52;
	r15 = NULL;
	goto label$1a968c6_2_55;
	label$1a968c6_2_52:
	r17 = r12->array;
	r16 = ((vdynamic**)(r17 + 1))[r10];
	r15 = (Object)r16;
	label$1a968c6_2_55:
	++r10;
	if( r15 == NULL ) hl_null_access();
	r13 = r15->zlayer;
	r14 = 1;
	if( r13 != r14 ) goto label$1a968c6_2_61;
	((void (*)(Object))r15->$type->vobj_proto[0])(r15);
	label$1a968c6_2_61:
	goto label$1a968c6_2_44;
	label$1a968c6_2_62:
	((void (*)(Eight,double))r0->$type->vobj_proto[1])(r0,r6);
	r10 = 0;
	r3 = ($Eight)g$_Eight;
	r12 = r3->updateCallbacks;
	label$1a968c6_2_66:
	if( r12 == NULL ) hl_null_access();
	r14 = r12->length;
	if( r10 >= r14 ) goto label$1a968c6_2_81;
	r14 = r12->length;
	if( ((unsigned)r10) < ((unsigned)r14) ) goto label$1a968c6_2_74;
	r18 = NULL;
	goto label$1a968c6_2_77;
	label$1a968c6_2_74:
	r17 = r12->array;
	r16 = ((vdynamic**)(r17 + 1))[r10];
	r18 = (vclosure*)r16;
	label$1a968c6_2_77:
	++r10;
	if( r18 == NULL ) hl_null_access();
	r18->hasValue ? ((void (*)(vdynamic*,double))r18->fun)((vdynamic*)r18->value,r6) : ((void (*)(double))r18->fun)(r6);
	goto label$1a968c6_2_66;
	label$1a968c6_2_81:
	r7 = hl_sys_time();
	r7 = r7 - r4;
	r19 = 0.016666666666666666;
	r19 = r19 - r7;
	r21 = 0.;
	if( !(r21 < r19) ) goto label$1a968c6_2_91;
	r21 = 1000.;
	r20 = r19 * r21;
	r10 = (int)r20;
	sdl_delay(r10);
	label$1a968c6_2_91:
	r20 = 1.;
	r20 = r20 / r7;
	r3 = ($Eight)g$_Eight;
	r3->fps = r20;
	r3 = ($Eight)g$_Eight;
	r10 = r3->frameNumber;
	++r10;
	r3->frameNumber = r10;
	r11 = ($Engine)g$_Engine;
	r1 = r11->fullQuad;
	if( !r1 ) goto label$1a968c6_2_170;
	r10 = 33984;
	sdl_gl_active_texture(r10);
	r10 = 37074;
	r13 = 0;
	r11 = ($Engine)g$_Engine;
	r9 = r11->data;
	r14 = 0;
	r11 = ($Engine)g$_Engine;
	r22 = r11->count;
	sdl_gl_get_buffer_sub_data(r10,r13,r9,r14,r22);
	r10 = 3553;
	r13 = 0;
	r14 = 6408;
	r11 = ($Engine)g$_Engine;
	r22 = r11->n;
	r11 = ($Engine)g$_Engine;
	r23 = r11->n2;
	r24 = 0;
	r25 = 6408;
	r26 = 5121;
	r11 = ($Engine)g$_Engine;
	r9 = r11->data;
	sdl_gl_tex_image2d(r10,r13,r14,r22,r23,r24,r25,r26,r9);
	r11 = ($Engine)g$_Engine;
	r27 = r11->shaderRender;
	sdl_gl_use_program(r27);
	r11 = ($Engine)g$_Engine;
	r27 = r11->shaderRender;
	r28 = (String)s$uTexelSize;
	r27 = sdl_gl_get_uniform_location(r27,r28);
	r10 = 16;
	r9 = hl_alloc_bytes(r10);
	r20 = 1.;
	r11 = ($Engine)g$_Engine;
	r10 = r11->n;
	r21 = (double)r10;
	r20 = r20 / r21;
	r21 = 2.2999999999999998;
	r20 = r20 / r21;
	r29 = (float)r20;
	r10 = 0;
	*(float*)(r9 + r10) = r29;
	r20 = 1.;
	r11 = ($Engine)g$_Engine;
	r10 = r11->n2;
	r21 = (double)r10;
	r20 = r20 / r21;
	r21 = 2.2999999999999998;
	r20 = r20 / r21;
	r29 = (float)r20;
	r10 = 4;
	*(float*)(r9 + r10) = r29;
	r10 = 8;
	r13 = 0;
	r29 = (float)r13;
	*(float*)(r9 + r10) = r29;
	r10 = 12;
	r13 = 0;
	r29 = (float)r13;
	*(float*)(r9 + r10) = r29;
	r10 = 0;
	r13 = 1;
	sdl_gl_uniform4fv(r27,r9,r10,r13);
	r10 = 5;
	r13 = 0;
	r14 = 4;
	sdl_gl_draw_arrays(r10,r13,r14);
	goto label$1a968c6_2_234;
	label$1a968c6_2_170:
	r11 = ($Engine)g$_Engine;
	r8 = r11->vertices;
	if( r8 == NULL ) hl_null_access();
	r10 = r8->length;
	r13 = 4;
	r10 = r10 * r13;
	r9 = hl_alloc_bytes(r10);
	r10 = 0;
	r11 = ($Engine)g$_Engine;
	r8 = r11->vertices;
	if( r8 == NULL ) hl_null_access();
	r13 = r8->length;
	label$1a968c6_2_182:
	if( r10 >= r13 ) goto label$1a968c6_2_202;
	r14 = r10;
	++r10;
	r11 = ($Engine)g$_Engine;
	r8 = r11->vertices;
	if( r8 == NULL ) hl_null_access();
	r23 = r8->length;
	if( ((unsigned)r14) < ((unsigned)r23) ) goto label$1a968c6_2_193;
	r20 = 0.;
	goto label$1a968c6_2_197;
	label$1a968c6_2_193:
	r30 = r8->bytes;
	r23 = 3;
	r23 = r14 << r23;
	r20 = *(double*)(r30 + r23);
	label$1a968c6_2_197:
	r29 = (float)r20;
	r23 = 4;
	r22 = r14 * r23;
	*(float*)(r9 + r22) = r29;
	goto label$1a968c6_2_182;
	label$1a968c6_2_202:
	r10 = 34962;
	r11 = ($Engine)g$_Engine;
	r27 = r11->vbo;
	sdl_gl_bind_buffer(r10,r27);
	r10 = 34962;
	r11 = ($Engine)g$_Engine;
	r8 = r11->vertices;
	if( r8 == NULL ) hl_null_access();
	r13 = r8->length;
	r14 = 4;
	r13 = r13 * r14;
	r14 = 35048;
	sdl_gl_buffer_data(r10,r13,r9,r14);
	r11 = ($Engine)g$_Engine;
	r27 = r11->shaderRender;
	sdl_gl_use_program(r27);
	r10 = 16640;
	sdl_gl_clear(r10);
	r11 = ($Engine)g$_Engine;
	r27 = r11->vao;
	sdl_gl_bind_vertex_array(r27);
	r11 = ($Engine)g$_Engine;
	r8 = r11->vertices;
	if( r8 == NULL ) hl_null_access();
	r10 = r8->length;
	r20 = (double)r10;
	r21 = 6.;
	r20 = r20 / r21;
	r10 = 4;
	r13 = 0;
	r14 = (int)r20;
	sdl_gl_draw_arrays(r10,r13,r14);
	label$1a968c6_2_234:
	r31 = r0->window;
	if( r31 == NULL ) hl_null_access();
	sdl_Window_present(r31);
	r3 = ($Eight)g$_Eight;
	r12 = r3->timerCallbacks;
	if( r12 == NULL ) hl_null_access();
	r10 = r12->length;
	label$1a968c6_2_241:
	--r10;
	r13 = -1;
	if( r13 >= r10 ) goto label$1a968c6_2_296;
	r3 = ($Eight)g$_Eight;
	r12 = r3->timerCallbacks;
	if( r12 == NULL ) hl_null_access();
	r14 = r12->length;
	if( ((unsigned)r10) < ((unsigned)r14) ) goto label$1a968c6_2_252;
	r32 = NULL;
	goto label$1a968c6_2_255;
	label$1a968c6_2_252:
	r17 = r12->array;
	r16 = ((vdynamic**)(r17 + 1))[r10];
	r32 = hl_to_virtual(&t$vrt_bcaa630,(vdynamic*)r16);
	label$1a968c6_2_255:
	if( r32 == NULL ) hl_null_access();
	r20 = hl_vfields(r32)[1] ? (*(double*)(hl_vfields(r32)[1])) : (double)hl_dyn_getd(r32->value,-130745572/*timeTrigger*/);
	r3 = ($Eight)g$_Eight;
	r21 = r3->lastTime;
	if( !(r20 < r21) ) goto label$1a968c6_2_295;
	r33 = hl_vfields(r32)[0] ? (*(vclosure**)(hl_vfields(r32)[0])) : (vclosure*)hl_dyn_getp(r32->value,520526676/*callback*/,&t$fun_7b48b4f);
	if( r33 == NULL ) hl_null_access();
	r33->hasValue ? ((void (*)(vdynamic*))r33->fun)((vdynamic*)r33->value) : ((void (*)(void))r33->fun)();
	r3 = ($Eight)g$_Eight;
	r12 = r3->timerCallbacks;
	if( r12 == NULL ) hl_null_access();
	r13 = r10;
	r14 = 1;
	r34 = hl_types_ArrayObj_splice(r12,r10,r14);
	r12 = (hl__types__ArrayObj)hl_dyn_castp(&r34,&t$hl_types_ArrayBase,&t$hl_types_ArrayObj);
	r36 = (haxe__$Log)g$_haxe_Log;
	r35 = r36->trace;
	if( r35 == NULL ) hl_null_access();
	r28 = (String)s$Timer_fired_;
	r20 = hl_vfields(r32)[1] ? (*(double*)(hl_vfields(r32)[1])) : (double)hl_dyn_getd(r32->value,-130745572/*timeTrigger*/);
	r37 = &r13;
	r9 = hl_ftos(r20,r37);
	r38 = String___alloc__(r9,r13);
	r28 = String___add__(r28,r38);
	r38 = (String)s$fc763cb;
	r28 = String___add__(r28,r38);
	r33 = hl_vfields(r32)[0] ? (*(vclosure**)(hl_vfields(r32)[0])) : (vclosure*)hl_dyn_getp(r32->value,520526676/*callback*/,&t$fun_7b48b4f);
	r38 = Std_string(((vdynamic*)r33));
	r28 = String___add__(r28,r38);
	r39 = hl_alloc_dynobj();
	r38 = (String)s$Eight_hx;
	hl_dyn_setp((vdynamic*)r39,37969014/*fileName*/,&t$String,r38);
	r13 = 365;
	hl_dyn_seti((vdynamic*)r39,371360620/*lineNumber*/,&t$_i32,r13);
	r38 = (String)s$Eight;
	hl_dyn_setp((vdynamic*)r39,-63073762/*className*/,&t$String,r38);
	r38 = (String)s$runMainLoop;
	hl_dyn_setp((vdynamic*)r39,302979532/*methodName*/,&t$String,r38);
	r40 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r39);
	r35->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r35->fun)((vdynamic*)r35->value,((vdynamic*)r28),r40) : ((void (*)(vdynamic*,vvirtual*))r35->fun)(((vdynamic*)r28),r40);
	label$1a968c6_2_295:
	goto label$1a968c6_2_241;
	label$1a968c6_2_296:
	goto label$1a968c6_2_0;
	label$1a968c6_2_297:
	return;
}

void Eight_delay(int r0) {
	sdl_delay(r0);
	return;
}

void Eight_wait(double r0,vclosure* r1) {
	vdynobj *r14;
	String r10, r13;
	$Eight r4;
	vvirtual *r5, *r15;
	hl__types__ArrayObj r3;
	haxe__$Log r9;
	vclosure *r8;
	double r6;
	int *r11;
	vbyte *r12;
	int r2;
	r4 = ($Eight)g$_Eight;
	r3 = r4->timerCallbacks;
	if( r3 == NULL ) hl_null_access();
	r5 = hl_alloc_virtual(&t$vrt_bcaa630);
	r4 = ($Eight)g$_Eight;
	r6 = r4->lastTime;
	r6 = r6 + r0;
	if( hl_vfields(r5)[1] ) *(double*)(hl_vfields(r5)[1]) = (double)r6; else hl_dyn_setd(r5->value,-130745572/*timeTrigger*/,r6);
	if( hl_vfields(r5)[0] ) *(vclosure**)(hl_vfields(r5)[0]) = (vclosure*)r1; else hl_dyn_setp(r5->value,520526676/*callback*/,&t$fun_7b48b4f,r1);
	r2 = hl_types_ArrayObj_push(r3,((vdynamic*)r5));
	r9 = (haxe__$Log)g$_haxe_Log;
	r8 = r9->trace;
	if( r8 == NULL ) hl_null_access();
	r10 = (String)s$Timer_registered_;
	r11 = &r2;
	r12 = hl_ftos(r0,r11);
	r13 = String___alloc__(r12,r2);
	r10 = String___add__(r10,r13);
	r14 = hl_alloc_dynobj();
	r13 = (String)s$Eight_hx;
	hl_dyn_setp((vdynamic*)r14,37969014/*fileName*/,&t$String,r13);
	r2 = 376;
	hl_dyn_seti((vdynamic*)r14,371360620/*lineNumber*/,&t$_i32,r2);
	r13 = (String)s$Eight;
	hl_dyn_setp((vdynamic*)r14,-63073762/*className*/,&t$String,r13);
	r13 = (String)s$wait;
	hl_dyn_setp((vdynamic*)r14,302979532/*methodName*/,&t$String,r13);
	r15 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r14);
	r8->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r8->fun)((vdynamic*)r8->value,((vdynamic*)r10),r15) : ((void (*)(vdynamic*,vvirtual*))r8->fun)(((vdynamic*)r10),r15);
	return;
}

void Eight_registerEventCallback__$1(vclosure* r0) {
	vdynobj *r11;
	String r7, r10;
	$Eight r3;
	vvirtual *r12;
	hl__types__ArrayObj r2;
	haxe__$Log r6;
	vclosure *r5;
	int *r8;
	vbyte *r9;
	int r1;
	r3 = ($Eight)g$_Eight;
	r2 = r3->eventCallbacks;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayObj_push(r2,((vdynamic*)r0));
	r6 = (haxe__$Log)g$_haxe_Log;
	r5 = r6->trace;
	if( r5 == NULL ) hl_null_access();
	r7 = (String)s$Event_callbacks_;
	r3 = ($Eight)g$_Eight;
	r2 = r3->eventCallbacks;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->length;
	r8 = &r1;
	r9 = hl_itos(r1,r8);
	r10 = String___alloc__(r9,r1);
	r7 = String___add__(r7,r10);
	r11 = hl_alloc_dynobj();
	r10 = (String)s$Eight_hx;
	hl_dyn_setp((vdynamic*)r11,37969014/*fileName*/,&t$String,r10);
	r1 = 383;
	hl_dyn_seti((vdynamic*)r11,371360620/*lineNumber*/,&t$_i32,r1);
	r10 = (String)s$Eight;
	hl_dyn_setp((vdynamic*)r11,-63073762/*className*/,&t$String,r10);
	r10 = (String)s$registerEventCallback;
	hl_dyn_setp((vdynamic*)r11,302979532/*methodName*/,&t$String,r10);
	r12 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r11);
	r5->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r5->fun)((vdynamic*)r5->value,((vdynamic*)r7),r12) : ((void (*)(vdynamic*,vvirtual*))r5->fun)(((vdynamic*)r7),r12);
	return;
}

void Eight_registerEventCallback(vclosure* r0) {
	vclosure *r3;
	double r2;
	r2 = 0.10000000000000001;
	r3 = hl_alloc_closure_ptr(&t$fun_4dfbfe4,Eight_registerEventCallback__$1,r0);
	Eight_wait(r2,r3);
	return;
}

hl__types__ArrayObj Eight_unregisterEventCallback(vclosure* r0) {
	vdynobj *r18;
	String r14, r17;
	$Eight r5;
	vvirtual *r19;
	hl__types__ArrayObj r4;
	hl__types__ArrayBase r20;
	haxe__$Log r13;
	vclosure *r9, *r12;
	int *r15;
	vdynamic *r10;
	vbyte *r16;
	varray *r11;
	int r1, r3, r6, r7, r8;
	r1 = 0;
	r5 = ($Eight)g$_Eight;
	r4 = r5->eventCallbacks;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->length;
	label$1a968c6_7_5:
	if( r1 >= r3 ) goto label$1a968c6_7_53;
	r6 = r1;
	++r1;
	r5 = ($Eight)g$_Eight;
	r4 = r5->eventCallbacks;
	if( r4 == NULL ) hl_null_access();
	r8 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r8) ) goto label$1a968c6_7_16;
	r9 = NULL;
	goto label$1a968c6_7_19;
	label$1a968c6_7_16:
	r11 = r4->array;
	r10 = ((vdynamic**)(r11 + 1))[r6];
	r9 = (vclosure*)r10;
	label$1a968c6_7_19:
	{ int i = hl_dyn_compare((vdynamic*)r9,(vdynamic*)r0); if( i != 0 ) goto label$1a968c6_7_52; };
	r13 = (haxe__$Log)g$_haxe_Log;
	r12 = r13->trace;
	if( r12 == NULL ) hl_null_access();
	r14 = (String)s$Event_callbacks_;
	r5 = ($Eight)g$_Eight;
	r4 = r5->eventCallbacks;
	if( r4 == NULL ) hl_null_access();
	r7 = r4->length;
	r8 = 1;
	r7 = r7 - r8;
	r15 = &r7;
	r16 = hl_itos(r7,r15);
	r17 = String___alloc__(r16,r7);
	r14 = String___add__(r14,r17);
	r18 = hl_alloc_dynobj();
	r17 = (String)s$Eight_hx;
	hl_dyn_setp((vdynamic*)r18,37969014/*fileName*/,&t$String,r17);
	r7 = 390;
	hl_dyn_seti((vdynamic*)r18,371360620/*lineNumber*/,&t$_i32,r7);
	r17 = (String)s$Eight;
	hl_dyn_setp((vdynamic*)r18,-63073762/*className*/,&t$String,r17);
	r17 = (String)s$unregisterEventCallback;
	hl_dyn_setp((vdynamic*)r18,302979532/*methodName*/,&t$String,r17);
	r19 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r18);
	r12->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r12->fun)((vdynamic*)r12->value,((vdynamic*)r14),r19) : ((void (*)(vdynamic*,vvirtual*))r12->fun)(((vdynamic*)r14),r19);
	r5 = ($Eight)g$_Eight;
	r4 = r5->eventCallbacks;
	if( r4 == NULL ) hl_null_access();
	r8 = 1;
	r20 = hl_types_ArrayObj_splice(r4,r6,r8);
	r4 = (hl__types__ArrayObj)hl_dyn_castp(&r20,&t$hl_types_ArrayBase,&t$hl_types_ArrayObj);
	return r4;
	label$1a968c6_7_52:
	goto label$1a968c6_7_5;
	label$1a968c6_7_53:
	r14 = (String)s$Event_callback_not_found_;
	hl_throw((vdynamic*)r14);
}

void Eight_registerUpdateCallback(vclosure* r0) {
	vdynobj *r11;
	String r7, r10;
	$Eight r3;
	vvirtual *r12;
	hl__types__ArrayObj r2;
	haxe__$Log r6;
	vclosure *r5;
	int *r8;
	vbyte *r9;
	int r1;
	r3 = ($Eight)g$_Eight;
	r2 = r3->updateCallbacks;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayObj_push(r2,((vdynamic*)r0));
	r6 = (haxe__$Log)g$_haxe_Log;
	r5 = r6->trace;
	if( r5 == NULL ) hl_null_access();
	r7 = (String)s$Update_callbacks_;
	r3 = ($Eight)g$_Eight;
	r2 = r3->updateCallbacks;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->length;
	r8 = &r1;
	r9 = hl_itos(r1,r8);
	r10 = String___alloc__(r9,r1);
	r7 = String___add__(r7,r10);
	r11 = hl_alloc_dynobj();
	r10 = (String)s$Eight_hx;
	hl_dyn_setp((vdynamic*)r11,37969014/*fileName*/,&t$String,r10);
	r1 = 399;
	hl_dyn_seti((vdynamic*)r11,371360620/*lineNumber*/,&t$_i32,r1);
	r10 = (String)s$Eight;
	hl_dyn_setp((vdynamic*)r11,-63073762/*className*/,&t$String,r10);
	r10 = (String)s$registerUpdateCallback;
	hl_dyn_setp((vdynamic*)r11,302979532/*methodName*/,&t$String,r10);
	r12 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r11);
	r5->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r5->fun)((vdynamic*)r5->value,((vdynamic*)r7),r12) : ((void (*)(vdynamic*,vvirtual*))r5->fun)(((vdynamic*)r7),r12);
	return;
}

hl__types__ArrayObj Eight_unregisterUpdateCallback(vclosure* r0) {
	vdynobj *r18;
	String r14, r17;
	$Eight r5;
	vvirtual *r19;
	hl__types__ArrayObj r4;
	hl__types__ArrayBase r20;
	haxe__$Log r13;
	vclosure *r9, *r12;
	int *r15;
	vdynamic *r10;
	vbyte *r16;
	varray *r11;
	int r1, r3, r6, r7, r8;
	r1 = 0;
	r5 = ($Eight)g$_Eight;
	r4 = r5->updateCallbacks;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->length;
	label$1a968c6_9_5:
	if( r1 >= r3 ) goto label$1a968c6_9_53;
	r6 = r1;
	++r1;
	r5 = ($Eight)g$_Eight;
	r4 = r5->updateCallbacks;
	if( r4 == NULL ) hl_null_access();
	r8 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r8) ) goto label$1a968c6_9_16;
	r9 = NULL;
	goto label$1a968c6_9_19;
	label$1a968c6_9_16:
	r11 = r4->array;
	r10 = ((vdynamic**)(r11 + 1))[r6];
	r9 = (vclosure*)r10;
	label$1a968c6_9_19:
	{ int i = hl_dyn_compare((vdynamic*)r9,(vdynamic*)r0); if( i != 0 ) goto label$1a968c6_9_52; };
	r13 = (haxe__$Log)g$_haxe_Log;
	r12 = r13->trace;
	if( r12 == NULL ) hl_null_access();
	r14 = (String)s$Update_callbacks_;
	r5 = ($Eight)g$_Eight;
	r4 = r5->updateCallbacks;
	if( r4 == NULL ) hl_null_access();
	r7 = r4->length;
	r8 = 1;
	r7 = r7 - r8;
	r15 = &r7;
	r16 = hl_itos(r7,r15);
	r17 = String___alloc__(r16,r7);
	r14 = String___add__(r14,r17);
	r18 = hl_alloc_dynobj();
	r17 = (String)s$Eight_hx;
	hl_dyn_setp((vdynamic*)r18,37969014/*fileName*/,&t$String,r17);
	r7 = 405;
	hl_dyn_seti((vdynamic*)r18,371360620/*lineNumber*/,&t$_i32,r7);
	r17 = (String)s$Eight;
	hl_dyn_setp((vdynamic*)r18,-63073762/*className*/,&t$String,r17);
	r17 = (String)s$unregisterUpdateCallback;
	hl_dyn_setp((vdynamic*)r18,302979532/*methodName*/,&t$String,r17);
	r19 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r18);
	r12->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r12->fun)((vdynamic*)r12->value,((vdynamic*)r14),r19) : ((void (*)(vdynamic*,vvirtual*))r12->fun)(((vdynamic*)r14),r19);
	r5 = ($Eight)g$_Eight;
	r4 = r5->updateCallbacks;
	if( r4 == NULL ) hl_null_access();
	r8 = 1;
	r20 = hl_types_ArrayObj_splice(r4,r6,r8);
	r4 = (hl__types__ArrayObj)hl_dyn_castp(&r20,&t$hl_types_ArrayBase,&t$hl_types_ArrayObj);
	return r4;
	label$1a968c6_9_52:
	goto label$1a968c6_9_5;
	label$1a968c6_9_53:
	r14 = (String)s$Update_callback_not_found_;
	hl_throw((vdynamic*)r14);
}

bool Eight_onEvent(Eight r0,sdl__Event r1) {
	$Eight r6;
	hl__types__ArrayObj r5;
	bool r11;
	vclosure *r8;
	vdynamic *r9;
	varray *r10;
	int r2, r4, r7;
	r2 = -1;
	label$1a968c6_10_1:
	++r2;
	r6 = ($Eight)g$_Eight;
	r5 = r6->eventCallbacks;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->length;
	if( r2 >= r4 ) goto label$1a968c6_10_21;
	r6 = ($Eight)g$_Eight;
	r5 = r6->eventCallbacks;
	if( r5 == NULL ) hl_null_access();
	r7 = r5->length;
	if( ((unsigned)r2) < ((unsigned)r7) ) goto label$1a968c6_10_15;
	r8 = NULL;
	goto label$1a968c6_10_18;
	label$1a968c6_10_15:
	r10 = r5->array;
	r9 = ((vdynamic**)(r10 + 1))[r2];
	r8 = (vclosure*)r9;
	label$1a968c6_10_18:
	if( r8 == NULL ) hl_null_access();
	r8->hasValue ? ((void (*)(vdynamic*,sdl__Event))r8->fun)((vdynamic*)r8->value,r1) : ((void (*)(sdl__Event))r8->fun)(r1);
	goto label$1a968c6_10_1;
	label$1a968c6_10_21:
	r11 = true;
	return r11;
}

void Eight_update(Eight r0,double r1) {
	return;
}

double Eight_distance(hl__types__ArrayBytes_Float r0,hl__types__ArrayBytes_Float r1) {
	double r2, r6, r7, r8;
	vbyte *r5;
	int r3, r4;
	if( r0 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r0->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$1a968c6_12_6;
	r2 = 0.;
	goto label$1a968c6_12_10;
	label$1a968c6_12_6:
	r5 = r0->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r2 = *(double*)(r5 + r4);
	label$1a968c6_12_10:
	if( r1 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r1->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$1a968c6_12_16;
	r6 = 0.;
	goto label$1a968c6_12_20;
	label$1a968c6_12_16:
	r5 = r1->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r6 = *(double*)(r5 + r4);
	label$1a968c6_12_20:
	r2 = r2 - r6;
	r3 = 1;
	r4 = r0->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$1a968c6_12_26;
	r6 = 0.;
	goto label$1a968c6_12_30;
	label$1a968c6_12_26:
	r5 = r0->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r6 = *(double*)(r5 + r4);
	label$1a968c6_12_30:
	r3 = 1;
	r4 = r1->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$1a968c6_12_35;
	r7 = 0.;
	goto label$1a968c6_12_39;
	label$1a968c6_12_35:
	r5 = r1->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r7 = *(double*)(r5 + r4);
	label$1a968c6_12_39:
	r6 = r6 - r7;
	r7 = r2 * r2;
	r8 = r6 * r6;
	r7 = r7 + r8;
	r7 = hl_math_sqrt(r7);
	return r7;
}

