// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__Eight
#define INC__std__Eight
typedef struct _$Eight *$Eight;
typedef struct _Eight *Eight;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>
#include <_std/Object.h>
#include <sdl/Event.h>
#include <hl/types/ArrayBytes_Float.h>
#include <sdl/Window.h>


struct _$Eight {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	hl__types__ArrayObj objects;
	Object currentSelected;
	int screenW;
	int screenH;
	int frameNumber;
	double lastTime;
	bool run;
	double fps;
	vbyte* objectsData;
	int objSize;
	vclosure* delay;
	hl__types__ArrayObj timerCallbacks;
	vclosure* wait;
	hl__types__ArrayObj eventCallbacks;
	vclosure* registerEventCallback;
	vclosure* unregisterEventCallback;
	hl__types__ArrayObj updateCallbacks;
	vclosure* registerUpdateCallback;
	vclosure* unregisterUpdateCallback;
	vclosure* distance;
};
struct _Eight {
	hl_type *$type;
	sdl__Window window;
};
#endif

