// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/ExtendableObject.h>
#include <hl/natives.h>
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
extern hl_type t$hl_types_ArrayBytes_Float;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
#include <_std/Math.h>
#include <_std/ConnectorLink.h>
extern $Math g$_Math;
extern String s$Temperature_;
String String___alloc__(vbyte*,int);
String String___add__(String,String);
void util_FontManager_drawText(String,int,int,int*);
extern String s$Conductivity_F_;
extern String s$Absorptivity_F_;
extern String s$Emission_F_;
void Object_draw(Object);
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
extern hl_type t$_dyn;
extern haxe__$Log g$_haxe_Log;
extern hl_type t$vrt_eaa6a3b;
extern String s$Game_hx;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$ExtendableObject;
extern String s$getNearestConnector;
extern hl_type t$_f64;
#include <hl/types/ArrayBase.h>
hl__types__ArrayDyn hl_types_ArrayDyn_alloc(hl__types__ArrayBase,bool*);
extern hl_type t$hl_types_ArrayDyn;
extern String s$best;
void ExtendableObject_connect(ExtendableObject,ExtendableObject,hl__types__ArrayBytes_Float,hl__types__ArrayBytes_Float);
#include <_std/ExtendableManager.h>
extern $ExtendableManager g$_ExtendableManager;
extern hl_type t$ConnectorLink;
void ConnectorLink_new(ConnectorLink,ExtendableObject,hl__types__ArrayBytes_Float,hl__types__ArrayBytes_Float);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
#include <_std/Game.h>
extern $Game g$_Game;
extern $ExtendableObject g$_ExtendableObject;
void objects_GameObject_select(objects__GameObject,bool);
vdynamic* Type_createInstance(hl__Class,hl__types__ArrayDyn);
extern hl_type t$ExtendableObject;
void objects_GameObject_new(objects__GameObject,int*,int*,String,int*);

hl__types__ArrayObj ExtendableObject_generateConnectors(ExtendableObject r0) {
	hl__types__ArrayObj r12;
	hl_type *r14;
	hl__types__ArrayBytes_Float r4, r8, r10, r15;
	double r1, r3, r7, r9, r11;
	varray *r13;
	vbyte *r5;
	int r2, r6;
	r2 = r0->sizeX;
	r1 = (double)r2;
	r3 = 2.;
	r1 = r1 / r3;
	r2 = 24;
	r5 = hl_alloc_bytes(r2);
	r2 = 0;
	r6 = (int)r1;
	r6 = -r6;
	r3 = (double)r6;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r3;
	++r2;
	r3 = 0.;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r3;
	++r2;
	r3 = 0.;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r3;
	++r2;
	r2 = 3;
	r4 = hl_types_ArrayBase_allocF64(r5,r2);
	r2 = r0->sizeX;
	r3 = (double)r2;
	r7 = 2.;
	r3 = r3 / r7;
	r2 = 24;
	r5 = hl_alloc_bytes(r2);
	r2 = 0;
	r6 = (int)r3;
	r7 = (double)r6;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r7;
	++r2;
	r7 = 0.;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r7;
	++r2;
	r7 = 0.;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r7;
	++r2;
	r2 = 3;
	r8 = hl_types_ArrayBase_allocF64(r5,r2);
	r2 = r0->sizeY;
	r7 = (double)r2;
	r9 = 2.;
	r7 = r7 / r9;
	r2 = 24;
	r5 = hl_alloc_bytes(r2);
	r2 = 0;
	r9 = 0.;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r9;
	++r2;
	r6 = (int)r7;
	r6 = -r6;
	r9 = (double)r6;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r9;
	++r2;
	r9 = 0.;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r9;
	++r2;
	r2 = 3;
	r10 = hl_types_ArrayBase_allocF64(r5,r2);
	r2 = r0->sizeY;
	r9 = (double)r2;
	r11 = 2.;
	r9 = r9 / r11;
	r14 = &t$hl_types_ArrayBytes_Float;
	r2 = 4;
	r13 = hl_alloc_array(r14,r2);
	r2 = 0;
	((hl__types__ArrayBytes_Float*)(r13 + 1))[r2] = r4;
	r2 = 1;
	((hl__types__ArrayBytes_Float*)(r13 + 1))[r2] = r8;
	r2 = 2;
	((hl__types__ArrayBytes_Float*)(r13 + 1))[r2] = r10;
	r2 = 24;
	r5 = hl_alloc_bytes(r2);
	r2 = 0;
	r11 = 0.;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r11;
	++r2;
	r6 = (int)r9;
	r11 = (double)r6;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r11;
	++r2;
	r11 = 0.;
	r6 = 3;
	r6 = r2 << r6;
	*(double*)(r5 + r6) = r11;
	++r2;
	r2 = 3;
	r15 = hl_types_ArrayBase_allocF64(r5,r2);
	r2 = 3;
	((hl__types__ArrayBytes_Float*)(r13 + 1))[r2] = r15;
	r12 = hl_types_ArrayObj_alloc(r13);
	return r12;
}

void ExtendableObject_rotateConnected(ExtendableObject r0,double r1) {
	ExtendableObject r17;
	hl__types__ArrayObj r12;
	ConnectorLink r14;
	$Math r5;
	hl__types__ArrayBytes_Float r18, r19, r20;
	double r2, r3, r4, r7, r8, r9, r22, r25, r26;
	vdynamic *r15;
	vbyte *r21, *r24;
	varray *r16;
	int r10, r11, r13, r23;
	r2 = r0->angle;
	r3 = 2.;
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	r3 = r3 * r4;
	r2 = fmod(r2,r3);
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	if( !(r4 < r2) ) goto label$6602245_2_16;
	r4 = 2.;
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	r4 = r4 * r7;
	r3 = r2 - r4;
	r2 = r3;
	goto label$6602245_2_26;
	label$6602245_2_16:
	r5 = ($Math)g$_Math;
	r4 = r5->PI;
	r4 = -r4;
	if( !(r2 < r4) ) goto label$6602245_2_26;
	r4 = 2.;
	r5 = ($Math)g$_Math;
	r7 = r5->PI;
	r4 = r4 * r7;
	r3 = r2 + r4;
	r2 = r3;
	label$6602245_2_26:
	r3 = hl_math_abs(r2);
	r4 = 0.5;
	if( !(r3 < r4) ) goto label$6602245_2_35;
	r3 = 1.;
	r4 = r2 * r2;
	r7 = 2.;
	r4 = r4 / r7;
	r3 = r3 - r4;
	goto label$6602245_2_36;
	label$6602245_2_35:
	r3 = hl_math_cos(r2);
	label$6602245_2_36:
	r4 = r0->angle;
	r7 = 2.;
	r5 = ($Math)g$_Math;
	r8 = r5->PI;
	r7 = r7 * r8;
	r4 = fmod(r4,r7);
	r5 = ($Math)g$_Math;
	r8 = r5->PI;
	if( !(r8 < r4) ) goto label$6602245_2_52;
	r8 = 2.;
	r5 = ($Math)g$_Math;
	r9 = r5->PI;
	r8 = r8 * r9;
	r7 = r4 - r8;
	r4 = r7;
	goto label$6602245_2_62;
	label$6602245_2_52:
	r5 = ($Math)g$_Math;
	r8 = r5->PI;
	r8 = -r8;
	if( !(r4 < r8) ) goto label$6602245_2_62;
	r8 = 2.;
	r5 = ($Math)g$_Math;
	r9 = r5->PI;
	r8 = r8 * r9;
	r7 = r4 + r8;
	r4 = r7;
	label$6602245_2_62:
	r7 = hl_math_abs(r4);
	r8 = 0.5;
	if( !(r7 < r8) ) goto label$6602245_2_71;
	r8 = r4 * r4;
	r8 = r8 * r4;
	r9 = 6.;
	r8 = r8 / r9;
	r7 = r4 - r8;
	goto label$6602245_2_72;
	label$6602245_2_71:
	r7 = hl_math_sin(r4);
	label$6602245_2_72:
	r10 = -1;
	label$6602245_2_73:
	++r10;
	r12 = r0->linked;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->length;
	if( r10 >= r11 ) goto label$6602245_2_199;
	r12 = r0->linked;
	if( r12 == NULL ) hl_null_access();
	r13 = r12->length;
	if( ((unsigned)r10) < ((unsigned)r13) ) goto label$6602245_2_85;
	r14 = NULL;
	goto label$6602245_2_88;
	label$6602245_2_85:
	r16 = r12->array;
	r15 = ((vdynamic**)(r16 + 1))[r10];
	r14 = (ConnectorLink)r15;
	label$6602245_2_88:
	if( r14 == NULL ) hl_null_access();
	r17 = r14->connected;
	r18 = r14->from;
	r19 = r14->to;
	if( r18 == NULL ) hl_null_access();
	r11 = 0;
	r13 = r18->length;
	if( ((unsigned)r11) < ((unsigned)r13) ) goto label$6602245_2_98;
	r8 = 0.;
	goto label$6602245_2_102;
	label$6602245_2_98:
	r21 = r18->bytes;
	r13 = 3;
	r13 = r11 << r13;
	r8 = *(double*)(r21 + r13);
	label$6602245_2_102:
	if( r19 == NULL ) hl_null_access();
	r11 = 0;
	r13 = r19->length;
	if( ((unsigned)r11) < ((unsigned)r13) ) goto label$6602245_2_108;
	r9 = 0.;
	goto label$6602245_2_112;
	label$6602245_2_108:
	r21 = r19->bytes;
	r13 = 3;
	r13 = r11 << r13;
	r9 = *(double*)(r21 + r13);
	label$6602245_2_112:
	r8 = r8 - r9;
	r11 = 1;
	r13 = r18->length;
	if( ((unsigned)r11) < ((unsigned)r13) ) goto label$6602245_2_118;
	r9 = 0.;
	goto label$6602245_2_122;
	label$6602245_2_118:
	r21 = r18->bytes;
	r13 = 3;
	r13 = r11 << r13;
	r9 = *(double*)(r21 + r13);
	label$6602245_2_122:
	r11 = 1;
	r13 = r19->length;
	if( ((unsigned)r11) < ((unsigned)r13) ) goto label$6602245_2_127;
	r22 = 0.;
	goto label$6602245_2_131;
	label$6602245_2_127:
	r21 = r19->bytes;
	r13 = 3;
	r13 = r11 << r13;
	r22 = *(double*)(r21 + r13);
	label$6602245_2_131:
	r9 = r9 - r22;
	if( r17 == NULL ) hl_null_access();
	r11 = 24;
	r21 = hl_alloc_bytes(r11);
	r11 = 0;
	r20 = r0->pos;
	if( r20 == NULL ) hl_null_access();
	r13 = 0;
	r23 = r20->length;
	if( ((unsigned)r13) < ((unsigned)r23) ) goto label$6602245_2_143;
	r22 = 0.;
	goto label$6602245_2_147;
	label$6602245_2_143:
	r24 = r20->bytes;
	r23 = 3;
	r23 = r13 << r23;
	r22 = *(double*)(r24 + r23);
	label$6602245_2_147:
	r25 = r8 * r3;
	r26 = r9 * r7;
	r25 = r25 - r26;
	r22 = r22 + r25;
	r13 = 3;
	r13 = r11 << r13;
	*(double*)(r21 + r13) = r22;
	++r11;
	r20 = r0->pos;
	if( r20 == NULL ) hl_null_access();
	r13 = 1;
	r23 = r20->length;
	if( ((unsigned)r13) < ((unsigned)r23) ) goto label$6602245_2_162;
	r22 = 0.;
	goto label$6602245_2_166;
	label$6602245_2_162:
	r24 = r20->bytes;
	r23 = 3;
	r23 = r13 << r23;
	r22 = *(double*)(r24 + r23);
	label$6602245_2_166:
	r25 = r8 * r7;
	r26 = r9 * r3;
	r25 = r25 + r26;
	r22 = r22 + r25;
	r13 = 3;
	r13 = r11 << r13;
	*(double*)(r21 + r13) = r22;
	++r11;
	r22 = 0.;
	r13 = 3;
	r13 = r11 << r13;
	*(double*)(r21 + r13) = r22;
	++r11;
	r11 = 3;
	r20 = hl_types_ArrayBase_allocF64(r21,r11);
	r17->pos = r20;
	r22 = r0->angle;
	r17->angle = r22;
	r22 = r0->heat;
	r25 = r17->heat;
	r22 = r22 - r25;
	r25 = r0->heatConductivityF;
	r22 = r22 * r25;
	r22 = r22 * r1;
	r25 = 0.10000000000000001;
	r22 = r22 * r25;
	r25 = r17->heat;
	r25 = r25 + r22;
	r17->heat = r25;
	r25 = r0->heat;
	r25 = r25 - r22;
	r0->heat = r25;
	goto label$6602245_2_73;
	label$6602245_2_199:
	r8 = r0->heat;
	r9 = 10000000.;
	r22 = r0->heat;
	r9 = r9 - r22;
	r22 = 1000000.;
	r9 = r9 / r22;
	r22 = 1360.;
	r9 = r9 * r22;
	r22 = r0->heatInF;
	r9 = r9 * r22;
	r9 = r9 * r1;
	r22 = 0.10000000000000001;
	r9 = r9 * r22;
	r8 = r8 + r9;
	r0->heat = r8;
	r9 = -300000.;
	r22 = r0->heat;
	r9 = r9 - r22;
	r22 = -300000.;
	r9 = r9 / r22;
	r22 = r0->heat;
	r9 = r9 * r22;
	r22 = r0->heatOutF;
	r9 = r9 * r22;
	r9 = r9 * r1;
	r22 = 0.10000000000000001;
	r9 = r9 * r22;
	r8 = r8 - r9;
	r0->heat = r8;
	return;
}

void ExtendableObject_receiveSunHeat(ExtendableObject r0,double r1,double r2) {
	double r3, r4, r5;
	r3 = r0->heat;
	r4 = 10000000.;
	r5 = r0->heat;
	r4 = r4 - r5;
	r5 = 1000000.;
	r4 = r4 / r5;
	r4 = r4 * r2;
	r5 = r0->heatInF;
	r4 = r4 * r5;
	r4 = r4 * r1;
	r5 = 0.10000000000000001;
	r4 = r4 * r5;
	r3 = r3 + r4;
	r0->heat = r3;
	r4 = -300000.;
	r5 = r0->heat;
	r4 = r4 - r5;
	r5 = -300000.;
	r4 = r4 / r5;
	r5 = r0->heat;
	r4 = r4 * r5;
	r5 = r0->heatOutF;
	r4 = r4 * r5;
	r4 = r4 * r1;
	r5 = 0.10000000000000001;
	r4 = r4 * r5;
	r3 = r3 - r4;
	r0->heat = r3;
	return;
}

void ExtendableObject_draw(ExtendableObject r0) {
	String r3, r9;
	bool r2;
	double r4, r5;
	int *r7;
	vbyte *r8;
	int r6, r10, r11, r12, r13, r14;
	r2 = r0->selected;
	if( !r2 ) goto label$6602245_4_48;
	r3 = (String)s$Temperature_;
	r4 = r0->heat;
	r5 = 1000.;
	r4 = r4 / r5;
	r7 = &r6;
	r8 = hl_ftos(r4,r7);
	r9 = String___alloc__(r8,r6);
	r3 = String___add__(r3,r9);
	r6 = 500;
	r10 = 100;
	r11 = 2432799;
	r7 = &r11;
	util_FontManager_drawText(r3,r6,r10,r7);
	r3 = (String)s$Conductivity_F_;
	r4 = r0->heatConductivityF;
	r7 = &r6;
	r8 = hl_ftos(r4,r7);
	r9 = String___alloc__(r8,r6);
	r3 = String___add__(r3,r9);
	r6 = 500;
	r10 = 82;
	r12 = 3023651;
	r7 = &r12;
	util_FontManager_drawText(r3,r6,r10,r7);
	r3 = (String)s$Absorptivity_F_;
	r4 = r0->heatInF;
	r7 = &r6;
	r8 = hl_ftos(r4,r7);
	r9 = String___alloc__(r8,r6);
	r3 = String___add__(r3,r9);
	r6 = 500;
	r10 = 64;
	r13 = 3023651;
	r7 = &r13;
	util_FontManager_drawText(r3,r6,r10,r7);
	r3 = (String)s$Emission_F_;
	r4 = r0->heatOutF;
	r7 = &r6;
	r8 = hl_ftos(r4,r7);
	r9 = String___alloc__(r8,r6);
	r3 = String___add__(r3,r9);
	r6 = 500;
	r10 = 46;
	r14 = 3023651;
	r7 = &r14;
	util_FontManager_drawText(r3,r6,r10,r7);
	label$6602245_4_48:
	Object_draw(((Object)r0));
	return;
}

hl__types__ArrayBytes_Float ExtendableObject_getConnectorPos(ExtendableObject r0,ExtendableObject r1,hl__types__ArrayBytes_Float r2) {
	$Math r6;
	hl__types__ArrayBytes_Float r10;
	double r3, r4, r5, r7, r8, r9;
	int r12, r13, r14;
	vbyte *r11, *r15;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->angle;
	r4 = 2.;
	r6 = ($Math)g$_Math;
	r5 = r6->PI;
	r4 = r4 * r5;
	r3 = fmod(r3,r4);
	r6 = ($Math)g$_Math;
	r5 = r6->PI;
	if( !(r5 < r3) ) goto label$6602245_5_17;
	r5 = 2.;
	r6 = ($Math)g$_Math;
	r7 = r6->PI;
	r5 = r5 * r7;
	r4 = r3 - r5;
	r3 = r4;
	goto label$6602245_5_27;
	label$6602245_5_17:
	r6 = ($Math)g$_Math;
	r5 = r6->PI;
	r5 = -r5;
	if( !(r3 < r5) ) goto label$6602245_5_27;
	r5 = 2.;
	r6 = ($Math)g$_Math;
	r7 = r6->PI;
	r5 = r5 * r7;
	r4 = r3 + r5;
	r3 = r4;
	label$6602245_5_27:
	r4 = hl_math_abs(r3);
	r5 = 0.5;
	if( !(r4 < r5) ) goto label$6602245_5_36;
	r4 = 1.;
	r5 = r3 * r3;
	r7 = 2.;
	r5 = r5 / r7;
	r4 = r4 - r5;
	goto label$6602245_5_37;
	label$6602245_5_36:
	r4 = hl_math_cos(r3);
	label$6602245_5_37:
	r5 = r1->angle;
	r7 = 2.;
	r6 = ($Math)g$_Math;
	r8 = r6->PI;
	r7 = r7 * r8;
	r5 = fmod(r5,r7);
	r6 = ($Math)g$_Math;
	r8 = r6->PI;
	if( !(r8 < r5) ) goto label$6602245_5_53;
	r8 = 2.;
	r6 = ($Math)g$_Math;
	r9 = r6->PI;
	r8 = r8 * r9;
	r7 = r5 - r8;
	r5 = r7;
	goto label$6602245_5_63;
	label$6602245_5_53:
	r6 = ($Math)g$_Math;
	r8 = r6->PI;
	r8 = -r8;
	if( !(r5 < r8) ) goto label$6602245_5_63;
	r8 = 2.;
	r6 = ($Math)g$_Math;
	r9 = r6->PI;
	r8 = r8 * r9;
	r7 = r5 + r8;
	r5 = r7;
	label$6602245_5_63:
	r7 = hl_math_abs(r5);
	r8 = 0.5;
	if( !(r7 < r8) ) goto label$6602245_5_72;
	r8 = r5 * r5;
	r8 = r8 * r5;
	r9 = 6.;
	r8 = r8 / r9;
	r7 = r5 - r8;
	goto label$6602245_5_73;
	label$6602245_5_72:
	r7 = hl_math_sin(r5);
	label$6602245_5_73:
	r12 = 24;
	r11 = hl_alloc_bytes(r12);
	r12 = 0;
	r10 = r1->pos;
	if( r10 == NULL ) hl_null_access();
	r13 = 0;
	r14 = r10->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_5_83;
	r8 = 0.;
	goto label$6602245_5_87;
	label$6602245_5_83:
	r15 = r10->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r8 = *(double*)(r15 + r14);
	label$6602245_5_87:
	if( r2 == NULL ) hl_null_access();
	r13 = 0;
	r14 = r2->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_5_93;
	r9 = 0.;
	goto label$6602245_5_97;
	label$6602245_5_93:
	r15 = r2->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r9 = *(double*)(r15 + r14);
	label$6602245_5_97:
	r9 = r9 * r4;
	r8 = r8 + r9;
	r13 = 1;
	r14 = r2->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_5_104;
	r9 = 0.;
	goto label$6602245_5_108;
	label$6602245_5_104:
	r15 = r2->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r9 = *(double*)(r15 + r14);
	label$6602245_5_108:
	r9 = r9 * r7;
	r8 = r8 - r9;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r11 + r13) = r8;
	++r12;
	r10 = r1->pos;
	if( r10 == NULL ) hl_null_access();
	r13 = 1;
	r14 = r10->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_5_121;
	r8 = 0.;
	goto label$6602245_5_125;
	label$6602245_5_121:
	r15 = r10->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r8 = *(double*)(r15 + r14);
	label$6602245_5_125:
	r13 = 0;
	r14 = r2->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_5_130;
	r9 = 0.;
	goto label$6602245_5_134;
	label$6602245_5_130:
	r15 = r2->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r9 = *(double*)(r15 + r14);
	label$6602245_5_134:
	r9 = r9 * r7;
	r8 = r8 + r9;
	r13 = 1;
	r14 = r2->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_5_141;
	r9 = 0.;
	goto label$6602245_5_145;
	label$6602245_5_141:
	r15 = r2->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r9 = *(double*)(r15 + r14);
	label$6602245_5_145:
	r9 = r9 * r4;
	r8 = r8 + r9;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r11 + r13) = r8;
	++r12;
	r8 = 0.;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r11 + r13) = r8;
	++r12;
	r12 = 3;
	r10 = hl_types_ArrayBase_allocF64(r11,r12);
	return r10;
}

hl__types__ArrayBytes_Float ExtendableObject_getNearestConnector(ExtendableObject r0,ExtendableObject r1,hl__types__ArrayBytes_Float r2,bool* r3) {
	String r36, r39;
	vvirtual *r35;
	hl__types__ArrayObj r7;
	hl_type *r38;
	bool r4, r15;
	haxe__$Log r32;
	$Math r21;
	hl__types__ArrayBytes_Float r10, r17, r25;
	hl__types__ArrayDyn r37;
	vclosure *r31;
	double r5, r18, r19, r20, r22, r23, r24, r27, r28, r29, r30;
	vdynamic *r11;
	vbyte *r26, *r34;
	varray *r12;
	int r8, r9, r13, r14, r16, r33;
	if( r3 ) goto label$6602245_6_3;
	r4 = false;
	goto label$6602245_6_4;
	label$6602245_6_3:
	r4 = *r3;
	label$6602245_6_4:
	r5 = 9999.;
	if( r1 == NULL ) hl_null_access();
	r7 = r1->connectors;
	if( r7 == NULL ) hl_null_access();
	r8 = 0;
	r9 = r7->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$6602245_6_13;
	r10 = NULL;
	goto label$6602245_6_16;
	label$6602245_6_13:
	r12 = r7->array;
	r11 = ((vdynamic**)(r12 + 1))[r8];
	r10 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_6_16:
	r8 = 0;
	r7 = r1->connectors;
	if( r7 == NULL ) hl_null_access();
	r9 = r7->length;
	label$6602245_6_20:
	if( r8 >= r9 ) goto label$6602245_6_554;
	r13 = r8;
	++r8;
	if( r4 ) goto label$6602245_6_201;
	if( r1 == NULL ) hl_null_access();
	r7 = r1->connectors;
	if( r7 == NULL ) hl_null_access();
	r16 = r7->length;
	if( ((unsigned)r13) < ((unsigned)r16) ) goto label$6602245_6_32;
	r17 = NULL;
	goto label$6602245_6_35;
	label$6602245_6_32:
	r12 = r7->array;
	r11 = ((vdynamic**)(r12 + 1))[r13];
	r17 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_6_35:
	r18 = r1->angle;
	r19 = 2.;
	r21 = ($Math)g$_Math;
	r20 = r21->PI;
	r19 = r19 * r20;
	r18 = fmod(r18,r19);
	r21 = ($Math)g$_Math;
	r20 = r21->PI;
	if( !(r20 < r18) ) goto label$6602245_6_51;
	r20 = 2.;
	r21 = ($Math)g$_Math;
	r22 = r21->PI;
	r20 = r20 * r22;
	r19 = r18 - r20;
	r18 = r19;
	goto label$6602245_6_61;
	label$6602245_6_51:
	r21 = ($Math)g$_Math;
	r20 = r21->PI;
	r20 = -r20;
	if( !(r18 < r20) ) goto label$6602245_6_61;
	r20 = 2.;
	r21 = ($Math)g$_Math;
	r22 = r21->PI;
	r20 = r20 * r22;
	r19 = r18 + r20;
	r18 = r19;
	label$6602245_6_61:
	r19 = hl_math_abs(r18);
	r20 = 0.5;
	if( !(r19 < r20) ) goto label$6602245_6_70;
	r19 = 1.;
	r20 = r18 * r18;
	r22 = 2.;
	r20 = r20 / r22;
	r19 = r19 - r20;
	goto label$6602245_6_71;
	label$6602245_6_70:
	r19 = hl_math_cos(r18);
	label$6602245_6_71:
	r20 = r1->angle;
	r22 = 2.;
	r21 = ($Math)g$_Math;
	r23 = r21->PI;
	r22 = r22 * r23;
	r20 = fmod(r20,r22);
	r21 = ($Math)g$_Math;
	r23 = r21->PI;
	if( !(r23 < r20) ) goto label$6602245_6_87;
	r23 = 2.;
	r21 = ($Math)g$_Math;
	r24 = r21->PI;
	r23 = r23 * r24;
	r22 = r20 - r23;
	r20 = r22;
	goto label$6602245_6_97;
	label$6602245_6_87:
	r21 = ($Math)g$_Math;
	r23 = r21->PI;
	r23 = -r23;
	if( !(r20 < r23) ) goto label$6602245_6_97;
	r23 = 2.;
	r21 = ($Math)g$_Math;
	r24 = r21->PI;
	r23 = r23 * r24;
	r22 = r20 + r23;
	r20 = r22;
	label$6602245_6_97:
	r22 = hl_math_abs(r20);
	r23 = 0.5;
	if( !(r22 < r23) ) goto label$6602245_6_106;
	r23 = r20 * r20;
	r23 = r23 * r20;
	r24 = 6.;
	r23 = r23 / r24;
	r22 = r20 - r23;
	goto label$6602245_6_107;
	label$6602245_6_106:
	r22 = hl_math_sin(r20);
	label$6602245_6_107:
	if( r2 == NULL ) hl_null_access();
	r14 = 0;
	r16 = r2->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_113;
	r23 = 0.;
	goto label$6602245_6_117;
	label$6602245_6_113:
	r26 = r2->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r23 = *(double*)(r26 + r16);
	label$6602245_6_117:
	r25 = r1->pos;
	if( r25 == NULL ) hl_null_access();
	r14 = 0;
	r16 = r25->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_124;
	r24 = 0.;
	goto label$6602245_6_128;
	label$6602245_6_124:
	r26 = r25->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r24 = *(double*)(r26 + r16);
	label$6602245_6_128:
	if( r17 == NULL ) hl_null_access();
	r14 = 0;
	r16 = r17->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_134;
	r27 = 0.;
	goto label$6602245_6_138;
	label$6602245_6_134:
	r26 = r17->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r27 = *(double*)(r26 + r16);
	label$6602245_6_138:
	r27 = r27 * r19;
	r24 = r24 + r27;
	r14 = 1;
	r16 = r17->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_145;
	r27 = 0.;
	goto label$6602245_6_149;
	label$6602245_6_145:
	r26 = r17->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r27 = *(double*)(r26 + r16);
	label$6602245_6_149:
	r27 = r27 * r22;
	r24 = r24 - r27;
	r23 = r23 - r24;
	r14 = 1;
	r16 = r2->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_157;
	r24 = 0.;
	goto label$6602245_6_161;
	label$6602245_6_157:
	r26 = r2->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r24 = *(double*)(r26 + r16);
	label$6602245_6_161:
	r25 = r1->pos;
	if( r25 == NULL ) hl_null_access();
	r14 = 1;
	r16 = r25->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_168;
	r27 = 0.;
	goto label$6602245_6_172;
	label$6602245_6_168:
	r26 = r25->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r27 = *(double*)(r26 + r16);
	label$6602245_6_172:
	r14 = 0;
	r16 = r17->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_177;
	r28 = 0.;
	goto label$6602245_6_181;
	label$6602245_6_177:
	r26 = r17->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r28 = *(double*)(r26 + r16);
	label$6602245_6_181:
	r28 = r28 * r22;
	r27 = r27 + r28;
	r14 = 1;
	r16 = r17->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_188;
	r28 = 0.;
	goto label$6602245_6_192;
	label$6602245_6_188:
	r26 = r17->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r28 = *(double*)(r26 + r16);
	label$6602245_6_192:
	r28 = r28 * r19;
	r27 = r27 + r28;
	r24 = r24 - r27;
	r28 = r23 * r23;
	r29 = r24 * r24;
	r28 = r28 + r29;
	r28 = hl_math_sqrt(r28);
	r27 = r28;
	goto label$6602245_6_363;
	label$6602245_6_201:
	if( r1 == NULL ) hl_null_access();
	r7 = r1->connectors;
	if( r7 == NULL ) hl_null_access();
	r16 = r7->length;
	if( ((unsigned)r13) < ((unsigned)r16) ) goto label$6602245_6_208;
	r17 = NULL;
	goto label$6602245_6_211;
	label$6602245_6_208:
	r12 = r7->array;
	r11 = ((vdynamic**)(r12 + 1))[r13];
	r17 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_6_211:
	r18 = r0->angle;
	r19 = r0->localAngle;
	r18 = r18 + r19;
	r19 = 2.;
	r21 = ($Math)g$_Math;
	r20 = r21->PI;
	r19 = r19 * r20;
	r18 = fmod(r18,r19);
	r21 = ($Math)g$_Math;
	r19 = r21->PI;
	r18 = r18 * r19;
	r19 = 180.;
	r18 = r18 / r19;
	r20 = 2.;
	r21 = ($Math)g$_Math;
	r22 = r21->PI;
	r20 = r20 * r22;
	r19 = fmod(r18,r20);
	r21 = ($Math)g$_Math;
	r22 = r21->PI;
	if( !(r22 < r19) ) goto label$6602245_6_239;
	r22 = 2.;
	r21 = ($Math)g$_Math;
	r23 = r21->PI;
	r22 = r22 * r23;
	r20 = r19 - r22;
	r19 = r20;
	goto label$6602245_6_249;
	label$6602245_6_239:
	r21 = ($Math)g$_Math;
	r22 = r21->PI;
	r22 = -r22;
	if( !(r19 < r22) ) goto label$6602245_6_249;
	r22 = 2.;
	r21 = ($Math)g$_Math;
	r23 = r21->PI;
	r22 = r22 * r23;
	r20 = r19 + r22;
	r19 = r20;
	label$6602245_6_249:
	r20 = hl_math_abs(r19);
	r22 = 0.5;
	if( !(r20 < r22) ) goto label$6602245_6_258;
	r20 = 1.;
	r22 = r19 * r19;
	r23 = 2.;
	r22 = r22 / r23;
	r20 = r20 - r22;
	goto label$6602245_6_259;
	label$6602245_6_258:
	r20 = hl_math_cos(r19);
	label$6602245_6_259:
	r23 = 2.;
	r21 = ($Math)g$_Math;
	r24 = r21->PI;
	r23 = r23 * r24;
	r22 = fmod(r18,r23);
	r21 = ($Math)g$_Math;
	r24 = r21->PI;
	if( !(r24 < r22) ) goto label$6602245_6_274;
	r24 = 2.;
	r21 = ($Math)g$_Math;
	r28 = r21->PI;
	r24 = r24 * r28;
	r23 = r22 - r24;
	r22 = r23;
	goto label$6602245_6_284;
	label$6602245_6_274:
	r21 = ($Math)g$_Math;
	r24 = r21->PI;
	r24 = -r24;
	if( !(r22 < r24) ) goto label$6602245_6_284;
	r24 = 2.;
	r21 = ($Math)g$_Math;
	r28 = r21->PI;
	r24 = r24 * r28;
	r23 = r22 + r24;
	r22 = r23;
	label$6602245_6_284:
	r23 = hl_math_abs(r22);
	r24 = 0.5;
	if( !(r23 < r24) ) goto label$6602245_6_293;
	r24 = r22 * r22;
	r24 = r24 * r22;
	r28 = 6.;
	r24 = r24 / r28;
	r23 = r22 - r24;
	goto label$6602245_6_294;
	label$6602245_6_293:
	r23 = hl_math_sin(r22);
	label$6602245_6_294:
	if( r2 == NULL ) hl_null_access();
	r14 = 0;
	r16 = r2->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_300;
	r24 = 0.;
	goto label$6602245_6_304;
	label$6602245_6_300:
	r26 = r2->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r24 = *(double*)(r26 + r16);
	label$6602245_6_304:
	if( r17 == NULL ) hl_null_access();
	r14 = 0;
	r16 = r17->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_310;
	r28 = 0.;
	goto label$6602245_6_314;
	label$6602245_6_310:
	r26 = r17->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r28 = *(double*)(r26 + r16);
	label$6602245_6_314:
	r28 = r28 * r20;
	r14 = 1;
	r16 = r17->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_320;
	r29 = 0.;
	goto label$6602245_6_324;
	label$6602245_6_320:
	r26 = r17->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r29 = *(double*)(r26 + r16);
	label$6602245_6_324:
	r29 = r29 * r23;
	r28 = r28 - r29;
	r24 = r24 - r28;
	r14 = 1;
	r16 = r2->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_332;
	r28 = 0.;
	goto label$6602245_6_336;
	label$6602245_6_332:
	r26 = r2->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r28 = *(double*)(r26 + r16);
	label$6602245_6_336:
	r14 = 0;
	r16 = r17->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_341;
	r29 = 0.;
	goto label$6602245_6_345;
	label$6602245_6_341:
	r26 = r17->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r29 = *(double*)(r26 + r16);
	label$6602245_6_345:
	r29 = r29 * r23;
	r14 = 1;
	r16 = r17->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$6602245_6_351;
	r30 = 0.;
	goto label$6602245_6_355;
	label$6602245_6_351:
	r26 = r17->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r30 = *(double*)(r26 + r16);
	label$6602245_6_355:
	r30 = r30 * r20;
	r29 = r29 + r30;
	r28 = r28 - r29;
	r29 = r24 * r24;
	r30 = r28 * r28;
	r29 = r29 + r30;
	r29 = hl_math_sqrt(r29);
	r27 = r29;
	label$6602245_6_363:
	if( !r4 ) goto label$6602245_6_541;
	r32 = (haxe__$Log)g$_haxe_Log;
	r31 = r32->trace;
	r7 = r1->connectors;
	if( r7 == NULL ) hl_null_access();
	r16 = r7->length;
	if( ((unsigned)r13) < ((unsigned)r16) ) goto label$6602245_6_372;
	r17 = NULL;
	goto label$6602245_6_375;
	label$6602245_6_372:
	r12 = r7->array;
	r11 = ((vdynamic**)(r12 + 1))[r13];
	r17 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_6_375:
	r18 = r0->angle;
	r19 = r0->localAngle;
	r18 = r18 + r19;
	r19 = 2.;
	r21 = ($Math)g$_Math;
	r20 = r21->PI;
	r19 = r19 * r20;
	r18 = fmod(r18,r19);
	r21 = ($Math)g$_Math;
	r19 = r21->PI;
	r18 = r18 * r19;
	r19 = 180.;
	r18 = r18 / r19;
	r20 = 2.;
	r21 = ($Math)g$_Math;
	r22 = r21->PI;
	r20 = r20 * r22;
	r19 = fmod(r18,r20);
	r21 = ($Math)g$_Math;
	r22 = r21->PI;
	if( !(r22 < r19) ) goto label$6602245_6_403;
	r22 = 2.;
	r21 = ($Math)g$_Math;
	r23 = r21->PI;
	r22 = r22 * r23;
	r20 = r19 - r22;
	r19 = r20;
	goto label$6602245_6_413;
	label$6602245_6_403:
	r21 = ($Math)g$_Math;
	r22 = r21->PI;
	r22 = -r22;
	if( !(r19 < r22) ) goto label$6602245_6_413;
	r22 = 2.;
	r21 = ($Math)g$_Math;
	r23 = r21->PI;
	r22 = r22 * r23;
	r20 = r19 + r22;
	r19 = r20;
	label$6602245_6_413:
	r20 = hl_math_abs(r19);
	r22 = 0.5;
	if( !(r20 < r22) ) goto label$6602245_6_422;
	r20 = 1.;
	r22 = r19 * r19;
	r23 = 2.;
	r22 = r22 / r23;
	r20 = r20 - r22;
	goto label$6602245_6_423;
	label$6602245_6_422:
	r20 = hl_math_cos(r19);
	label$6602245_6_423:
	r23 = 2.;
	r21 = ($Math)g$_Math;
	r24 = r21->PI;
	r23 = r23 * r24;
	r22 = fmod(r18,r23);
	r21 = ($Math)g$_Math;
	r24 = r21->PI;
	if( !(r24 < r22) ) goto label$6602245_6_438;
	r24 = 2.;
	r21 = ($Math)g$_Math;
	r28 = r21->PI;
	r24 = r24 * r28;
	r23 = r22 - r24;
	r22 = r23;
	goto label$6602245_6_448;
	label$6602245_6_438:
	r21 = ($Math)g$_Math;
	r24 = r21->PI;
	r24 = -r24;
	if( !(r22 < r24) ) goto label$6602245_6_448;
	r24 = 2.;
	r21 = ($Math)g$_Math;
	r28 = r21->PI;
	r24 = r24 * r28;
	r23 = r22 + r24;
	r22 = r23;
	label$6602245_6_448:
	r23 = hl_math_abs(r22);
	r24 = 0.5;
	if( !(r23 < r24) ) goto label$6602245_6_457;
	r24 = r22 * r22;
	r24 = r24 * r22;
	r28 = 6.;
	r24 = r24 / r28;
	r23 = r22 - r24;
	goto label$6602245_6_458;
	label$6602245_6_457:
	r23 = hl_math_sin(r22);
	label$6602245_6_458:
	if( r31 == NULL ) hl_null_access();
	r14 = 24;
	r26 = hl_alloc_bytes(r14);
	r14 = 0;
	if( r17 == NULL ) hl_null_access();
	r16 = 0;
	r33 = r17->length;
	if( ((unsigned)r16) < ((unsigned)r33) ) goto label$6602245_6_468;
	r24 = 0.;
	goto label$6602245_6_472;
	label$6602245_6_468:
	r34 = r17->bytes;
	r33 = 3;
	r33 = r16 << r33;
	r24 = *(double*)(r34 + r33);
	label$6602245_6_472:
	r24 = r24 * r20;
	r16 = 1;
	r33 = r17->length;
	if( ((unsigned)r16) < ((unsigned)r33) ) goto label$6602245_6_478;
	r28 = 0.;
	goto label$6602245_6_482;
	label$6602245_6_478:
	r34 = r17->bytes;
	r33 = 3;
	r33 = r16 << r33;
	r28 = *(double*)(r34 + r33);
	label$6602245_6_482:
	r28 = r28 * r23;
	r24 = r24 - r28;
	r16 = 3;
	r16 = r14 << r16;
	*(double*)(r26 + r16) = r24;
	++r14;
	r16 = 0;
	r33 = r17->length;
	if( ((unsigned)r16) < ((unsigned)r33) ) goto label$6602245_6_493;
	r24 = 0.;
	goto label$6602245_6_497;
	label$6602245_6_493:
	r34 = r17->bytes;
	r33 = 3;
	r33 = r16 << r33;
	r24 = *(double*)(r34 + r33);
	label$6602245_6_497:
	r24 = r24 * r23;
	r16 = 1;
	r33 = r17->length;
	if( ((unsigned)r16) < ((unsigned)r33) ) goto label$6602245_6_503;
	r28 = 0.;
	goto label$6602245_6_507;
	label$6602245_6_503:
	r34 = r17->bytes;
	r33 = 3;
	r33 = r16 << r33;
	r28 = *(double*)(r34 + r33);
	label$6602245_6_507:
	r28 = r28 * r20;
	r24 = r24 + r28;
	r16 = 3;
	r16 = r14 << r16;
	*(double*)(r26 + r16) = r24;
	++r14;
	r24 = 0.;
	r16 = 3;
	r16 = r14 << r16;
	*(double*)(r26 + r16) = r24;
	++r14;
	r14 = 3;
	r25 = hl_types_ArrayBase_allocF64(r26,r14);
	r35 = hl_alloc_virtual(&t$vrt_eaa6a3b);
	r36 = (String)s$Game_hx;
	if( hl_vfields(r35)[2] ) *(String*)(hl_vfields(r35)[2]) = (String)r36; else hl_dyn_setp(r35->value,37969014/*fileName*/,&t$String,r36);
	r14 = 348;
	if( hl_vfields(r35)[3] ) *(int*)(hl_vfields(r35)[3]) = (int)r14; else hl_dyn_seti(r35->value,371360620/*lineNumber*/,&t$_i32,r14);
	r36 = (String)s$ExtendableObject;
	if( hl_vfields(r35)[0] ) *(String*)(hl_vfields(r35)[0]) = (String)r36; else hl_dyn_setp(r35->value,-63073762/*className*/,&t$String,r36);
	r36 = (String)s$getNearestConnector;
	if( hl_vfields(r35)[4] ) *(String*)(hl_vfields(r35)[4]) = (String)r36; else hl_dyn_setp(r35->value,302979532/*methodName*/,&t$String,r36);
	r38 = &t$_dyn;
	r14 = 1;
	r12 = hl_alloc_array(r38,r14);
	r11 = hl_alloc_dynamic(&t$_f64);
	r11->v.d = r27;
	r14 = 0;
	((vdynamic**)(r12 + 1))[r14] = r11;
	r7 = hl_types_ArrayObj_alloc(r12);
	r15 = true;
	r3 = &r15;
	r37 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r7),r3);
	if( hl_vfields(r35)[1] ) *(hl__types__ArrayDyn*)(hl_vfields(r35)[1]) = (hl__types__ArrayDyn)r37; else hl_dyn_setp(r35->value,-317173289/*customParams*/,&t$hl_types_ArrayDyn,r37);
	r31->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r31->fun)((vdynamic*)r31->value,((vdynamic*)r25),r35) : ((void (*)(vdynamic*,vvirtual*))r31->fun)(((vdynamic*)r25),r35);
	label$6602245_6_541:
	if( !(r27 < r5) ) goto label$6602245_6_553;
	r5 = r27;
	r7 = r1->connectors;
	if( r7 == NULL ) hl_null_access();
	r16 = r7->length;
	if( ((unsigned)r13) < ((unsigned)r16) ) goto label$6602245_6_549;
	r17 = NULL;
	goto label$6602245_6_552;
	label$6602245_6_549:
	r12 = r7->array;
	r11 = ((vdynamic**)(r12 + 1))[r13];
	r17 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_6_552:
	r10 = r17;
	label$6602245_6_553:
	goto label$6602245_6_20;
	label$6602245_6_554:
	if( !r4 ) goto label$6602245_6_579;
	r32 = (haxe__$Log)g$_haxe_Log;
	r31 = r32->trace;
	if( r31 == NULL ) hl_null_access();
	r36 = (String)s$best;
	r35 = hl_alloc_virtual(&t$vrt_eaa6a3b);
	r39 = (String)s$Game_hx;
	if( hl_vfields(r35)[2] ) *(String*)(hl_vfields(r35)[2]) = (String)r39; else hl_dyn_setp(r35->value,37969014/*fileName*/,&t$String,r39);
	r8 = 354;
	if( hl_vfields(r35)[3] ) *(int*)(hl_vfields(r35)[3]) = (int)r8; else hl_dyn_seti(r35->value,371360620/*lineNumber*/,&t$_i32,r8);
	r39 = (String)s$ExtendableObject;
	if( hl_vfields(r35)[0] ) *(String*)(hl_vfields(r35)[0]) = (String)r39; else hl_dyn_setp(r35->value,-63073762/*className*/,&t$String,r39);
	r39 = (String)s$getNearestConnector;
	if( hl_vfields(r35)[4] ) *(String*)(hl_vfields(r35)[4]) = (String)r39; else hl_dyn_setp(r35->value,302979532/*methodName*/,&t$String,r39);
	r38 = &t$_dyn;
	r8 = 1;
	r12 = hl_alloc_array(r38,r8);
	r8 = 0;
	((hl__types__ArrayBytes_Float*)(r12 + 1))[r8] = r10;
	r7 = hl_types_ArrayObj_alloc(r12);
	r15 = true;
	r3 = &r15;
	r37 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r7),r3);
	if( hl_vfields(r35)[1] ) *(hl__types__ArrayDyn*)(hl_vfields(r35)[1]) = (hl__types__ArrayDyn)r37; else hl_dyn_setp(r35->value,-317173289/*customParams*/,&t$hl_types_ArrayDyn,r37);
	r31->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r31->fun)((vdynamic*)r31->value,((vdynamic*)r36),r35) : ((void (*)(vdynamic*,vvirtual*))r31->fun)(((vdynamic*)r36),r35);
	label$6602245_6_579:
	return r10;
}

bool ExtendableObject_connectNearest(ExtendableObject r0,ExtendableObject r1,double r2,double r3) {
	hl__types__ArrayObj r6;
	bool r31;
	$Math r19;
	hl__types__ArrayBytes_Float r9, r15, r23, r29, r30;
	double r4, r16, r17, r18, r20, r21, r22, r25, r26, r27, r28;
	vdynamic *r10;
	vbyte *r24;
	varray *r11;
	int r7, r8, r12, r13, r14;
	r4 = 9999.;
	r6 = r0->connectors;
	if( r6 == NULL ) hl_null_access();
	r7 = 0;
	r8 = r6->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$6602245_7_8;
	r9 = NULL;
	goto label$6602245_7_11;
	label$6602245_7_8:
	r11 = r6->array;
	r10 = ((vdynamic**)(r11 + 1))[r7];
	r9 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r10,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_7_11:
	r7 = 0;
	r6 = r0->connectors;
	if( r6 == NULL ) hl_null_access();
	r8 = r6->length;
	label$6602245_7_15:
	if( r7 >= r8 ) goto label$6602245_7_186;
	r12 = r7;
	++r7;
	r6 = r0->connectors;
	if( r6 == NULL ) hl_null_access();
	r14 = r6->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$6602245_7_25;
	r15 = NULL;
	goto label$6602245_7_28;
	label$6602245_7_25:
	r11 = r6->array;
	r10 = ((vdynamic**)(r11 + 1))[r12];
	r15 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r10,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_7_28:
	r16 = r0->angle;
	r17 = 2.;
	r19 = ($Math)g$_Math;
	r18 = r19->PI;
	r17 = r17 * r18;
	r16 = fmod(r16,r17);
	r19 = ($Math)g$_Math;
	r18 = r19->PI;
	if( !(r18 < r16) ) goto label$6602245_7_44;
	r18 = 2.;
	r19 = ($Math)g$_Math;
	r20 = r19->PI;
	r18 = r18 * r20;
	r17 = r16 - r18;
	r16 = r17;
	goto label$6602245_7_54;
	label$6602245_7_44:
	r19 = ($Math)g$_Math;
	r18 = r19->PI;
	r18 = -r18;
	if( !(r16 < r18) ) goto label$6602245_7_54;
	r18 = 2.;
	r19 = ($Math)g$_Math;
	r20 = r19->PI;
	r18 = r18 * r20;
	r17 = r16 + r18;
	r16 = r17;
	label$6602245_7_54:
	r17 = hl_math_abs(r16);
	r18 = 0.5;
	if( !(r17 < r18) ) goto label$6602245_7_63;
	r17 = 1.;
	r18 = r16 * r16;
	r20 = 2.;
	r18 = r18 / r20;
	r17 = r17 - r18;
	goto label$6602245_7_64;
	label$6602245_7_63:
	r17 = hl_math_cos(r16);
	label$6602245_7_64:
	r18 = r0->angle;
	r20 = 2.;
	r19 = ($Math)g$_Math;
	r21 = r19->PI;
	r20 = r20 * r21;
	r18 = fmod(r18,r20);
	r19 = ($Math)g$_Math;
	r21 = r19->PI;
	if( !(r21 < r18) ) goto label$6602245_7_80;
	r21 = 2.;
	r19 = ($Math)g$_Math;
	r22 = r19->PI;
	r21 = r21 * r22;
	r20 = r18 - r21;
	r18 = r20;
	goto label$6602245_7_90;
	label$6602245_7_80:
	r19 = ($Math)g$_Math;
	r21 = r19->PI;
	r21 = -r21;
	if( !(r18 < r21) ) goto label$6602245_7_90;
	r21 = 2.;
	r19 = ($Math)g$_Math;
	r22 = r19->PI;
	r21 = r21 * r22;
	r20 = r18 + r21;
	r18 = r20;
	label$6602245_7_90:
	r20 = hl_math_abs(r18);
	r21 = 0.5;
	if( !(r20 < r21) ) goto label$6602245_7_99;
	r21 = r18 * r18;
	r21 = r21 * r18;
	r22 = 6.;
	r21 = r21 / r22;
	r20 = r18 - r21;
	goto label$6602245_7_100;
	label$6602245_7_99:
	r20 = hl_math_sin(r18);
	label$6602245_7_100:
	r23 = r0->pos;
	if( r23 == NULL ) hl_null_access();
	r13 = 0;
	r14 = r23->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_107;
	r22 = 0.;
	goto label$6602245_7_111;
	label$6602245_7_107:
	r24 = r23->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r22 = *(double*)(r24 + r14);
	label$6602245_7_111:
	if( r15 == NULL ) hl_null_access();
	r13 = 0;
	r14 = r15->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_117;
	r25 = 0.;
	goto label$6602245_7_121;
	label$6602245_7_117:
	r24 = r15->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r25 = *(double*)(r24 + r14);
	label$6602245_7_121:
	r25 = r25 * r17;
	r22 = r22 + r25;
	r13 = 1;
	r14 = r15->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_128;
	r25 = 0.;
	goto label$6602245_7_132;
	label$6602245_7_128:
	r24 = r15->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r25 = *(double*)(r24 + r14);
	label$6602245_7_132:
	r25 = r25 * r20;
	r22 = r22 - r25;
	r21 = r2 - r22;
	r23 = r0->pos;
	if( r23 == NULL ) hl_null_access();
	r13 = 1;
	r14 = r23->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_142;
	r25 = 0.;
	goto label$6602245_7_146;
	label$6602245_7_142:
	r24 = r23->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r25 = *(double*)(r24 + r14);
	label$6602245_7_146:
	r13 = 0;
	r14 = r15->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_151;
	r26 = 0.;
	goto label$6602245_7_155;
	label$6602245_7_151:
	r24 = r15->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r26 = *(double*)(r24 + r14);
	label$6602245_7_155:
	r26 = r26 * r20;
	r25 = r25 + r26;
	r13 = 1;
	r14 = r15->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_162;
	r26 = 0.;
	goto label$6602245_7_166;
	label$6602245_7_162:
	r24 = r15->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r26 = *(double*)(r24 + r14);
	label$6602245_7_166:
	r26 = r26 * r17;
	r25 = r25 + r26;
	r22 = r3 - r25;
	r26 = r21 * r21;
	r27 = r22 * r22;
	r26 = r26 + r27;
	r26 = hl_math_sqrt(r26);
	if( !(r26 < r4) ) goto label$6602245_7_185;
	r4 = r26;
	r6 = r0->connectors;
	if( r6 == NULL ) hl_null_access();
	r14 = r6->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$6602245_7_181;
	r15 = NULL;
	goto label$6602245_7_184;
	label$6602245_7_181:
	r11 = r6->array;
	r10 = ((vdynamic**)(r11 + 1))[r12];
	r15 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r10,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_7_184:
	r9 = r15;
	label$6602245_7_185:
	goto label$6602245_7_15;
	label$6602245_7_186:
	r15 = r9;
	r16 = 9999.;
	if( r1 == NULL ) hl_null_access();
	r6 = r1->connectors;
	if( r6 == NULL ) hl_null_access();
	r7 = 0;
	r8 = r6->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$6602245_7_196;
	r23 = NULL;
	goto label$6602245_7_199;
	label$6602245_7_196:
	r11 = r6->array;
	r10 = ((vdynamic**)(r11 + 1))[r7];
	r23 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r10,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_7_199:
	r7 = 0;
	r6 = r1->connectors;
	if( r6 == NULL ) hl_null_access();
	r8 = r6->length;
	label$6602245_7_203:
	if( r7 >= r8 ) goto label$6602245_7_375;
	r12 = r7;
	++r7;
	if( r1 == NULL ) hl_null_access();
	r6 = r1->connectors;
	if( r6 == NULL ) hl_null_access();
	r14 = r6->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$6602245_7_214;
	r29 = NULL;
	goto label$6602245_7_217;
	label$6602245_7_214:
	r11 = r6->array;
	r10 = ((vdynamic**)(r11 + 1))[r12];
	r29 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r10,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_7_217:
	r17 = r1->angle;
	r18 = 2.;
	r19 = ($Math)g$_Math;
	r20 = r19->PI;
	r18 = r18 * r20;
	r17 = fmod(r17,r18);
	r19 = ($Math)g$_Math;
	r20 = r19->PI;
	if( !(r20 < r17) ) goto label$6602245_7_233;
	r20 = 2.;
	r19 = ($Math)g$_Math;
	r21 = r19->PI;
	r20 = r20 * r21;
	r18 = r17 - r20;
	r17 = r18;
	goto label$6602245_7_243;
	label$6602245_7_233:
	r19 = ($Math)g$_Math;
	r20 = r19->PI;
	r20 = -r20;
	if( !(r17 < r20) ) goto label$6602245_7_243;
	r20 = 2.;
	r19 = ($Math)g$_Math;
	r21 = r19->PI;
	r20 = r20 * r21;
	r18 = r17 + r20;
	r17 = r18;
	label$6602245_7_243:
	r18 = hl_math_abs(r17);
	r20 = 0.5;
	if( !(r18 < r20) ) goto label$6602245_7_252;
	r18 = 1.;
	r20 = r17 * r17;
	r21 = 2.;
	r20 = r20 / r21;
	r18 = r18 - r20;
	goto label$6602245_7_253;
	label$6602245_7_252:
	r18 = hl_math_cos(r17);
	label$6602245_7_253:
	r20 = r1->angle;
	r21 = 2.;
	r19 = ($Math)g$_Math;
	r22 = r19->PI;
	r21 = r21 * r22;
	r20 = fmod(r20,r21);
	r19 = ($Math)g$_Math;
	r22 = r19->PI;
	if( !(r22 < r20) ) goto label$6602245_7_269;
	r22 = 2.;
	r19 = ($Math)g$_Math;
	r25 = r19->PI;
	r22 = r22 * r25;
	r21 = r20 - r22;
	r20 = r21;
	goto label$6602245_7_279;
	label$6602245_7_269:
	r19 = ($Math)g$_Math;
	r22 = r19->PI;
	r22 = -r22;
	if( !(r20 < r22) ) goto label$6602245_7_279;
	r22 = 2.;
	r19 = ($Math)g$_Math;
	r25 = r19->PI;
	r22 = r22 * r25;
	r21 = r20 + r22;
	r20 = r21;
	label$6602245_7_279:
	r21 = hl_math_abs(r20);
	r22 = 0.5;
	if( !(r21 < r22) ) goto label$6602245_7_288;
	r22 = r20 * r20;
	r22 = r22 * r20;
	r25 = 6.;
	r22 = r22 / r25;
	r21 = r20 - r22;
	goto label$6602245_7_289;
	label$6602245_7_288:
	r21 = hl_math_sin(r20);
	label$6602245_7_289:
	r30 = r1->pos;
	if( r30 == NULL ) hl_null_access();
	r13 = 0;
	r14 = r30->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_296;
	r25 = 0.;
	goto label$6602245_7_300;
	label$6602245_7_296:
	r24 = r30->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r25 = *(double*)(r24 + r14);
	label$6602245_7_300:
	if( r29 == NULL ) hl_null_access();
	r13 = 0;
	r14 = r29->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_306;
	r26 = 0.;
	goto label$6602245_7_310;
	label$6602245_7_306:
	r24 = r29->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r26 = *(double*)(r24 + r14);
	label$6602245_7_310:
	r26 = r26 * r18;
	r25 = r25 + r26;
	r13 = 1;
	r14 = r29->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_317;
	r26 = 0.;
	goto label$6602245_7_321;
	label$6602245_7_317:
	r24 = r29->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r26 = *(double*)(r24 + r14);
	label$6602245_7_321:
	r26 = r26 * r21;
	r25 = r25 - r26;
	r22 = r2 - r25;
	r30 = r1->pos;
	if( r30 == NULL ) hl_null_access();
	r13 = 1;
	r14 = r30->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_331;
	r26 = 0.;
	goto label$6602245_7_335;
	label$6602245_7_331:
	r24 = r30->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r26 = *(double*)(r24 + r14);
	label$6602245_7_335:
	r13 = 0;
	r14 = r29->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_340;
	r27 = 0.;
	goto label$6602245_7_344;
	label$6602245_7_340:
	r24 = r29->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r27 = *(double*)(r24 + r14);
	label$6602245_7_344:
	r27 = r27 * r21;
	r26 = r26 + r27;
	r13 = 1;
	r14 = r29->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$6602245_7_351;
	r27 = 0.;
	goto label$6602245_7_355;
	label$6602245_7_351:
	r24 = r29->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r27 = *(double*)(r24 + r14);
	label$6602245_7_355:
	r27 = r27 * r18;
	r26 = r26 + r27;
	r25 = r3 - r26;
	r27 = r22 * r22;
	r28 = r25 * r25;
	r27 = r27 + r28;
	r27 = hl_math_sqrt(r27);
	if( !(r27 < r16) ) goto label$6602245_7_374;
	r16 = r27;
	r6 = r1->connectors;
	if( r6 == NULL ) hl_null_access();
	r14 = r6->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$6602245_7_370;
	r29 = NULL;
	goto label$6602245_7_373;
	label$6602245_7_370:
	r11 = r6->array;
	r10 = ((vdynamic**)(r11 + 1))[r12];
	r29 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r10,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_7_373:
	r23 = r29;
	label$6602245_7_374:
	goto label$6602245_7_203;
	label$6602245_7_375:
	ExtendableObject_connect(r0,r1,r15,r23);
	r31 = false;
	return r31;
}

ExtendableObject ExtendableObject_findNearest(ExtendableObject r0,hl__types__ArrayBytes_Float r1) {
	ExtendableObject r4, r13;
	hl__types__ArrayObj r7;
	$ExtendableManager r8;
	hl__types__ArrayBytes_Float r2, r11;
	double r3, r16, r18, r19, r20;
	vdynamic *r14;
	vbyte *r17;
	varray *r15;
	int r5, r6, r9, r10, r12;
	if( r1 ) goto label$6602245_8_3;
	r2 = r0->pos;
	goto label$6602245_8_4;
	label$6602245_8_3:
	r2 = r1;
	label$6602245_8_4:
	r3 = 9999.;
	r4 = NULL;
	r5 = 0;
	r8 = ($ExtendableManager)g$_ExtendableManager;
	r7 = r8->objects;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->length;
	label$6602245_8_11:
	if( r5 >= r6 ) goto label$6602245_8_96;
	r9 = r5;
	++r5;
	r8 = ($ExtendableManager)g$_ExtendableManager;
	r7 = r8->objects;
	if( r7 == NULL ) hl_null_access();
	r12 = r7->length;
	if( ((unsigned)r9) < ((unsigned)r12) ) goto label$6602245_8_22;
	r13 = NULL;
	goto label$6602245_8_25;
	label$6602245_8_22:
	r15 = r7->array;
	r14 = ((vdynamic**)(r15 + 1))[r9];
	r13 = (ExtendableObject)r14;
	label$6602245_8_25:
	if( r13 == NULL ) hl_null_access();
	r11 = r13->pos;
	if( r2 == NULL ) hl_null_access();
	r10 = 0;
	r12 = r2->length;
	if( ((unsigned)r10) < ((unsigned)r12) ) goto label$6602245_8_33;
	r16 = 0.;
	goto label$6602245_8_37;
	label$6602245_8_33:
	r17 = r2->bytes;
	r12 = 3;
	r12 = r10 << r12;
	r16 = *(double*)(r17 + r12);
	label$6602245_8_37:
	if( r11 == NULL ) hl_null_access();
	r10 = 0;
	r12 = r11->length;
	if( ((unsigned)r10) < ((unsigned)r12) ) goto label$6602245_8_43;
	r18 = 0.;
	goto label$6602245_8_47;
	label$6602245_8_43:
	r17 = r11->bytes;
	r12 = 3;
	r12 = r10 << r12;
	r18 = *(double*)(r17 + r12);
	label$6602245_8_47:
	r16 = r16 - r18;
	r10 = 1;
	r12 = r2->length;
	if( ((unsigned)r10) < ((unsigned)r12) ) goto label$6602245_8_53;
	r18 = 0.;
	goto label$6602245_8_57;
	label$6602245_8_53:
	r17 = r2->bytes;
	r12 = 3;
	r12 = r10 << r12;
	r18 = *(double*)(r17 + r12);
	label$6602245_8_57:
	r10 = 1;
	r12 = r11->length;
	if( ((unsigned)r10) < ((unsigned)r12) ) goto label$6602245_8_62;
	r19 = 0.;
	goto label$6602245_8_66;
	label$6602245_8_62:
	r17 = r11->bytes;
	r12 = 3;
	r12 = r10 << r12;
	r19 = *(double*)(r17 + r12);
	label$6602245_8_66:
	r18 = r18 - r19;
	r19 = r16 * r16;
	r20 = r18 * r18;
	r19 = r19 + r20;
	r19 = hl_math_sqrt(r19);
	if( !(r19 < r3) ) goto label$6602245_8_95;
	r8 = ($ExtendableManager)g$_ExtendableManager;
	r7 = r8->objects;
	if( r7 == NULL ) hl_null_access();
	r12 = r7->length;
	if( ((unsigned)r9) < ((unsigned)r12) ) goto label$6602245_8_79;
	r13 = NULL;
	goto label$6602245_8_82;
	label$6602245_8_79:
	r15 = r7->array;
	r14 = ((vdynamic**)(r15 + 1))[r9];
	r13 = (ExtendableObject)r14;
	label$6602245_8_82:
	if( r13 == r0 ) goto label$6602245_8_95;
	r8 = ($ExtendableManager)g$_ExtendableManager;
	r7 = r8->objects;
	if( r7 == NULL ) hl_null_access();
	r12 = r7->length;
	if( ((unsigned)r9) < ((unsigned)r12) ) goto label$6602245_8_90;
	r13 = NULL;
	goto label$6602245_8_93;
	label$6602245_8_90:
	r15 = r7->array;
	r14 = ((vdynamic**)(r15 + 1))[r9];
	r13 = (ExtendableObject)r14;
	label$6602245_8_93:
	r4 = r13;
	r3 = r19;
	label$6602245_8_95:
	goto label$6602245_8_11;
	label$6602245_8_96:
	return r4;
}

void ExtendableObject_connect(ExtendableObject r0,ExtendableObject r1,hl__types__ArrayBytes_Float r2,hl__types__ArrayBytes_Float r3) {
	hl__types__ArrayObj r5;
	ConnectorLink r6;
	$ExtendableManager r8;
	int r4;
	r5 = r0->linked;
	if( r5 == NULL ) hl_null_access();
	r6 = (ConnectorLink)hl_alloc_obj(&t$ConnectorLink);
	ConnectorLink_new(r6,r1,r2,r3);
	r4 = hl_types_ArrayObj_push(r5,((vdynamic*)r6));
	r8 = ($ExtendableManager)g$_ExtendableManager;
	r5 = r8->objects;
	if( r5 == NULL ) hl_null_access();
	r4 = hl_types_ArrayObj_push(r5,((vdynamic*)r0));
	return;
}

void ExtendableObject_select(ExtendableObject r0,bool r1) {
	$Game r6;
	$ExtendableObject r8;
	hl__types__ArrayBytes_Float r2;
	double r5;
	int r4, r7;
	vbyte *r3;
	r4 = 24;
	r3 = hl_alloc_bytes(r4);
	r4 = 0;
	r6 = ($Game)g$_Game;
	r5 = r6->mx;
	r7 = 3;
	r7 = r4 << r7;
	*(double*)(r3 + r7) = r5;
	++r4;
	r6 = ($Game)g$_Game;
	r5 = r6->my;
	r7 = 3;
	r7 = r4 << r7;
	*(double*)(r3 + r7) = r5;
	++r4;
	r5 = 0.;
	r7 = 3;
	r7 = r4 << r7;
	*(double*)(r3 + r7) = r5;
	++r4;
	r4 = 3;
	r2 = hl_types_ArrayBase_allocF64(r3,r4);
	r8 = ($ExtendableObject)g$_ExtendableObject;
	r8->mouseClicked = r2;
	objects_GameObject_select(((objects__GameObject)r0),r1);
	return;
}

ExtendableObject ExtendableObject_extendUp(ExtendableObject r0,hl__Class r1) {
	bool *r9;
	ExtendableObject r10;
	hl__types__ArrayObj r7;
	hl_type *r5;
	bool r8;
	hl__types__ArrayBytes_Float r13, r14;
	hl__types__ArrayDyn r3;
	vdynamic *r2;
	int r6, r12;
	varray *r4;
	r5 = &t$_dyn;
	r6 = 0;
	r4 = hl_alloc_array(r5,r6);
	r7 = hl_types_ArrayObj_alloc(r4);
	r8 = true;
	r9 = &r8;
	r3 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r7),r9);
	r2 = Type_createInstance(r1,r3);
	r10 = (ExtendableObject)hl_dyn_castp(&r2,&t$_dyn,&t$ExtendableObject);
	r7 = r0->connectors;
	if( r7 == NULL ) hl_null_access();
	r6 = 3;
	r12 = r7->length;
	if( ((unsigned)r6) < ((unsigned)r12) ) goto label$6602245_11_16;
	r13 = NULL;
	goto label$6602245_11_19;
	label$6602245_11_16:
	r4 = r7->array;
	r2 = ((vdynamic**)(r4 + 1))[r6];
	r13 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r2,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_11_19:
	if( r10 == NULL ) hl_null_access();
	r7 = r10->connectors;
	if( r7 == NULL ) hl_null_access();
	r6 = 2;
	r12 = r7->length;
	if( ((unsigned)r6) < ((unsigned)r12) ) goto label$6602245_11_27;
	r14 = NULL;
	goto label$6602245_11_30;
	label$6602245_11_27:
	r4 = r7->array;
	r2 = ((vdynamic**)(r4 + 1))[r6];
	r14 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r2,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_11_30:
	ExtendableObject_connect(r0,r10,r13,r14);
	return r10;
}

ExtendableObject ExtendableObject_extendDown(ExtendableObject r0,hl__Class r1) {
	bool *r9;
	ExtendableObject r10;
	hl__types__ArrayObj r7;
	hl_type *r5;
	bool r8;
	hl__types__ArrayBytes_Float r13, r14;
	hl__types__ArrayDyn r3;
	vdynamic *r2;
	int r6, r12;
	varray *r4;
	r5 = &t$_dyn;
	r6 = 0;
	r4 = hl_alloc_array(r5,r6);
	r7 = hl_types_ArrayObj_alloc(r4);
	r8 = true;
	r9 = &r8;
	r3 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r7),r9);
	r2 = Type_createInstance(r1,r3);
	r10 = (ExtendableObject)hl_dyn_castp(&r2,&t$_dyn,&t$ExtendableObject);
	r7 = r0->connectors;
	if( r7 == NULL ) hl_null_access();
	r6 = 2;
	r12 = r7->length;
	if( ((unsigned)r6) < ((unsigned)r12) ) goto label$6602245_12_16;
	r13 = NULL;
	goto label$6602245_12_19;
	label$6602245_12_16:
	r4 = r7->array;
	r2 = ((vdynamic**)(r4 + 1))[r6];
	r13 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r2,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_12_19:
	if( r10 == NULL ) hl_null_access();
	r7 = r10->connectors;
	if( r7 == NULL ) hl_null_access();
	r6 = 3;
	r12 = r7->length;
	if( ((unsigned)r6) < ((unsigned)r12) ) goto label$6602245_12_27;
	r14 = NULL;
	goto label$6602245_12_30;
	label$6602245_12_27:
	r4 = r7->array;
	r2 = ((vdynamic**)(r4 + 1))[r6];
	r14 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r2,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_12_30:
	ExtendableObject_connect(r0,r10,r13,r14);
	return r10;
}

ExtendableObject ExtendableObject_extendLeft(ExtendableObject r0,hl__Class r1) {
	bool *r9;
	ExtendableObject r10;
	hl__types__ArrayObj r7;
	hl_type *r5;
	bool r8;
	hl__types__ArrayBytes_Float r13, r14;
	hl__types__ArrayDyn r3;
	vdynamic *r2;
	int r6, r12;
	varray *r4;
	r5 = &t$_dyn;
	r6 = 0;
	r4 = hl_alloc_array(r5,r6);
	r7 = hl_types_ArrayObj_alloc(r4);
	r8 = true;
	r9 = &r8;
	r3 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r7),r9);
	r2 = Type_createInstance(r1,r3);
	r10 = (ExtendableObject)hl_dyn_castp(&r2,&t$_dyn,&t$ExtendableObject);
	r7 = r0->connectors;
	if( r7 == NULL ) hl_null_access();
	r6 = 0;
	r12 = r7->length;
	if( ((unsigned)r6) < ((unsigned)r12) ) goto label$6602245_13_16;
	r13 = NULL;
	goto label$6602245_13_19;
	label$6602245_13_16:
	r4 = r7->array;
	r2 = ((vdynamic**)(r4 + 1))[r6];
	r13 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r2,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_13_19:
	if( r10 == NULL ) hl_null_access();
	r7 = r10->connectors;
	if( r7 == NULL ) hl_null_access();
	r6 = 1;
	r12 = r7->length;
	if( ((unsigned)r6) < ((unsigned)r12) ) goto label$6602245_13_27;
	r14 = NULL;
	goto label$6602245_13_30;
	label$6602245_13_27:
	r4 = r7->array;
	r2 = ((vdynamic**)(r4 + 1))[r6];
	r14 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r2,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_13_30:
	ExtendableObject_connect(r0,r10,r13,r14);
	return r10;
}

ExtendableObject ExtendableObject_extendRight(ExtendableObject r0,hl__Class r1) {
	bool *r9;
	ExtendableObject r10;
	hl__types__ArrayObj r7;
	hl_type *r5;
	bool r8;
	hl__types__ArrayBytes_Float r13, r14;
	hl__types__ArrayDyn r3;
	vdynamic *r2;
	int r6, r12;
	varray *r4;
	r5 = &t$_dyn;
	r6 = 0;
	r4 = hl_alloc_array(r5,r6);
	r7 = hl_types_ArrayObj_alloc(r4);
	r8 = true;
	r9 = &r8;
	r3 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r7),r9);
	r2 = Type_createInstance(r1,r3);
	r10 = (ExtendableObject)hl_dyn_castp(&r2,&t$_dyn,&t$ExtendableObject);
	r7 = r0->connectors;
	if( r7 == NULL ) hl_null_access();
	r6 = 1;
	r12 = r7->length;
	if( ((unsigned)r6) < ((unsigned)r12) ) goto label$6602245_14_16;
	r13 = NULL;
	goto label$6602245_14_19;
	label$6602245_14_16:
	r4 = r7->array;
	r2 = ((vdynamic**)(r4 + 1))[r6];
	r13 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r2,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_14_19:
	if( r10 == NULL ) hl_null_access();
	r7 = r10->connectors;
	if( r7 == NULL ) hl_null_access();
	r6 = 0;
	r12 = r7->length;
	if( ((unsigned)r6) < ((unsigned)r12) ) goto label$6602245_14_27;
	r14 = NULL;
	goto label$6602245_14_30;
	label$6602245_14_27:
	r4 = r7->array;
	r2 = ((vdynamic**)(r4 + 1))[r6];
	r14 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r2,&t$_dyn,&t$hl_types_ArrayBytes_Float);
	label$6602245_14_30:
	ExtendableObject_connect(r0,r10,r13,r14);
	return r10;
}

void ExtendableObject_new(ExtendableObject r0,int* r1,int* r2,String r3,int* r4) {
	hl__types__ArrayObj r9;
	hl_type *r11;
	bool r16;
	double r8;
	varray *r10;
	int r5, r6, r7, r12, r14, r15;
	if( r1 ) goto label$6602245_15_3;
	r5 = 61;
	goto label$6602245_15_4;
	label$6602245_15_3:
	r5 = *r1;
	label$6602245_15_4:
	if( r2 ) goto label$6602245_15_7;
	r6 = 61;
	goto label$6602245_15_8;
	label$6602245_15_7:
	r6 = *r2;
	label$6602245_15_8:
	if( r4 ) goto label$6602245_15_11;
	r7 = 0;
	goto label$6602245_15_12;
	label$6602245_15_11:
	r7 = *r4;
	label$6602245_15_12:
	r8 = 0.050000000000000003;
	r0->heatOutF = r8;
	r8 = 0.14999999999999999;
	r0->heatInF = r8;
	r8 = 0.80000000000000004;
	r0->heatConductivityF = r8;
	r8 = 0.;
	r0->heat = r8;
	r11 = &t$ConnectorLink;
	r12 = 0;
	r10 = hl_alloc_array(r11,r12);
	r9 = hl_types_ArrayObj_alloc(r10);
	r0->linked = r9;
	r11 = &t$hl_types_ArrayBytes_Float;
	r12 = 0;
	r10 = hl_alloc_array(r11,r12);
	r9 = hl_types_ArrayObj_alloc(r10);
	r0->connectors = r9;
	r12 = r5;
	r1 = &r12;
	r14 = r6;
	r2 = &r14;
	r15 = r7;
	r4 = &r15;
	objects_GameObject_new(((objects__GameObject)r0),r1,r2,r3,r4);
	r16 = true;
	r0->selectable = r16;
	r9 = ((hl__types__ArrayObj (*)(ExtendableObject))r0->$type->vobj_proto[2])(r0);
	r0->connectors = r9;
	return;
}

