// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/ExtendableManager.h>
#include <_std/ConnectorLink.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
#include <hl/types/ArrayBase.h>
extern $ExtendableManager g$_ExtendableManager;
extern haxe__$Log g$_haxe_Log;
extern String s$Deattached_;
String Std_string(vdynamic*);
String String___add__(String,String);
extern String s$Game_hx;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$ExtendableManager;
extern String s$deattach;
extern hl_type t$vrt_eaa6a3b;
hl__types__ArrayBase hl_types_ArrayObj_splice(hl__types__ArrayObj,int,int);
extern hl_type t$hl_types_ArrayObj;
extern hl_type t$hl_types_ArrayBase;
#include <util/Worker.h>
extern util__$Worker g$_util_Worker;
bool haxe_ds_ObjectMap_exists(haxe__ds__ObjectMap,vdynamic*);
extern hl_type t$haxe_ds_ObjectMap;
void haxe_ds_ObjectMap_new(haxe__ds__ObjectMap);
void haxe_ds_ObjectMap_set(haxe__ds__ObjectMap,vdynamic*,vdynamic*);
void ExtendableObject_rotateConnected(ExtendableObject,double);
extern hl_type t$fun_51b9903;

void ExtendableManager_deattach(ExtendableObject r0) {
	vdynobj *r19;
	String r17, r18;
	ExtendableObject r8, r11;
	vvirtual *r20;
	hl__types__ArrayObj r4;
	hl__types__ArrayBase r21;
	haxe__$Log r16;
	ConnectorLink r14;
	$ExtendableManager r5;
	vclosure *r15;
	vdynamic *r9;
	varray *r10;
	int r1, r3, r6, r7, r12, r13;
	r1 = 0;
	r5 = ($ExtendableManager)g$_ExtendableManager;
	r4 = r5->objects;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->length;
	label$625c188_1_5:
	if( r1 >= r3 ) goto label$625c188_1_72;
	r5 = ($ExtendableManager)g$_ExtendableManager;
	r4 = r5->objects;
	if( r4 == NULL ) hl_null_access();
	r6 = r1;
	++r1;
	r7 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$625c188_1_16;
	r8 = NULL;
	goto label$625c188_1_19;
	label$625c188_1_16:
	r10 = r4->array;
	r9 = ((vdynamic**)(r10 + 1))[r6];
	r8 = (ExtendableObject)r9;
	label$625c188_1_19:
	if( r8 == NULL ) hl_null_access();
	r4 = r8->linked;
	if( r4 == NULL ) hl_null_access();
	r6 = r4->length;
	r7 = 1;
	r6 = r6 - r7;
	label$625c188_1_25:
	r12 = 0;
	if( r6 < r12 ) goto label$625c188_1_71;
	if( r8 == NULL ) hl_null_access();
	r4 = r8->linked;
	if( r4 == NULL ) hl_null_access();
	r7 = r4->length;
	r12 = 1;
	r7 = r7 - r12;
	r7 = r7 - r6;
	r4 = r8->linked;
	if( r4 == NULL ) hl_null_access();
	r13 = r4->length;
	if( ((unsigned)r7) < ((unsigned)r13) ) goto label$625c188_1_41;
	r14 = NULL;
	goto label$625c188_1_44;
	label$625c188_1_41:
	r10 = r4->array;
	r9 = ((vdynamic**)(r10 + 1))[r7];
	r14 = (ConnectorLink)r9;
	label$625c188_1_44:
	if( r14 == NULL ) hl_null_access();
	r11 = r14->connected;
	if( r11 != r0 ) goto label$625c188_1_69;
	r16 = (haxe__$Log)g$_haxe_Log;
	r15 = r16->trace;
	if( r15 == NULL ) hl_null_access();
	r17 = (String)s$Deattached_;
	r18 = Std_string(((vdynamic*)r0));
	r17 = String___add__(r17,r18);
	r19 = hl_alloc_dynobj();
	r18 = (String)s$Game_hx;
	hl_dyn_setp((vdynamic*)r19,37969014/*fileName*/,&t$String,r18);
	r12 = 203;
	hl_dyn_seti((vdynamic*)r19,371360620/*lineNumber*/,&t$_i32,r12);
	r18 = (String)s$ExtendableManager;
	hl_dyn_setp((vdynamic*)r19,-63073762/*className*/,&t$String,r18);
	r18 = (String)s$deattach;
	hl_dyn_setp((vdynamic*)r19,302979532/*methodName*/,&t$String,r18);
	r20 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r19);
	r15->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r15->fun)((vdynamic*)r15->value,((vdynamic*)r17),r20) : ((void (*)(vdynamic*,vvirtual*))r15->fun)(((vdynamic*)r17),r20);
	r4 = r8->linked;
	if( r4 == NULL ) hl_null_access();
	r13 = 1;
	r21 = hl_types_ArrayObj_splice(r4,r7,r13);
	r4 = (hl__types__ArrayObj)hl_dyn_castp(&r21,&t$hl_types_ArrayBase,&t$hl_types_ArrayObj);
	label$625c188_1_69:
	--r6;
	goto label$625c188_1_25;
	label$625c188_1_71:
	goto label$625c188_1_5;
	label$625c188_1_72:
	return;
}

void ExtendableManager_traverse(double r0,ExtendableObject r1) {
	haxe__ds__ObjectMap r10;
	ExtendableObject r3;
	hl__types__ArrayObj r5;
	bool r9;
	ConnectorLink r14;
	util__$Worker r6;
	$ExtendableManager r11;
	vdynamic *r8;
	varray *r12;
	int r4, r7, r13;
	if( r1 ) goto label$625c188_2_8;
	r6 = (util__$Worker)g$_util_Worker;
	r5 = r6->tasks;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->length;
	r7 = 0;
	if( r7 >= r4 ) goto label$625c188_2_8;
	return;
	label$625c188_2_8:
	r11 = ($ExtendableManager)g$_ExtendableManager;
	r10 = r11->traversed;
	if( r10 == NULL ) hl_null_access();
	r9 = haxe_ds_ObjectMap_exists(r10,((vdynamic*)r1));
	if( !r9 ) goto label$625c188_2_14;
	return;
	label$625c188_2_14:
	if( r1 ) goto label$625c188_2_38;
	r11 = ($ExtendableManager)g$_ExtendableManager;
	r5 = r11->objects;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->length;
	r7 = 0;
	if( r4 != r7 ) goto label$625c188_2_22;
	return;
	label$625c188_2_22:
	r11 = ($ExtendableManager)g$_ExtendableManager;
	r5 = r11->objects;
	if( r5 == NULL ) hl_null_access();
	r4 = 0;
	r7 = r5->length;
	if( ((unsigned)r4) < ((unsigned)r7) ) goto label$625c188_2_30;
	r3 = NULL;
	goto label$625c188_2_33;
	label$625c188_2_30:
	r12 = r5->array;
	r8 = ((vdynamic**)(r12 + 1))[r4];
	r3 = (ExtendableObject)r8;
	label$625c188_2_33:
	r1 = r3;
	r10 = (haxe__ds__ObjectMap)hl_alloc_obj(&t$haxe_ds_ObjectMap);
	haxe_ds_ObjectMap_new(r10);
	r11 = ($ExtendableManager)g$_ExtendableManager;
	r11->traversed = r10;
	label$625c188_2_38:
	r11 = ($ExtendableManager)g$_ExtendableManager;
	r10 = r11->traversed;
	if( r10 == NULL ) hl_null_access();
	r9 = true;
	r8 = hl_alloc_dynbool(r9);
	haxe_ds_ObjectMap_set(r10,((vdynamic*)r1),r8);
	if( r1 == NULL ) hl_null_access();
	ExtendableObject_rotateConnected(r1,r0);
	r4 = -1;
	label$625c188_2_47:
	++r4;
	if( r1 == NULL ) hl_null_access();
	r5 = r1->linked;
	if( r5 == NULL ) hl_null_access();
	r7 = r5->length;
	if( r4 >= r7 ) goto label$625c188_2_67;
	r5 = r1->linked;
	if( r5 == NULL ) hl_null_access();
	r13 = r5->length;
	if( ((unsigned)r4) < ((unsigned)r13) ) goto label$625c188_2_60;
	r14 = NULL;
	goto label$625c188_2_63;
	label$625c188_2_60:
	r12 = r5->array;
	r8 = ((vdynamic**)(r12 + 1))[r4];
	r14 = (ConnectorLink)r8;
	label$625c188_2_63:
	if( r14 == NULL ) hl_null_access();
	r3 = r14->connected;
	ExtendableManager_traverse(r0,r3);
	goto label$625c188_2_47;
	label$625c188_2_67:
	return;
}

void ExtendableManager_traverseCycle(double r0) {
	ExtendableObject r7;
	hl__types__ArrayObj r4;
	$ExtendableManager r5;
	vdynamic *r8;
	varray *r9;
	int r1, r3, r6;
	r1 = -1;
	r5 = ($ExtendableManager)g$_ExtendableManager;
	r4 = r5->objects;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->length;
	label$625c188_3_5:
	++r1;
	if( r1 >= r3 ) goto label$625c188_3_21;
	r5 = ($ExtendableManager)g$_ExtendableManager;
	r4 = r5->objects;
	if( r4 == NULL ) hl_null_access();
	r6 = r4->length;
	if( ((unsigned)r1) < ((unsigned)r6) ) goto label$625c188_3_15;
	r7 = NULL;
	goto label$625c188_3_18;
	label$625c188_3_15:
	r9 = r4->array;
	r8 = ((vdynamic**)(r9 + 1))[r1];
	r7 = (ExtendableObject)r8;
	label$625c188_3_18:
	if( r7 == NULL ) hl_null_access();
	ExtendableObject_rotateConnected(r7,r0);
	goto label$625c188_3_5;
	label$625c188_3_21:
	return;
}

bool ExtendableManager_check__$1(ExtendableObject r0) {
	haxe__ds__ObjectMap r8;
	ExtendableObject r4;
	hl__types__ArrayObj r3, r10;
	bool r6;
	ConnectorLink r12;
	vdynamic *r7, *r14;
	varray *r13;
	int r2, r5, r9, r11;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->linked;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	r5 = 2;
	if( r2 < r5 ) goto label$625c188_4_8;
	r6 = true;
	return r6;
	label$625c188_4_8:
	r8 = (haxe__ds__ObjectMap)hl_alloc_obj(&t$haxe_ds_ObjectMap);
	haxe_ds_ObjectMap_new(r8);
	r2 = 0;
	r3 = r0->linked;
	label$625c188_4_12:
	if( r3 == NULL ) hl_null_access();
	r9 = r3->length;
	if( r2 >= r9 ) goto label$625c188_4_53;
	r5 = 0;
	r9 = r2;
	++r2;
	r11 = r3->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$625c188_4_23;
	r12 = NULL;
	goto label$625c188_4_26;
	label$625c188_4_23:
	r13 = r3->array;
	r7 = ((vdynamic**)(r13 + 1))[r9];
	r12 = (ConnectorLink)r7;
	label$625c188_4_26:
	if( r12 == NULL ) hl_null_access();
	r4 = r12->connected;
	if( r4 == NULL ) hl_null_access();
	r10 = r4->linked;
	label$625c188_4_30:
	if( r10 == NULL ) hl_null_access();
	r11 = r10->length;
	if( r5 >= r11 ) goto label$625c188_4_52;
	r11 = r10->length;
	if( ((unsigned)r5) < ((unsigned)r11) ) goto label$625c188_4_38;
	r12 = NULL;
	goto label$625c188_4_41;
	label$625c188_4_38:
	r13 = r10->array;
	r7 = ((vdynamic**)(r13 + 1))[r5];
	r12 = (ConnectorLink)r7;
	label$625c188_4_41:
	++r5;
	if( r8 == NULL ) hl_null_access();
	r6 = haxe_ds_ObjectMap_exists(r8,((vdynamic*)r12));
	if( r6 ) goto label$625c188_4_49;
	r9 = 1;
	r14 = hl_alloc_dynamic(&t$_i32);
	r14->v.i = r9;
	haxe_ds_ObjectMap_set(r8,((vdynamic*)r12),((vdynamic*)r14));
	goto label$625c188_4_51;
	label$625c188_4_49:
	r6 = true;
	return r6;
	label$625c188_4_51:
	goto label$625c188_4_30;
	label$625c188_4_52:
	goto label$625c188_4_12;
	label$625c188_4_53:
	r6 = false;
	return r6;
}

bool ExtendableManager_check() {
	ExtendableObject r7;
	hl__types__ArrayObj r3;
	bool r5;
	$ExtendableManager r4;
	vclosure *r0;
	vdynamic *r8;
	varray *r9;
	int r1, r2, r6;
	static vclosure cl$0 = { &t$fun_51b9903, ExtendableManager_check__$1, 0 };
	r0 = &cl$0;
	r1 = -1;
	r4 = ($ExtendableManager)g$_ExtendableManager;
	r3 = r4->objects;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	label$625c188_5_6:
	++r1;
	if( r1 >= r2 ) goto label$625c188_5_25;
	if( r0 == NULL ) hl_null_access();
	r4 = ($ExtendableManager)g$_ExtendableManager;
	r3 = r4->objects;
	if( r3 == NULL ) hl_null_access();
	r6 = r3->length;
	if( ((unsigned)r1) < ((unsigned)r6) ) goto label$625c188_5_17;
	r7 = NULL;
	goto label$625c188_5_20;
	label$625c188_5_17:
	r9 = r3->array;
	r8 = ((vdynamic**)(r9 + 1))[r1];
	r7 = (ExtendableObject)r8;
	label$625c188_5_20:
	r5 = r0->hasValue ? ((bool (*)(vdynamic*,ExtendableObject))r0->fun)((vdynamic*)r0->value,r7) : ((bool (*)(ExtendableObject))r0->fun)(r7);
	if( r5 ) goto label$625c188_5_24;
	r5 = false;
	return r5;
	label$625c188_5_24:
	goto label$625c188_5_6;
	label$625c188_5_25:
	r5 = true;
	return r5;
}

