// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__Fractal
#define INC__std__Fractal
typedef struct _$Fractal *$Fractal;
typedef struct _Fractal *Fractal;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <_std/Eight.h>
#include <sdl/Window.h>
#include <_std/Object.h>
#include <_std/Circle.h>
#include <hl/types/ArrayBytes_Float.h>
#include <hl/types/ArrayBytes_Int.h>


struct _$Fractal {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	double mx;
	double my;
	double zoom;
	vclosure* main;
};
struct _Fractal {
	hl_type *$type;
	sdl__Window window;
	Object bg;
	Circle circle;
	Object dot1;
	Object dot2;
	hl__types__ArrayBytes_Float c;
	int r;
	double _hx_t;
	hl__types__ArrayBytes_Int colors;
	double d1;
	double d2;
	double s1;
	double s2;
	int i;
};
#endif

