// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__HaulJob
#define INC__std__HaulJob
typedef struct _$HaulJob *$HaulJob;
typedef struct _HaulJob *HaulJob;
#include <_std/Character.h>
#include <_std/HaulJob.h>
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <_std/PawnJob.h>
#include <objects/ExtendableObject.h>


typedef struct {
	HL__ENUM_CONSTRUCT__
	Character p0;
	vclosure* p1;
	HaulJob p2;
} Enumt$ctx_1b4df96;
struct _$HaulJob {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _HaulJob {
	hl_type *$type;
	String label;
	objects__ExtendableObject sourceObj;
	objects__ExtendableObject targetObj;
	String itemName;
	double workTime;
};
#endif

