// Generated by HLC 4.3.7 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/Lambda.h>
extern hl_type t$fun_eb2fdfb;
extern hl_type t$fun_bf7849e;
extern hl_type t$fun_b157a06;

int Lambda_findIndex(vvirtual* r0,vclosure* r1) {
	vvirtual *r3;
	bool r4;
	vdynamic *r5;
	int r2, r6;
	r2 = 0;
	if( r0 == NULL ) hl_null_access();
	if( hl_vfields(r0)[0] ) r3 = ((vvirtual* (*)(vdynamic*))hl_vfields(r0)[0])(r0->value); else {
		r3 = (vvirtual*)hl_dyn_call_obj(r0->value,&t$fun_eb2fdfb,-207992737/*iterator*/,NULL,NULL);
	}
	label$22eed56_1_3:
	if( r3 == NULL ) hl_null_access();
	if( hl_vfields(r3)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r3)[0])(r3->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r3->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$22eed56_1_14;
	if( hl_vfields(r3)[1] ) r5 = ((vdynamic* (*)(vdynamic*))hl_vfields(r3)[1])(r3->value); else {
		r5 = (vdynamic*)hl_dyn_call_obj(r3->value,&t$fun_b157a06,151160317/*next*/,NULL,NULL);
	}
	if( r1 == NULL ) hl_null_access();
	r4 = r1->hasValue ? ((bool (*)(vdynamic*,vdynamic*))r1->fun)((vdynamic*)r1->value,r5) : ((bool (*)(vdynamic*))r1->fun)(r5);
	if( !r4 ) goto label$22eed56_1_12;
	return r2;
	label$22eed56_1_12:
	++r2;
	goto label$22eed56_1_3;
	label$22eed56_1_14:
	r6 = -1;
	return r6;
}

