// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__MoveJob
#define INC__std__MoveJob
typedef struct _$MoveJob *$MoveJob;
typedef struct _MoveJob *MoveJob;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <_std/PawnJob.h>
#include <hl/types/ArrayBytes_Float.h>


struct _$MoveJob {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _MoveJob {
	hl_type *$type;
	String label;
	hl__types__ArrayBytes_Float target;
};
#endif

