// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__PawnJob
#define INC__std__PawnJob
typedef struct _$PawnJob *$PawnJob;
typedef struct _PawnJob *PawnJob;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _$PawnJob {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _PawnJob {
	hl_type *$type;
	String label;
};
#endif

