// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__StringTools
#define INC__std__StringTools
typedef struct _$StringTools *$StringTools;
typedef struct _StringTools *StringTools;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _$StringTools {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* startsWith;
	vclosure* isSpace;
	vclosure* ltrim;
	vclosure* rtrim;
	vclosure* trim;
	vclosure* lpad;
};
struct _StringTools {
	hl_type *$type;
};
#endif

