// Generated by HLC 4.3.7 (HL v4)
#ifndef INC__std__UseJob
#define INC__std__UseJob
typedef struct _$UseJob *$UseJob;
typedef struct _UseJob *UseJob;
#include <_std/Character.h>
#include <_std/UseJob.h>
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <_std/PawnJob.h>
#include <objects/ExtendableObject.h>


typedef struct {
	HL__ENUM_CONSTRUCT__
	Character p0;
	vclosure* p1;
	UseJob p2;
} Enumt$ctx_4a26182;
struct _$UseJob {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _UseJob {
	hl_type *$type;
	String label;
	objects__ExtendableObject targetObj;
	double workTime;
};
#endif

